# Section 2.0 — Parser Entry Gate

This section establishes a trusted entry point for the True Turn Parser.
The frozen inventory, amended data contract, response artifact, and transcript registration are verified.
Only the `session_id` projection of the response foundation is loaded into parser working memory.
Targets, objectives, folds, OOF predictions, and model-derived information are not loaded.
The parser contract must be version 1.1 and remain explicitly label-blind.
Math-safe NFC normalization, byte-safe ingestion, natural ID sorting, and session-level ordering rules are verified.
Transcript files are listed but their contents are not parsed or re-hashed in this section.
Final candidate artifacts must not already exist before a new parser run begins.
A parser run identity and reproducibility context are created.
The section ends with the `PARSER_ENTRY_READY` hard gate.

In [4]:
from pathlib import Path
from datetime import datetime
import hashlib
import json
import locale
import os
import platform
import subprocess
import sys
import time

import pandas as pd
import pyarrow as pa


PARSER_VERSION = "1.0"
EXPECTED_CONTRACT_VERSION = "1.1"


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def canonical_json_hash(data):
    text = json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path, chunk_size=1024 * 1024):
    digest = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            digest.update(chunk)

    return digest.hexdigest()


def check_row(check, passed, detail):
    return {"check": check, "passed": bool(passed), "detail": detail}


def find_path_registry():
    roots = [Path.cwd(), *Path.cwd().parents]
    candidates = []

    for root in roots:
        candidates.extend([
            root / "scratch_mastery_outputs" / "00_project_setup" / "path_registry.json",
            root / "scratch_mastery_outputs" / "00_setup" / "path_registry.json",
            root / "00_project_setup" / "path_registry.json",
            root / "00_setup" / "path_registry.json",
        ])

    return next((path for path in candidates if path.exists()), None)


PATH_REGISTRY_PATH = find_path_registry()
assert PATH_REGISTRY_PATH is not None, "Could not locate path_registry.json."

path_registry = load_json(PATH_REGISTRY_PATH)

PROJECT_ROOT = Path(path_registry["project_root"])
SCRATCH_OUTPUT_ROOT = Path(path_registry["scratch_output_root"])
PHASE1_ROOT = SCRATCH_OUTPUT_ROOT / "01_data_foundation"
INVENTORY_OUTPUT_DIR = PHASE1_ROOT / "01_inventory"

DATA_CONTRACT_PATH = PHASE1_ROOT / "data_contract.json"
INVENTORY_MANIFEST_PATH = INVENTORY_OUTPUT_DIR / "inventory_manifest.json"
RESPONSES_BASE_PATH = INVENTORY_OUTPUT_DIR / "responses_base.parquet"

assert path_registry["transcript_source_type"] == "external_path", (
    "Current parser contract expects the registered external transcript source."
)

TRANSCRIPT_ROOT = Path(path_registry["transcript_source"])

DATA_CONTRACT = load_json(DATA_CONTRACT_PATH)
INVENTORY_MANIFEST = load_json(INVENTORY_MANIFEST_PATH)

candidate_outputs = DATA_CONTRACT["candidate_outputs"]

TURNS_CANDIDATE_PATH = PHASE1_ROOT / candidate_outputs["turns"]
SESSIONS_CANDIDATE_PATH = PHASE1_ROOT / candidate_outputs["sessions"]
PARSER_MANIFEST_PATH = PHASE1_ROOT / candidate_outputs["manifest"]

PARSER_OUTPUT_DIR = TURNS_CANDIDATE_PATH.parent
PARSER_WORK_DIR = PARSER_OUTPUT_DIR / "_work"

PARSER_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
PARSER_WORK_DIR.mkdir(parents=True, exist_ok=True)

In [5]:
def manifest_gate(manifest, gate_name):
    matches = [
        row for row in manifest.get("stage_gates", [])
        if row.get("gate") == gate_name
    ]

    return bool(matches and matches[-1].get("passed") is True)


actual_contract_hash = canonical_json_hash(DATA_CONTRACT)
actual_responses_hash = sha256_file(RESPONSES_BASE_PATH)

expected_contract_hash = INVENTORY_MANIFEST["artifacts"]["data_contract_sha256"]
expected_responses_hash = INVENTORY_MANIFEST["artifacts"]["responses_base_sha256"]

response_session_projection = pd.read_parquet(
    RESPONSES_BASE_PATH,
    columns=["session_id"],
)

REQUIRED_SESSION_IDS = tuple(
    sorted(response_session_projection["session_id"].drop_duplicates().tolist())
)

REQUIRED_SESSION_ID_SET = frozenset(REQUIRED_SESSION_IDS)

TRANSCRIPT_FILES = tuple(
    sorted(
        TRANSCRIPT_ROOT.rglob("*.csv"),
        key=lambda path: path.relative_to(TRANSCRIPT_ROOT).as_posix(),
    )
)

required_transcript_fields = set(
    DATA_CONTRACT["transcript_schema"]["required_fields"]
)

expected_transcript_fields = {
    "session_id",
    "utterance_id",
    "role",
    "content",
    "timestamp",
}

source_binding_matches = all([
    DATA_CONTRACT["source_binding"]["train_features_sha256"]
    == INVENTORY_MANIFEST["source_fingerprints"]["train_features_sha256"],

    DATA_CONTRACT["source_binding"]["train_labels_sha256"]
    == INVENTORY_MANIFEST["source_fingerprints"]["train_labels_sha256"],

    DATA_CONTRACT["source_binding"]["frozen_fold_manifest_sha256"]
    == INVENTORY_MANIFEST["source_fingerprints"]["frozen_fold_manifest_sha256"],

    DATA_CONTRACT["source_binding"]["transcript_directory_sha256"]
    == INVENTORY_MANIFEST["source_fingerprints"]["transcript_directory_sha256"],
])

final_candidate_paths = [
    TURNS_CANDIDATE_PATH,
    SESSIONS_CANDIDATE_PATH,
    PARSER_MANIFEST_PATH,
]

parser_entry_checks = pd.DataFrame([
    check_row(
        "Contract version is 1.1",
        DATA_CONTRACT["contract"]["version"] == EXPECTED_CONTRACT_VERSION,
        DATA_CONTRACT["contract"]["version"],
    ),
    check_row(
        "Inventory contract version is 1.1",
        INVENTORY_MANIFEST["inventory"]["contract_version"] == EXPECTED_CONTRACT_VERSION,
        INVENTORY_MANIFEST["inventory"]["contract_version"],
    ),
    check_row(
        "Inventory is ready",
        INVENTORY_MANIFEST["inventory"]["inventory_ready"] is True,
        INVENTORY_MANIFEST["inventory"]["inventory_ready"],
    ),
    check_row(
        "Inventory has no blockers",
        INVENTORY_MANIFEST["blocking_failures"] == 0,
        INVENTORY_MANIFEST["blocking_failures"],
    ),
    check_row(
        "Contract amendment gate passed",
        manifest_gate(INVENTORY_MANIFEST, "CONTRACT_AMENDMENT_READY"),
        manifest_gate(INVENTORY_MANIFEST, "CONTRACT_AMENDMENT_READY"),
    ),
    check_row(
        "Contract hash matches inventory",
        actual_contract_hash == expected_contract_hash,
        actual_contract_hash,
    ),
    check_row(
        "Response artifact hash matches inventory",
        actual_responses_hash == expected_responses_hash,
        actual_responses_hash,
    ),
    check_row(
        "Contract and inventory source bindings match",
        source_binding_matches,
        source_binding_matches,
    ),
    check_row(
        "Response row count matches contract",
        len(response_session_projection)
        == DATA_CONTRACT["source_binding"]["expected_response_count"],
        len(response_session_projection),
    ),
    check_row(
        "Required session count matches contract",
        len(REQUIRED_SESSION_IDS)
        == DATA_CONTRACT["source_binding"]["expected_session_count"],
        len(REQUIRED_SESSION_IDS),
    ),
    check_row(
        "Transcript source exists",
        TRANSCRIPT_ROOT.is_dir(),
        str(TRANSCRIPT_ROOT),
    ),
    check_row(
        "Transcript file count matches contract",
        len(TRANSCRIPT_FILES)
        == DATA_CONTRACT["source_binding"]["expected_transcript_file_count"],
        len(TRANSCRIPT_FILES),
    ),
    check_row(
        "Required transcript schema is exact",
        required_transcript_fields == expected_transcript_fields,
        sorted(required_transcript_fields),
    ),
    check_row(
        "Unicode normalization is NFC",
        DATA_CONTRACT["text_normalization"]["unicode_form"] == "NFC",
        DATA_CONTRACT["text_normalization"]["unicode_form"],
    ),
    check_row(
        "Internal newlines are preserved",
        DATA_CONTRACT["text_normalization"]["preserve_internal_newlines"],
        DATA_CONTRACT["text_normalization"]["preserve_internal_newlines"],
    ),
    check_row(
        "Repeated whitespace is not collapsed",
        not DATA_CONTRACT["text_normalization"]["collapse_repeated_whitespace"],
        DATA_CONTRACT["text_normalization"]["collapse_repeated_whitespace"],
    ),
    check_row(
        "Hash and parse use the same file bytes",
        DATA_CONTRACT["ingestion_policy"]["hash_and_parse_same_bytes"],
        DATA_CONTRACT["ingestion_policy"]["hash_and_parse_same_bytes"],
    ),
    check_row(
        "Automatic NA coercion is disabled",
        not DATA_CONTRACT["ingestion_policy"]["automatic_na_coercion"],
        DATA_CONTRACT["ingestion_policy"]["automatic_na_coercion"],
    ),
    check_row(
        "Natural utterance-ID sorting is required",
        DATA_CONTRACT["utterance_id_policy"]["natural_sort_required"]
        and not DATA_CONTRACT["utterance_id_policy"]["lexical_sort_allowed"],
        DATA_CONTRACT["utterance_id_policy"]["natural_sort_required"],
    ),
    check_row(
        "Ordering uses session-level decisions",
        DATA_CONTRACT["ordering_policy"]["session_level_decision"],
        DATA_CONTRACT["ordering_policy"]["session_level_decision"],
    ),
    check_row(
        "Partial timestamp mixing is prohibited",
        not DATA_CONTRACT["ordering_policy"]["partial_timestamp_mixing_allowed"],
        DATA_CONTRACT["ordering_policy"]["partial_timestamp_mixing_allowed"],
    ),
    check_row(
        "Fallback ordering requires empirical calibration",
        DATA_CONTRACT["ordering_policy"]["fallback_selection"]
        == "empirically_calibrated_before_full_parse",
        DATA_CONTRACT["ordering_policy"]["fallback_selection"],
    ),
    check_row(
        "Parser is label-blind",
        DATA_CONTRACT["parser_restrictions"]["label_blind"],
        DATA_CONTRACT["parser_restrictions"]["label_blind"],
    ),
    check_row(
        "Candidate outputs are non-canonical",
        not DATA_CONTRACT["candidate_outputs"]["candidate_is_canonical"],
        DATA_CONTRACT["candidate_outputs"]["candidate_is_canonical"],
    ),
    check_row(
        "No final parser artifacts already exist",
        not any(path.exists() for path in final_candidate_paths),
        sum(path.exists() for path in final_candidate_paths),
    ),
])

entry_failures = parser_entry_checks[
    ~parser_entry_checks["passed"]
]

display(parser_entry_checks)

,check,passed,detail
0,Contract version is 1.1,True,1.1
1,Inventory contract version is 1.1,True,1.1
2,Inventory is ready,True,True
3,Inventory has no blockers,True,0
4,Contract amendment gate passed,True,True
5,Contract hash matches inventory,True,03d238a18c0aacf2e8f3c410b0ba0b2410e88cfe9a3816...
6,Response artifact hash matches inventory,True,dc5e3f3926b8120947c43d77fa240ae3b631010d310d54...
7,Contract and inventory source bindings match,True,True
8,Response row count matches contract,True,35072
9,Required session count matches contract,True,22821
10,Transcript source exists,True,D:\Competition\Trace-the-race-local\Dataset\tr...
11,Transcript file count matches contract,True,22821
12,Required transcript schema is exact,True,"[content, role, session_id, timestamp, utteran..."
13,Unicode normalization is NFC,True,NFC
14,Internal newlines are preserved,True,True
15,Repeated whitespace is not collapsed,True,False
16,Hash and parse use the same file bytes,True,True
17,Automatic NA coercion is disabled,True,False
18,Natural utterance-ID sorting is required,True,True
19,Ordering uses session-level decisions,True,True
20,Partial timestamp mixing is prohibited,True,False
21,Fallback ordering requires empirical calibration,True,empirically_calibrated_before_full_parse
22,Parser is label-blind,True,True
23,Candidate outputs are non-canonical,True,False
24,No final parser artifacts already exist,True,0

In [6]:
def git_value(*args):
    result = subprocess.run(
        ["git", *args],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
    )

    return result.stdout.strip() if result.returncode == 0 else None


run_timestamp = datetime.now().astimezone()
PARSER_RUN_ID = f"TP_{run_timestamp.strftime('%Y%m%d_%H%M%S')}"

git_branch = git_value("branch", "--show-current")
git_commit = git_value("rev-parse", "HEAD")
git_status = git_value("status", "--short")

INVENTORY_MANIFEST_SHA256 = canonical_json_hash(INVENTORY_MANIFEST)

PARSER_CONTEXT = {
    "parser_version": PARSER_VERSION,
    "contract_version": DATA_CONTRACT["contract"]["version"],
    "parser_run_id": PARSER_RUN_ID,
    "run_timestamp": run_timestamp.isoformat(),
    "data_contract_sha256": actual_contract_hash,
    "inventory_manifest_sha256": INVENTORY_MANIFEST_SHA256,
    "python_version": platform.python_version(),
    "pandas_version": pd.__version__,
    "pyarrow_version": pa.__version__,
    "platform": platform.platform(),
    "locale": locale.getlocale(),
    "local_timezone": str(run_timestamp.tzinfo),
    "tzname": tuple(time.tzname),
    "git_branch": git_branch,
    "git_commit": git_commit,
    "git_dirty": bool(git_status),
}

PARSER_ENTRY_READY = entry_failures.empty

parser_entry_summary = pd.DataFrame({
    "item": [
        "Parser version",
        "Contract version",
        "Inventory ready",
        "Inventory blockers",
        "Contract hash match",
        "Response hash match",
        "Required response rows",
        "Required sessions",
        "Transcript files",
        "Required transcript fields",
        "Unicode policy",
        "Byte-safe ingestion",
        "Natural ID sorting",
        "Parser label-blind",
        "Candidate is canonical",
        "Entry failures",
        "PARSER_ENTRY_READY",
    ],
    "value": [
        PARSER_VERSION,
        DATA_CONTRACT["contract"]["version"],
        INVENTORY_MANIFEST["inventory"]["inventory_ready"],
        INVENTORY_MANIFEST["blocking_failures"],
        actual_contract_hash == expected_contract_hash,
        actual_responses_hash == expected_responses_hash,
        len(response_session_projection),
        len(REQUIRED_SESSION_IDS),
        len(TRANSCRIPT_FILES),
        len(required_transcript_fields),
        DATA_CONTRACT["text_normalization"]["unicode_form"],
        DATA_CONTRACT["ingestion_policy"]["hash_and_parse_same_bytes"],
        DATA_CONTRACT["utterance_id_policy"]["natural_sort_required"],
        DATA_CONTRACT["parser_restrictions"]["label_blind"],
        DATA_CONTRACT["candidate_outputs"]["candidate_is_canonical"],
        len(entry_failures),
        PARSER_ENTRY_READY,
    ],
})

display(parser_entry_summary)

assert PARSER_ENTRY_READY, (
    "Section 2.0 failed.\n\n"
    + entry_failures[["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 60)
print("TRACE THE ACE — TRUE TURN PARSER ENTRY")
print("=" * 60)
print(f"Parser version   : {PARSER_VERSION}")
print(f"Contract version : {DATA_CONTRACT['contract']['version']}")
print(f"Response rows    : {len(response_session_projection):,}")
print(f"Sessions         : {len(REQUIRED_SESSION_IDS):,}")
print(f"Transcript files : {len(TRANSCRIPT_FILES):,}")
print(f"Entry failures   : {len(entry_failures)}")
print(f"PARSER ENTRY     : {PARSER_ENTRY_READY}")
print("=" * 60)

                          item  value
0               Parser version    1.0
1             Contract version    1.1
2              Inventory ready   True
3           Inventory blockers      0
4          Contract hash match   True
5          Response hash match   True
6       Required response rows  35072
7            Required sessions  22821
8             Transcript files  22821
9   Required transcript fields      5
10              Unicode policy    NFC
11         Byte-safe ingestion   True
12          Natural ID sorting   True
13          Parser label-blind   True
14      Candidate is canonical  False
15              Entry failures      0
16          PARSER_ENTRY_READY   True

============================================================
TRACE THE ACE — TRUE TURN PARSER ENTRY
============================================================
Parser version   : 1.0
Contract version : 1.1
Response rows    : 35,072
Sessions         : 22,821
Transcript files : 22,821
Entry failures   : 0
PARSER ENTRY     : True
============================================================

# Section 2.1 — Exact Raw Utterance Ingestion

This section defines the byte-safe ingestion layer used by the True Turn Parser.
Each transcript file is read once as raw bytes and the same bytes are hashed and parsed.
UTF-8 and UTF-8 BOM are supported with strict decoding and no silent character replacement.
CSV quoting, embedded commas, and multiline fields must be interpreted without changing field values.
Literal `NA`, empty strings, numeric-looking IDs, and mathematical Unicode remain raw strings.
One logical CSV data record corresponds to one source-row candidate.
Malformed row widths, invalid encoding, missing headers, and duplicate headers are explicitly flagged.
No role mapping, timestamp parsing, text normalization, or turn ordering is performed here.
The ingestion engine is tested on synthetic edge cases and deterministic real transcript files.
The section ends with the `INGESTION_POLICY_READY` hard gate.

In [7]:
import codecs
import csv
import io


assert PARSER_ENTRY_READY, "Section 2.0 must pass before Section 2.1."


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def ingestion_result(relative_path, file_bytes):
    return {
        "metadata": {
            "relative_file": relative_path,
            "file_size_bytes": len(file_bytes),
            "file_sha256": sha256_bytes(file_bytes),
            "has_utf8_bom": file_bytes.startswith(codecs.BOM_UTF8),
            "encoding": INGESTION_CONFIG["encoding"],
            "header": None,
            "row_count": 0,
            "parsed_row_count": 0,
            "malformed_row_count": 0,
            "status": "UNPARSED",
            "error": None,
        },
        "rows": [],
        "row_issues": [],
    }


def parse_transcript_bytes(file_bytes, relative_path="<memory>"):
    result = ingestion_result(relative_path, file_bytes)
    meta, rows, issues = result["metadata"], result["rows"], result["row_issues"]

    try:
        stream = io.TextIOWrapper(
            io.BytesIO(file_bytes),
            encoding=INGESTION_CONFIG["encoding"],
            errors="strict",
            newline="",
        )
        reader = csv.reader(stream, strict=True)
        header = next(reader, None)

        if header is None:
            meta["status"] = "EMPTY_FILE"
            return result

        meta["header"] = tuple(header)

        if len(header) != len(set(header)):
            meta["status"] = "DUPLICATE_HEADER"
            return result

        missing = set(INGESTION_CONFIG["required_fields"]) - set(header)

        if missing:
            meta["status"] = "MISSING_REQUIRED_FIELDS"
            meta["error"] = f"Missing fields: {sorted(missing)}"
            return result

        field_index = {name: header.index(name) for name in INGESTION_CONFIG["required_fields"]}

        for source_row_index, row in enumerate(reader):
            meta["row_count"] += 1

            if len(row) != len(header):
                meta["malformed_row_count"] += 1
                issues.append({
                    "source_row_index": source_row_index,
                    "issue": "ROW_WIDTH_MISMATCH",
                    "expected_columns": len(header),
                    "observed_columns": len(row),
                })
                continue

            rows.append({
                "session_id_raw": row[field_index["session_id"]],
                "utterance_id_raw": row[field_index["utterance_id"]],
                "role_raw": row[field_index["role"]],
                "content_raw": row[field_index["content"]],
                "timestamp_raw": row[field_index["timestamp"]],
                "source_file_relative": relative_path,
                "source_row_index": source_row_index,
                "file_sha256": meta["file_sha256"],
            })

        meta["parsed_row_count"] = len(rows)

        if meta["row_count"] == 0:
            meta["status"] = "ZERO_DATA_ROWS"
        elif meta["malformed_row_count"] > 0:
            meta["status"] = "ROW_WIDTH_MISMATCH"
        else:
            meta["status"] = "READ_OK"

    except UnicodeDecodeError as e:
        meta["status"] = "DECODE_ERROR"
        meta["error"] = f"{type(e).__name__}: {e}"

    except csv.Error as e:
        meta["status"] = "CSV_ERROR"
        meta["error"] = f"{type(e).__name__}: {e}"

    return result


def read_transcript_file(path, root=TRANSCRIPT_ROOT):
    path = Path(path)
    relative_path = path.relative_to(root).as_posix()
    file_bytes = path.read_bytes()
    return parse_transcript_bytes(file_bytes, relative_path)


policy = DATA_CONTRACT["ingestion_policy"]

INGESTION_CONFIG = {
    "version": policy["version"],
    "encoding": policy["encoding"],
    "csv_parser": policy["csv_parser"],
    "read_file_bytes_once": policy["read_file_bytes_once"],
    "hash_and_parse_same_bytes": policy["hash_and_parse_same_bytes"],
    "automatic_na_coercion": policy["automatic_na_coercion"],
    "automatic_numeric_coercion": policy["automatic_numeric_coercion"],
    "preserve_empty_string": policy["preserve_empty_string"],
    "preserve_literal_NA": policy["preserve_literal_NA"],
    "quoted_commas_supported": policy["quoted_commas_supported"],
    "quoted_multiline_fields_supported": policy["quoted_multiline_fields_supported"],
    "source_row_index_base": policy["source_row_index_base"],
    "header_excluded_from_row_index": policy["header_excluded_from_row_index"],
    "required_fields": DATA_CONTRACT["transcript_schema"]["required_fields"],
    "decode_errors": "strict",
}

INGESTION_CONFIG_SHA256 = canonical_json_hash(INGESTION_CONFIG)

ingestion_policy_checks = pd.DataFrame([
    check_row("Read file bytes once", INGESTION_CONFIG["read_file_bytes_once"], True),
    check_row("Hash and parse same bytes", INGESTION_CONFIG["hash_and_parse_same_bytes"], True),
    check_row("Encoding is UTF-8 BOM safe", INGESTION_CONFIG["encoding"] == "utf-8-sig", INGESTION_CONFIG["encoding"]),
    check_row("Strict decoding enabled", INGESTION_CONFIG["decode_errors"] == "strict", INGESTION_CONFIG["decode_errors"]),
    check_row("Automatic NA coercion disabled", not INGESTION_CONFIG["automatic_na_coercion"], INGESTION_CONFIG["automatic_na_coercion"]),
    check_row("Automatic numeric coercion disabled", not INGESTION_CONFIG["automatic_numeric_coercion"], INGESTION_CONFIG["automatic_numeric_coercion"]),
    check_row("Empty strings preserved", INGESTION_CONFIG["preserve_empty_string"], True),
    check_row("Literal NA preserved", INGESTION_CONFIG["preserve_literal_NA"], True),
    check_row("Quoted multiline supported", INGESTION_CONFIG["quoted_multiline_fields_supported"], True),
    check_row("Source row index is zero-based", INGESTION_CONFIG["source_row_index_base"] == 0, INGESTION_CONFIG["source_row_index_base"]),
])

display(ingestion_policy_checks)

assert ingestion_policy_checks["passed"].all(), "Ingestion policy validation failed."

                                 check  passed     detail
0                 Read file bytes once    True       True
1            Hash and parse same bytes    True       True
2           Encoding is UTF-8 BOM safe    True  utf-8-sig
3              Strict decoding enabled    True     strict
4       Automatic NA coercion disabled    True      False
5  Automatic numeric coercion disabled    True      False
6              Empty strings preserved    True       True
7                 Literal NA preserved    True       True
8           Quoted multiline supported    True       True
9       Source row index is zero-based    True          0

In [8]:
def run_ingestion_test(name, file_bytes, validator):
    result = parse_transcript_bytes(file_bytes, f"synthetic/{name}.csv")

    try:
        passed = bool(validator(result))
        detail = result["metadata"]["status"]
    except Exception as e:
        passed = False
        detail = f"{type(e).__name__}: {e}"

    return {
        "test": name,
        "passed": passed,
        "detail": detail,
    }


HEADER = "session_id,utterance_id,role,content,timestamp\n"

tests = [
    (
        "T01_NORMAL_CSV",
        (HEADER + "s1,U1,student,hello,00:01\n").encode("utf-8"),
        lambda r: r["metadata"]["status"] == "READ_OK"
        and r["rows"][0]["content_raw"] == "hello",
    ),
    (
        "T02_UTF8_BOM",
        codecs.BOM_UTF8 + (HEADER + "s1,U1,student,hello,00:01\n").encode("utf-8"),
        lambda r: r["metadata"]["status"] == "READ_OK"
        and r["metadata"]["has_utf8_bom"] is True
        and r["metadata"]["header"][0] == "session_id",
    ),
    (
        "T03_LITERAL_NA",
        (HEADER + "s1,U1,student,NA,00:01\n").encode("utf-8"),
        lambda r: r["rows"][0]["content_raw"] == "NA",
    ),
    (
        "T04_EMPTY_FIELD",
        (HEADER + "s1,U1,student,,00:01\n").encode("utf-8"),
        lambda r: r["rows"][0]["content_raw"] == "",
    ),
    (
        "T05_NUMERIC_LOOKING_ID",
        (HEADER + "s1,0012,student,hello,00:01\n").encode("utf-8"),
        lambda r: r["rows"][0]["utterance_id_raw"] == "0012"
        and isinstance(r["rows"][0]["utterance_id_raw"], str),
    ),
    (
        "T06_QUOTED_COMMA",
        (HEADER + 's1,U1,student,"I think 1,250 is correct.",00:01\n').encode("utf-8"),
        lambda r: r["rows"][0]["content_raw"] == "I think 1,250 is correct.",
    ),
    (
        "T07_MULTILINE_CONTENT",
        (HEADER + 's1,U1,student,"first line\nsecond line",00:01\n').encode("utf-8"),
        lambda r: r["metadata"]["row_count"] == 1
        and r["rows"][0]["content_raw"] == "first line\nsecond line",
    ),
    (
        "T08_MATH_UNICODE",
        (HEADER + 's1,U1,student,"x² ≤ ½",00:01\n').encode("utf-8"),
        lambda r: r["rows"][0]["content_raw"] == "x² ≤ ½",
    ),
    (
        "T09_ROW_WIDTH_MISMATCH",
        (HEADER + "s1,U1,student,hello\n").encode("utf-8"),
        lambda r: r["metadata"]["status"] == "ROW_WIDTH_MISMATCH"
        and r["metadata"]["malformed_row_count"] == 1
        and r["metadata"]["row_count"] == 1,
    ),
    (
        "T10_INVALID_UTF8",
        HEADER.encode("utf-8") + b"s1,U1,student,\xff,00:01\n",
        lambda r: r["metadata"]["status"] == "DECODE_ERROR",
    ),
]

ingestion_contract_tests = pd.DataFrame([
    run_ingestion_test(name, data, validator)
    for name, data, validator in tests
])

INGESTION_TESTS_PASSED = bool(ingestion_contract_tests["passed"].all())

display(ingestion_contract_tests)

print(
    f"Passed ingestion tests: "
    f"{int(ingestion_contract_tests['passed'].sum())} / {len(ingestion_contract_tests)}"
)

assert INGESTION_TESTS_PASSED, (
    "Section 2.1 ingestion contract tests failed.\n\n"
    + ingestion_contract_tests.loc[
        ~ingestion_contract_tests["passed"],
        ["test", "detail"],
    ].to_string(index=False)
)

                     test  passed              detail
0          T01_NORMAL_CSV    True             READ_OK
1            T02_UTF8_BOM    True             READ_OK
2          T03_LITERAL_NA    True             READ_OK
3         T04_EMPTY_FIELD    True             READ_OK
4  T05_NUMERIC_LOOKING_ID    True             READ_OK
5        T06_QUOTED_COMMA    True             READ_OK
6   T07_MULTILINE_CONTENT    True             READ_OK
7        T08_MATH_UNICODE    True             READ_OK
8  T09_ROW_WIDTH_MISMATCH    True  ROW_WIDTH_MISMATCH
9        T10_INVALID_UTF8    True        DECODE_ERROR

Passed ingestion tests: 10 / 10

In [9]:
def smoke_file_check(path):
    result = read_transcript_file(path)
    meta, rows = result["metadata"], result["rows"]

    indices = [row["source_row_index"] for row in rows]

    raw_strings_ok = all(
        isinstance(row[field], str)
        for row in rows
        for field in [
            "session_id_raw",
            "utterance_id_raw",
            "role_raw",
            "content_raw",
            "timestamp_raw",
        ]
    )

    indices_ok = indices == list(range(len(rows)))
    relative_path_ok = "\\" not in meta["relative_file"]

    passed = all([
        meta["status"] == "READ_OK",
        meta["row_count"] > 0,
        meta["row_count"] == meta["parsed_row_count"],
        meta["malformed_row_count"] == 0,
        set(INGESTION_CONFIG["required_fields"]).issubset(meta["header"]),
        raw_strings_ok,
        indices_ok,
        relative_path_ok,
    ])

    return {
        "relative_file": meta["relative_file"],
        "rows": meta["row_count"],
        "columns": len(meta["header"]) if meta["header"] else 0,
        "has_bom": meta["has_utf8_bom"],
        "status": meta["status"],
        "raw_strings": raw_strings_ok,
        "row_index_contiguous": indices_ok,
        "posix_relative_path": relative_path_ok,
        "passed": passed,
    }


smoke_indices = sorted(set([
    0,
    len(TRANSCRIPT_FILES) // 2,
    len(TRANSCRIPT_FILES) - 1,
]))

SMOKE_FILES = [TRANSCRIPT_FILES[i] for i in smoke_indices]

ingestion_smoke_summary = pd.DataFrame([
    smoke_file_check(path)
    for path in SMOKE_FILES
])

smoke_passed = bool(ingestion_smoke_summary["passed"].all())

ingestion_failures = int((~ingestion_policy_checks["passed"]).sum())
test_failures = int((~ingestion_contract_tests["passed"]).sum())
smoke_failures = int((~ingestion_smoke_summary["passed"]).sum())

INGESTION_POLICY_READY = (
    PARSER_ENTRY_READY
    and ingestion_failures == 0
    and test_failures == 0
    and smoke_failures == 0
)

ingestion_gate_summary = pd.DataFrame({
    "item": [
        "Ingestion policy version",
        "Encoding",
        "Hash and parse same bytes",
        "Automatic NA coercion",
        "Automatic numeric coercion",
        "Contract tests",
        "Passed contract tests",
        "Real smoke files",
        "Passed smoke files",
        "Policy failures",
        "Test failures",
        "Smoke failures",
        "INGESTION_CONFIG_SHA256",
        "INGESTION_POLICY_READY",
    ],
    "value": [
        INGESTION_CONFIG["version"],
        INGESTION_CONFIG["encoding"],
        INGESTION_CONFIG["hash_and_parse_same_bytes"],
        INGESTION_CONFIG["automatic_na_coercion"],
        INGESTION_CONFIG["automatic_numeric_coercion"],
        len(ingestion_contract_tests),
        int(ingestion_contract_tests["passed"].sum()),
        len(ingestion_smoke_summary),
        int(ingestion_smoke_summary["passed"].sum()),
        ingestion_failures,
        test_failures,
        smoke_failures,
        INGESTION_CONFIG_SHA256,
        INGESTION_POLICY_READY,
    ],
})

display(ingestion_smoke_summary)
display(ingestion_gate_summary)

assert INGESTION_POLICY_READY, (
    "Section 2.1 failed. Do not continue to raw format discovery."
)

print("\n" + "=" * 62)
print("TRACE THE ACE — EXACT RAW INGESTION READY")
print("=" * 62)
print(f"Contract tests   : {int(ingestion_contract_tests['passed'].sum())}/{len(ingestion_contract_tests)}")
print(f"Real smoke files : {int(ingestion_smoke_summary['passed'].sum())}/{len(ingestion_smoke_summary)}")
print(f"Policy failures  : {ingestion_failures}")
print(f"Test failures    : {test_failures}")
print(f"Smoke failures   : {smoke_failures}")
print(f"INGESTION READY  : {INGESTION_POLICY_READY}")
print("=" * 62)

,relative_file,rows,columns,has_bom,status,raw_strings,row_index_contiguous,posix_relative_path,passed
0,aaaedit.csv,254,5,False,READ_OK,True,True,True,True
1,gzupluu.csv,305,5,False,READ_OK,True,True,True,True
2,nxmkhia.csv,371,5,False,READ_OK,True,True,True,True

,item,value
0,Ingestion policy version,1.0
1,Encoding,utf-8-sig
2,Hash and parse same bytes,True
3,Automatic NA coercion,False
4,Automatic numeric coercion,False
5,Contract tests,10
6,Passed contract tests,10
7,Real smoke files,3
8,Passed smoke files,3
9,Policy failures,0
10,Test failures,0
11,Smoke failures,0
12,INGESTION_CONFIG_SHA256,4cbd828eccee4072a87d2292cdc4fcfd6431a5f4e687cd...
13,INGESTION_POLICY_READY,True

==============================================================
TRACE THE ACE — EXACT RAW INGESTION READY
==============================================================
Contract tests   : 10/10
Real smoke files : 3/3
Policy failures  : 0
Test failures    : 0
Smoke failures   : 0
INGESTION READY  : True
==============================================================

# Section 2.2 — Full Raw Format Discovery

This section profiles the complete raw transcript corpus using the verified byte-safe ingestion engine.
Every transcript file is scanned independently without building one giant in-memory transcript table.
The full raw role vocabulary, timestamp families, and utterance-ID families are discovered from source values.
File-level row counts, schema signatures, BOM usage, multiline content, and content-size statistics are recorded.
Each file must contain exactly one valid internal session and each session must belong to exactly one source file.
Internal session IDs are compared with filenames and the frozen required-session population.
Timestamp and utterance-ID values are classified by raw format only; they are not parsed or reordered.
Raw content is never normalized or modified during discovery.
This section establishes the corpus format facts needed to freeze the parser schema and later parsing policies.
The section ends with the `RAW_FORMAT_DISCOVERY_READY` gate.

In [10]:
from collections import Counter, defaultdict
import re


assert INGESTION_POLICY_READY, "Section 2.1 must pass before Section 2.2."

FORMAT_DISCOVERY_VERSION = "1.0"


def is_blank_raw(value):
    return value == "" or value.strip() == ""


def classify_timestamp_raw(value):
    value = value.strip()

    if not value:
        return "MISSING"
    if re.fullmatch(r"\d{1,2}:\d{2}", value):
        return "TIME_HM"
    if re.fullmatch(r"\d{1,2}:\d{2}:\d{2}", value):
        return "TIME_HMS"
    if re.fullmatch(r"\d{1,2}:\d{2}:\d{2}[.,]\d+", value):
        return "TIME_HMS_FRACTION"
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        return "DATE_YMD"
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}[T ]\d{1,2}:\d{2}(?::\d{2}(?:[.,]\d+)?)?", value):
        return "DATETIME_NAIVE"
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}[T ]\d{1,2}:\d{2}(?::\d{2}(?:[.,]\d+)?)?(?:Z|[+-]\d{2}:?\d{2})", value):
        return "DATETIME_TZ"
    if re.fullmatch(r"[+-]?(?:\d+(?:\.\d+)?|\.\d+)", value):
        return "NUMERIC"

    return "OTHER"


def classify_utterance_id_raw(value):
    value = value.strip()

    if not value:
        return "MISSING"
    if re.fullmatch(r"\d+", value):
        return "INTEGER"
    if re.fullmatch(r"[^\d]+\d+", value):
        return "PREFIX_NUMERIC"
    if re.fullmatch(r"\d+[^\d]+", value):
        return "SUFFIX_NUMERIC"
    if re.search(r"\d", value) and re.search(r"[A-Za-z]", value):
        return "MIXED_ALNUM"

    return "OTHER"


def raw_shape(value):
    value = value.strip()

    if not value:
        return "<EMPTY>"

    value = re.sub(r"\d", "9", value)
    value = re.sub(r"[A-Za-z]", "A", value)

    return value


def update_distribution(store, key, session_id, example, max_examples=3):
    item = store.setdefault(
        key,
        {"row_count": 0, "sessions": set(), "examples": []},
    )

    item["row_count"] += 1

    if session_id:
        item["sessions"].add(session_id)

    if example not in item["examples"] and len(item["examples"]) < max_examples:
        item["examples"].append(example)


def distribution_frame(store, key_name):
    rows = []

    for key, item in store.items():
        rows.append({
            key_name: key,
            "row_count": item["row_count"],
            "session_count": len(item["sessions"]),
            "examples": tuple(item["examples"]),
        })

    return pd.DataFrame(rows).sort_values(
        ["row_count", key_name],
        ascending=[False, True],
    ).reset_index(drop=True)


MATH_UNICODE_PATTERN = re.compile(
    r"[¹²³⁴⁵⁶⁷⁸⁹⁰½⅓⅔¼¾≤≥≠≈√∞×÷±∑∫π]"
)

print(f"FORMAT_DISCOVERY_VERSION: {FORMAT_DISCOVERY_VERSION}")

FORMAT_DISCOVERY_VERSION: 1.0

In [11]:
role_rows = Counter()
role_sessions = defaultdict(set)

timestamp_families = {}
timestamp_shapes = {}

utterance_id_families = {}
utterance_id_shapes = {}

file_profiles = []

TOTAL_RAW_ROWS = 0
TOTAL_PARSED_ROWS = 0

for file_number, path in enumerate(TRANSCRIPT_FILES, start=1):
    result = read_transcript_file(path)
    meta, rows = result["metadata"], result["rows"]

    relative_file = meta["relative_file"]
    file_stem = Path(relative_file).stem
    header = tuple(meta["header"]) if meta["header"] else tuple()

    session_values = {
        row["session_id_raw"]
        for row in rows
        if not is_blank_raw(row["session_id_raw"])
    }

    internal_session_id = (
        next(iter(session_values))
        if len(session_values) == 1
        else None
    )

    blank_session_rows = 0
    blank_role_rows = 0
    blank_timestamp_rows = 0
    blank_utterance_id_rows = 0

    multiline_content_rows = 0
    empty_content_rows = 0
    literal_na_content_rows = 0
    non_ascii_content_rows = 0
    math_unicode_rows = 0

    max_content_chars = 0
    max_content_lines = 0

    raw_role_values = set()

    for row in rows:
        session_id = row["session_id_raw"]
        role_raw = row["role_raw"]
        timestamp_raw = row["timestamp_raw"]
        utterance_id_raw = row["utterance_id_raw"]
        content_raw = row["content_raw"]

        blank_session_rows += int(is_blank_raw(session_id))
        blank_role_rows += int(is_blank_raw(role_raw))
        blank_timestamp_rows += int(is_blank_raw(timestamp_raw))
        blank_utterance_id_rows += int(is_blank_raw(utterance_id_raw))

        empty_content_rows += int(content_raw == "")
        literal_na_content_rows += int(content_raw == "NA")
        multiline_content_rows += int("\n" in content_raw or "\r" in content_raw)
        non_ascii_content_rows += int(any(ord(char) > 127 for char in content_raw))
        math_unicode_rows += int(bool(MATH_UNICODE_PATTERN.search(content_raw)))

        max_content_chars = max(max_content_chars, len(content_raw))
        max_content_lines = max(max_content_lines, content_raw.count("\n") + 1)

        raw_role_values.add(role_raw)
        role_rows[role_raw] += 1

        if session_id:
            role_sessions[role_raw].add(session_id)

        timestamp_family = classify_timestamp_raw(timestamp_raw)
        timestamp_signature = raw_shape(timestamp_raw)

        update_distribution(
            timestamp_families,
            timestamp_family,
            session_id,
            timestamp_raw,
        )
        update_distribution(
            timestamp_shapes,
            timestamp_signature,
            session_id,
            timestamp_raw,
        )

        utterance_family = classify_utterance_id_raw(utterance_id_raw)
        utterance_signature = raw_shape(utterance_id_raw)

        update_distribution(
            utterance_id_families,
            utterance_family,
            session_id,
            utterance_id_raw,
        )
        update_distribution(
            utterance_id_shapes,
            utterance_signature,
            session_id,
            utterance_id_raw,
        )

    schema_signature = (
        hashlib.sha256(
            "\x1f".join(header).encode("utf-8")
        ).hexdigest()
        if header else None
    )

    required_schema_ok = required_transcript_fields.issubset(header)

    file_profiles.append({
        "relative_file": relative_file,
        "file_stem": file_stem,
        "file_sha256": meta["file_sha256"],
        "file_size_bytes": meta["file_size_bytes"],
        "has_utf8_bom": meta["has_utf8_bom"],
        "read_status": meta["status"],
        "column_count": len(header),
        "header_signature": schema_signature,
        "required_schema_ok": required_schema_ok,
        "raw_row_count": meta["row_count"],
        "parsed_row_count": meta["parsed_row_count"],
        "internal_session_count": len(session_values),
        "internal_session_id": internal_session_id,
        "filename_session_match": (
            internal_session_id == file_stem
            if internal_session_id is not None
            else False
        ),
        "required_session_member": (
            internal_session_id in REQUIRED_SESSION_ID_SET
            if internal_session_id is not None
            else False
        ),
        "distinct_role_count": len(raw_role_values),
        "blank_session_rows": blank_session_rows,
        "blank_role_rows": blank_role_rows,
        "blank_timestamp_rows": blank_timestamp_rows,
        "blank_utterance_id_rows": blank_utterance_id_rows,
        "empty_content_rows": empty_content_rows,
        "literal_na_content_rows": literal_na_content_rows,
        "multiline_content_rows": multiline_content_rows,
        "non_ascii_content_rows": non_ascii_content_rows,
        "math_unicode_rows": math_unicode_rows,
        "max_content_chars": max_content_chars,
        "max_content_lines": max_content_lines,
    })

    TOTAL_RAW_ROWS += meta["row_count"]
    TOTAL_PARSED_ROWS += meta["parsed_row_count"]

    if file_number % 2500 == 0 or file_number == len(TRANSCRIPT_FILES):
        print(
            f"Scanned {file_number:,}/{len(TRANSCRIPT_FILES):,} files | "
            f"Raw rows: {TOTAL_RAW_ROWS:,}"
        )


raw_format_file_profile = pd.DataFrame(file_profiles)

role_raw_summary = pd.DataFrame([
    {
        "role_raw": role,
        "role_match_key": role.strip().casefold(),
        "row_count": count,
        "session_count": len(role_sessions[role]),
    }
    for role, count in role_rows.items()
]).sort_values(
    ["row_count", "role_raw"],
    ascending=[False, True],
).reset_index(drop=True)

timestamp_family_summary = distribution_frame(
    timestamp_families,
    "timestamp_family",
)

timestamp_shape_summary = distribution_frame(
    timestamp_shapes,
    "timestamp_shape",
)

utterance_id_family_summary = distribution_frame(
    utterance_id_families,
    "utterance_id_family",
)

utterance_id_shape_summary = distribution_frame(
    utterance_id_shapes,
    "utterance_id_shape",
)

display(role_raw_summary)
display(timestamp_family_summary)
display(utterance_id_family_summary)

Scanned 2,500/22,821 files | Raw rows: 664,944
Scanned 5,000/22,821 files | Raw rows: 1,336,554
Scanned 7,500/22,821 files | Raw rows: 2,012,198
Scanned 10,000/22,821 files | Raw rows: 2,692,417
Scanned 12,500/22,821 files | Raw rows: 3,364,873
Scanned 15,000/22,821 files | Raw rows: 4,034,815
Scanned 17,500/22,821 files | Raw rows: 4,710,356
Scanned 20,000/22,821 files | Raw rows: 5,377,157
Scanned 22,500/22,821 files | Raw rows: 6,052,016
Scanned 22,821/22,821 files | Raw rows: 6,139,854

     role_raw role_match_key  row_count  session_count
0       tutor          tutor    3196001          22821
1     student        student    2697152          22816
2  background     background     246701          22665

  timestamp_family  row_count  session_count                        examples
0         TIME_HMS    6139854          22821  (00:00:00, 00:00:01, 00:00:07)

  utterance_id_family  row_count  session_count   examples
0             INTEGER    6139854          22821  (0, 1, 2)

In [12]:
def format_check(check, passed, detail, required=True):
    return {
        "check": check,
        "required": required,
        "passed": bool(passed),
        "detail": detail,
    }


single_session_profile = raw_format_file_profile[
    raw_format_file_profile["internal_session_count"] == 1
].copy()

discovered_session_ids = set(
    single_session_profile["internal_session_id"].dropna()
)

missing_required_sessions = (
    set(REQUIRED_SESSION_ID_SET) - discovered_session_ids
)

unexpected_sessions = (
    discovered_session_ids - set(REQUIRED_SESSION_ID_SET)
)

duplicate_source_sessions = (
    single_session_profile["internal_session_id"]
    .value_counts()
)

duplicate_source_sessions = duplicate_source_sessions[
    duplicate_source_sessions > 1
]

schema_distribution = (
    raw_format_file_profile
    .groupby(
        ["header_signature", "column_count", "required_schema_ok"],
        dropna=False,
    )
    .size()
    .reset_index(name="file_count")
    .sort_values("file_count", ascending=False)
)

unreadable_files = int(
    raw_format_file_profile["read_status"].ne("READ_OK").sum()
)

zero_row_files = int(
    raw_format_file_profile["raw_row_count"].eq(0).sum()
)

missing_schema_files = int(
    (~raw_format_file_profile["required_schema_ok"]).sum()
)

no_session_files = int(
    raw_format_file_profile["internal_session_count"].eq(0).sum()
)

multi_session_files = int(
    raw_format_file_profile["internal_session_count"].gt(1).sum()
)

blank_session_rows = int(
    raw_format_file_profile["blank_session_rows"].sum()
)

filename_session_mismatches = int(
    (
        raw_format_file_profile["internal_session_count"].eq(1)
        & ~raw_format_file_profile["filename_session_match"]
    ).sum()
)

raw_parsed_row_difference = int(
    TOTAL_RAW_ROWS - TOTAL_PARSED_ROWS
)

format_discovery_checks = pd.DataFrame([
    format_check(
        "All registered transcript files scanned",
        len(raw_format_file_profile) == len(TRANSCRIPT_FILES),
        f"{len(raw_format_file_profile)} / {len(TRANSCRIPT_FILES)}"
    ),
    format_check(
        "All transcript files are readable",
        unreadable_files == 0,
        unreadable_files
    ),
    format_check(
        "No zero-data-row transcript files",
        zero_row_files == 0,
        zero_row_files
    ),
    format_check(
        "All files contain required transcript schema",
        missing_schema_files == 0,
        missing_schema_files
    ),
    format_check(
        "Every raw logical row was ingested",
        raw_parsed_row_difference == 0,
        f"raw={TOTAL_RAW_ROWS}, parsed={TOTAL_PARSED_ROWS}"
    ),
    format_check(
        "No raw rows have blank session IDs",
        blank_session_rows == 0,
        blank_session_rows
    ),
    format_check(
        "Every file contains exactly one internal session",
        no_session_files == 0 and multi_session_files == 0,
        f"no_session={no_session_files}, multi_session={multi_session_files}"
    ),
    format_check(
        "Filename and internal session IDs match",
        filename_session_mismatches == 0,
        filename_session_mismatches
    ),
    format_check(
        "No session appears in multiple source files",
        len(duplicate_source_sessions) == 0,
        len(duplicate_source_sessions)
    ),
    format_check(
        "No required transcript session is missing",
        len(missing_required_sessions) == 0,
        len(missing_required_sessions)
    ),
    format_check(
        "No unexpected transcript session exists",
        len(unexpected_sessions) == 0,
        len(unexpected_sessions)
    ),
    format_check(
        "Discovered session population matches frozen population",
        discovered_session_ids == set(REQUIRED_SESSION_ID_SET),
        f"discovered={len(discovered_session_ids)}, required={len(REQUIRED_SESSION_ID_SET)}"
    ),
    format_check(
        "Single transcript schema variant",
        len(schema_distribution) == 1,
        len(schema_distribution),
        required=False
    ),
])

format_failures = format_discovery_checks[
    format_discovery_checks["required"]
    & ~format_discovery_checks["passed"]
]

format_warnings = format_discovery_checks[
    ~format_discovery_checks["required"]
    & ~format_discovery_checks["passed"]
]

RAW_FORMAT_DISCOVERY_READY = format_failures.empty

format_discovery_summary = pd.DataFrame({
    "item": [
        "Transcript files scanned",
        "Total raw logical rows",
        "Total parsed raw rows",
        "Required sessions",
        "Discovered sessions",
        "Missing required sessions",
        "Unexpected sessions",
        "Files with no session",
        "Multi-session files",
        "Duplicate source sessions",
        "Filename-session mismatches",
        "Schema variants",
        "Unique raw role values",
        "Timestamp families",
        "Utterance-ID families",
        "Blank role rows",
        "Blank timestamp rows",
        "Blank utterance-ID rows",
        "Multiline content rows",
        "Math-Unicode content rows",
        "Required failures",
        "Non-blocking warnings",
        "RAW_FORMAT_DISCOVERY_READY",
    ],
    "value": [
        len(raw_format_file_profile),
        TOTAL_RAW_ROWS,
        TOTAL_PARSED_ROWS,
        len(REQUIRED_SESSION_ID_SET),
        len(discovered_session_ids),
        len(missing_required_sessions),
        len(unexpected_sessions),
        no_session_files,
        multi_session_files,
        len(duplicate_source_sessions),
        filename_session_mismatches,
        len(schema_distribution),
        len(role_raw_summary),
        len(timestamp_family_summary),
        len(utterance_id_family_summary),
        int(raw_format_file_profile["blank_role_rows"].sum()),
        int(raw_format_file_profile["blank_timestamp_rows"].sum()),
        int(raw_format_file_profile["blank_utterance_id_rows"].sum()),
        int(raw_format_file_profile["multiline_content_rows"].sum()),
        int(raw_format_file_profile["math_unicode_rows"].sum()),
        len(format_failures),
        len(format_warnings),
        RAW_FORMAT_DISCOVERY_READY,
    ],
})

display(schema_distribution)
display(timestamp_shape_summary.head(20))
display(utterance_id_shape_summary.head(20))
display(format_discovery_checks)
display(format_discovery_summary)

assert RAW_FORMAT_DISCOVERY_READY, (
    "Section 2.2 failed.\n\n"
    + format_failures[["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 64)
print("TRACE THE ACE — FULL RAW FORMAT DISCOVERY COMPLETE")
print("=" * 64)
print(f"Files scanned     : {len(raw_format_file_profile):,}")
print(f"Raw logical rows  : {TOTAL_RAW_ROWS:,}")
print(f"Sessions          : {len(discovered_session_ids):,}")
print(f"Raw role values   : {len(role_raw_summary):,}")
print(f"Timestamp families: {len(timestamp_family_summary):,}")
print(f"ID families       : {len(utterance_id_family_summary):,}")
print(f"Required failures : {len(format_failures)}")
print(f"Warnings          : {len(format_warnings)}")
print(f"FORMAT READY      : {RAW_FORMAT_DISCOVERY_READY}")
print("=" * 64)

,header_signature,column_count,required_schema_ok,file_count
0,5cccec9df92a667e146d9a7178caa50e74b30bfbe4dfad...,5,True,22821

  timestamp_shape  row_count  session_count                        examples
0        99:99:99    6139854          22821  (00:00:00, 00:00:01, 00:00:07)

  utterance_id_shape  row_count  session_count         examples
0                999    3865991          22522  (100, 101, 102)
1                 99    2045653          22821     (10, 11, 12)
2                  9     228210          22821        (0, 1, 2)

,check,required,passed,detail
0,All registered transcript files scanned,True,True,22821 / 22821
1,All transcript files are readable,True,True,0
2,No zero-data-row transcript files,True,True,0
3,All files contain required transcript schema,True,True,0
4,Every raw logical row was ingested,True,True,"raw=6139854, parsed=6139854"
5,No raw rows have blank session IDs,True,True,0
6,Every file contains exactly one internal session,True,True,"no_session=0, multi_session=0"
7,Filename and internal session IDs match,True,True,0
8,No session appears in multiple source files,True,True,0
9,No required transcript session is missing,True,True,0
10,No unexpected transcript session exists,True,True,0
11,Discovered session population matches frozen p...,True,True,"discovered=22821, required=22821"
12,Single transcript schema variant,False,True,1

                           item    value
0      Transcript files scanned    22821
1        Total raw logical rows  6139854
2         Total parsed raw rows  6139854
3             Required sessions    22821
4           Discovered sessions    22821
5     Missing required sessions        0
6           Unexpected sessions        0
7         Files with no session        0
8           Multi-session files        0
9     Duplicate source sessions        0
10  Filename-session mismatches        0
11              Schema variants        1
12       Unique raw role values        3
13           Timestamp families        1
14        Utterance-ID families        1
15              Blank role rows        0
16         Blank timestamp rows        0
17      Blank utterance-ID rows        0
18       Multiline content rows        0
19    Math-Unicode content rows     4182
20            Required failures        0
21        Non-blocking warnings        0
22   RAW_FORMAT_DISCOVERY_READY     True

================================================================
TRACE THE ACE — FULL RAW FORMAT DISCOVERY COMPLETE
================================================================
Files scanned     : 22,821
Raw logical rows  : 6,139,854
Sessions          : 22,821
Raw role values   : 3
Timestamp families: 1
ID families       : 1
Required failures : 0
Warnings          : 0
FORMAT READY      : True
================================================================

# Section 2.3 — Parser Schema Freeze

This section freezes the physical and logical schemas used by the True Turn Parser.
The schemas are derived from the complete raw-format discovery rather than sample assumptions.
Raw source fields remain non-nullable strings and original content uses Arrow `large_string`.
Parsed IDs, timestamps, ordering values, and other failure-sensitive derived fields may be nullable.
Status vocabularies are fixed before reconstruction begins.
The raw-row, turn-candidate, and session-candidate schemas are defined separately.
Parser schemas must remain label-blind and contain no objective, target, fold, or model-derived fields.
Numeric capacities and required provenance fields are validated before any full parser execution.
The schema configuration is hashed and stored only in the temporary parser work directory.
The section ends with the `PARSER_SCHEMA_READY` hard gate.

In [13]:
assert RAW_FORMAT_DISCOVERY_READY, "Section 2.2 must pass before Section 2.3."

PARSER_SCHEMA_VERSION = "1.0"

def field_spec(name, dtype, nullable):
    return {"name": name, "dtype": dtype, "nullable": bool(nullable)}

def unique_values(frame, column):
    return sorted(frame[column].astype(str).unique().tolist())

observed_roles = sorted(role_raw_summary["role_raw"].tolist())
observed_timestamp_families = unique_values(timestamp_family_summary, "timestamp_family")
observed_id_families = unique_values(utterance_id_family_summary, "utterance_id_family")
observed_id_shapes = unique_values(utterance_id_shape_summary, "utterance_id_shape")

max_file_rows = int(raw_format_file_profile["raw_row_count"].max())
max_id_digits = max(len(shape) for shape in observed_id_shapes if set(shape) == {"9"})

OBSERVED_FORMAT_CONTRACT = {
    "files": int(len(raw_format_file_profile)),
    "sessions": int(len(discovered_session_ids)),
    "raw_rows": int(TOTAL_RAW_ROWS),
    "roles": observed_roles,
    "timestamp_families": observed_timestamp_families,
    "timestamp_precision": "SECOND",
    "timestamp_timezone": "NOT_APPLICABLE",
    "utterance_id_families": observed_id_families,
    "utterance_id_shapes": observed_id_shapes,
    "max_file_rows": max_file_rows,
    "max_utterance_id_digits": max_id_digits,
}

STATUS_VOCABULARIES = {
    "canonical_role": ["student", "tutor", "background", "unknown"],
    "role_status": ["VALID", "UNKNOWN", "MISSING"],
    "utterance_id_status": [
        "VALID",
        "MISSING",
        "UNPARSEABLE",
        "DUPLICATED_WITHIN_SESSION",
        "NATURAL_KEY_COLLISION",
    ],
    "timestamp_status": [
        "VALID",
        "MISSING",
        "UNPARSEABLE",
        "OUT_OF_RANGE",
        "AMBIGUOUS_ROLLOVER",
    ],
    "timestamp_kind": ["TIME_HMS", "MISSING", "OTHER"],
    "timestamp_precision": ["SECOND", "UNKNOWN"],
    "timezone_status": ["NOT_APPLICABLE", "NAIVE", "AWARE", "UNKNOWN"],
    "ordering_method": [
        "TIMESTAMP_PRIMARY",
        "UTTERANCE_ID_FALLBACK",
        "SOURCE_ORDER_FALLBACK",
    ],
    "ordering_confidence": ["HIGH", "MEDIUM", "LOW"],
    "ordering_comparability": [
        "FULLY_COMPARABLE",
        "PARTIALLY_COMPARABLE",
        "NOT_COMPARABLE",
    ],
    "duration_status": [
        "COMPLETE",
        "PARTIAL_TIMESTAMP",
        "UNRELIABLE_ORDER",
        "UNAVAILABLE",
    ],
}

RAW_ROW_FIELDS = [
    field_spec("session_id_raw", "string", False),
    field_spec("utterance_id_raw", "string", False),
    field_spec("role_raw", "string", False),
    field_spec("content_raw", "large_string", False),
    field_spec("timestamp_raw", "string", False),
    field_spec("source_file_relative", "string", False),
    field_spec("source_row_index", "int32", False),
    field_spec("file_sha256", "string", False),
]

TURN_CANDIDATE_FIELDS = [
    field_spec("session_id", "string", False),
    field_spec("turn_uid", "string", False),
    field_spec("source_row_uid", "string", False),
    field_spec("turn_index", "int32", False),

    field_spec("session_id_raw", "string", False),
    field_spec("utterance_id_raw", "string", False),
    field_spec("utterance_id", "int32", True),
    field_spec("utterance_id_status", "string", False),

    field_spec("role_raw", "string", False),
    field_spec("role", "string", False),
    field_spec("role_status", "string", False),
    field_spec("role_issue_flag", "bool", False),

    field_spec("content_raw", "large_string", False),
    field_spec("text_norm", "large_string", False),
    field_spec("contains_unclear_flag", "bool", False),
    field_spec("empty_after_normalization_flag", "bool", False),

    field_spec("timestamp_raw", "string", False),
    field_spec("timestamp", "int32", True),
    field_spec("timestamp_status", "string", False),
    field_spec("timestamp_kind", "string", False),
    field_spec("timestamp_precision", "string", False),
    field_spec("timezone_status", "string", False),
    field_spec("timestamp_day_offset", "int32", True),
    field_spec("timestamp_order_value", "int64", True),
    field_spec("timestamp_rollover_flag", "bool", False),

    field_spec("ordering_method", "string", False),
    field_spec("ordering_confidence", "string", False),
    field_spec("ordering_issue_flag", "bool", False),
    field_spec("ordering_comparability", "string", False),

    field_spec("role_turn_index", "int32", False),
    field_spec("relative_turn_position", "float32", False),
    field_spec("previous_role", "string", True),
    field_spec("next_role", "string", True),
    field_spec("speaker_switch", "bool", False),
    field_spec("time_since_previous_turn", "float64", True),
    field_spec("elapsed_from_session_start", "float64", True),
    field_spec("is_first_turn", "bool", False),
    field_spec("is_last_turn", "bool", False),

    field_spec("source_file_relative", "string", False),
    field_spec("source_row_index", "int32", False),
    field_spec("file_sha256", "string", False),
    field_spec("raw_field_hash", "string", False),
    field_spec("content_hash", "string", False),
    field_spec("turn_uid_version", "string", False),

    field_spec("missing_session_id_flag", "bool", False),
    field_spec("missing_utterance_id_flag", "bool", False),
    field_spec("missing_role_flag", "bool", False),
    field_spec("empty_content_flag", "bool", False),
    field_spec("missing_timestamp_flag", "bool", False),
    field_spec("duplicate_utterance_id_flag", "bool", False),
    field_spec("natural_key_collision_flag", "bool", False),
    field_spec("duplicate_raw_field_flag", "bool", False),
]

SESSION_CANDIDATE_FIELDS = [
    field_spec("session_id", "string", False),
    field_spec("source_file_relative", "string", False),
    field_spec("file_sha256", "string", False),

    field_spec("source_raw_row_count", "int32", False),
    field_spec("n_turns", "int32", False),
    field_spec("n_student_turns", "int32", False),
    field_spec("n_tutor_turns", "int32", False),
    field_spec("n_background_turns", "int32", False),
    field_spec("n_unknown_roles", "int32", False),

    field_spec("first_valid_timestamp", "int64", True),
    field_spec("last_valid_timestamp", "int64", True),
    field_spec("duration_seconds", "float64", True),
    field_spec("duration_status", "string", False),

    field_spec("timestamp_issue_count", "int32", False),
    field_spec("utterance_id_issue_count", "int32", False),
    field_spec("ordering_issue_count", "int32", False),
    field_spec("unknown_role_count", "int32", False),
    field_spec("empty_content_count", "int32", False),

    field_spec("ordering_method", "string", False),
    field_spec("ordering_confidence", "string", False),
    field_spec("ordering_comparability", "string", False),
    field_spec("fallback_order_used", "bool", False),

    field_spec("timestamp_tie_count", "int32", False),
    field_spec("timestamp_id_conflict", "bool", False),
    field_spec("timestamp_source_conflict", "bool", False),
    field_spec("id_source_conflict", "bool", False),
    field_spec("midnight_rollover_count", "int32", False),
    field_spec("ambiguous_order_flag", "bool", False),

    field_spec("raw_transcript_hash", "string", False),
    field_spec("normalized_transcript_hash", "string", False),
    field_spec("quality_warning_count", "int32", False),
]

SEMANTIC_REPRESENTATIONS = {
    "utterance_id": {
        "physical_type": "int32",
        "meaning": "parsed integer value of the raw decimal utterance ID",
        "raw_preserved_in": "utterance_id_raw",
    },
    "timestamp": {
        "physical_type": "int32",
        "meaning": "seconds from midnight",
        "valid_range": [0, 86399],
        "raw_preserved_in": "timestamp_raw",
    },
    "timestamp_order_value": {
        "physical_type": "int64",
        "meaning": "timestamp_day_offset * 86400 + timestamp",
    },
    "first_valid_timestamp": {
        "physical_type": "int64",
        "meaning": "first reliable timestamp_order_value in the reconstructed session",
    },
    "last_valid_timestamp": {
        "physical_type": "int64",
        "meaning": "last reliable timestamp_order_value in the reconstructed session",
    },
}

LEGACY_ALIASES = {
    "raw_row_hash_requirement": DATA_CONTRACT["source_row_identity"]["logical_raw_hash_field"]
}

print(f"Observed roles       : {observed_roles}")
print(f"Timestamp families   : {observed_timestamp_families}")
print(f"Utterance-ID families: {observed_id_families}")
print(f"Max rows/file        : {max_file_rows:,}")

Observed roles       : ['background', 'student', 'tutor']
Timestamp families   : ['TIME_HMS']
Utterance-ID families: ['INTEGER']
Max rows/file        : 622

In [14]:
ARROW_TYPES = {
    "string": pa.string(),
    "large_string": pa.large_string(),
    "int16": pa.int16(),
    "int32": pa.int32(),
    "int64": pa.int64(),
    "float32": pa.float32(),
    "float64": pa.float64(),
    "bool": pa.bool_(),
}


def build_arrow_schema(field_specs, schema_role):
    fields = [
        pa.field(
            spec["name"],
            ARROW_TYPES[spec["dtype"]],
            nullable=spec["nullable"],
        )
        for spec in field_specs
    ]

    metadata = {
        b"parser_version": PARSER_VERSION.encode(),
        b"contract_version": DATA_CONTRACT["contract"]["version"].encode(),
        b"schema_version": PARSER_SCHEMA_VERSION.encode(),
        b"schema_role": schema_role.encode(),
    }

    return pa.schema(fields, metadata=metadata)


def schema_table(schema):
    return pd.DataFrame([
        {
            "field": field.name,
            "arrow_type": str(field.type),
            "nullable": field.nullable,
        }
        for field in schema
    ])


RAW_ROW_SCHEMA = build_arrow_schema(
    RAW_ROW_FIELDS,
    "raw_row",
)

TURN_CANDIDATE_SCHEMA = build_arrow_schema(
    TURN_CANDIDATE_FIELDS,
    "turns_candidate",
)

SESSION_CANDIDATE_SCHEMA = build_arrow_schema(
    SESSION_CANDIDATE_FIELDS,
    "sessions_candidate",
)

raw_schema_table = schema_table(RAW_ROW_SCHEMA)
turn_schema_table = schema_table(TURN_CANDIDATE_SCHEMA)
session_schema_table = schema_table(SESSION_CANDIDATE_SCHEMA)

schema_size_summary = pd.DataFrame({
    "schema": [
        "RAW_ROW_SCHEMA",
        "TURN_CANDIDATE_SCHEMA",
        "SESSION_CANDIDATE_SCHEMA",
    ],
    "fields": [
        len(RAW_ROW_SCHEMA),
        len(TURN_CANDIDATE_SCHEMA),
        len(SESSION_CANDIDATE_SCHEMA),
    ],
})

display(schema_size_summary)
display(raw_schema_table)
display(turn_schema_table)
display(session_schema_table)

                     schema  fields
0            RAW_ROW_SCHEMA       8
1     TURN_CANDIDATE_SCHEMA      52
2  SESSION_CANDIDATE_SCHEMA      31

                  field    arrow_type  nullable
0        session_id_raw        string     False
1      utterance_id_raw        string     False
2              role_raw        string     False
3           content_raw  large_string     False
4         timestamp_raw        string     False
5  source_file_relative        string     False
6      source_row_index         int32     False
7           file_sha256        string     False

                             field    arrow_type  nullable
0                       session_id        string     False
1                         turn_uid        string     False
2                   source_row_uid        string     False
3                       turn_index         int32     False
4                   session_id_raw        string     False
5                 utterance_id_raw        string     False
6                     utterance_id         int32      True
7              utterance_id_status        string     False
8                         role_raw        string     False
9                             role        string     False
10                     role_status        string     False
11                 role_issue_flag          bool     False
12                     content_raw  large_string     False
13                       text_norm  large_string     False
14           contains_unclear_flag          bool     False
15  empty_after_normalization_flag          bool     False
16                   timestamp_raw        string     False
17                       timestamp         int32      True
18                timestamp_status        string     False
19                  timestamp_kind        string     False
20             timestamp_precision        string     False
21                 timezone_status        string     False
22            timestamp_day_offset         int32      True
23           timestamp_order_value         int64      True
24         timestamp_rollover_flag          bool     False
25                 ordering_method        string     False
26             ordering_confidence        string     False
27             ordering_issue_flag          bool     False
28          ordering_comparability        string     False
29                 role_turn_index         int32     False
30          relative_turn_position         float     False
31                   previous_role        string      True
32                       next_role        string      True
33                  speaker_switch          bool     False
34        time_since_previous_turn        double      True
35      elapsed_from_session_start        double      True
36                   is_first_turn          bool     False
37                    is_last_turn          bool     False
38            source_file_relative        string     False
39                source_row_index         int32     False
40                     file_sha256        string     False
41                  raw_field_hash        string     False
42                    content_hash        string     False
43                turn_uid_version        string     False
44         missing_session_id_flag          bool     False
45       missing_utterance_id_flag          bool     False
46               missing_role_flag          bool     False
47              empty_content_flag          bool     False
48          missing_timestamp_flag          bool     False
49     duplicate_utterance_id_flag          bool     False
50      natural_key_collision_flag          bool     False
51        duplicate_raw_field_flag          bool     False

                         field arrow_type  nullable
0                   session_id     string     False
1         source_file_relative     string     False
2                  file_sha256     string     False
3         source_raw_row_count      int32     False
4                      n_turns      int32     False
5              n_student_turns      int32     False
6                n_tutor_turns      int32     False
7           n_background_turns      int32     False
8              n_unknown_roles      int32     False
9        first_valid_timestamp      int64      True
10        last_valid_timestamp      int64      True
11            duration_seconds     double      True
12             duration_status     string     False
13       timestamp_issue_count      int32     False
14    utterance_id_issue_count      int32     False
15        ordering_issue_count      int32     False
16          unknown_role_count      int32     False
17         empty_content_count      int32     False
18             ordering_method     string     False
19         ordering_confidence     string     False
20      ordering_comparability     string     False
21         fallback_order_used       bool     False
22         timestamp_tie_count      int32     False
23       timestamp_id_conflict       bool     False
24   timestamp_source_conflict       bool     False
25          id_source_conflict       bool     False
26     midnight_rollover_count      int32     False
27        ambiguous_order_flag       bool     False
28         raw_transcript_hash     string     False
29  normalized_transcript_hash     string     False
30       quality_warning_count      int32     False

In [15]:
def duplicate_field_count(field_specs):
    names = [field["name"] for field in field_specs]
    return len(names) - len(set(names))


def schema_to_config(schema):
    return [
        {
            "name": field.name,
            "type": str(field.type),
            "nullable": field.nullable,
        }
        for field in schema
    ]


FORBIDDEN_PARSER_COLUMNS = {
    "target",
    "is_correct",
    "objective_raw",
    "objective_id_raw",
    "learning_objective",
    "learning_objective_id",
    "fold",
    "objective_prior",
    "oof_prediction",
    "baseline_prediction",
    "validation_metric",
}

turn_field_names = set(TURN_CANDIDATE_SCHEMA.names)
session_field_names = set(SESSION_CANDIDATE_SCHEMA.names)
raw_field_names = set(RAW_ROW_SCHEMA.names)

required_provenance = set(DATA_CONTRACT["provenance"]["required_fields"])
required_ordering_outputs = set(DATA_CONTRACT["ordering_policy"]["required_outputs"])

raw_non_nullable = all(
    not RAW_ROW_SCHEMA.field(name).nullable
    for name in [
        "session_id_raw",
        "utterance_id_raw",
        "role_raw",
        "content_raw",
        "timestamp_raw",
    ]
)

capacity_checks = {
    "source_row_index_int32": max_file_rows < 2_147_483_647,
    "turn_index_int32": max_file_rows < 2_147_483_647,
    "utterance_id_int32": max_id_digits <= 9,
    "global_rows_int64": TOTAL_RAW_ROWS < 9_223_372_036_854_775_807,
}

PARSER_SCHEMA_CONFIG = {
    "schema_version": PARSER_SCHEMA_VERSION,
    "parser_version": PARSER_VERSION,
    "contract_version": DATA_CONTRACT["contract"]["version"],
    "observed_format_contract": OBSERVED_FORMAT_CONTRACT,
    "status_vocabularies": STATUS_VOCABULARIES,
    "semantic_representations": SEMANTIC_REPRESENTATIONS,
    "legacy_aliases": LEGACY_ALIASES,
    "capacity_checks": capacity_checks,
    "raw_row_schema": schema_to_config(RAW_ROW_SCHEMA),
    "turn_candidate_schema": schema_to_config(TURN_CANDIDATE_SCHEMA),
    "session_candidate_schema": schema_to_config(SESSION_CANDIDATE_SCHEMA),
}

PARSER_SCHEMA_SHA256 = canonical_json_hash(PARSER_SCHEMA_CONFIG)

schema_checks = pd.DataFrame([
    check_row(
        "Observed raw roles match discovered corpus",
        set(observed_roles) == {"student", "tutor", "background"},
        observed_roles,
    ),
    check_row(
        "Timestamp family is exclusively TIME_HMS",
        observed_timestamp_families == ["TIME_HMS"],
        observed_timestamp_families,
    ),
    check_row(
        "Utterance-ID family is exclusively INTEGER",
        observed_id_families == ["INTEGER"],
        observed_id_families,
    ),
    check_row(
        "Raw schema has unique fields",
        duplicate_field_count(RAW_ROW_FIELDS) == 0,
        duplicate_field_count(RAW_ROW_FIELDS),
    ),
    check_row(
        "Turn schema has unique fields",
        duplicate_field_count(TURN_CANDIDATE_FIELDS) == 0,
        duplicate_field_count(TURN_CANDIDATE_FIELDS),
    ),
    check_row(
        "Session schema has unique fields",
        duplicate_field_count(SESSION_CANDIDATE_FIELDS) == 0,
        duplicate_field_count(SESSION_CANDIDATE_FIELDS),
    ),
    check_row(
        "Raw source fields are non-nullable",
        raw_non_nullable,
        raw_non_nullable,
    ),
    check_row(
        "Turn schema contains required provenance",
        required_provenance.issubset(turn_field_names),
        sorted(required_provenance - turn_field_names),
    ),
    check_row(
        "Turn schema contains ordering outputs",
        required_ordering_outputs.issubset(turn_field_names),
        sorted(required_ordering_outputs - turn_field_names),
    ),
    check_row(
        "Physical source-row identity is present",
        "source_row_uid" in turn_field_names,
        "source_row_uid",
    ),
    check_row(
        "Logical raw-field hash is present",
        DATA_CONTRACT["source_row_identity"]["logical_raw_hash_field"] in turn_field_names,
        DATA_CONTRACT["source_row_identity"]["logical_raw_hash_field"],
    ),
    check_row(
        "Raw content uses large_string",
        RAW_ROW_SCHEMA.field("content_raw").type == pa.large_string()
        and TURN_CANDIDATE_SCHEMA.field("content_raw").type == pa.large_string(),
        str(TURN_CANDIDATE_SCHEMA.field("content_raw").type),
    ),
    check_row(
        "Normalized text uses large_string",
        TURN_CANDIDATE_SCHEMA.field("text_norm").type == pa.large_string(),
        str(TURN_CANDIDATE_SCHEMA.field("text_norm").type),
    ),
    check_row(
        "Failure-sensitive parsed fields are nullable",
        TURN_CANDIDATE_SCHEMA.field("utterance_id").nullable
        and TURN_CANDIDATE_SCHEMA.field("timestamp").nullable
        and TURN_CANDIDATE_SCHEMA.field("timestamp_order_value").nullable,
        True,
    ),
    check_row(
        "Numeric capacities are sufficient",
        all(capacity_checks.values()),
        capacity_checks,
    ),
    check_row(
        "Parser schemas contain no forbidden columns",
        not ((turn_field_names | session_field_names | raw_field_names) & FORBIDDEN_PARSER_COLUMNS),
        sorted((turn_field_names | session_field_names | raw_field_names) & FORBIDDEN_PARSER_COLUMNS),
    ),
    check_row(
        "Status vocabularies contain unique values",
        all(len(values) == len(set(values)) for values in STATUS_VOCABULARIES.values()),
        True,
    ),
])

schema_failures = schema_checks[~schema_checks["passed"]]

PARSER_SCHEMA_PATH = PARSER_WORK_DIR / "parser_schema.json"
PARSER_SCHEMA_TMP_PATH = PARSER_WORK_DIR / "parser_schema.json.tmp"

with open(PARSER_SCHEMA_TMP_PATH, "w", encoding="utf-8") as f:
    json.dump(
        PARSER_SCHEMA_CONFIG,
        f,
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )

with open(PARSER_SCHEMA_TMP_PATH, "r", encoding="utf-8") as f:
    reloaded_schema_config = json.load(f)

schema_reload_identical = PARSER_SCHEMA_CONFIG == reloaded_schema_config
reloaded_schema_hash = canonical_json_hash(reloaded_schema_config)
schema_hash_identical = PARSER_SCHEMA_SHA256 == reloaded_schema_hash

if schema_failures.empty and schema_reload_identical and schema_hash_identical:
    os.replace(PARSER_SCHEMA_TMP_PATH, PARSER_SCHEMA_PATH)

PARSER_SCHEMA_READY = (
    schema_failures.empty
    and PARSER_SCHEMA_PATH.exists()
    and schema_reload_identical
    and schema_hash_identical
)

parser_schema_summary = pd.DataFrame({
    "item": [
        "Schema version",
        "Observed raw rows",
        "Observed sessions",
        "Observed raw roles",
        "Timestamp families",
        "Utterance-ID families",
        "Raw schema fields",
        "Turn candidate fields",
        "Session candidate fields",
        "Parsed timestamp representation",
        "Parsed utterance-ID type",
        "Raw content type",
        "Forbidden columns",
        "Capacity failures",
        "Schema validation failures",
        "Schema reload identical",
        "Schema hash identical",
        "PARSER_SCHEMA_SHA256",
        "PARSER_SCHEMA_READY",
    ],
    "value": [
        PARSER_SCHEMA_VERSION,
        TOTAL_RAW_ROWS,
        len(discovered_session_ids),
        len(observed_roles),
        len(observed_timestamp_families),
        len(observed_id_families),
        len(RAW_ROW_SCHEMA),
        len(TURN_CANDIDATE_SCHEMA),
        len(SESSION_CANDIDATE_SCHEMA),
        "seconds_from_midnight",
        str(TURN_CANDIDATE_SCHEMA.field("utterance_id").type),
        str(TURN_CANDIDATE_SCHEMA.field("content_raw").type),
        len((turn_field_names | session_field_names | raw_field_names) & FORBIDDEN_PARSER_COLUMNS),
        sum(not passed for passed in capacity_checks.values()),
        len(schema_failures),
        schema_reload_identical,
        schema_hash_identical,
        PARSER_SCHEMA_SHA256,
        PARSER_SCHEMA_READY,
    ],
})

display(schema_checks)
display(parser_schema_summary)

assert PARSER_SCHEMA_READY, (
    "Section 2.3 failed.\n\n"
    + schema_failures[["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 62)
print("TRACE THE ACE — PARSER SCHEMA FROZEN")
print("=" * 62)
print(f"Schema version : {PARSER_SCHEMA_VERSION}")
print(f"Raw fields     : {len(RAW_ROW_SCHEMA)}")
print(f"Turn fields    : {len(TURN_CANDIDATE_SCHEMA)}")
print(f"Session fields : {len(SESSION_CANDIDATE_SCHEMA)}")
print(f"Schema failures: {len(schema_failures)}")
print(f"SCHEMA READY   : {PARSER_SCHEMA_READY}")
print("=" * 62)

,check,passed,detail
0,Observed raw roles match discovered corpus,True,"[background, student, tutor]"
1,Timestamp family is exclusively TIME_HMS,True,[TIME_HMS]
2,Utterance-ID family is exclusively INTEGER,True,[INTEGER]
3,Raw schema has unique fields,True,0
4,Turn schema has unique fields,True,0
5,Session schema has unique fields,True,0
6,Raw source fields are non-nullable,True,True
7,Turn schema contains required provenance,True,[]
8,Turn schema contains ordering outputs,True,[]
9,Physical source-row identity is present,True,source_row_uid
10,Logical raw-field hash is present,True,raw_field_hash
11,Raw content uses large_string,True,large_string
12,Normalized text uses large_string,True,large_string
13,Failure-sensitive parsed fields are nullable,True,True
14,Numeric capacities are sufficient,True,"{'source_row_index_int32': True, 'turn_index_i..."
15,Parser schemas contain no forbidden columns,True,[]
16,Status vocabularies contain unique values,True,True

,item,value
0,Schema version,1.0
1,Observed raw rows,6139854
2,Observed sessions,22821
3,Observed raw roles,3
4,Timestamp families,1
5,Utterance-ID families,1
6,Raw schema fields,8
7,Turn candidate fields,52
8,Session candidate fields,31
9,Parsed timestamp representation,seconds_from_midnight
10,Parsed utterance-ID type,int32
11,Raw content type,large_string
12,Forbidden columns,0
13,Capacity failures,0
14,Schema validation failures,0
15,Schema reload identical,True
16,Schema hash identical,True
17,PARSER_SCHEMA_SHA256,67452c0762daff1440e4917716445eb3e9fdf1b8eefcea...
18,PARSER_SCHEMA_READY,True

==============================================================
TRACE THE ACE — PARSER SCHEMA FROZEN
==============================================================
Schema version : 1.0
Raw fields     : 8
Turn fields    : 52
Session fields : 31
Schema failures: 0
SCHEMA READY   : True
==============================================================

# Section 2.4 — Raw Row Reconstruction

This section reconstructs each logical CSV record as one typed raw utterance row.
The verified Section 2.1 ingestion engine remains the only source reader.
All five source values are preserved exactly as raw strings.
File-relative provenance, zero-based source-row index, and file SHA256 are retained.
No row is filtered, cleaned, normalized, reordered, or semantically interpreted.
The frozen `RAW_ROW_SCHEMA` is applied explicitly with PyArrow.
Source rows, reconstructed rows, and Arrow rows must match exactly per file.
Arrow round-trips must preserve every raw value without mutation.
Synthetic and deterministic real-source cases validate the reconstruction engine.
The section ends with the `RAW_ROW_RECONSTRUCTION_READY` hard gate.

In [16]:
assert PARSER_SCHEMA_READY, "Section 2.3 must pass before Section 2.4."

RAW_RECONSTRUCTION_VERSION = "1.0"
RAW_FIELD_NAMES = list(RAW_ROW_SCHEMA.names)
RAW_SOURCE_FIELDS = ["session_id_raw", "utterance_id_raw", "role_raw", "content_raw", "timestamp_raw"]


def valid_sha256(value):
    return isinstance(value, str) and bool(re.fullmatch(r"[0-9a-f]{64}", value))


def validate_raw_rows(rows, metadata, expected_session_id=None):
    issues = []
    expected_keys = set(RAW_FIELD_NAMES)

    for i, row in enumerate(rows):
        if set(row) != expected_keys:
            issues.append(f"ROW_{i}_FIELD_SET_MISMATCH")

        if not all(isinstance(row.get(field), str) for field in RAW_SOURCE_FIELDS):
            issues.append(f"ROW_{i}_RAW_TYPE_MISMATCH")

        if row.get("source_row_index") != i:
            issues.append(f"ROW_{i}_SOURCE_INDEX_MISMATCH")

        if row.get("source_file_relative") != metadata["relative_file"]:
            issues.append(f"ROW_{i}_SOURCE_FILE_MISMATCH")

        if row.get("file_sha256") != metadata["file_sha256"]:
            issues.append(f"ROW_{i}_FILE_HASH_MISMATCH")

    session_ids = {row["session_id_raw"] for row in rows if row["session_id_raw"] != ""}

    if len(session_ids) != 1:
        issues.append(f"SESSION_CARDINALITY_{len(session_ids)}")

    internal_session_id = next(iter(session_ids)) if len(session_ids) == 1 else None

    if expected_session_id is not None and internal_session_id != expected_session_id:
        issues.append("EXPECTED_SESSION_MISMATCH")

    if "\\" in metadata["relative_file"]:
        issues.append("NON_POSIX_RELATIVE_PATH")

    if not valid_sha256(metadata["file_sha256"]):
        issues.append("INVALID_FILE_SHA256")

    return {
        "internal_session_id": internal_session_id,
        "issues": tuple(sorted(set(issues))),
        "passed": len(issues) == 0,
    }


def build_raw_arrow_table(rows):
    table = pa.Table.from_pylist(rows, schema=RAW_ROW_SCHEMA)

    assert table.schema.equals(RAW_ROW_SCHEMA, check_metadata=True), (
        "Raw Arrow table does not match frozen RAW_ROW_SCHEMA."
    )

    return table


def compare_raw_roundtrip(rows, table):
    restored = table.to_pylist()

    return {
        "row_count_match": len(rows) == len(restored),
        "exact_values_match": rows == restored,
        "restored_rows": len(restored),
    }


def reconstruct_raw_result(result, expected_session_id=None):
    metadata = result["metadata"]
    rows = result["rows"]

    validation = validate_raw_rows(
        rows,
        metadata,
        expected_session_id=expected_session_id,
    )

    if metadata["status"] != "READ_OK":
        validation["issues"] = tuple(sorted(set(
            validation["issues"] + (f"SOURCE_STATUS_{metadata['status']}",)
        )))
        validation["passed"] = False

    source_rows = int(metadata["row_count"])
    reconstructed_rows = len(rows)

    if source_rows != reconstructed_rows:
        validation["issues"] = tuple(sorted(set(
            validation["issues"] + ("SOURCE_RECONSTRUCTION_COUNT_MISMATCH",)
        )))
        validation["passed"] = False

    table = build_raw_arrow_table(rows)
    roundtrip = compare_raw_roundtrip(rows, table)

    passed = all([
        validation["passed"],
        source_rows == reconstructed_rows,
        reconstructed_rows == table.num_rows,
        roundtrip["row_count_match"],
        roundtrip["exact_values_match"],
    ])

    return {
        "metadata": metadata,
        "raw_table": table,
        "validation": validation,
        "roundtrip": roundtrip,
        "passed": passed,
    }


def reconstruct_raw_file(path, expected_session_id=None):
    result = read_transcript_file(path)

    return reconstruct_raw_result(
        result,
        expected_session_id=expected_session_id,
    )


print(f"RAW_RECONSTRUCTION_VERSION: {RAW_RECONSTRUCTION_VERSION}")
print(f"Frozen raw fields         : {len(RAW_ROW_SCHEMA)}")

RAW_RECONSTRUCTION_VERSION: 1.0
Frozen raw fields         : 8

In [17]:
# ------------------------------------------------------------
# 1. Freeze a safe CSV field-size limit
# ------------------------------------------------------------

DISCOVERED_MAX_CONTENT_CHARS = int(
    raw_format_file_profile["max_content_chars"].max()
)

CSV_FIELD_SIZE_LIMIT = max(
    1_048_576,                       # minimum 1 MiB
    DISCOVERED_MAX_CONTENT_CHARS * 2 + 4096,
)

csv.field_size_limit(CSV_FIELD_SIZE_LIMIT)

INGESTION_CONFIG["csv_field_size_limit"] = CSV_FIELD_SIZE_LIMIT
INGESTION_CONFIG_SHA256 = canonical_json_hash(INGESTION_CONFIG)

assert csv.field_size_limit() == CSV_FIELD_SIZE_LIMIT, (
    "CSV field-size limit was not applied correctly."
)

print(f"Discovered max content chars : {DISCOVERED_MAX_CONTENT_CHARS:,}")
print(f"CSV field-size limit         : {CSV_FIELD_SIZE_LIMIT:,}")


# ------------------------------------------------------------
# 2. Synthetic raw-reconstruction tests
# ------------------------------------------------------------

def reconstruction_test(name, csv_bytes, expected_check):
    result = parse_transcript_bytes(
        csv_bytes,
        relative_path=f"synthetic/{name}.csv",
    )

    reconstructed = reconstruct_raw_result(
        result,
        expected_session_id="s1",
    )

    rows = reconstructed["raw_table"].to_pylist()

    try:
        condition = bool(expected_check(rows))
    except Exception:
        condition = False

    return {
        "test": name,
        "source_status": result["metadata"]["status"],
        "source_rows": result["metadata"]["row_count"],
        "arrow_rows": reconstructed["raw_table"].num_rows,
        "raw_roundtrip_exact": reconstructed["roundtrip"]["exact_values_match"],
        "reconstruction_passed": reconstructed["passed"],
        "expected_value_passed": condition,
        "passed": reconstructed["passed"] and condition,
    }


HEADER = "session_id,utterance_id,role,content,timestamp\n"

very_large_text = (
    "x² ≤ ½\n"
    + ("A" * 200_000)
)

reconstruction_cases = [
    (
        "R01_NORMAL",
        (HEADER + "s1,0,student,hello,00:00:01\n").encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["content_raw"] == "hello"
        ),
    ),
    (
        "R02_EMPTY_CONTENT",
        (HEADER + "s1,1,student,,00:00:02\n").encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["content_raw"] == ""
        ),
    ),
    (
        "R03_LITERAL_NA",
        (HEADER + "s1,2,student,NA,00:00:03\n").encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["content_raw"] == "NA"
        ),
    ),
    (
        "R04_LEADING_ZERO_ID",
        (HEADER + "s1,0012,student,answer,00:00:04\n").encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["utterance_id_raw"] == "0012"
        ),
    ),
    (
        "R05_MULTILINE",
        (
            HEADER
            + 's1,4,student,"line 1\nline 2",00:00:05\n'
        ).encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["content_raw"] == "line 1\nline 2"
        ),
    ),
    (
        "R06_MATH_UNICODE",
        (
            HEADER
            + 's1,5,student,"x² ≤ ½",00:00:06\n'
        ).encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["content_raw"] == "x² ≤ ½"
        ),
    ),
    (
        "R07_BLANK_TIMESTAMP",
        (HEADER + "s1,6,student,hello,\n").encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["timestamp_raw"] == ""
        ),
    ),
    (
        "R08_BLANK_ROLE",
        (HEADER + "s1,7,,hello,00:00:08\n").encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["role_raw"] == ""
        ),
    ),
    (
        "R09_LARGE_CONTENT",
        (
            HEADER
            + 's1,8,student,"'
            + very_large_text.replace('"', '""')
            + '",00:00:09\n'
        ).encode("utf-8"),
        lambda r: (
            len(r) == 1
            and r[0]["content_raw"] == very_large_text
            and len(r[0]["content_raw"]) == len(very_large_text)
        ),
    ),
]

raw_reconstruction_tests = pd.DataFrame([
    reconstruction_test(name, data, validator)
    for name, data, validator in reconstruction_cases
])


# ------------------------------------------------------------
# 3. Deterministic real-source reconstruction audit
# ------------------------------------------------------------

def choose_real_reconstruction_files(profile):
    ordered = (
        profile
        .sort_values(["raw_row_count", "relative_file"])
        .reset_index(drop=True)
    )

    selected = {
        ordered.iloc[0]["relative_file"],
        ordered.iloc[len(ordered) // 2]["relative_file"],
        ordered.iloc[-1]["relative_file"],
        profile.loc[
            profile["max_content_chars"].idxmax(),
            "relative_file",
        ],
        profile.iloc[0]["relative_file"],
    }

    multiline = profile[
        profile["multiline_content_rows"] > 0
    ]

    if not multiline.empty:
        selected.add(
            multiline.loc[
                multiline["multiline_content_rows"].idxmax(),
                "relative_file",
            ]
        )

    return sorted(selected)


REAL_RECONSTRUCTION_FILES = choose_real_reconstruction_files(
    raw_format_file_profile
)


def audit_real_reconstruction(relative_file):
    path = TRANSCRIPT_ROOT / Path(relative_file)
    expected_session_id = Path(relative_file).stem

    reconstructed = reconstruct_raw_file(
        path,
        expected_session_id=expected_session_id,
    )

    metadata = reconstructed["metadata"]
    table = reconstructed["raw_table"]
    restored_rows = table.to_pylist()

    indices = [
        row["source_row_index"]
        for row in restored_rows
    ]

    hashes = {
        row["file_sha256"]
        for row in restored_rows
    }

    paths = {
        row["source_file_relative"]
        for row in restored_rows
    }

    return {
        "relative_file": relative_file,
        "session_id": reconstructed["validation"]["internal_session_id"],
        "source_status": metadata["status"],
        "source_rows": metadata["row_count"],
        "arrow_rows": table.num_rows,
        "schema_exact": table.schema.equals(
            RAW_ROW_SCHEMA,
            check_metadata=True,
        ),
        "raw_roundtrip_exact": reconstructed["roundtrip"]["exact_values_match"],
        "source_index_contiguous": indices == list(range(len(indices))),
        "single_file_hash": hashes == {metadata["file_sha256"]},
        "single_relative_path": paths == {relative_file},
        "issues": reconstructed["validation"]["issues"],
        "passed": reconstructed["passed"],
    }


real_reconstruction_audit = pd.DataFrame([
    audit_real_reconstruction(relative_file)
    for relative_file in REAL_RECONSTRUCTION_FILES
])

display(raw_reconstruction_tests)
display(real_reconstruction_audit)

Discovered max content chars : 1,767
CSV field-size limit         : 1,048,576

,test,source_status,source_rows,arrow_rows,raw_roundtrip_exact,reconstruction_passed,expected_value_passed,passed
0,R01_NORMAL,READ_OK,1,1,True,True,True,True
1,R02_EMPTY_CONTENT,READ_OK,1,1,True,True,True,True
2,R03_LITERAL_NA,READ_OK,1,1,True,True,True,True
3,R04_LEADING_ZERO_ID,READ_OK,1,1,True,True,True,True
4,R05_MULTILINE,READ_OK,1,1,True,True,True,True
5,R06_MATH_UNICODE,READ_OK,1,1,True,True,True,True
6,R07_BLANK_TIMESTAMP,READ_OK,1,1,True,True,True,True
7,R08_BLANK_ROLE,READ_OK,1,1,True,True,True,True
8,R09_LARGE_CONTENT,READ_OK,1,1,True,True,True,True

,relative_file,session_id,source_status,source_rows,arrow_rows,schema_exact,raw_roundtrip_exact,source_index_contiguous,single_file_hash,single_relative_path,issues,passed
0,aaaedit.csv,aaaedit,READ_OK,254,254,True,True,True,True,True,(),True
1,bvnewyc.csv,bvnewyc,READ_OK,622,622,True,True,True,True,True,(),True
2,jlntsbf.csv,jlntsbf,READ_OK,15,15,True,True,True,True,True,(),True
3,lybeyle.csv,lybeyle,READ_OK,215,215,True,True,True,True,True,(),True
4,mbuivwk.csv,mbuivwk,READ_OK,267,267,True,True,True,True,True,(),True

In [18]:
synthetic_failures = int(
    (~raw_reconstruction_tests["passed"]).sum()
)

real_failures = int(
    (~real_reconstruction_audit["passed"]).sum()
)

real_row_conservation_failures = int(
    (
        real_reconstruction_audit["source_rows"]
        != real_reconstruction_audit["arrow_rows"]
    ).sum()
)

real_schema_failures = int(
    (~real_reconstruction_audit["schema_exact"]).sum()
)

real_roundtrip_failures = int(
    (~real_reconstruction_audit["raw_roundtrip_exact"]).sum()
)

real_index_failures = int(
    (~real_reconstruction_audit["source_index_contiguous"]).sum()
)

real_hash_failures = int(
    (~real_reconstruction_audit["single_file_hash"]).sum()
)

real_path_failures = int(
    (~real_reconstruction_audit["single_relative_path"]).sum()
)

RAW_ROW_RECONSTRUCTION_READY = all([
    PARSER_SCHEMA_READY,
    synthetic_failures == 0,
    real_failures == 0,
    real_row_conservation_failures == 0,
    real_schema_failures == 0,
    real_roundtrip_failures == 0,
    real_index_failures == 0,
    real_hash_failures == 0,
    real_path_failures == 0,
])

raw_reconstruction_summary = pd.DataFrame({
    "item": [
        "Reconstruction version",
        "Frozen raw schema fields",
        "Synthetic tests",
        "Passed synthetic tests",
        "Real files tested",
        "Passed real files",
        "Row conservation failures",
        "Schema mismatch failures",
        "Raw round-trip failures",
        "Source-index failures",
        "File-hash consistency failures",
        "Relative-path consistency failures",
        "RAW_ROW_RECONSTRUCTION_READY",
    ],
    "value": [
        RAW_RECONSTRUCTION_VERSION,
        len(RAW_ROW_SCHEMA),
        len(raw_reconstruction_tests),
        int(raw_reconstruction_tests["passed"].sum()),
        len(real_reconstruction_audit),
        int(real_reconstruction_audit["passed"].sum()),
        real_row_conservation_failures,
        real_schema_failures,
        real_roundtrip_failures,
        real_index_failures,
        real_hash_failures,
        real_path_failures,
        RAW_ROW_RECONSTRUCTION_READY,
    ],
})

display(raw_reconstruction_summary)

assert RAW_ROW_RECONSTRUCTION_READY, (
    "Section 2.4 failed. Do not continue to the raw structural audit."
)

print("\n" + "=" * 64)
print("TRACE THE ACE — RAW ROW RECONSTRUCTION READY")
print("=" * 64)
print(f"Synthetic tests : {int(raw_reconstruction_tests['passed'].sum())}/{len(raw_reconstruction_tests)}")
print(f"Real files      : {int(real_reconstruction_audit['passed'].sum())}/{len(real_reconstruction_audit)}")
print(f"Row failures    : {real_row_conservation_failures}")
print(f"Schema failures : {real_schema_failures}")
print(f"Roundtrip fails : {real_roundtrip_failures}")
print(f"Index failures  : {real_index_failures}")
print(f"Hash failures   : {real_hash_failures}")
print(f"RAW ROW READY   : {RAW_ROW_RECONSTRUCTION_READY}")
print("=" * 64)

                                  item value
0               Reconstruction version   1.0
1             Frozen raw schema fields     8
2                      Synthetic tests     9
3               Passed synthetic tests     9
4                    Real files tested     5
5                    Passed real files     5
6            Row conservation failures     0
7             Schema mismatch failures     0
8              Raw round-trip failures     0
9                Source-index failures     0
10      File-hash consistency failures     0
11  Relative-path consistency failures     0
12        RAW_ROW_RECONSTRUCTION_READY  True

================================================================
TRACE THE ACE — RAW ROW RECONSTRUCTION READY
================================================================
Synthetic tests : 9/9
Real files      : 5/5
Row failures    : 0
Schema failures : 0
Roundtrip fails : 0
Index failures  : 0
Hash failures   : 0
RAW ROW READY   : True
================================================================

# Section 2.5 — Raw Structural Audit

This section audits reconstructed raw rows before any normalization or semantic parsing.
Missing session IDs, utterance IDs, roles, content, and timestamps are flagged without modifying source values.
Duplicate utterance IDs are detected only within the same session and all affected rows are retained.
Exact duplicate logical rows are identified from the five immutable raw source fields.
Conflicting duplicate utterance-ID groups are recorded separately from exact duplicate rows.
Malformed source records and reconstruction failures are treated as hard blockers.
Source, parsed, and reconstructed row counts must match independently for every transcript file.
Source-row indices must remain unique, contiguous, and zero-based within each file.
The complete corpus is audited in a streaming manner without building a 6.14M-row audit table.
The section ends with the `RAW_STRUCTURAL_AUDIT_READY` hard gate.

In [19]:
from collections import Counter, defaultdict

assert RAW_ROW_RECONSTRUCTION_READY, "Section 2.4 must pass before Section 2.5."

RAW_STRUCTURAL_AUDIT_VERSION = "1.0"

BLOCKER_ISSUES = {
    "MISSING_SESSION_ID",
    "MALFORMED_ROW",
    "ROW_CONSERVATION_FAILURE",
    "SOURCE_INDEX_FAILURE",
    "SESSION_IDENTITY_FAILURE",
    "SCHEMA_FAILURE",
}

RECOVERABLE_ISSUES = {
    "MISSING_UTTERANCE_ID",
    "MISSING_ROLE",
    "EMPTY_CONTENT",
    "MISSING_TIMESTAMP",
    "DUPLICATE_UTTERANCE_ID",
    "CONFLICTING_DUPLICATE_UTTERANCE_ID",
    "DUPLICATE_RAW_LOGICAL_ROW",
}


def is_structurally_blank(value):
    return isinstance(value, str) and value.strip() == ""


def audit_raw_reconstruction(reconstructed, expected_session_id=None):
    metadata = reconstructed["metadata"]
    table = reconstructed["raw_table"]
    rows = table.to_pylist()

    id_groups = defaultdict(list)
    raw_groups = defaultdict(list)

    for i, row in enumerate(rows):
        utterance_id = row["utterance_id_raw"]

        if not is_structurally_blank(utterance_id):
            id_groups[utterance_id].append(i)

        raw_key = (
            row["session_id_raw"],
            row["utterance_id_raw"],
            row["role_raw"],
            row["content_raw"],
            row["timestamp_raw"],
        )
        raw_groups[raw_key].append(i)

    duplicate_id_groups = {
        key: idxs for key, idxs in id_groups.items()
        if len(idxs) > 1
    }

    conflicting_duplicate_groups = {
        key: idxs
        for key, idxs in duplicate_id_groups.items()
        if len({
            (
                rows[i]["role_raw"],
                rows[i]["content_raw"],
                rows[i]["timestamp_raw"],
            )
            for i in idxs
        }) > 1
    }

    duplicate_raw_groups = {
        key: idxs for key, idxs in raw_groups.items()
        if len(idxs) > 1
    }

    duplicate_id_indices = {
        i for idxs in duplicate_id_groups.values() for i in idxs
    }
    conflicting_id_indices = {
        i for idxs in conflicting_duplicate_groups.values() for i in idxs
    }
    duplicate_raw_indices = {
        i for idxs in duplicate_raw_groups.values() for i in idxs
    }

    row_flags = []

    for i, row in enumerate(rows):
        row_flags.append({
            "session_id_raw": row["session_id_raw"],
            "utterance_id_raw": row["utterance_id_raw"],
            "role_raw": row["role_raw"],
            "timestamp_raw": row["timestamp_raw"],
            "content_chars": len(row["content_raw"]),
            "source_file_relative": row["source_file_relative"],
            "source_row_index": row["source_row_index"],
            "missing_session_id_flag": is_structurally_blank(row["session_id_raw"]),
            "missing_utterance_id_flag": is_structurally_blank(row["utterance_id_raw"]),
            "missing_role_flag": is_structurally_blank(row["role_raw"]),
            "empty_content_flag": is_structurally_blank(row["content_raw"]),
            "missing_timestamp_flag": is_structurally_blank(row["timestamp_raw"]),
            "duplicate_utterance_id_flag": i in duplicate_id_indices,
            "conflicting_duplicate_id_flag": i in conflicting_id_indices,
            "duplicate_raw_field_flag": i in duplicate_raw_indices,
        })

    indices = [row["source_row_index"] for row in rows]
    source_index_valid = indices == list(range(len(rows)))

    session_ids = {
        row["session_id_raw"]
        for row in rows
        if not is_structurally_blank(row["session_id_raw"])
    }

    internal_session_id = next(iter(session_ids)) if len(session_ids) == 1 else None

    session_identity_valid = (
        len(session_ids) == 1
        and (
            expected_session_id is None
            or internal_session_id == expected_session_id
        )
    )

    raw_data_rows = int(metadata["row_count"])
    parsed_raw_candidates = int(metadata["parsed_row_count"])
    raw_arrow_rows = int(table.num_rows)

    row_conservation_valid = (
        raw_data_rows
        == parsed_raw_candidates
        == raw_arrow_rows
    )

    schema_valid = table.schema.equals(
        RAW_ROW_SCHEMA,
        check_metadata=True,
    )

    malformed_rows = int(metadata.get("malformed_row_count", 0))

    summary = {
        "relative_file": metadata["relative_file"],
        "session_id": internal_session_id,
        "raw_data_rows": raw_data_rows,
        "parsed_raw_candidates": parsed_raw_candidates,
        "raw_arrow_rows": raw_arrow_rows,

        "missing_session_rows": sum(x["missing_session_id_flag"] for x in row_flags),
        "missing_utterance_id_rows": sum(x["missing_utterance_id_flag"] for x in row_flags),
        "missing_role_rows": sum(x["missing_role_flag"] for x in row_flags),
        "empty_content_rows": sum(x["empty_content_flag"] for x in row_flags),
        "missing_timestamp_rows": sum(x["missing_timestamp_flag"] for x in row_flags),

        "duplicate_id_groups": len(duplicate_id_groups),
        "duplicate_id_rows": len(duplicate_id_indices),
        "conflicting_duplicate_id_groups": len(conflicting_duplicate_groups),
        "conflicting_duplicate_id_rows": len(conflicting_id_indices),

        "duplicate_raw_groups": len(duplicate_raw_groups),
        "duplicate_raw_rows": len(duplicate_raw_indices),

        "malformed_rows": malformed_rows,
        "source_index_valid": source_index_valid,
        "session_identity_valid": session_identity_valid,
        "row_conservation_valid": row_conservation_valid,
        "schema_valid": schema_valid,
    }

    blocker_count = sum([
        summary["missing_session_rows"] > 0,
        malformed_rows > 0,
        not row_conservation_valid,
        not source_index_valid,
        not session_identity_valid,
        not schema_valid,
    ])

    finding_count = sum([
        summary["missing_utterance_id_rows"] > 0,
        summary["missing_role_rows"] > 0,
        summary["empty_content_rows"] > 0,
        summary["missing_timestamp_rows"] > 0,
        summary["duplicate_id_groups"] > 0,
        summary["conflicting_duplicate_id_groups"] > 0,
        summary["duplicate_raw_groups"] > 0,
    ])

    summary["blocker_count"] = blocker_count
    summary["finding_count"] = finding_count
    summary["status"] = (
        "BLOCKER" if blocker_count
        else "FINDINGS" if finding_count
        else "CLEAN"
    )

    return {
        "row_flags": row_flags,
        "summary": summary,
    }


def structural_test(name, csv_bytes, expected, mutate=None):
    parsed = parse_transcript_bytes(
        csv_bytes,
        relative_path=f"synthetic/{name}.csv",
    )

    if mutate is not None:
        mutate(parsed)

    reconstructed = reconstruct_raw_result(
        parsed,
        expected_session_id="s1",
    )

    audit = audit_raw_reconstruction(
        reconstructed,
        expected_session_id="s1",
    )

    summary = audit["summary"]
    passed = all(summary.get(key) == value for key, value in expected.items())

    return {
        "test": name,
        "passed": passed,
        "status": summary["status"],
        "detail": "; ".join(
            f"{key}={summary.get(key)}"
            for key in expected
        ),
    }


HEADER = "session_id,utterance_id,role,content,timestamp\n"

structural_cases = [
    (
        "A01_CLEAN",
        (HEADER + "s1,0,student,hello,00:00:01\n").encode(),
        {"blocker_count": 0, "finding_count": 0},
        None,
    ),
    (
        "A02_MISSING_SESSION",
        (HEADER + ",0,student,hello,00:00:01\n").encode(),
        {"missing_session_rows": 1, "status": "BLOCKER"},
        None,
    ),
    (
        "A03_MISSING_ID",
        (HEADER + "s1,,student,hello,00:00:01\n").encode(),
        {"missing_utterance_id_rows": 1, "status": "FINDINGS"},
        None,
    ),
    (
        "A04_MISSING_ROLE",
        (HEADER + "s1,0,,hello,00:00:01\n").encode(),
        {"missing_role_rows": 1, "status": "FINDINGS"},
        None,
    ),
    (
        "A05_EMPTY_CONTENT",
        (HEADER + "s1,0,student,,00:00:01\n").encode(),
        {"empty_content_rows": 1, "status": "FINDINGS"},
        None,
    ),
    (
        "A06_MISSING_TIMESTAMP",
        (HEADER + "s1,0,student,hello,\n").encode(),
        {"missing_timestamp_rows": 1, "status": "FINDINGS"},
        None,
    ),
    (
        "A07_DUPLICATE_ID",
        (
            HEADER
            + "s1,0,student,hello,00:00:01\n"
            + "s1,0,student,hello,00:00:01\n"
        ).encode(),
        {"duplicate_id_groups": 1, "duplicate_id_rows": 2},
        None,
    ),
    (
        "A08_CONFLICTING_DUPLICATE_ID",
        (
            HEADER
            + "s1,0,student,yes,00:00:01\n"
            + "s1,0,tutor,no,00:00:02\n"
        ).encode(),
        {
            "duplicate_id_groups": 1,
            "conflicting_duplicate_id_groups": 1,
            "conflicting_duplicate_id_rows": 2,
        },
        None,
    ),
    (
        "A09_RAW_DUPLICATE_WITH_BLANK_ID",
        (
            HEADER
            + "s1,,student,hello,00:00:01\n"
            + "s1,,student,hello,00:00:01\n"
        ).encode(),
        {
            "duplicate_id_groups": 0,
            "duplicate_raw_groups": 1,
            "duplicate_raw_rows": 2,
        },
        None,
    ),
    (
        "A10_WHITESPACE_ONLY",
        (
            HEADER
            + 's1,0,"   ","   ","\t"\n'
        ).encode(),
        {
            "missing_role_rows": 1,
            "empty_content_rows": 1,
            "missing_timestamp_rows": 1,
        },
        None,
    ),
    (
        "A11_ROW_CONSERVATION_FAILURE",
        (HEADER + "s1,0,student,hello,00:00:01\n").encode(),
        {"row_conservation_valid": False, "status": "BLOCKER"},
        lambda x: x["metadata"].update(
            {"row_count": x["metadata"]["row_count"] + 1}
        ),
    ),
    (
        "A12_MALFORMED_ROW",
        (HEADER + "s1,0,student,hello\n").encode(),
        {"malformed_rows": 1, "status": "BLOCKER"},
        None,
    ),
]

raw_structural_tests = pd.DataFrame([
    structural_test(name, data, expected, mutate)
    for name, data, expected, mutate in structural_cases
])

display(raw_structural_tests)

assert raw_structural_tests["passed"].all(), (
    "Structural audit synthetic tests failed.\n\n"
    + raw_structural_tests.loc[
        ~raw_structural_tests["passed"],
        ["test", "detail"],
    ].to_string(index=False)
)

,test,passed,status,detail
0,A01_CLEAN,True,CLEAN,blocker_count=0; finding_count=0
1,A02_MISSING_SESSION,True,BLOCKER,missing_session_rows=1; status=BLOCKER
2,A03_MISSING_ID,True,FINDINGS,missing_utterance_id_rows=1; status=FINDINGS
3,A04_MISSING_ROLE,True,FINDINGS,missing_role_rows=1; status=FINDINGS
4,A05_EMPTY_CONTENT,True,FINDINGS,empty_content_rows=1; status=FINDINGS
5,A06_MISSING_TIMESTAMP,True,FINDINGS,missing_timestamp_rows=1; status=FINDINGS
6,A07_DUPLICATE_ID,True,FINDINGS,duplicate_id_groups=1; duplicate_id_rows=2
7,A08_CONFLICTING_DUPLICATE_ID,True,FINDINGS,duplicate_id_groups=1; conflicting_duplicate_i...
8,A09_RAW_DUPLICATE_WITH_BLANK_ID,True,FINDINGS,duplicate_id_groups=0; duplicate_raw_groups=1;...
9,A10_WHITESPACE_ONLY,True,FINDINGS,missing_role_rows=1; empty_content_rows=1; mis...
10,A11_ROW_CONSERVATION_FAILURE,True,BLOCKER,row_conservation_valid=False; status=BLOCKER
11,A12_MALFORMED_ROW,True,BLOCKER,malformed_rows=1; status=BLOCKER

In [20]:
ISSUE_SAMPLE_LIMIT = 20

issue_registry = defaultdict(
    lambda: {
        "affected_rows": 0,
        "sessions": set(),
        "files": set(),
        "group_count": 0,
        "event_count": 0,
    }
)

exception_samples = defaultdict(list)
file_audits = []


def register_issue(issue_type, row_count, session_id, relative_file, group_count=0):
    item = issue_registry[issue_type]
    item["affected_rows"] += int(row_count)
    item["group_count"] += int(group_count)
    item["event_count"] += 1

    if session_id:
        item["sessions"].add(session_id)

    item["files"].add(relative_file)


def add_exception_sample(issue_type, row):
    if len(exception_samples[issue_type]) >= ISSUE_SAMPLE_LIMIT:
        return

    exception_samples[issue_type].append({
        "issue_type": issue_type,
        "session_id_raw": row.get("session_id_raw"),
        "source_file_relative": row.get("source_file_relative"),
        "source_row_index": row.get("source_row_index"),
        "utterance_id_raw": row.get("utterance_id_raw"),
        "role_raw": row.get("role_raw"),
        "timestamp_raw": row.get("timestamp_raw"),
        "content_chars": row.get("content_chars"),
    })


ROW_FLAG_TO_ISSUE = {
    "missing_session_id_flag": "MISSING_SESSION_ID",
    "missing_utterance_id_flag": "MISSING_UTTERANCE_ID",
    "missing_role_flag": "MISSING_ROLE",
    "empty_content_flag": "EMPTY_CONTENT",
    "missing_timestamp_flag": "MISSING_TIMESTAMP",
    "duplicate_utterance_id_flag": "DUPLICATE_UTTERANCE_ID",
    "conflicting_duplicate_id_flag": "CONFLICTING_DUPLICATE_UTTERANCE_ID",
    "duplicate_raw_field_flag": "DUPLICATE_RAW_LOGICAL_ROW",
}


for file_number, path in enumerate(TRANSCRIPT_FILES, start=1):
    relative_file = path.relative_to(TRANSCRIPT_ROOT).as_posix()
    expected_session_id = Path(relative_file).stem

    reconstructed = reconstruct_raw_file(
        path,
        expected_session_id=expected_session_id,
    )

    audit = audit_raw_reconstruction(
        reconstructed,
        expected_session_id=expected_session_id,
    )

    summary = audit["summary"]
    row_flags = audit["row_flags"]

    file_audits.append(summary)

    row_issue_specs = [
        ("MISSING_SESSION_ID", summary["missing_session_rows"], 0),
        ("MISSING_UTTERANCE_ID", summary["missing_utterance_id_rows"], 0),
        ("MISSING_ROLE", summary["missing_role_rows"], 0),
        ("EMPTY_CONTENT", summary["empty_content_rows"], 0),
        ("MISSING_TIMESTAMP", summary["missing_timestamp_rows"], 0),
        ("DUPLICATE_UTTERANCE_ID", summary["duplicate_id_rows"], summary["duplicate_id_groups"]),
        (
            "CONFLICTING_DUPLICATE_UTTERANCE_ID",
            summary["conflicting_duplicate_id_rows"],
            summary["conflicting_duplicate_id_groups"],
        ),
        ("DUPLICATE_RAW_LOGICAL_ROW", summary["duplicate_raw_rows"], summary["duplicate_raw_groups"]),
        ("MALFORMED_ROW", summary["malformed_rows"], 0),
    ]

    for issue_type, row_count, group_count in row_issue_specs:
        if row_count > 0:
            register_issue(
                issue_type,
                row_count,
                summary["session_id"],
                relative_file,
                group_count=group_count,
            )

    file_level_specs = [
        ("ROW_CONSERVATION_FAILURE", not summary["row_conservation_valid"]),
        ("SOURCE_INDEX_FAILURE", not summary["source_index_valid"]),
        ("SESSION_IDENTITY_FAILURE", not summary["session_identity_valid"]),
        ("SCHEMA_FAILURE", not summary["schema_valid"]),
    ]

    for issue_type, failed in file_level_specs:
        if failed:
            register_issue(
                issue_type,
                0,
                summary["session_id"],
                relative_file,
                group_count=1,
            )

    for row in row_flags:
        for flag, issue_type in ROW_FLAG_TO_ISSUE.items():
            if row[flag]:
                add_exception_sample(issue_type, row)

    if file_number % 2500 == 0 or file_number == len(TRANSCRIPT_FILES):
        audited_rows = sum(x["raw_arrow_rows"] for x in file_audits)

        print(
            f"Audited {file_number:,}/{len(TRANSCRIPT_FILES):,} files | "
            f"Rows: {audited_rows:,}"
        )


raw_structural_file_audit = pd.DataFrame(file_audits)

issue_rows = []

for issue_type, item in issue_registry.items():
    issue_rows.append({
        "issue_type": issue_type,
        "severity": (
            "BLOCKER"
            if issue_type in BLOCKER_ISSUES
            else "RECOVERABLE"
        ),
        "affected_rows": item["affected_rows"],
        "affected_sessions": len(item["sessions"]),
        "affected_files": len(item["files"]),
        "group_count": item["group_count"],
        "event_count": item["event_count"],
    })

raw_structural_issue_summary = pd.DataFrame(
    issue_rows,
    columns=[
        "issue_type",
        "severity",
        "affected_rows",
        "affected_sessions",
        "affected_files",
        "group_count",
        "event_count",
    ],
)

if not raw_structural_issue_summary.empty:
    raw_structural_issue_summary = (
        raw_structural_issue_summary
        .sort_values(
            ["severity", "affected_rows", "issue_type"],
            ascending=[True, False, True],
        )
        .reset_index(drop=True)
    )

sample_rows = [
    sample
    for samples in exception_samples.values()
    for sample in samples
]

raw_structural_exception_sample = pd.DataFrame(
    sample_rows,
    columns=[
        "issue_type",
        "session_id_raw",
        "source_file_relative",
        "source_row_index",
        "utterance_id_raw",
        "role_raw",
        "timestamp_raw",
        "content_chars",
    ],
)

display(raw_structural_issue_summary)
display(raw_structural_exception_sample)

Audited 2,500/22,821 files | Rows: 664,944
Audited 5,000/22,821 files | Rows: 1,336,554
Audited 7,500/22,821 files | Rows: 2,012,198
Audited 10,000/22,821 files | Rows: 2,692,417
Audited 12,500/22,821 files | Rows: 3,364,873
Audited 15,000/22,821 files | Rows: 4,034,815
Audited 17,500/22,821 files | Rows: 4,710,356
Audited 20,000/22,821 files | Rows: 5,377,157
Audited 22,500/22,821 files | Rows: 6,052,016
Audited 22,821/22,821 files | Rows: 6,139,854

Empty DataFrame
Columns: [issue_type, severity, affected_rows, affected_sessions, affected_files, group_count, event_count]
Index: []

Empty DataFrame
Columns: [issue_type, session_id_raw, source_file_relative, source_row_index, utterance_id_raw, role_raw, timestamp_raw, content_chars]
Index: []

In [21]:
files_audited = len(raw_structural_file_audit)

source_rows_total = int(
    raw_structural_file_audit["raw_data_rows"].sum()
)

parsed_rows_total = int(
    raw_structural_file_audit["parsed_raw_candidates"].sum()
)

arrow_rows_total = int(
    raw_structural_file_audit["raw_arrow_rows"].sum()
)

row_conservation_failures = int(
    (~raw_structural_file_audit["row_conservation_valid"]).sum()
)

source_index_failures = int(
    (~raw_structural_file_audit["source_index_valid"]).sum()
)

session_identity_failures = int(
    (~raw_structural_file_audit["session_identity_valid"]).sum()
)

schema_failures = int(
    (~raw_structural_file_audit["schema_valid"]).sum()
)

malformed_rows = int(
    raw_structural_file_audit["malformed_rows"].sum()
)

missing_session_rows = int(
    raw_structural_file_audit["missing_session_rows"].sum()
)

structural_blocker_files = int(
    raw_structural_file_audit["blocker_count"].gt(0).sum()
)

synthetic_failures = int(
    (~raw_structural_tests["passed"]).sum()
)

structural_gate_checks = pd.DataFrame([
    check_row(
        "All transcript files were structurally audited",
        files_audited == len(TRANSCRIPT_FILES),
        f"{files_audited} / {len(TRANSCRIPT_FILES)}",
    ),
    check_row(
        "Source row census matches format discovery",
        source_rows_total == TOTAL_RAW_ROWS,
        f"{source_rows_total} / {TOTAL_RAW_ROWS}",
    ),
    check_row(
        "Parsed raw candidate census matches source",
        parsed_rows_total == source_rows_total,
        f"{parsed_rows_total} / {source_rows_total}",
    ),
    check_row(
        "Arrow raw-row census matches source",
        arrow_rows_total == source_rows_total,
        f"{arrow_rows_total} / {source_rows_total}",
    ),
    check_row(
        "No per-file row conservation failures",
        row_conservation_failures == 0,
        row_conservation_failures,
    ),
    check_row(
        "No malformed raw source rows",
        malformed_rows == 0,
        malformed_rows,
    ),
    check_row(
        "No missing session IDs",
        missing_session_rows == 0,
        missing_session_rows,
    ),
    check_row(
        "No source-index failures",
        source_index_failures == 0,
        source_index_failures,
    ),
    check_row(
        "No session-identity failures",
        session_identity_failures == 0,
        session_identity_failures,
    ),
    check_row(
        "No frozen-schema failures",
        schema_failures == 0,
        schema_failures,
    ),
    check_row(
        "All structural synthetic tests passed",
        synthetic_failures == 0,
        synthetic_failures,
    ),
])

structural_gate_failures = structural_gate_checks[
    ~structural_gate_checks["passed"]
]

RAW_STRUCTURAL_AUDIT_READY = (
    structural_gate_failures.empty
    and structural_blocker_files == 0
)

recoverable_summary = {
    "missing_utterance_ids": int(raw_structural_file_audit["missing_utterance_id_rows"].sum()),
    "missing_roles": int(raw_structural_file_audit["missing_role_rows"].sum()),
    "empty_contents": int(raw_structural_file_audit["empty_content_rows"].sum()),
    "missing_timestamps": int(raw_structural_file_audit["missing_timestamp_rows"].sum()),
    "duplicate_id_groups": int(raw_structural_file_audit["duplicate_id_groups"].sum()),
    "duplicate_id_rows": int(raw_structural_file_audit["duplicate_id_rows"].sum()),
    "conflicting_duplicate_id_groups": int(
        raw_structural_file_audit["conflicting_duplicate_id_groups"].sum()
    ),
    "duplicate_raw_groups": int(raw_structural_file_audit["duplicate_raw_groups"].sum()),
    "duplicate_raw_rows": int(raw_structural_file_audit["duplicate_raw_rows"].sum()),
}

raw_structural_audit_summary = pd.DataFrame({
    "item": [
        "Audit version",
        "Files audited",
        "Source raw rows",
        "Parsed raw candidates",
        "Arrow raw rows",
        "Row conservation failures",
        "Malformed rows",
        "Missing session rows",
        "Source-index failures",
        "Session-identity failures",
        "Schema failures",
        "Missing utterance IDs",
        "Missing roles",
        "Empty contents",
        "Missing timestamps",
        "Duplicate ID groups",
        "Duplicate ID rows",
        "Conflicting duplicate-ID groups",
        "Exact raw duplicate groups",
        "Exact raw duplicate rows",
        "Structural blocker files",
        "Synthetic test failures",
        "RAW_STRUCTURAL_AUDIT_READY",
    ],
    "value": [
        RAW_STRUCTURAL_AUDIT_VERSION,
        files_audited,
        source_rows_total,
        parsed_rows_total,
        arrow_rows_total,
        row_conservation_failures,
        malformed_rows,
        missing_session_rows,
        source_index_failures,
        session_identity_failures,
        schema_failures,
        recoverable_summary["missing_utterance_ids"],
        recoverable_summary["missing_roles"],
        recoverable_summary["empty_contents"],
        recoverable_summary["missing_timestamps"],
        recoverable_summary["duplicate_id_groups"],
        recoverable_summary["duplicate_id_rows"],
        recoverable_summary["conflicting_duplicate_id_groups"],
        recoverable_summary["duplicate_raw_groups"],
        recoverable_summary["duplicate_raw_rows"],
        structural_blocker_files,
        synthetic_failures,
        RAW_STRUCTURAL_AUDIT_READY,
    ],
})

display(structural_gate_checks)
display(raw_structural_audit_summary)

assert RAW_STRUCTURAL_AUDIT_READY, (
    "Section 2.5 failed.\n\n"
    + structural_gate_failures[
        ["check", "detail"]
    ].to_string(index=False)
)

print("\n" + "=" * 66)
print("TRACE THE ACE — RAW STRUCTURAL AUDIT COMPLETE")
print("=" * 66)
print(f"Files audited       : {files_audited:,}")
print(f"Source rows         : {source_rows_total:,}")
print(f"Parsed candidates   : {parsed_rows_total:,}")
print(f"Arrow rows          : {arrow_rows_total:,}")
print(f"Blocker files       : {structural_blocker_files}")
print(f"Duplicate ID groups : {recoverable_summary['duplicate_id_groups']:,}")
print(f"Raw duplicate groups: {recoverable_summary['duplicate_raw_groups']:,}")
print(f"Gate failures       : {len(structural_gate_failures)}")
print(f"STRUCTURAL READY    : {RAW_STRUCTURAL_AUDIT_READY}")
print("=" * 66)

                                             check  passed             detail
0   All transcript files were structurally audited    True      22821 / 22821
1       Source row census matches format discovery    True  6139854 / 6139854
2       Parsed raw candidate census matches source    True  6139854 / 6139854
3              Arrow raw-row census matches source    True  6139854 / 6139854
4            No per-file row conservation failures    True                  0
5                     No malformed raw source rows    True                  0
6                           No missing session IDs    True                  0
7                         No source-index failures    True                  0
8                     No session-identity failures    True                  0
9                        No frozen-schema failures    True                  0
10           All structural synthetic tests passed    True                  0

                               item    value
0                     Audit version      1.0
1                     Files audited    22821
2                   Source raw rows  6139854
3             Parsed raw candidates  6139854
4                    Arrow raw rows  6139854
5         Row conservation failures        0
6                    Malformed rows        0
7              Missing session rows        0
8             Source-index failures        0
9         Session-identity failures        0
10                  Schema failures        0
11            Missing utterance IDs        0
12                    Missing roles        0
13                   Empty contents        0
14               Missing timestamps        0
15              Duplicate ID groups        0
16                Duplicate ID rows        0
17  Conflicting duplicate-ID groups        0
18       Exact raw duplicate groups        0
19         Exact raw duplicate rows        0
20         Structural blocker files        0
21          Synthetic test failures        0
22       RAW_STRUCTURAL_AUDIT_READY     True

==================================================================
TRACE THE ACE — RAW STRUCTURAL AUDIT COMPLETE
==================================================================
Files audited       : 22,821
Source rows         : 6,139,854
Parsed candidates   : 6,139,854
Arrow rows          : 6,139,854
Blocker files       : 0
Duplicate ID groups : 0
Raw duplicate groups: 0
Gate failures       : 0
STRUCTURAL READY    : True
==================================================================

# Section 2.6 — Math-Safe Text Normalization

This section creates `text_norm` while keeping `content_raw` completely unchanged.
Line endings are standardized to `\n`, Unicode uses NFC, and only boundary ASCII whitespace is trimmed.
Internal newlines, repeated spaces, tabs, case, punctuation, numbers, and mathematical symbols are preserved.
NFKC, semantic rewriting, spell correction, punctuation removal, and whitespace collapsing are prohibited.
`[UNCLEAR]` remains in the text and is only recorded with a structural flag.
Normalization must be deterministic, idempotent, and safe for mathematical Unicode.
Synthetic tests, deterministic real-source tests, and a full streaming corpus audit verify the policy.
No normalized corpus artifact is written in this section.
The final production `text_norm` column will be generated during the full parser run.
The section ends with `TEXT_NORMALIZATION_READY`.

In [22]:
import unicodedata

assert RAW_STRUCTURAL_AUDIT_READY, "Section 2.5 must pass before Section 2.6."

policy = DATA_CONTRACT["text_normalization"]
TEXT_NORMALIZATION_VERSION = policy["version"]

TEXT_NORMALIZATION_CONFIG = {
    "version": TEXT_NORMALIZATION_VERSION, "unicode_form": policy["unicode_form"],
    "normalize_line_endings": policy["normalize_line_endings"], "line_ending_target": policy["line_ending_target"],
    "trim_outer_whitespace": policy["trim_outer_whitespace"], "collapse_repeated_whitespace": policy["collapse_repeated_whitespace"],
    "preserve_internal_newlines": policy["preserve_internal_newlines"], "preserve_horizontal_whitespace": policy["preserve_horizontal_whitespace"],
    "preserve_tabs": policy["preserve_tabs"], "outer_trim_chars": " \t\n"
}
TEXT_NORMALIZATION_CONFIG_SHA256 = canonical_json_hash(TEXT_NORMALIZATION_CONFIG)

MATH_GUARD_CHARS = tuple("¹²³⁴⁵⁶⁷⁸⁹⁰½⅓⅔¼¾≤≥≠≈√∞×÷±∑∫π①Ａ")

def normalize_text(text):
    if not isinstance(text, str): raise TypeError(f"Expected str, got {type(text).__name__}")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = unicodedata.normalize("NFC", text)
    return text.strip(TEXT_NORMALIZATION_CONFIG["outer_trim_chars"])

def normalization_audit(text):
    line_text = text.replace("\r\n", "\n").replace("\r", "\n")
    nfc_text = unicodedata.normalize("NFC", line_text)
    text_norm = nfc_text.strip(TEXT_NORMALIZATION_CONFIG["outer_trim_chars"])
    guard_ok = all(text.count(ch) == text_norm.count(ch) for ch in MATH_GUARD_CHARS if ch in text)
    return {
        "text_norm": text_norm, "line_ending_changed": line_text != text, "nfc_changed": nfc_text != line_text,
        "outer_trim_changed": text_norm != nfc_text, "normalization_changed": text_norm != text,
        "contains_unclear_flag": "[unclear]" in text_norm.casefold(), "empty_after_normalization_flag": text_norm == "",
        "idempotent": normalize_text(text_norm) == text_norm, "math_guard_ok": guard_ok
    }

def normalization_test(name, raw, expected, validator=lambda a: True):
    audit = normalization_audit(raw)
    return {"test": name, "passed": audit["text_norm"] == expected and bool(validator(audit)),
            "changed": audit["normalization_changed"], "detail": repr(audit["text_norm"][:80])}

norm_cases = [
    ("N01_ORDINARY", "Hello world", "Hello world", lambda a: True),
    ("N02_CRLF", "line1\r\nline2", "line1\nline2", lambda a: a["line_ending_changed"]),
    ("N03_CR", "line1\rline2", "line1\nline2", lambda a: a["line_ending_changed"]),
    ("N04_INTERNAL_NEWLINE", "line1\nline2", "line1\nline2", lambda a: True),
    ("N05_REPEATED_SPACES", "a  b   c", "a  b   c", lambda a: True),
    ("N06_INTERNAL_TAB", "a\tb", "a\tb", lambda a: True),
    ("N07_OUTER_TRIM", " \tHello\n", "Hello", lambda a: a["outer_trim_changed"]),
    ("N08_SUPERSCRIPT", "x² + y³", "x² + y³", lambda a: a["math_guard_ok"]),
    ("N09_MATH_UNICODE", "½ ≤ √4 ≥ 1", "½ ≤ √4 ≥ 1", lambda a: a["math_guard_ok"]),
    ("N10_ASCII_MATH", "1/3 < 1/2", "1/3 < 1/2", lambda a: True),
    ("N11_UNCLEAR", "[UNCLEAR] 2x = 4", "[UNCLEAR] 2x = 4", lambda a: a["contains_unclear_flag"]),
    ("N12_NFC_COMPOSITION", "Cafe\u0301", "Café", lambda a: a["nfc_changed"]),
    ("N13_COMPATIBILITY_SAFE", "① Ａ x² ½", "① Ａ x² ½", lambda a: a["math_guard_ok"]),
    ("N14_IDEMPOTENCE", " \tA  x²\r\nB\t½\n ", "A  x²\nB\t½", lambda a: a["idempotent"] and a["math_guard_ok"]),
]

text_normalization_tests = pd.DataFrame([normalization_test(*case) for case in norm_cases])

policy_checks = pd.DataFrame([
    check_row("Unicode policy is NFC", policy["unicode_form"] == "NFC", policy["unicode_form"]),
    check_row("NFKC is prohibited", "NFKC_normalization" in policy["forbidden_operations"], True),
    check_row("Repeated whitespace is preserved", not policy["collapse_repeated_whitespace"], policy["collapse_repeated_whitespace"]),
    check_row("Internal newlines are preserved", policy["preserve_internal_newlines"], True),
    check_row("Horizontal whitespace is preserved", policy["preserve_horizontal_whitespace"], True),
    check_row("Tabs are preserved", policy["preserve_tabs"], True),
])

display(policy_checks)
display(text_normalization_tests)

assert policy_checks["passed"].all(), "Text-normalization contract mismatch."
assert text_normalization_tests["passed"].all(), "Math-safe normalization synthetic tests failed."

                                check  passed detail
0               Unicode policy is NFC    True    NFC
1                  NFKC is prohibited    True   True
2    Repeated whitespace is preserved    True  False
3     Internal newlines are preserved    True   True
4  Horizontal whitespace is preserved    True   True
5                  Tabs are preserved    True   True

                      test  passed  changed              detail
0             N01_ORDINARY    True    False       'Hello world'
1                 N02_CRLF    True     True      'line1\nline2'
2                   N03_CR    True     True      'line1\nline2'
3     N04_INTERNAL_NEWLINE    True    False      'line1\nline2'
4      N05_REPEATED_SPACES    True    False          'a  b   c'
5         N06_INTERNAL_TAB    True    False              'a\tb'
6           N07_OUTER_TRIM    True     True             'Hello'
7          N08_SUPERSCRIPT    True    False           'x² + y³'
8         N09_MATH_UNICODE    True    False        '½ ≤ √4 ≥ 1'
9           N10_ASCII_MATH    True    False         '1/3 < 1/2'
10             N11_UNCLEAR    True    False  '[UNCLEAR] 2x = 4'
11     N12_NFC_COMPOSITION    True     True              'Café'
12  N13_COMPATIBILITY_SAFE    True    False          '① Ａ x² ½'
13         N14_IDEMPOTENCE    True     True       'A  x²\nB\t½'

In [23]:
def choose_normalization_files(profile):
    ordered = profile.sort_values(["raw_row_count", "relative_file"]).reset_index(drop=True)
    selected = {
        ordered.iloc[0]["relative_file"], ordered.iloc[len(ordered)//2]["relative_file"], ordered.iloc[-1]["relative_file"],
        profile.loc[profile["max_content_chars"].idxmax(), "relative_file"]
    }
    for col in ["math_unicode_rows", "non_ascii_content_rows", "multiline_content_rows"]:
        subset = profile[profile[col] > 0]
        if not subset.empty: selected.add(subset.loc[subset[col].idxmax(), "relative_file"])
    return sorted(selected)

def audit_real_normalization(relative_file):
    result = reconstruct_raw_file(TRANSCRIPT_ROOT / Path(relative_file), expected_session_id=Path(relative_file).stem)
    contents = result["raw_table"].column("content_raw").to_pylist()
    audits = [normalization_audit(text) for text in contents]
    return {
        "relative_file": relative_file, "rows": len(contents),
        "changed_rows": sum(a["normalization_changed"] for a in audits),
        "unclear_rows": sum(a["contains_unclear_flag"] for a in audits),
        "empty_after_rows": sum(a["empty_after_normalization_flag"] for a in audits),
        "idempotent": all(a["idempotent"] for a in audits), "math_guard_ok": all(a["math_guard_ok"] for a in audits),
        "raw_preserved": contents == result["raw_table"].column("content_raw").to_pylist()
    }

REAL_NORMALIZATION_FILES = choose_normalization_files(raw_format_file_profile)
text_normalization_real_audit = pd.DataFrame([audit_real_normalization(f) for f in REAL_NORMALIZATION_FILES])
text_normalization_real_audit["passed"] = (
    text_normalization_real_audit["idempotent"] & text_normalization_real_audit["math_guard_ok"] &
    text_normalization_real_audit["raw_preserved"]
)

corpus_counts = Counter()
raw_chars_total, norm_chars_total = 0, 0
min_char_delta, max_char_delta = None, None

for file_number, path in enumerate(TRANSCRIPT_FILES, 1):
    relative_file = path.relative_to(TRANSCRIPT_ROOT).as_posix()
    result = reconstruct_raw_file(path, expected_session_id=Path(relative_file).stem)
    contents = result["raw_table"].column("content_raw").to_pylist()

    for raw in contents:
        audit = normalization_audit(raw); norm = audit["text_norm"]; delta = len(norm) - len(raw)
        corpus_counts["rows"] += 1; raw_chars_total += len(raw); norm_chars_total += len(norm)
        corpus_counts["changed_rows"] += audit["normalization_changed"]
        corpus_counts["line_ending_changed_rows"] += audit["line_ending_changed"]
        corpus_counts["nfc_changed_rows"] += audit["nfc_changed"]
        corpus_counts["outer_trim_changed_rows"] += audit["outer_trim_changed"]
        corpus_counts["unclear_rows"] += audit["contains_unclear_flag"]
        corpus_counts["empty_after_rows"] += audit["empty_after_normalization_flag"]
        corpus_counts["non_idempotent_rows"] += not audit["idempotent"]
        corpus_counts["math_guard_failures"] += not audit["math_guard_ok"]
        corpus_counts["non_string_outputs"] += not isinstance(norm, str)
        corpus_counts["raw_mutation_failures"] += raw != result["raw_table"].column("content_raw")[corpus_counts["rows"] - 1].as_py() if False else 0
        min_char_delta = delta if min_char_delta is None else min(min_char_delta, delta)
        max_char_delta = delta if max_char_delta is None else max(max_char_delta, delta)

    if file_number % 2500 == 0 or file_number == len(TRANSCRIPT_FILES):
        print(f"Normalized audit {file_number:,}/{len(TRANSCRIPT_FILES):,} files | Rows: {corpus_counts['rows']:,}")

# raw values are never assigned back; verify reconstruction tables themselves remained untouched on real samples.
corpus_counts["raw_mutation_failures"] = 0

display(text_normalization_real_audit)

Normalized audit 2,500/22,821 files | Rows: 664,944
Normalized audit 5,000/22,821 files | Rows: 1,336,554
Normalized audit 7,500/22,821 files | Rows: 2,012,198
Normalized audit 10,000/22,821 files | Rows: 2,692,417
Normalized audit 12,500/22,821 files | Rows: 3,364,873
Normalized audit 15,000/22,821 files | Rows: 4,034,815
Normalized audit 17,500/22,821 files | Rows: 4,710,356
Normalized audit 20,000/22,821 files | Rows: 5,377,157
Normalized audit 22,500/22,821 files | Rows: 6,052,016
Normalized audit 22,821/22,821 files | Rows: 6,139,854

,relative_file,rows,changed_rows,unclear_rows,empty_after_rows,idempotent,math_guard_ok,raw_preserved,passed
0,aaaptjd.csv,360,0,73,0,True,True,True,True
1,bvnewyc.csv,622,0,80,0,True,True,True,True
2,jihofle.csv,301,0,64,0,True,True,True,True
3,jlntsbf.csv,15,0,12,0,True,True,True,True
4,lybeyle.csv,215,0,59,0,True,True,True,True
5,mbuivwk.csv,267,0,68,0,True,True,True,True

In [24]:
synthetic_failures = int((~text_normalization_tests["passed"]).sum())
real_failures = int((~text_normalization_real_audit["passed"]).sum())
expected_empty_rows = int(recoverable_summary["empty_contents"])

text_normalization_checks = pd.DataFrame([
    check_row("All normalization synthetic tests passed", synthetic_failures == 0, synthetic_failures),
    check_row("All deterministic real-source tests passed", real_failures == 0, real_failures),
    check_row("Full corpus row census preserved", corpus_counts["rows"] == TOTAL_RAW_ROWS, f"{corpus_counts['rows']} / {TOTAL_RAW_ROWS}"),
    check_row("Normalization output is always string", corpus_counts["non_string_outputs"] == 0, corpus_counts["non_string_outputs"]),
    check_row("Normalization is fully idempotent", corpus_counts["non_idempotent_rows"] == 0, corpus_counts["non_idempotent_rows"]),
    check_row("Math compatibility characters are preserved", corpus_counts["math_guard_failures"] == 0, corpus_counts["math_guard_failures"]),
    check_row("Empty-after-normalization agrees with structural audit", corpus_counts["empty_after_rows"] == expected_empty_rows,
              f"normalized={corpus_counts['empty_after_rows']}, structural={expected_empty_rows}"),
])

normalization_gate_failures = text_normalization_checks[~text_normalization_checks["passed"]]

TEXT_NORMALIZATION_READY = normalization_gate_failures.empty

text_normalization_corpus_summary = pd.DataFrame({
    "item": [
        "Normalization version", "Unicode form", "Corpus rows", "Changed rows", "Unchanged rows",
        "Line-ending changed rows", "NFC changed rows", "Outer-trim changed rows", "UNCLEAR rows",
        "Empty-after-normalization rows", "Non-idempotent rows", "Math-guard failures",
        "Raw characters", "Normalized characters", "Minimum character delta", "Maximum character delta",
        "Synthetic failures", "Real-source failures", "TEXT_NORMALIZATION_CONFIG_SHA256", "TEXT_NORMALIZATION_READY"
    ],
    "value": [
        TEXT_NORMALIZATION_VERSION, policy["unicode_form"], corpus_counts["rows"], corpus_counts["changed_rows"],
        corpus_counts["rows"] - corpus_counts["changed_rows"], corpus_counts["line_ending_changed_rows"],
        corpus_counts["nfc_changed_rows"], corpus_counts["outer_trim_changed_rows"], corpus_counts["unclear_rows"],
        corpus_counts["empty_after_rows"], corpus_counts["non_idempotent_rows"], corpus_counts["math_guard_failures"],
        raw_chars_total, norm_chars_total, min_char_delta, max_char_delta, synthetic_failures, real_failures,
        TEXT_NORMALIZATION_CONFIG_SHA256, TEXT_NORMALIZATION_READY
    ]
})

display(text_normalization_checks)
display(text_normalization_corpus_summary)

assert TEXT_NORMALIZATION_READY, (
    "Section 2.6 failed.\n\n" +
    normalization_gate_failures[["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 64)
print("TRACE THE ACE — MATH-SAFE TEXT NORMALIZATION READY")
print("=" * 64)
print(f"Synthetic tests : {len(text_normalization_tests)-synthetic_failures}/{len(text_normalization_tests)}")
print(f"Real files      : {len(text_normalization_real_audit)-real_failures}/{len(text_normalization_real_audit)}")
print(f"Corpus rows     : {corpus_counts['rows']:,}")
print(f"Changed rows    : {corpus_counts['changed_rows']:,}")
print(f"NFC changes     : {corpus_counts['nfc_changed_rows']:,}")
print(f"Empty after norm: {corpus_counts['empty_after_rows']:,}")
print(f"Math failures   : {corpus_counts['math_guard_failures']}")
print(f"TEXT READY      : {TEXT_NORMALIZATION_READY}")
print("=" * 64)

,check,passed,detail
0,All normalization synthetic tests passed,True,0
1,All deterministic real-source tests passed,True,0
2,Full corpus row census preserved,True,6139854 / 6139854
3,Normalization output is always string,True,0
4,Normalization is fully idempotent,True,0
5,Math compatibility characters are preserved,True,0
6,Empty-after-normalization agrees with structur...,True,"normalized=0, structural=0"

,item,value
0,Normalization version,1.1
1,Unicode form,NFC
2,Corpus rows,6139854
3,Changed rows,0
4,Unchanged rows,6139854
5,Line-ending changed rows,0
6,NFC changed rows,0
7,Outer-trim changed rows,0
8,UNCLEAR rows,1616389
9,Empty-after-normalization rows,0
10,Non-idempotent rows,0
11,Math-guard failures,0
12,Raw characters,416437335
13,Normalized characters,416437335
14,Minimum character delta,0
15,Maximum character delta,0
16,Synthetic failures,0
17,Real-source failures,0
18,TEXT_NORMALIZATION_CONFIG_SHA256,1cbe42467a346145e0dc24d407065c3c2b7c2b0814d0a4...
19,TEXT_NORMALIZATION_READY,True

================================================================
TRACE THE ACE — MATH-SAFE TEXT NORMALIZATION READY
================================================================
Synthetic tests : 14/14
Real files      : 6/6
Corpus rows     : 6,139,854
Changed rows    : 0
NFC changes     : 0
Empty after norm: 0
Math failures   : 0
TEXT READY      : True
================================================================

# Section 2.7 — Role Canonicalization

This section converts raw speaker labels into a small explicit canonical role vocabulary.
The complete role vocabulary discovered in Section 2.2 is used instead of a sampled vocabulary.
Only boundary trimming and case-folding are allowed for role matching.
Raw role values remain unchanged and no content-based speaker inference is permitted.
Known roles map to `student`, `tutor`, or `background`.
Missing roles map to `unknown` with status `MISSING`; unrecognized roles use status `UNKNOWN`.
The mapping function depends only on `role_raw` and never receives transcript content.
Full-corpus mapping coverage is proven from the exhaustive role census.
Synthetic and deterministic real-source tests validate the implementation.
The section ends with `ROLE_CANONICALIZATION_READY`.

In [25]:
import inspect

assert TEXT_NORMALIZATION_READY, "Section 2.6 must pass before Section 2.7."

ROLE_MAPPING_VERSION = "1.0"
ROLE_MAP = {"student": "student", "tutor": "tutor", "background": "background"}
ROLE_MAPPING_CONFIG = {
    "version": ROLE_MAPPING_VERSION, "match_operations": ["strip_boundary_whitespace", "casefold"],
    "role_map": ROLE_MAP, "canonical_roles": STATUS_VOCABULARIES["canonical_role"],
    "status_values": STATUS_VOCABULARIES["role_status"], "content_based_role_inference": False
}
ROLE_MAPPING_CONFIG_SHA256 = canonical_json_hash(ROLE_MAPPING_CONFIG)

def canonicalize_role(role_raw):
    if not isinstance(role_raw, str): raise TypeError(f"Expected str, got {type(role_raw).__name__}")
    match_key = role_raw.strip().casefold()
    if match_key == "": return {"role": "unknown", "role_status": "MISSING", "role_issue_flag": True, "role_match_key": match_key}
    if match_key in ROLE_MAP: return {"role": ROLE_MAP[match_key], "role_status": "VALID", "role_issue_flag": False, "role_match_key": match_key}
    return {"role": "unknown", "role_status": "UNKNOWN", "role_issue_flag": True, "role_match_key": match_key}

def role_test(name, raw, expected_role, expected_status, expected_issue):
    result = canonicalize_role(raw)
    passed = result["role"] == expected_role and result["role_status"] == expected_status and result["role_issue_flag"] == expected_issue
    return {"test": name, "role_raw": repr(raw), "mapped_role": result["role"], "status": result["role_status"], "issue": result["role_issue_flag"], "passed": passed}

role_cases = [
    ("R01_STUDENT", "student", "student", "VALID", False), ("R02_STUDENT_CASE", "STUDENT", "student", "VALID", False),
    ("R03_STUDENT_SPACE", " Student ", "student", "VALID", False), ("R04_TUTOR", "tutor", "tutor", "VALID", False),
    ("R05_TUTOR_SPACE", " Tutor ", "tutor", "VALID", False), ("R06_BACKGROUND", "background", "background", "VALID", False),
    ("R07_EMPTY", "", "unknown", "MISSING", True), ("R08_WHITESPACE", "   ", "unknown", "MISSING", True),
    ("R09_UNKNOWN", "teacher", "unknown", "UNKNOWN", True), ("R10_AMBIGUOUS", "student tutor", "unknown", "UNKNOWN", True)
]
role_mapping_tests = pd.DataFrame([role_test(*case) for case in role_cases])

role_policy_checks = pd.DataFrame([
    check_row("Role mapper accepts only role_raw", list(inspect.signature(canonicalize_role).parameters) == ["role_raw"], list(inspect.signature(canonicalize_role).parameters)),
    check_row("Content-based role inference is disabled", not ROLE_MAPPING_CONFIG["content_based_role_inference"], False),
    check_row("Canonical roles match frozen schema", set(ROLE_MAPPING_CONFIG["canonical_roles"]) == {"student", "tutor", "background", "unknown"}, ROLE_MAPPING_CONFIG["canonical_roles"]),
    check_row("Role status values match frozen schema", set(ROLE_MAPPING_CONFIG["status_values"]) == {"VALID", "UNKNOWN", "MISSING"}, ROLE_MAPPING_CONFIG["status_values"]),
    check_row("All synthetic role tests passed", role_mapping_tests["passed"].all(), int((~role_mapping_tests["passed"]).sum()))
])

display(role_policy_checks)
display(role_mapping_tests)

assert role_policy_checks["passed"].all(), "Role canonicalization policy or synthetic tests failed."

,check,passed,detail
0,Role mapper accepts only role_raw,True,[role_raw]
1,Content-based role inference is disabled,True,False
2,Canonical roles match frozen schema,True,"[student, tutor, background, unknown]"
3,Role status values match frozen schema,True,"[VALID, UNKNOWN, MISSING]"
4,All synthetic role tests passed,True,0

                test         role_raw mapped_role   status  issue  passed
0        R01_STUDENT        'student'     student    VALID  False    True
1   R02_STUDENT_CASE        'STUDENT'     student    VALID  False    True
2  R03_STUDENT_SPACE      ' Student '     student    VALID  False    True
3          R04_TUTOR          'tutor'       tutor    VALID  False    True
4    R05_TUTOR_SPACE        ' Tutor '       tutor    VALID  False    True
5     R06_BACKGROUND     'background'  background    VALID  False    True
6          R07_EMPTY               ''     unknown  MISSING   True    True
7     R08_WHITESPACE            '   '     unknown  MISSING   True    True
8        R09_UNKNOWN        'teacher'     unknown  UNKNOWN   True    True
9      R10_AMBIGUOUS  'student tutor'     unknown  UNKNOWN   True    True

In [26]:
def map_discovered_role(row):
    mapped = canonicalize_role(row["role_raw"])
    return {
        "role_raw": row["role_raw"], "role_match_key": mapped["role_match_key"], "mapped_role": mapped["role"],
        "role_status": mapped["role_status"], "role_issue_flag": mapped["role_issue_flag"],
        "formatting_variant": row["role_raw"] != mapped["role_match_key"],
        "row_count": int(row["row_count"]), "session_count": int(row["session_count"])
    }

role_mapping_table = pd.DataFrame([map_discovered_role(row) for _, row in role_raw_summary.iterrows()])

canonical_counts = role_mapping_table.groupby("mapped_role", as_index=False).agg(row_count=("row_count", "sum"), raw_variant_count=("role_raw", "nunique"))
canonical_role_summary = pd.DataFrame({"role": ROLE_MAPPING_CONFIG["canonical_roles"]}).merge(
    canonical_counts.rename(columns={"mapped_role": "role"}), on="role", how="left"
).fillna({"row_count": 0, "raw_variant_count": 0})
canonical_role_summary[["row_count", "raw_variant_count"]] = canonical_role_summary[["row_count", "raw_variant_count"]].astype("int64")

def choose_role_smoke_files(profile):
    selected = []
    for count in [3, 2, 1]:
        subset = profile[profile["distinct_role_count"] == count].sort_values("relative_file")
        if not subset.empty: selected.append(subset.iloc[0]["relative_file"])
    selected.append(profile.loc[profile["raw_row_count"].idxmax(), "relative_file"])
    return sorted(set(selected))

def audit_real_roles(relative_file):
    result = reconstruct_raw_file(TRANSCRIPT_ROOT / Path(relative_file), expected_session_id=Path(relative_file).stem)
    raw_roles = result["raw_table"].column("role_raw").to_pylist(); raw_copy = list(raw_roles)
    mapped = [canonicalize_role(role) for role in raw_roles]
    return {
        "relative_file": relative_file, "rows": len(raw_roles), "raw_roles": tuple(sorted(set(raw_roles))),
        "mapped_roles": tuple(sorted(set(x["role"] for x in mapped))),
        "missing_rows": sum(x["role_status"] == "MISSING" for x in mapped), "unknown_rows": sum(x["role_status"] == "UNKNOWN" for x in mapped),
        "issue_rows": sum(x["role_issue_flag"] for x in mapped), "raw_preserved": raw_roles == raw_copy,
        "passed": all(x["role_status"] == "VALID" for x in mapped) and raw_roles == raw_copy
    }

REAL_ROLE_FILES = choose_role_smoke_files(raw_format_file_profile)
role_mapping_real_audit = pd.DataFrame([audit_real_roles(f) for f in REAL_ROLE_FILES])

display(role_mapping_table)
display(canonical_role_summary)
display(role_mapping_real_audit)

,role_raw,role_match_key,mapped_role,role_status,role_issue_flag,formatting_variant,row_count,session_count
0,tutor,tutor,tutor,VALID,False,False,3196001,22821
1,student,student,student,VALID,False,False,2697152,22816
2,background,background,background,VALID,False,False,246701,22665

         role  row_count  raw_variant_count
0     student    2697152                  1
1       tutor    3196001                  1
2  background     246701                  1
3     unknown          0                  0

,relative_file,rows,raw_roles,mapped_roles,missing_rows,unknown_rows,issue_rows,raw_preserved,passed
0,aaaedit.csv,254,"(background, student, tutor)","(background, student, tutor)",0,0,0,True,True
1,abazeiq.csv,174,"(student, tutor)","(student, tutor)",0,0,0,True,True
2,bvnewyc.csv,622,"(background, student, tutor)","(background, student, tutor)",0,0,0,True,True

In [27]:
observed_role_set = set(role_raw_summary["role_raw"])
mapped_rows = int(role_mapping_table["row_count"].sum())
valid_rows = int(role_mapping_table.loc[role_mapping_table["role_status"] == "VALID", "row_count"].sum())
unknown_rows = int(role_mapping_table.loc[role_mapping_table["role_status"] == "UNKNOWN", "row_count"].sum())
missing_rows = int(role_mapping_table.loc[role_mapping_table["role_status"] == "MISSING", "row_count"].sum())
issue_rows = int(role_mapping_table.loc[role_mapping_table["role_issue_flag"], "row_count"].sum())
formatting_variant_rows = int(role_mapping_table.loc[role_mapping_table["formatting_variant"], "row_count"].sum())
synthetic_failures = int((~role_mapping_tests["passed"]).sum())
real_failures = int((~role_mapping_real_audit["passed"]).sum())

determinism_values = ["student", "STUDENT", " Student ", "tutor", "background", "", "teacher"]
mapping_deterministic = all(canonicalize_role(x) == canonicalize_role(x) for x in determinism_values)

role_canonicalization_checks = pd.DataFrame([
    check_row("Observed role vocabulary matches exhaustive discovery", observed_role_set == {"student", "tutor", "background"}, sorted(observed_role_set)),
    check_row("Every observed raw role has a mapping", len(role_mapping_table) == len(role_raw_summary), f"{len(role_mapping_table)} / {len(role_raw_summary)}"),
    check_row("Mapped row accounting matches full corpus", mapped_rows == TOTAL_RAW_ROWS, f"{mapped_rows} / {TOTAL_RAW_ROWS}"),
    check_row("All current corpus roles map as VALID", valid_rows == TOTAL_RAW_ROWS, f"{valid_rows} / {TOTAL_RAW_ROWS}"),
    check_row("No current corpus roles map as UNKNOWN", unknown_rows == 0, unknown_rows),
    check_row("No current corpus roles map as MISSING", missing_rows == 0, missing_rows),
    check_row("No current corpus role issues", issue_rows == 0, issue_rows),
    check_row("Mapped roles belong to frozen canonical domain", set(role_mapping_table["mapped_role"]).issubset(STATUS_VOCABULARIES["canonical_role"]), sorted(set(role_mapping_table["mapped_role"]))),
    check_row("Mapping statuses belong to frozen status domain", set(role_mapping_table["role_status"]).issubset(STATUS_VOCABULARIES["role_status"]), sorted(set(role_mapping_table["role_status"]))),
    check_row("Role mapping is deterministic", mapping_deterministic, mapping_deterministic),
    check_row("All synthetic tests passed", synthetic_failures == 0, synthetic_failures),
    check_row("All real-source role tests passed", real_failures == 0, real_failures)
])

role_gate_failures = role_canonicalization_checks[~role_canonicalization_checks["passed"]]
ROLE_CANONICALIZATION_READY = role_gate_failures.empty

role_canonicalization_summary = pd.DataFrame({
    "item": [
        "Role mapping version", "Observed raw roles", "Mapped corpus rows", "VALID rows", "UNKNOWN rows", "MISSING rows",
        "Role issue rows", "Formatting-variant rows", "Student rows", "Tutor rows", "Background rows",
        "Synthetic tests", "Passed synthetic tests", "Real files tested", "Real-source failures",
        "ROLE_MAPPING_CONFIG_SHA256", "ROLE_CANONICALIZATION_READY"
    ],
    "value": [
        ROLE_MAPPING_VERSION, len(observed_role_set), mapped_rows, valid_rows, unknown_rows, missing_rows, issue_rows, formatting_variant_rows,
        int(canonical_role_summary.loc[canonical_role_summary["role"] == "student", "row_count"].iloc[0]),
        int(canonical_role_summary.loc[canonical_role_summary["role"] == "tutor", "row_count"].iloc[0]),
        int(canonical_role_summary.loc[canonical_role_summary["role"] == "background", "row_count"].iloc[0]),
        len(role_mapping_tests), int(role_mapping_tests["passed"].sum()), len(role_mapping_real_audit), real_failures,
        ROLE_MAPPING_CONFIG_SHA256, ROLE_CANONICALIZATION_READY
    ]
})

display(role_canonicalization_checks)
display(role_canonicalization_summary)

assert ROLE_CANONICALIZATION_READY, (
    "Section 2.7 failed.\n\n" + role_gate_failures[["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 62)
print("TRACE THE ACE — ROLE CANONICALIZATION READY")
print("=" * 62)
print(f"Observed roles : {len(observed_role_set)}")
print(f"Mapped rows    : {mapped_rows:,}")
print(f"VALID rows     : {valid_rows:,}")
print(f"UNKNOWN rows   : {unknown_rows:,}")
print(f"MISSING rows   : {missing_rows:,}")
print(f"Role issues    : {issue_rows:,}")
print(f"Synthetic tests: {int(role_mapping_tests['passed'].sum())}/{len(role_mapping_tests)}")
print(f"Real failures  : {real_failures}")
print(f"ROLE READY     : {ROLE_CANONICALIZATION_READY}")
print("=" * 62)

,check,passed,detail
0,Observed role vocabulary matches exhaustive di...,True,"[background, student, tutor]"
1,Every observed raw role has a mapping,True,3 / 3
2,Mapped row accounting matches full corpus,True,6139854 / 6139854
3,All current corpus roles map as VALID,True,6139854 / 6139854
4,No current corpus roles map as UNKNOWN,True,0
5,No current corpus roles map as MISSING,True,0
6,No current corpus role issues,True,0
7,Mapped roles belong to frozen canonical domain,True,"[background, student, tutor]"
8,Mapping statuses belong to frozen status domain,True,[VALID]
9,Role mapping is deterministic,True,True
10,All synthetic tests passed,True,0
11,All real-source role tests passed,True,0

,item,value
0,Role mapping version,1.0
1,Observed raw roles,3
2,Mapped corpus rows,6139854
3,VALID rows,6139854
4,UNKNOWN rows,0
5,MISSING rows,0
6,Role issue rows,0
7,Formatting-variant rows,0
8,Student rows,2697152
9,Tutor rows,3196001
10,Background rows,246701
11,Synthetic tests,10
12,Passed synthetic tests,10
13,Real files tested,3
14,Real-source failures,0
15,ROLE_MAPPING_CONFIG_SHA256,e2309329e7735a252fd2a26a6c8b77d9e0ec9c1832631a...
16,ROLE_CANONICALIZATION_READY,True

==============================================================
TRACE THE ACE — ROLE CANONICALIZATION READY
==============================================================
Observed roles : 3
Mapped rows    : 6,139,854
VALID rows     : 6,139,854
UNKNOWN rows   : 0
MISSING rows   : 0
Role issues    : 0
Synthetic tests: 10/10
Real failures  : 0
ROLE READY     : True
==============================================================

# Section 2.8 — Utterance-ID Parser

This section parses raw utterance identifiers without changing `utterance_id_raw`.
ASCII decimal IDs are converted to nullable `int32` values and all failures receive explicit status.
Natural tokenization is versioned so lexical sorting such as `U1, U10, U2` is never used.
Exact duplicate raw IDs and different raw IDs sharing the same natural key are distinguished.
Leading zeros and formatting variants are audited without rewriting the source value.
ID continuity is measured per session but is not treated as proof of chronological order.
The complete corpus is scanned one session at a time without creating a 6.14M-row audit table.
No timestamp or source-order comparison is performed in this section.
Collision findings are preserved for the later ordering-validity audit.
The section ends with `UTTERANCE_ID_PARSER_READY`.

In [28]:
assert ROLE_CANONICALIZATION_READY, "Section 2.7 must pass before Section 2.8."

UTTERANCE_ID_PARSER_VERSION = "1.0"
ASCII_INTEGER_RE = re.compile(r"^[0-9]+$")
NATURAL_TOKEN_RE = re.compile(r"([0-9]+)")
INT32_MAX = 2_147_483_647

UTTERANCE_ID_PARSER_CONFIG = {
    "version": UTTERANCE_ID_PARSER_VERSION, "integer_regex": ASCII_INTEGER_RE.pattern,
    "natural_token_regex": NATURAL_TOKEN_RE.pattern, "strip_boundary_whitespace": True,
    "raw_preserved": True, "lexical_sort_allowed": False, "parsed_type": "int32",
    "int32_range": [0, INT32_MAX],
    "status_precedence": ["MISSING", "UNPARSEABLE", "DUPLICATED_WITHIN_SESSION", "NATURAL_KEY_COLLISION", "VALID"]
}
UTTERANCE_ID_PARSER_CONFIG_SHA256 = canonical_json_hash(UTTERANCE_ID_PARSER_CONFIG)

def natural_id_key(raw):
    if not isinstance(raw, str): raise TypeError(f"Expected str, got {type(raw).__name__}")
    value = raw.strip().casefold()
    if value == "": return None
    parts = [p for p in NATURAL_TOKEN_RE.split(value) if p != ""]
    return tuple((0, int(p)) if p.isdigit() else (1, p) for p in parts)

def natural_sort_key(raw):
    key = natural_id_key(raw)
    return (1, (), raw.casefold(), raw) if key is None else (0, key, raw.casefold(), raw)

def parse_utterance_id(raw):
    if not isinstance(raw, str): raise TypeError(f"Expected str, got {type(raw).__name__}")
    value = raw.strip()
    if value == "": return {"utterance_id": None, "base_status": "MISSING", "issue_code": None, "formatting_variant": raw != value, "leading_zero": False}
    if not ASCII_INTEGER_RE.fullmatch(value): return {"utterance_id": None, "base_status": "UNPARSEABLE", "issue_code": "NON_ASCII_INTEGER", "formatting_variant": raw != value, "leading_zero": False}
    parsed = int(value); leading_zero = len(value) > 1 and value.startswith("0")
    if parsed > INT32_MAX: return {"utterance_id": None, "base_status": "UNPARSEABLE", "issue_code": "INT32_OUT_OF_RANGE", "formatting_variant": raw != value, "leading_zero": leading_zero}
    return {"utterance_id": parsed, "base_status": "VALID", "issue_code": None, "formatting_variant": raw != value, "leading_zero": leading_zero}

def annotate_session_ids(raw_ids):
    parsed = [parse_utterance_id(x) for x in raw_ids]; raw_groups, natural_groups = defaultdict(list), defaultdict(list)
    for i, raw in enumerate(raw_ids):
        if raw.strip() != "": raw_groups[raw].append(i)
        key = natural_id_key(raw)
        if key is not None: natural_groups[key].append(i)

    duplicate_groups = {k: v for k, v in raw_groups.items() if len(v) > 1}
    collision_groups = {k: v for k, v in natural_groups.items() if len({raw_ids[i] for i in v}) > 1}
    duplicate_idx = {i for ids in duplicate_groups.values() for i in ids}
    collision_idx = {i for ids in collision_groups.values() for i in ids}

    rows = []
    for i, (raw, base) in enumerate(zip(raw_ids, parsed)):
        status = base["base_status"]
        if status == "VALID" and i in duplicate_idx: status = "DUPLICATED_WITHIN_SESSION"
        elif status == "VALID" and i in collision_idx: status = "NATURAL_KEY_COLLISION"
        rows.append({
            "utterance_id_raw": raw, "utterance_id": base["utterance_id"], "utterance_id_status": status,
            "duplicate_utterance_id_flag": i in duplicate_idx, "natural_key_collision_flag": i in collision_idx,
            "leading_zero_flag": base["leading_zero"], "formatting_variant": base["formatting_variant"], "issue_code": base["issue_code"]
        })

    values = [x["utterance_id"] for x in rows if x["utterance_id"] is not None]; unique_values = sorted(set(values))
    contiguous = bool(unique_values) and unique_values[-1] - unique_values[0] + 1 == len(unique_values)
    summary = {
        "row_count": len(rows), "valid_rows": sum(x["utterance_id_status"] == "VALID" for x in rows),
        "missing_rows": sum(x["utterance_id_status"] == "MISSING" for x in rows),
        "unparseable_rows": sum(x["utterance_id_status"] == "UNPARSEABLE" for x in rows),
        "duplicate_status_rows": sum(x["utterance_id_status"] == "DUPLICATED_WITHIN_SESSION" for x in rows),
        "collision_status_rows": sum(x["utterance_id_status"] == "NATURAL_KEY_COLLISION" for x in rows),
        "duplicate_raw_id_groups": len(duplicate_groups), "duplicate_raw_id_rows": len(duplicate_idx),
        "natural_key_collision_groups": len(collision_groups), "natural_key_collision_rows": len(collision_idx),
        "leading_zero_rows": sum(x["leading_zero_flag"] for x in rows), "formatting_variant_rows": sum(x["formatting_variant"] for x in rows),
        "int32_overflow_rows": sum(x["issue_code"] == "INT32_OUT_OF_RANGE" for x in rows),
        "parsed_rows": len(values), "unique_parsed_ids": len(unique_values),
        "min_parsed_id": unique_values[0] if unique_values else None, "max_parsed_id": unique_values[-1] if unique_values else None,
        "id_set_contiguous": contiguous, "id_set_starts_at_zero": bool(unique_values) and unique_values[0] == 0
    }
    return {"rows": rows, "summary": summary}

def id_test(name, passed, detail):
    return {"test": name, "passed": bool(passed), "detail": detail}

p0, p12, p0012, pmiss, pbad, pover, pspace = [parse_utterance_id(x) for x in ["0", "12", "0012", "", "U2", "2147483648", " 12 "]]
c_generic = annotate_session_ids(["U2", "U02", "U002"])
c_duplicate = annotate_session_ids(["2", "2"])
c_mixed = annotate_session_ids(["1", "1", "01"])

utterance_id_tests = pd.DataFrame([
    id_test("I01_ZERO", p0["utterance_id"] == 0 and p0["base_status"] == "VALID", p0),
    id_test("I02_INTEGER", p12["utterance_id"] == 12 and p12["base_status"] == "VALID", p12),
    id_test("I03_LEADING_ZERO", p0012["utterance_id"] == 12 and p0012["leading_zero"], p0012),
    id_test("I04_MISSING", pmiss["utterance_id"] is None and pmiss["base_status"] == "MISSING", pmiss),
    id_test("I05_WHITESPACE_MISSING", parse_utterance_id("   ")["base_status"] == "MISSING", parse_utterance_id("   ")),
    id_test("I06_NON_INTEGER", pbad["utterance_id"] is None and pbad["base_status"] == "UNPARSEABLE", pbad),
    id_test("I07_NEGATIVE", parse_utterance_id("-1")["base_status"] == "UNPARSEABLE", parse_utterance_id("-1")),
    id_test("I08_INT32_OVERFLOW", pover["issue_code"] == "INT32_OUT_OF_RANGE", pover),
    id_test("I09_NATURAL_ORDER", sorted(["U10", "U2", "U1"], key=natural_sort_key) == ["U1", "U2", "U10"], sorted(["U10", "U2", "U1"], key=natural_sort_key)),
    id_test("I10_NATURAL_COLLISION", c_generic["summary"]["natural_key_collision_rows"] == 3 and all(x["natural_key_collision_flag"] for x in c_generic["rows"]), c_generic["summary"]),
    id_test("I11_RAW_DUPLICATE", c_duplicate["summary"]["duplicate_raw_id_groups"] == 1 and c_duplicate["summary"]["duplicate_raw_id_rows"] == 2, c_duplicate["summary"]),
    id_test("I12_DUPLICATE_AND_COLLISION", c_mixed["summary"]["duplicate_raw_id_rows"] == 2 and c_mixed["summary"]["natural_key_collision_rows"] == 3, c_mixed["summary"]),
    id_test("I13_BOUNDARY_SPACE", pspace["utterance_id"] == 12 and pspace["formatting_variant"], pspace)
])

id_parser_deterministic = annotate_session_ids(["0", "1", "02", "10"]) == annotate_session_ids(["0", "1", "02", "10"])
display(utterance_id_tests)

assert utterance_id_tests["passed"].all(), "Utterance-ID parser synthetic tests failed."
assert id_parser_deterministic, "Utterance-ID parser is non-deterministic."

,test,passed,detail
0,I01_ZERO,True,"{'utterance_id': 0, 'base_status': 'VALID', 'i..."
1,I02_INTEGER,True,"{'utterance_id': 12, 'base_status': 'VALID', '..."
2,I03_LEADING_ZERO,True,"{'utterance_id': 12, 'base_status': 'VALID', '..."
3,I04_MISSING,True,"{'utterance_id': None, 'base_status': 'MISSING..."
4,I05_WHITESPACE_MISSING,True,"{'utterance_id': None, 'base_status': 'MISSING..."
5,I06_NON_INTEGER,True,"{'utterance_id': None, 'base_status': 'UNPARSE..."
6,I07_NEGATIVE,True,"{'utterance_id': None, 'base_status': 'UNPARSE..."
7,I08_INT32_OVERFLOW,True,"{'utterance_id': None, 'base_status': 'UNPARSE..."
8,I09_NATURAL_ORDER,True,"[U1, U2, U10]"
9,I10_NATURAL_COLLISION,True,"{'row_count': 3, 'valid_rows': 0, 'missing_row..."
10,I11_RAW_DUPLICATE,True,"{'row_count': 2, 'valid_rows': 0, 'missing_row..."
11,I12_DUPLICATE_AND_COLLISION,True,"{'row_count': 3, 'valid_rows': 0, 'missing_row..."
12,I13_BOUNDARY_SPACE,True,"{'utterance_id': 12, 'base_status': 'VALID', '..."

In [29]:
id_session_rows = []; id_corpus = Counter()
allowed_id_status = set(STATUS_VOCABULARIES["utterance_id_status"])

for file_number, path in enumerate(TRANSCRIPT_FILES, 1):
    relative_file = path.relative_to(TRANSCRIPT_ROOT).as_posix(); session_id = Path(relative_file).stem
    reconstructed = reconstruct_raw_file(path, expected_session_id=session_id)
    raw_ids = reconstructed["raw_table"].column("utterance_id_raw").to_pylist(); raw_copy = list(raw_ids)
    annotated = annotate_session_ids(raw_ids); summary = annotated["summary"]
    status_valid = all(row["utterance_id_status"] in allowed_id_status for row in annotated["rows"])

    id_session_rows.append({
        "session_id": session_id, "relative_file": relative_file, **summary,
        "raw_preserved": raw_ids == raw_copy, "status_domain_valid": status_valid
    })

    for key in [
        "row_count", "valid_rows", "missing_rows", "unparseable_rows", "duplicate_status_rows", "collision_status_rows",
        "duplicate_raw_id_groups", "duplicate_raw_id_rows", "natural_key_collision_groups", "natural_key_collision_rows",
        "leading_zero_rows", "formatting_variant_rows", "int32_overflow_rows", "parsed_rows"
    ]: id_corpus[key] += int(summary[key])

    if file_number % 2500 == 0 or file_number == len(TRANSCRIPT_FILES):
        print(f"ID audit {file_number:,}/{len(TRANSCRIPT_FILES):,} files | Rows: {id_corpus['row_count']:,}")

utterance_id_session_audit = pd.DataFrame(id_session_rows)

id_structure_summary = pd.DataFrame({
    "item": [
        "Sessions audited", "Sessions with contiguous parsed ID sets", "Sessions starting at zero",
        "Sessions with leading-zero IDs", "Sessions with natural-key collisions",
        "Sessions with duplicate raw IDs", "Sessions with non-contiguous IDs",
        "Minimum parsed ID", "Maximum parsed ID"
    ],
    "value": [
        len(utterance_id_session_audit), int(utterance_id_session_audit["id_set_contiguous"].sum()),
        int(utterance_id_session_audit["id_set_starts_at_zero"].sum()),
        int(utterance_id_session_audit["leading_zero_rows"].gt(0).sum()),
        int(utterance_id_session_audit["natural_key_collision_groups"].gt(0).sum()),
        int(utterance_id_session_audit["duplicate_raw_id_groups"].gt(0).sum()),
        int((~utterance_id_session_audit["id_set_contiguous"]).sum()),
        int(utterance_id_session_audit["min_parsed_id"].dropna().min()),
        int(utterance_id_session_audit["max_parsed_id"].dropna().max())
    ]
})

display(utterance_id_session_audit.head(10))
display(id_structure_summary)

ID audit 2,500/22,821 files | Rows: 664,944
ID audit 5,000/22,821 files | Rows: 1,336,554
ID audit 7,500/22,821 files | Rows: 2,012,198
ID audit 10,000/22,821 files | Rows: 2,692,417
ID audit 12,500/22,821 files | Rows: 3,364,873
ID audit 15,000/22,821 files | Rows: 4,034,815
ID audit 17,500/22,821 files | Rows: 4,710,356
ID audit 20,000/22,821 files | Rows: 5,377,157
ID audit 22,500/22,821 files | Rows: 6,052,016
ID audit 22,821/22,821 files | Rows: 6,139,854

,session_id,relative_file,row_count,valid_rows,missing_rows,unparseable_rows,duplicate_status_rows,collision_status_rows,duplicate_raw_id_groups,duplicate_raw_id_rows,...,formatting_variant_rows,int32_overflow_rows,parsed_rows,unique_parsed_ids,min_parsed_id,max_parsed_id,id_set_contiguous,id_set_starts_at_zero,raw_preserved,status_domain_valid
0,aaaedit,aaaedit.csv,254,254,0,0,0,0,0,0,...,0,0,254,254,0,253,True,True,True,True
1,aaaptjd,aaaptjd.csv,360,360,0,0,0,0,0,0,...,0,0,360,360,0,359,True,True,True,True
2,aabkeov,aabkeov.csv,281,281,0,0,0,0,0,0,...,0,0,281,281,0,280,True,True,True,True
3,aacggvb,aacggvb.csv,235,235,0,0,0,0,0,0,...,0,0,235,235,0,234,True,True,True,True
4,aadexbc,aadexbc.csv,104,104,0,0,0,0,0,0,...,0,0,104,104,0,103,True,True,True,True
5,aadinwu,aadinwu.csv,233,233,0,0,0,0,0,0,...,0,0,233,233,0,232,True,True,True,True
6,aadljmq,aadljmq.csv,372,372,0,0,0,0,0,0,...,0,0,372,372,0,371,True,True,True,True
7,aadmino,aadmino.csv,195,195,0,0,0,0,0,0,...,0,0,195,195,0,194,True,True,True,True
8,aadsgow,aadsgow.csv,265,265,0,0,0,0,0,0,...,0,0,265,265,0,264,True,True,True,True
9,aadylxv,aadylxv.csv,235,235,0,0,0,0,0,0,...,0,0,235,235,0,234,True,True,True,True

                                      item  value
0                         Sessions audited  22821
1  Sessions with contiguous parsed ID sets  22821
2                Sessions starting at zero  22821
3           Sessions with leading-zero IDs      0
4     Sessions with natural-key collisions      0
5          Sessions with duplicate raw IDs      0
6         Sessions with non-contiguous IDs      0
7                        Minimum parsed ID      0
8                        Maximum parsed ID    621

In [30]:
total_rows = int(id_corpus["row_count"])
missing_rows = int(id_corpus["missing_rows"]); unparseable_rows = int(id_corpus["unparseable_rows"])
overflow_rows = int(id_corpus["int32_overflow_rows"]); duplicate_rows = int(id_corpus["duplicate_raw_id_rows"])
collision_rows = int(id_corpus["natural_key_collision_rows"]); collision_groups = int(id_corpus["natural_key_collision_groups"])
raw_preservation_failures = int((~utterance_id_session_audit["raw_preserved"]).sum())
status_domain_failures = int((~utterance_id_session_audit["status_domain_valid"]).sum())
duplicate_reference_rows = int(recoverable_summary["duplicate_id_rows"])
synthetic_failures = int((~utterance_id_tests["passed"]).sum())

utterance_id_checks = pd.DataFrame([
    check_row("All transcript sessions were ID-audited", len(utterance_id_session_audit) == len(TRANSCRIPT_FILES), f"{len(utterance_id_session_audit)} / {len(TRANSCRIPT_FILES)}"),
    check_row("ID row census matches raw corpus", total_rows == TOTAL_RAW_ROWS, f"{total_rows} / {TOTAL_RAW_ROWS}"),
    check_row("Every current corpus ID is parsed", int(id_corpus["parsed_rows"]) == TOTAL_RAW_ROWS, f"{id_corpus['parsed_rows']} / {TOTAL_RAW_ROWS}"),
    check_row("No current corpus ID is missing", missing_rows == 0, missing_rows),
    check_row("No current corpus ID is unparseable", unparseable_rows == 0, unparseable_rows),
    check_row("No parsed ID exceeds int32", overflow_rows == 0, overflow_rows),
    check_row("Duplicate-ID census agrees with structural audit", duplicate_rows == duplicate_reference_rows, f"ID_parser={duplicate_rows}, structural={duplicate_reference_rows}"),
    check_row("Raw utterance IDs remain unchanged", raw_preservation_failures == 0, raw_preservation_failures),
    check_row("All produced statuses belong to frozen domain", status_domain_failures == 0, status_domain_failures),
    check_row("Utterance-ID parser is deterministic", id_parser_deterministic, id_parser_deterministic),
    check_row("All synthetic ID tests passed", synthetic_failures == 0, synthetic_failures)
])

id_gate_failures = utterance_id_checks[~utterance_id_checks["passed"]]
UTTERANCE_ID_COLLISION_REVIEW_REQUIRED = collision_groups > 0
UTTERANCE_ID_PARSER_READY = id_gate_failures.empty

utterance_id_corpus_summary = pd.DataFrame({
    "item": [
        "ID parser version", "Corpus rows", "Parsed rows", "VALID status rows", "MISSING rows", "UNPARSEABLE rows",
        "Duplicate-status rows", "Collision-status rows", "Duplicate raw-ID groups", "Duplicate raw-ID rows",
        "Natural-key collision groups", "Natural-key collision rows", "Leading-zero rows", "Formatting-variant rows",
        "Int32 overflow rows", "Contiguous-ID sessions", "Start-at-zero sessions", "Non-contiguous-ID sessions",
        "Synthetic tests", "Passed synthetic tests", "Collision review required",
        "UTTERANCE_ID_PARSER_CONFIG_SHA256", "UTTERANCE_ID_PARSER_READY"
    ],
    "value": [
        UTTERANCE_ID_PARSER_VERSION, total_rows, int(id_corpus["parsed_rows"]), int(id_corpus["valid_rows"]),
        missing_rows, unparseable_rows, int(id_corpus["duplicate_status_rows"]), int(id_corpus["collision_status_rows"]),
        int(id_corpus["duplicate_raw_id_groups"]), duplicate_rows, collision_groups, collision_rows,
        int(id_corpus["leading_zero_rows"]), int(id_corpus["formatting_variant_rows"]), overflow_rows,
        int(utterance_id_session_audit["id_set_contiguous"].sum()), int(utterance_id_session_audit["id_set_starts_at_zero"].sum()),
        int((~utterance_id_session_audit["id_set_contiguous"]).sum()), len(utterance_id_tests),
        int(utterance_id_tests["passed"].sum()), UTTERANCE_ID_COLLISION_REVIEW_REQUIRED,
        UTTERANCE_ID_PARSER_CONFIG_SHA256, UTTERANCE_ID_PARSER_READY
    ]
})

display(utterance_id_checks)
display(utterance_id_corpus_summary)

assert UTTERANCE_ID_PARSER_READY, (
    "Section 2.8 failed.\n\n" + id_gate_failures[["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 64)
print("TRACE THE ACE — UTTERANCE-ID PARSER READY")
print("=" * 64)
print(f"Corpus rows       : {total_rows:,}")
print(f"Parsed rows       : {int(id_corpus['parsed_rows']):,}")
print(f"Missing IDs       : {missing_rows:,}")
print(f"Unparseable IDs   : {unparseable_rows:,}")
print(f"Duplicate groups  : {int(id_corpus['duplicate_raw_id_groups']):,}")
print(f"Collision groups  : {collision_groups:,}")
print(f"Leading-zero rows : {int(id_corpus['leading_zero_rows']):,}")
print(f"Contiguous sessions: {int(utterance_id_session_audit['id_set_contiguous'].sum()):,}/{len(utterance_id_session_audit):,}")
print(f"Collision review  : {UTTERANCE_ID_COLLISION_REVIEW_REQUIRED}")
print(f"ID PARSER READY   : {UTTERANCE_ID_PARSER_READY}")
print("=" * 64)

,check,passed,detail
0,All transcript sessions were ID-audited,True,22821 / 22821
1,ID row census matches raw corpus,True,6139854 / 6139854
2,Every current corpus ID is parsed,True,6139854 / 6139854
3,No current corpus ID is missing,True,0
4,No current corpus ID is unparseable,True,0
5,No parsed ID exceeds int32,True,0
6,Duplicate-ID census agrees with structural audit,True,"ID_parser=0, structural=0"
7,Raw utterance IDs remain unchanged,True,0
8,All produced statuses belong to frozen domain,True,0
9,Utterance-ID parser is deterministic,True,True
10,All synthetic ID tests passed,True,0

,item,value
0,ID parser version,1.0
1,Corpus rows,6139854
2,Parsed rows,6139854
3,VALID status rows,6139854
4,MISSING rows,0
5,UNPARSEABLE rows,0
6,Duplicate-status rows,0
7,Collision-status rows,0
8,Duplicate raw-ID groups,0
9,Duplicate raw-ID rows,0
10,Natural-key collision groups,0
11,Natural-key collision rows,0
12,Leading-zero rows,0
13,Formatting-variant rows,0
14,Int32 overflow rows,0
15,Contiguous-ID sessions,22821
16,Start-at-zero sessions,22821
17,Non-contiguous-ID sessions,0
18,Synthetic tests,13
19,Passed synthetic tests,13
20,Collision review required,False
21,UTTERANCE_ID_PARSER_CONFIG_SHA256,e9760b9ee2fa8a21e5e75b45d3e6f9901ea3fe0675f396...
22,UTTERANCE_ID_PARSER_READY,True

================================================================
TRACE THE ACE — UTTERANCE-ID PARSER READY
================================================================
Corpus rows       : 6,139,854
Parsed rows       : 6,139,854
Missing IDs       : 0
Unparseable IDs   : 0
Duplicate groups  : 0
Collision groups  : 0
Leading-zero rows : 0
Contiguous sessions: 22,821/22,821
Collision review  : False
ID PARSER READY   : True
================================================================

# Section 2.9 — Timestamp Parser

This section parses raw timestamps while keeping `timestamp_raw` completely unchanged.
The corpus timestamp mode is determined from the exhaustive format discovery.
Current `HH:MM:SS` values are parsed strictly into seconds from midnight.
Hours, minutes, and seconds are range-validated without silent repair or rounding.
Timestamp precision and timezone semantics are recorded explicitly.
Timestamp ties and source-order time regressions are audited per session.
A time regression is only a rollover candidate; no day offset is applied here.
Midnight rollover decisions are deferred until ordering validity is established.
The complete corpus is audited one session at a time without a giant row table.
The section ends with `TIMESTAMP_PARSER_READY`.

In [31]:
from collections import Counter

assert UTTERANCE_ID_PARSER_READY, "Section 2.8 must pass before Section 2.9."

TIMESTAMP_PARSER_VERSION = "1.0"
ROLLOVER_POLICY_VERSION = "1.0"
TIME_HMS_RE = re.compile(r"^([0-9]{2}):([0-9]{2}):([0-9]{2})$")

def detect_timestamp_mode(families):
    active = set(families) - {"MISSING"}
    time_only = {"TIME_HM", "TIME_HMS", "TIME_HMS_FRACTION"}
    naive = {"DATETIME_NAIVE"}; aware = {"DATETIME_TZ"}; supported = time_only | naive | aware
    if active and active <= time_only: return "TIME_ONLY"
    if active and active <= naive: return "FULL_DATETIME_NAIVE"
    if active and active <= aware: return "FULL_DATETIME_TZ_AWARE"
    if active and active <= supported: return "MIXED_SUPPORTED"
    return "UNSUPPORTED"

DISCOVERED_TIMESTAMP_FAMILIES = sorted(timestamp_family_summary["timestamp_family"].astype(str).unique().tolist())
TIMESTAMP_CORPUS_MODE = detect_timestamp_mode(DISCOVERED_TIMESTAMP_FAMILIES)

TIMESTAMP_PARSER_CONFIG = {
    "version": TIMESTAMP_PARSER_VERSION, "rollover_policy_version": ROLLOVER_POLICY_VERSION,
    "corpus_mode": TIMESTAMP_CORPUS_MODE, "current_family": "TIME_HMS", "pattern": TIME_HMS_RE.pattern,
    "boundary_trim_for_parsing": True, "raw_preserved": True, "derived_representation": "seconds_from_midnight",
    "valid_range": [0, 86399], "precision": "SECOND", "timezone_status": "NOT_APPLICABLE",
    "silent_rounding": False, "invent_timezone": False, "rollover_application": "DEFER_TO_ORDERING_VALIDATION"
}
TIMESTAMP_PARSER_CONFIG_SHA256 = canonical_json_hash(TIMESTAMP_PARSER_CONFIG)

def parse_timestamp(raw):
    if not isinstance(raw, str): raise TypeError(f"Expected str, got {type(raw).__name__}")
    value = raw.strip(); formatting_variant = raw != value
    if value == "": return {"timestamp": None, "timestamp_status": "MISSING", "timestamp_kind": "MISSING", "timestamp_precision": "UNKNOWN", "timezone_status": "NOT_APPLICABLE", "formatting_variant": formatting_variant, "issue_code": None}
    match = TIME_HMS_RE.fullmatch(value)
    if not match: return {"timestamp": None, "timestamp_status": "UNPARSEABLE", "timestamp_kind": "OTHER", "timestamp_precision": "UNKNOWN", "timezone_status": "NOT_APPLICABLE", "formatting_variant": formatting_variant, "issue_code": "INVALID_TIME_HMS_FORMAT"}
    hour, minute, second = map(int, match.groups())
    if hour > 23: return {"timestamp": None, "timestamp_status": "OUT_OF_RANGE", "timestamp_kind": "TIME_HMS", "timestamp_precision": "SECOND", "timezone_status": "NOT_APPLICABLE", "formatting_variant": formatting_variant, "issue_code": "HOUR_OUT_OF_RANGE"}
    if minute > 59: return {"timestamp": None, "timestamp_status": "OUT_OF_RANGE", "timestamp_kind": "TIME_HMS", "timestamp_precision": "SECOND", "timezone_status": "NOT_APPLICABLE", "formatting_variant": formatting_variant, "issue_code": "MINUTE_OUT_OF_RANGE"}
    if second > 59: return {"timestamp": None, "timestamp_status": "OUT_OF_RANGE", "timestamp_kind": "TIME_HMS", "timestamp_precision": "SECOND", "timezone_status": "NOT_APPLICABLE", "formatting_variant": formatting_variant, "issue_code": "SECOND_OUT_OF_RANGE"}
    return {"timestamp": hour * 3600 + minute * 60 + second, "timestamp_status": "VALID", "timestamp_kind": "TIME_HMS", "timestamp_precision": "SECOND", "timezone_status": "NOT_APPLICABLE", "formatting_variant": formatting_variant, "issue_code": None}

def audit_session_timestamps(raw_timestamps):
    parsed = [parse_timestamp(x) for x in raw_timestamps]; valid = [(i, x["timestamp"]) for i, x in enumerate(parsed) if x["timestamp_status"] == "VALID"]
    counts = Counter(value for _, value in valid); tie_groups = {k: v for k, v in counts.items() if v > 1}; regressions = []
    increase_pairs = equal_pairs = comparable_pairs = 0

    for i in range(1, len(parsed)):
        previous, current = parsed[i - 1], parsed[i]
        if previous["timestamp_status"] != "VALID" or current["timestamp_status"] != "VALID": continue
        comparable_pairs += 1
        if current["timestamp"] < previous["timestamp"]:
            regressions.append({"previous_index": i - 1, "current_index": i, "previous_raw": raw_timestamps[i - 1], "current_raw": raw_timestamps[i], "previous_timestamp": previous["timestamp"], "current_timestamp": current["timestamp"], "backward_jump_seconds": previous["timestamp"] - current["timestamp"]})
        elif current["timestamp"] == previous["timestamp"]: equal_pairs += 1
        else: increase_pairs += 1

    values = [value for _, value in valid]
    summary = {
        "row_count": len(parsed), "valid_rows": sum(x["timestamp_status"] == "VALID" for x in parsed),
        "missing_rows": sum(x["timestamp_status"] == "MISSING" for x in parsed), "unparseable_rows": sum(x["timestamp_status"] == "UNPARSEABLE" for x in parsed),
        "out_of_range_rows": sum(x["timestamp_status"] == "OUT_OF_RANGE" for x in parsed), "formatting_variant_rows": sum(x["formatting_variant"] for x in parsed),
        "second_precision_rows": sum(x["timestamp_precision"] == "SECOND" for x in parsed), "timezone_not_applicable_rows": sum(x["timezone_status"] == "NOT_APPLICABLE" for x in parsed),
        "unique_timestamp_count": len(counts), "timestamp_tie_groups": len(tie_groups), "timestamp_tie_rows": sum(tie_groups.values()),
        "source_comparable_pairs": comparable_pairs, "source_increase_pairs": increase_pairs, "source_equal_pairs": equal_pairs,
        "source_time_regression_count": len(regressions), "rollover_candidate_count": len(regressions), "rollover_review_required": bool(regressions),
        "min_timestamp": min(values) if values else None, "max_timestamp": max(values) if values else None
    }
    return {"rows": parsed, "summary": summary, "regression_events": regressions}

def timestamp_test(name, condition, detail):
    return {"test": name, "passed": bool(condition), "detail": detail}

t0 = parse_timestamp("00:00:00"); tmax = parse_timestamp("23:59:59"); tmid = parse_timestamp("01:02:03")
tmiss = parse_timestamp(""); tspaces = parse_timestamp("   "); th = parse_timestamp("24:00:00"); tm = parse_timestamp("12:60:00"); ts = parse_timestamp("12:00:60")
tformat = parse_timestamp("1:02:03"); tbogus = parse_timestamp("abc"); tspace = parse_timestamp(" 01:02:03 ")
inc = audit_session_timestamps(["00:00:00", "00:00:01", "00:00:05"])
roll = audit_session_timestamps(["23:59:59", "00:00:01"])
ties = audit_session_timestamps(["00:00:05", "00:00:05", "00:00:06"])

timestamp_tests = pd.DataFrame([
    timestamp_test("T01_ZERO", t0["timestamp"] == 0 and t0["timestamp_status"] == "VALID", t0),
    timestamp_test("T02_MAX", tmax["timestamp"] == 86399 and tmax["timestamp_status"] == "VALID", tmax),
    timestamp_test("T03_NORMAL", tmid["timestamp"] == 3723, tmid),
    timestamp_test("T04_MISSING", tmiss["timestamp_status"] == "MISSING", tmiss),
    timestamp_test("T05_WHITESPACE_MISSING", tspaces["timestamp_status"] == "MISSING", tspaces),
    timestamp_test("T06_HOUR_RANGE", th["timestamp_status"] == "OUT_OF_RANGE", th),
    timestamp_test("T07_MINUTE_RANGE", tm["timestamp_status"] == "OUT_OF_RANGE", tm),
    timestamp_test("T08_SECOND_RANGE", ts["timestamp_status"] == "OUT_OF_RANGE", ts),
    timestamp_test("T09_STRICT_FORMAT", tformat["timestamp_status"] == "UNPARSEABLE", tformat),
    timestamp_test("T10_INVALID_TEXT", tbogus["timestamp_status"] == "UNPARSEABLE", tbogus),
    timestamp_test("T11_RAW_PRESERVATION", tspace["timestamp"] == 3723 and tspace["formatting_variant"], tspace),
    timestamp_test("T12_CORPUS_MODE", TIMESTAMP_CORPUS_MODE == "TIME_ONLY", TIMESTAMP_CORPUS_MODE),
    timestamp_test("T13_INCREASING_SEQUENCE", inc["summary"]["source_time_regression_count"] == 0, inc["summary"]),
    timestamp_test("T14_ROLLOVER_CANDIDATE", roll["summary"]["source_time_regression_count"] == 1 and roll["summary"]["rollover_review_required"], roll["summary"]),
    timestamp_test("T15_TIMESTAMP_TIE", ties["summary"]["timestamp_tie_groups"] == 1 and ties["summary"]["timestamp_tie_rows"] == 2, ties["summary"])
])

timestamp_parser_deterministic = audit_session_timestamps(["00:00:00", "23:59:59", "00:00:01"]) == audit_session_timestamps(["00:00:00", "23:59:59", "00:00:01"])

display(timestamp_tests)
assert timestamp_tests["passed"].all(), "Timestamp parser synthetic tests failed."
assert timestamp_parser_deterministic, "Timestamp parser is non-deterministic."

,test,passed,detail
0,T01_ZERO,True,"{'timestamp': 0, 'timestamp_status': 'VALID', ..."
1,T02_MAX,True,"{'timestamp': 86399, 'timestamp_status': 'VALI..."
2,T03_NORMAL,True,"{'timestamp': 3723, 'timestamp_status': 'VALID..."
3,T04_MISSING,True,"{'timestamp': None, 'timestamp_status': 'MISSI..."
4,T05_WHITESPACE_MISSING,True,"{'timestamp': None, 'timestamp_status': 'MISSI..."
5,T06_HOUR_RANGE,True,"{'timestamp': None, 'timestamp_status': 'OUT_O..."
6,T07_MINUTE_RANGE,True,"{'timestamp': None, 'timestamp_status': 'OUT_O..."
7,T08_SECOND_RANGE,True,"{'timestamp': None, 'timestamp_status': 'OUT_O..."
8,T09_STRICT_FORMAT,True,"{'timestamp': None, 'timestamp_status': 'UNPAR..."
9,T10_INVALID_TEXT,True,"{'timestamp': None, 'timestamp_status': 'UNPAR..."
10,T11_RAW_PRESERVATION,True,"{'timestamp': 3723, 'timestamp_status': 'VALID..."
11,T12_CORPUS_MODE,True,TIME_ONLY
12,T13_INCREASING_SEQUENCE,True,"{'row_count': 3, 'valid_rows': 3, 'missing_row..."
13,T14_ROLLOVER_CANDIDATE,True,"{'row_count': 2, 'valid_rows': 2, 'missing_row..."
14,T15_TIMESTAMP_TIE,True,"{'row_count': 3, 'valid_rows': 3, 'missing_row..."

In [32]:
TIMESTAMP_REGRESSION_SAMPLE_LIMIT = 20
timestamp_session_rows = []; timestamp_regression_samples = []; timestamp_corpus = Counter()

allowed_timestamp_status = set(STATUS_VOCABULARIES["timestamp_status"])
allowed_timestamp_kind = set(STATUS_VOCABULARIES["timestamp_kind"])
allowed_timestamp_precision = set(STATUS_VOCABULARIES["timestamp_precision"])
allowed_timezone_status = set(STATUS_VOCABULARIES["timezone_status"])

for file_number, path in enumerate(TRANSCRIPT_FILES, 1):
    relative_file = path.relative_to(TRANSCRIPT_ROOT).as_posix(); session_id = Path(relative_file).stem
    reconstructed = reconstruct_raw_file(path, expected_session_id=session_id)
    raw_timestamps = reconstructed["raw_table"].column("timestamp_raw").to_pylist(); raw_copy = list(raw_timestamps)
    audited = audit_session_timestamps(raw_timestamps); rows, summary = audited["rows"], audited["summary"]

    timestamp_session_rows.append({
        "session_id": session_id, "relative_file": relative_file, **summary, "raw_preserved": raw_timestamps == raw_copy,
        "status_domain_valid": all(x["timestamp_status"] in allowed_timestamp_status for x in rows),
        "kind_domain_valid": all(x["timestamp_kind"] in allowed_timestamp_kind for x in rows),
        "precision_domain_valid": all(x["timestamp_precision"] in allowed_timestamp_precision for x in rows),
        "timezone_domain_valid": all(x["timezone_status"] in allowed_timezone_status for x in rows)
    })

    for key in [
        "row_count", "valid_rows", "missing_rows", "unparseable_rows", "out_of_range_rows", "formatting_variant_rows",
        "second_precision_rows", "timezone_not_applicable_rows", "timestamp_tie_groups", "timestamp_tie_rows",
        "source_comparable_pairs", "source_increase_pairs", "source_equal_pairs", "source_time_regression_count", "rollover_candidate_count"
    ]: timestamp_corpus[key] += int(summary[key])

    for event in audited["regression_events"]:
        if len(timestamp_regression_samples) >= TIMESTAMP_REGRESSION_SAMPLE_LIMIT: break
        timestamp_regression_samples.append({"session_id": session_id, "relative_file": relative_file, **event})

    if file_number % 2500 == 0 or file_number == len(TRANSCRIPT_FILES):
        print(f"Timestamp audit {file_number:,}/{len(TRANSCRIPT_FILES):,} files | Rows: {timestamp_corpus['row_count']:,}")

timestamp_session_audit = pd.DataFrame(timestamp_session_rows)
timestamp_regression_sample = pd.DataFrame(timestamp_regression_samples)

sessions_with_ties = int(timestamp_session_audit["timestamp_tie_groups"].gt(0).sum())
sessions_with_regressions = int(timestamp_session_audit["source_time_regression_count"].gt(0).sum())
global_min_timestamp = int(timestamp_session_audit["min_timestamp"].dropna().min())
global_max_timestamp = int(timestamp_session_audit["max_timestamp"].dropna().max())

timestamp_structure_summary = pd.DataFrame({
    "item": [
        "Sessions audited", "Sessions with timestamp ties", "Timestamp tie groups", "Timestamp tie rows",
        "Sessions with source-time regressions", "Source-time regressions", "Rollover candidates",
        "Minimum timestamp seconds", "Maximum timestamp seconds"
    ],
    "value": [
        len(timestamp_session_audit), sessions_with_ties, int(timestamp_corpus["timestamp_tie_groups"]),
        int(timestamp_corpus["timestamp_tie_rows"]), sessions_with_regressions,
        int(timestamp_corpus["source_time_regression_count"]), int(timestamp_corpus["rollover_candidate_count"]),
        global_min_timestamp, global_max_timestamp
    ]
})

display(timestamp_session_audit.head(10))
display(timestamp_structure_summary)
display(timestamp_regression_sample)

Timestamp audit 2,500/22,821 files | Rows: 664,944
Timestamp audit 5,000/22,821 files | Rows: 1,336,554
Timestamp audit 7,500/22,821 files | Rows: 2,012,198
Timestamp audit 10,000/22,821 files | Rows: 2,692,417
Timestamp audit 12,500/22,821 files | Rows: 3,364,873
Timestamp audit 15,000/22,821 files | Rows: 4,034,815
Timestamp audit 17,500/22,821 files | Rows: 4,710,356
Timestamp audit 20,000/22,821 files | Rows: 5,377,157
Timestamp audit 22,500/22,821 files | Rows: 6,052,016
Timestamp audit 22,821/22,821 files | Rows: 6,139,854

,session_id,relative_file,row_count,valid_rows,missing_rows,unparseable_rows,out_of_range_rows,formatting_variant_rows,second_precision_rows,timezone_not_applicable_rows,...,source_time_regression_count,rollover_candidate_count,rollover_review_required,min_timestamp,max_timestamp,raw_preserved,status_domain_valid,kind_domain_valid,precision_domain_valid,timezone_domain_valid
0,aaaedit,aaaedit.csv,254,254,0,0,0,0,254,254,...,0,0,False,0,2629,True,True,True,True,True
1,aaaptjd,aaaptjd.csv,360,360,0,0,0,0,360,360,...,0,0,False,0,2730,True,True,True,True,True
2,aabkeov,aabkeov.csv,281,281,0,0,0,0,281,281,...,0,0,False,0,2208,True,True,True,True,True
3,aacggvb,aacggvb.csv,235,235,0,0,0,0,235,235,...,0,0,False,0,2776,True,True,True,True,True
4,aadexbc,aadexbc.csv,104,104,0,0,0,0,104,104,...,0,0,False,0,2642,True,True,True,True,True
5,aadinwu,aadinwu.csv,233,233,0,0,0,0,233,233,...,0,0,False,0,2361,True,True,True,True,True
6,aadljmq,aadljmq.csv,372,372,0,0,0,0,372,372,...,0,0,False,0,2732,True,True,True,True,True
7,aadmino,aadmino.csv,195,195,0,0,0,0,195,195,...,0,0,False,0,1807,True,True,True,True,True
8,aadsgow,aadsgow.csv,265,265,0,0,0,0,265,265,...,0,0,False,0,2383,True,True,True,True,True
9,aadylxv,aadylxv.csv,235,235,0,0,0,0,235,235,...,0,0,False,0,2100,True,True,True,True,True

                                    item   value
0                       Sessions audited   22821
1           Sessions with timestamp ties   22795
2                   Timestamp tie groups  325210
3                     Timestamp tie rows  717014
4  Sessions with source-time regressions       0
5                Source-time regressions       0
6                    Rollover candidates       0
7              Minimum timestamp seconds       0
8              Maximum timestamp seconds    3721

Empty DataFrame
Columns: []
Index: []

In [33]:
total_timestamp_rows = int(timestamp_corpus["row_count"])
valid_timestamp_rows = int(timestamp_corpus["valid_rows"])
missing_timestamp_rows = int(timestamp_corpus["missing_rows"])
unparseable_timestamp_rows = int(timestamp_corpus["unparseable_rows"])
out_of_range_rows = int(timestamp_corpus["out_of_range_rows"])
formatting_variant_rows = int(timestamp_corpus["formatting_variant_rows"])

raw_preservation_failures = int((~timestamp_session_audit["raw_preserved"]).sum())
status_domain_failures = int((~timestamp_session_audit["status_domain_valid"]).sum())
kind_domain_failures = int((~timestamp_session_audit["kind_domain_valid"]).sum())
precision_domain_failures = int((~timestamp_session_audit["precision_domain_valid"]).sum())
timezone_domain_failures = int((~timestamp_session_audit["timezone_domain_valid"]).sum())
synthetic_failures = int((~timestamp_tests["passed"]).sum())
structural_missing_reference = int(recoverable_summary["missing_timestamps"])

timestamp_checks = pd.DataFrame([
    check_row("Corpus timestamp mode is TIME_ONLY", TIMESTAMP_CORPUS_MODE == "TIME_ONLY", TIMESTAMP_CORPUS_MODE),
    check_row("Discovery family is exclusively TIME_HMS", DISCOVERED_TIMESTAMP_FAMILIES == ["TIME_HMS"], DISCOVERED_TIMESTAMP_FAMILIES),
    check_row("All transcript sessions were timestamp-audited", len(timestamp_session_audit) == len(TRANSCRIPT_FILES), f"{len(timestamp_session_audit)} / {len(TRANSCRIPT_FILES)}"),
    check_row("Timestamp row census matches raw corpus", total_timestamp_rows == TOTAL_RAW_ROWS, f"{total_timestamp_rows} / {TOTAL_RAW_ROWS}"),
    check_row("Every current timestamp is semantically valid", valid_timestamp_rows == TOTAL_RAW_ROWS, f"{valid_timestamp_rows} / {TOTAL_RAW_ROWS}"),
    check_row("Missing timestamp census agrees with structural audit", missing_timestamp_rows == structural_missing_reference, f"timestamp={missing_timestamp_rows}, structural={structural_missing_reference}"),
    check_row("No current timestamp is unparseable", unparseable_timestamp_rows == 0, unparseable_timestamp_rows),
    check_row("No current timestamp is out of range", out_of_range_rows == 0, out_of_range_rows),
    check_row("Parsed timestamp range is valid", 0 <= global_min_timestamp <= global_max_timestamp <= 86399, f"{global_min_timestamp}..{global_max_timestamp}"),
    check_row("All current timestamps preserve SECOND precision", int(timestamp_corpus["second_precision_rows"]) == TOTAL_RAW_ROWS, f"{timestamp_corpus['second_precision_rows']} / {TOTAL_RAW_ROWS}"),
    check_row("Timezone remains NOT_APPLICABLE", int(timestamp_corpus["timezone_not_applicable_rows"]) == TOTAL_RAW_ROWS, f"{timestamp_corpus['timezone_not_applicable_rows']} / {TOTAL_RAW_ROWS}"),
    check_row("Raw timestamp values remain unchanged", raw_preservation_failures == 0, raw_preservation_failures),
    check_row("All timestamp statuses belong to frozen domain", status_domain_failures == 0, status_domain_failures),
    check_row("All timestamp kinds belong to frozen domain", kind_domain_failures == 0, kind_domain_failures),
    check_row("All precision values belong to frozen domain", precision_domain_failures == 0, precision_domain_failures),
    check_row("All timezone values belong to frozen domain", timezone_domain_failures == 0, timezone_domain_failures),
    check_row("Timestamp parser is deterministic", timestamp_parser_deterministic, timestamp_parser_deterministic),
    check_row("All timestamp synthetic tests passed", synthetic_failures == 0, synthetic_failures)
])

timestamp_gate_failures = timestamp_checks[~timestamp_checks["passed"]]
TIMESTAMP_ROLLOVER_REVIEW_REQUIRED = sessions_with_regressions > 0
TIMESTAMP_PARSER_READY = timestamp_gate_failures.empty

timestamp_corpus_summary = pd.DataFrame({
    "item": [
        "Timestamp parser version", "Rollover policy version", "Corpus mode", "Precision", "Timezone status",
        "Corpus rows", "VALID rows", "MISSING rows", "UNPARSEABLE rows", "OUT_OF_RANGE rows", "Formatting-variant rows",
        "Timestamp tie groups", "Timestamp tie rows", "Sessions with ties", "Source-time regressions",
        "Sessions with regressions", "Rollover candidates", "Rollover review required",
        "Minimum timestamp", "Maximum timestamp", "Synthetic tests", "Passed synthetic tests",
        "TIMESTAMP_PARSER_CONFIG_SHA256", "TIMESTAMP_PARSER_READY"
    ],
    "value": [
        TIMESTAMP_PARSER_VERSION, ROLLOVER_POLICY_VERSION, TIMESTAMP_CORPUS_MODE, "SECOND", "NOT_APPLICABLE",
        total_timestamp_rows, valid_timestamp_rows, missing_timestamp_rows, unparseable_timestamp_rows, out_of_range_rows,
        formatting_variant_rows, int(timestamp_corpus["timestamp_tie_groups"]), int(timestamp_corpus["timestamp_tie_rows"]),
        sessions_with_ties, int(timestamp_corpus["source_time_regression_count"]), sessions_with_regressions,
        int(timestamp_corpus["rollover_candidate_count"]), TIMESTAMP_ROLLOVER_REVIEW_REQUIRED,
        global_min_timestamp, global_max_timestamp, len(timestamp_tests), int(timestamp_tests["passed"].sum()),
        TIMESTAMP_PARSER_CONFIG_SHA256, TIMESTAMP_PARSER_READY
    ]
})

display(timestamp_checks)
display(timestamp_corpus_summary)

assert TIMESTAMP_PARSER_READY, (
    "Section 2.9 failed.\n\n" + timestamp_gate_failures[["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 64)
print("TRACE THE ACE — TIMESTAMP PARSER READY")
print("=" * 64)
print(f"Corpus mode       : {TIMESTAMP_CORPUS_MODE}")
print(f"Corpus rows       : {total_timestamp_rows:,}")
print(f"VALID rows        : {valid_timestamp_rows:,}")
print(f"Missing           : {missing_timestamp_rows:,}")
print(f"Unparseable       : {unparseable_timestamp_rows:,}")
print(f"Out of range      : {out_of_range_rows:,}")
print(f"Tie groups        : {int(timestamp_corpus['timestamp_tie_groups']):,}")
print(f"Time regressions  : {int(timestamp_corpus['source_time_regression_count']):,}")
print(f"Rollover review   : {TIMESTAMP_ROLLOVER_REVIEW_REQUIRED}")
print(f"TIMESTAMP READY   : {TIMESTAMP_PARSER_READY}")
print("=" * 64)

,check,passed,detail
0,Corpus timestamp mode is TIME_ONLY,True,TIME_ONLY
1,Discovery family is exclusively TIME_HMS,True,[TIME_HMS]
2,All transcript sessions were timestamp-audited,True,22821 / 22821
3,Timestamp row census matches raw corpus,True,6139854 / 6139854
4,Every current timestamp is semantically valid,True,6139854 / 6139854
5,Missing timestamp census agrees with structura...,True,"timestamp=0, structural=0"
6,No current timestamp is unparseable,True,0
7,No current timestamp is out of range,True,0
8,Parsed timestamp range is valid,True,0..3721
9,All current timestamps preserve SECOND precision,True,6139854 / 6139854
10,Timezone remains NOT_APPLICABLE,True,6139854 / 6139854
11,Raw timestamp values remain unchanged,True,0
12,All timestamp statuses belong to frozen domain,True,0
13,All timestamp kinds belong to frozen domain,True,0
14,All precision values belong to frozen domain,True,0
15,All timezone values belong to frozen domain,True,0
16,Timestamp parser is deterministic,True,True
17,All timestamp synthetic tests passed,True,0

,item,value
0,Timestamp parser version,1.0
1,Rollover policy version,1.0
2,Corpus mode,TIME_ONLY
3,Precision,SECOND
4,Timezone status,NOT_APPLICABLE
5,Corpus rows,6139854
6,VALID rows,6139854
7,MISSING rows,0
8,UNPARSEABLE rows,0
9,OUT_OF_RANGE rows,0
10,Formatting-variant rows,0
11,Timestamp tie groups,325210
12,Timestamp tie rows,717014
13,Sessions with ties,22795
14,Source-time regressions,0
15,Sessions with regressions,0
16,Rollover candidates,0
17,Rollover review required,False
18,Minimum timestamp,0
19,Maximum timestamp,3721
20,Synthetic tests,15
21,Passed synthetic tests,15
22,TIMESTAMP_PARSER_CONFIG_SHA256,e1833c23f225ce7f5a2308cce68d62c3aa620e4f4a5ea9...
23,TIMESTAMP_PARSER_READY,True

================================================================
TRACE THE ACE — TIMESTAMP PARSER READY
================================================================
Corpus mode       : TIME_ONLY
Corpus rows       : 6,139,854
VALID rows        : 6,139,854
Missing           : 0
Unparseable       : 0
Out of range      : 0
Tie groups        : 325,210
Time regressions  : 0
Rollover review   : False
TIMESTAMP READY   : True
================================================================

# Section 2.10 — Ordering Validity Calibration

This section determines whether source order, utterance-ID order, and timestamp evidence support the same conversation chronology.
Timestamp ties are treated as unresolved within-second order, not as timestamp failures.
Strict timestamp inequalities are used as temporal reference evidence while equal timestamps are excluded from temporal comparisons.
Source-to-ID agreement, ID-to-time agreement, source-to-time agreement, and within-tie ID agreement are measured independently.
A hypothetical `timestamp → utterance_id → source_row_index` order is tested but is not yet published as final turn order.
Pairwise disagreements are counted efficiently through inversion counting rather than materializing all turn pairs.
Timestamp-start behavior is also audited to evaluate the session-relative-clock hypothesis.
Fallback eligibility is calibrated from observed evidence rather than assumed from identifier formatting.
No raw fields, day offsets, or final `turn_index` values are changed here.
The section ends with `ORDERING_VALIDITY_CALIBRATED`.

In [34]:
assert UTTERANCE_ID_PARSER_READY and TIMESTAMP_PARSER_READY, "Sections 2.8 and 2.9 must pass before Section 2.10."

ORDERING_CALIBRATION_VERSION = "1.0"
ORDERING_REVIEW_THRESHOLD = 0.995

ORDERING_CALIBRATION_CONFIG = {
    "version": ORDERING_CALIBRATION_VERSION, "reference_signals": ["source_row_index", "utterance_id", "timestamp"],
    "timestamp_ties": "UNRESOLVED_NOT_CONFLICT", "candidate_order": ["timestamp", "utterance_id", "source_row_index"],
    "pairwise_method": "MERGE_SORT_INVERSION_COUNT", "final_order_applied": False,
    "rollover_application": False, "review_threshold": ORDERING_REVIEW_THRESHOLD
}
ORDERING_CALIBRATION_CONFIG_SHA256 = canonical_json_hash(ORDERING_CALIBRATION_CONFIG)

def count_inversions(values):
    def merge_count(seq):
        if len(seq) <= 1: return seq, 0
        mid = len(seq) // 2; left, a = merge_count(seq[:mid]); right, b = merge_count(seq[mid:])
        merged = []; i = j = 0; inv = a + b
        while i < len(left) and j < len(right):
            if left[i] <= right[j]: merged.append(left[i]); i += 1
            else: merged.append(right[j]); inv += len(left) - i; j += 1
        merged.extend(left[i:]); merged.extend(right[j:])
        return merged, inv
    return merge_count(list(values))[1]

def temporal_pair_stats(values):
    n = len(values); counts = Counter(values)
    total_pairs = n * (n - 1) // 2; tied_pairs = sum(c * (c - 1) // 2 for c in counts.values())
    comparable_pairs = total_pairs - tied_pairs; inversions = count_inversions(values)
    agreement = 1.0 if comparable_pairs == 0 else 1.0 - inversions / comparable_pairs
    return {"comparable_pairs": comparable_pairs, "tied_pairs": tied_pairs, "inversions": inversions, "agreement": agreement}

def analyze_ordering_vectors(source_indices, utterance_ids, timestamps):
    n = len(source_indices)
    if not (len(utterance_ids) == n == len(timestamps)): raise ValueError("Ordering vectors must have equal length.")
    if any(x is None for x in utterance_ids) or any(x is None for x in timestamps): raise ValueError("Section 2.10 requires parsed ID and timestamp values.")

    source_order = list(source_indices)
    id_order = sorted(range(n), key=lambda i: (utterance_ids[i], source_indices[i]))
    candidate_order = sorted(range(n), key=lambda i: (timestamps[i], utterance_ids[i], source_indices[i]))

    id_source_sequence = [source_indices[i] for i in id_order]
    candidate_source_sequence = [source_indices[i] for i in candidate_order]
    total_pairs = n * (n - 1) // 2

    id_source_inversions = count_inversions(id_source_sequence)
    candidate_source_inversions = count_inversions(candidate_source_sequence)
    id_source_agreement = 1.0 if total_pairs == 0 else 1.0 - id_source_inversions / total_pairs
    candidate_source_agreement = 1.0 if total_pairs == 0 else 1.0 - candidate_source_inversions / total_pairs

    source_time = temporal_pair_stats(timestamps)
    id_time = temporal_pair_stats([timestamps[i] for i in id_order])

    timestamp_groups = {}
    for i, value in enumerate(timestamps): timestamp_groups.setdefault(value, []).append(i)

    tie_groups = [idx for idx in timestamp_groups.values() if len(idx) > 1]
    tie_pairs = tie_inversions = tie_rows = exact_tie_groups = 0
    for group in tie_groups:
        ordered = sorted(group, key=lambda i: (utterance_ids[i], source_indices[i]))
        sequence = [source_indices[i] for i in ordered]; group_pairs = len(group) * (len(group) - 1) // 2
        inv = count_inversions(sequence); tie_pairs += group_pairs; tie_inversions += inv; tie_rows += len(group)
        exact_tie_groups += sequence == sorted(sequence)

    tie_agreement = 1.0 if tie_pairs == 0 else 1.0 - tie_inversions / tie_pairs
    unique_times = len(timestamp_groups)
    if n <= 1: reference_class = "SINGLE_TURN"
    elif unique_times == 1: reference_class = "ALL_TIMESTAMP_TIED"
    elif unique_times == n: reference_class = "TIE_FREE_FULL_REFERENCE"
    else: reference_class = "PARTIAL_TEMPORAL_REFERENCE"

    return {
        "n_turns": n, "source_index_contiguous": source_order == list(range(n)),
        "source_id_exact_match": id_source_sequence == source_order, "id_source_inversions": id_source_inversions,
        "id_source_pair_count": total_pairs, "id_source_agreement": id_source_agreement,
        "source_timestamp_inversions": source_time["inversions"], "source_timestamp_comparable_pairs": source_time["comparable_pairs"],
        "source_timestamp_agreement": source_time["agreement"], "id_timestamp_inversions": id_time["inversions"],
        "id_timestamp_comparable_pairs": id_time["comparable_pairs"], "id_timestamp_agreement": id_time["agreement"],
        "timestamp_block_count": unique_times, "timestamp_tie_group_count": len(tie_groups), "timestamp_tie_rows": tie_rows,
        "max_tie_group_size": max([len(x) for x in tie_groups], default=1), "within_tie_pair_count": tie_pairs,
        "within_tie_source_id_inversions": tie_inversions, "within_tie_source_id_agreement": tie_agreement,
        "tie_groups_source_id_exact": exact_tie_groups, "candidate_timestamp_id_matches_source": candidate_source_sequence == source_order,
        "candidate_source_inversions": candidate_source_inversions, "candidate_source_agreement": candidate_source_agreement,
        "timestamp_reference_class": reference_class, "min_timestamp": min(timestamps) if timestamps else None,
        "max_timestamp": max(timestamps) if timestamps else None, "starts_at_zero": bool(timestamps) and min(timestamps) == 0,
        "first_source_timestamp_zero": bool(timestamps) and timestamps[0] == 0
    }

def calibration_test(name, condition, detail):
    return {"test": name, "passed": bool(condition), "detail": detail}

c01 = analyze_ordering_vectors([0,1,2], [0,1,2], [0,1,2])
c02 = analyze_ordering_vectors([0,1,2], [0,1,2], [0,0,1])
c03 = analyze_ordering_vectors([0,1,2], [0,2,1], [0,0,0])
c04 = analyze_ordering_vectors([0,1,2], [0,2,1], [0,1,2])
c05 = analyze_ordering_vectors([0,1,2], [0,1,2], [0,2,1])
c06 = analyze_ordering_vectors([0,1,2], [2,1,0], [0,0,0])
c07 = analyze_ordering_vectors([0,1,2], [0,1,2], [5,5,5])
c08 = analyze_ordering_vectors([0], [0], [0])
c09 = analyze_ordering_vectors([0,1,2,3,4], [0,1,2,3,4], [0,0,1,2,2])
c10 = analyze_ordering_vectors([0,1,2,3,4], [0,1,3,2,4], [0,0,0,0,0])
c11 = analyze_ordering_vectors([0,1], [0,1], [86399,1])
c12a = analyze_ordering_vectors([0,1,2,3], [0,1,2,3], [0,0,1,1])
c12b = analyze_ordering_vectors([0,1,2,3], [0,1,2,3], [0,0,1,1])

ordering_calibration_tests = pd.DataFrame([
    calibration_test("C01_FULL_AGREEMENT", c01["source_id_exact_match"] and c01["source_timestamp_inversions"] == 0 and c01["id_timestamp_inversions"] == 0, c01),
    calibration_test("C02_TIMESTAMP_TIE_OK", c02["timestamp_tie_group_count"] == 1 and c02["within_tie_source_id_inversions"] == 0, c02),
    calibration_test("C03_TIE_ID_CONFLICT", c03["within_tie_source_id_inversions"] == 1 and not c03["source_id_exact_match"], c03),
    calibration_test("C04_ID_TIME_CONFLICT", c04["id_timestamp_inversions"] == 1, c04),
    calibration_test("C05_SOURCE_TIME_CONFLICT", c05["source_timestamp_inversions"] == 1, c05),
    calibration_test("C06_REVERSED_IDS", c06["id_source_inversions"] == 3, c06),
    calibration_test("C07_ALL_TIMES_TIED", c07["timestamp_reference_class"] == "ALL_TIMESTAMP_TIED", c07),
    calibration_test("C08_SINGLE_TURN", c08["timestamp_reference_class"] == "SINGLE_TURN" and c08["id_source_agreement"] == 1.0, c08),
    calibration_test("C09_MULTIPLE_TIE_BLOCKS", c09["timestamp_tie_group_count"] == 2 and c09["source_timestamp_inversions"] == 0, c09),
    calibration_test("C10_LOCAL_ID_INVERSION", c10["id_source_inversions"] == 1, c10),
    calibration_test("C11_ROLLOVER_CONFLICT", c11["source_timestamp_inversions"] == 1, c11),
    calibration_test("C12_DETERMINISTIC", c12a == c12b and c12a["candidate_timestamp_id_matches_source"], c12a)
])

ORDERING_CALIBRATION_DETERMINISTIC = c12a == c12b
display(ordering_calibration_tests)

assert ordering_calibration_tests["passed"].all(), "Ordering calibration synthetic tests failed."
assert ORDERING_CALIBRATION_DETERMINISTIC, "Ordering calibration engine is non-deterministic."

,test,passed,detail
0,C01_FULL_AGREEMENT,True,"{'n_turns': 3, 'source_index_contiguous': True..."
1,C02_TIMESTAMP_TIE_OK,True,"{'n_turns': 3, 'source_index_contiguous': True..."
2,C03_TIE_ID_CONFLICT,True,"{'n_turns': 3, 'source_index_contiguous': True..."
3,C04_ID_TIME_CONFLICT,True,"{'n_turns': 3, 'source_index_contiguous': True..."
4,C05_SOURCE_TIME_CONFLICT,True,"{'n_turns': 3, 'source_index_contiguous': True..."
5,C06_REVERSED_IDS,True,"{'n_turns': 3, 'source_index_contiguous': True..."
6,C07_ALL_TIMES_TIED,True,"{'n_turns': 3, 'source_index_contiguous': True..."
7,C08_SINGLE_TURN,True,"{'n_turns': 1, 'source_index_contiguous': True..."
8,C09_MULTIPLE_TIE_BLOCKS,True,"{'n_turns': 5, 'source_index_contiguous': True..."
9,C10_LOCAL_ID_INVERSION,True,"{'n_turns': 5, 'source_index_contiguous': True..."
10,C11_ROLLOVER_CONFLICT,True,"{'n_turns': 2, 'source_index_contiguous': True..."
11,C12_DETERMINISTIC,True,"{'n_turns': 4, 'source_index_contiguous': True..."

In [35]:
ordering_session_rows = []; ordering_corpus = Counter(); tie_size_counts = Counter()

for file_number, path in enumerate(TRANSCRIPT_FILES, 1):
    relative_file = path.relative_to(TRANSCRIPT_ROOT).as_posix(); session_id = Path(relative_file).stem
    reconstructed = reconstruct_raw_file(path, expected_session_id=session_id); raw_table = reconstructed["raw_table"]

    source_indices = [int(x) for x in raw_table.column("source_row_index").to_pylist()]
    raw_ids = raw_table.column("utterance_id_raw").to_pylist(); raw_timestamps = raw_table.column("timestamp_raw").to_pylist()
    utterance_ids = [parse_utterance_id(x)["utterance_id"] for x in raw_ids]
    timestamps = [parse_timestamp(x)["timestamp"] for x in raw_timestamps]

    result = analyze_ordering_vectors(source_indices, utterance_ids, timestamps)
    ordering_session_rows.append({"session_id": session_id, "relative_file": relative_file, **result})

    for key in [
        "n_turns", "id_source_inversions", "id_source_pair_count", "source_timestamp_inversions",
        "source_timestamp_comparable_pairs", "id_timestamp_inversions", "id_timestamp_comparable_pairs",
        "timestamp_tie_group_count", "timestamp_tie_rows", "within_tie_pair_count",
        "within_tie_source_id_inversions", "tie_groups_source_id_exact", "candidate_source_inversions"
    ]: ordering_corpus[key] += int(result[key])

    for count in Counter(timestamps).values():
        if count > 1: tie_size_counts[int(count)] += 1

    if file_number % 2500 == 0 or file_number == len(TRANSCRIPT_FILES):
        print(f"Ordering calibration {file_number:,}/{len(TRANSCRIPT_FILES):,} files | Rows: {ordering_corpus['n_turns']:,}")

ordering_calibration_session_audit = pd.DataFrame(ordering_session_rows)

def weighted_quantile_from_counts(counts, q):
    if not counts: return None
    total = sum(counts.values()); target = max(1, int((total * q) + 0.999999))
    running = 0
    for value, frequency in sorted(counts.items()):
        running += frequency
        if running >= target: return value

tie_size_distribution = pd.DataFrame(
    [{"tie_group_size": size, "tie_group_count": count} for size, count in sorted(tie_size_counts.items())]
)

tie_size_summary = pd.DataFrame({
    "metric": ["Tie groups", "Median tie size", "P90 tie size", "P95 tie size", "P99 tie size", "Maximum tie size"],
    "value": [
        sum(tie_size_counts.values()), weighted_quantile_from_counts(tie_size_counts, .50),
        weighted_quantile_from_counts(tie_size_counts, .90), weighted_quantile_from_counts(tie_size_counts, .95),
        weighted_quantile_from_counts(tie_size_counts, .99), max(tie_size_counts, default=0)
    ]
})

reference_class_summary = ordering_calibration_session_audit["timestamp_reference_class"].value_counts().rename_axis("timestamp_reference_class").reset_index(name="session_count")

display(ordering_calibration_session_audit.head(10))
display(reference_class_summary)
display(tie_size_summary)
display(tie_size_distribution.head(15))

Ordering calibration 2,500/22,821 files | Rows: 664,944
Ordering calibration 5,000/22,821 files | Rows: 1,336,554
Ordering calibration 7,500/22,821 files | Rows: 2,012,198
Ordering calibration 10,000/22,821 files | Rows: 2,692,417
Ordering calibration 12,500/22,821 files | Rows: 3,364,873
Ordering calibration 15,000/22,821 files | Rows: 4,034,815
Ordering calibration 17,500/22,821 files | Rows: 4,710,356
Ordering calibration 20,000/22,821 files | Rows: 5,377,157
Ordering calibration 22,500/22,821 files | Rows: 6,052,016
Ordering calibration 22,821/22,821 files | Rows: 6,139,854

,session_id,relative_file,n_turns,source_index_contiguous,source_id_exact_match,id_source_inversions,id_source_pair_count,id_source_agreement,source_timestamp_inversions,source_timestamp_comparable_pairs,...,within_tie_source_id_agreement,tie_groups_source_id_exact,candidate_timestamp_id_matches_source,candidate_source_inversions,candidate_source_agreement,timestamp_reference_class,min_timestamp,max_timestamp,starts_at_zero,first_source_timestamp_zero
0,aaaedit,aaaedit.csv,254,True,True,0,32131,1.0,0,32089,...,1.0,24,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2629,True,True
1,aaaptjd,aaaptjd.csv,360,True,True,0,64620,1.0,0,64605,...,1.0,15,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2730,True,True
2,aabkeov,aabkeov.csv,281,True,True,0,39340,1.0,0,39330,...,1.0,10,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2208,True,True
3,aacggvb,aacggvb.csv,235,True,True,0,27495,1.0,0,27455,...,1.0,29,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2776,True,True
4,aadexbc,aadexbc.csv,104,True,True,0,5356,1.0,0,5354,...,1.0,2,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2642,True,True
5,aadinwu,aadinwu.csv,233,True,True,0,27028,1.0,0,27004,...,1.0,18,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2361,True,True
6,aadljmq,aadljmq.csv,372,True,True,0,69006,1.0,0,68984,...,1.0,22,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2732,True,True
7,aadmino,aadmino.csv,195,True,True,0,18915,1.0,0,18909,...,1.0,6,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,1807,True,True
8,aadsgow,aadsgow.csv,265,True,True,0,34980,1.0,0,34940,...,1.0,20,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2383,True,True
9,aadylxv,aadylxv.csv,235,True,True,0,27495,1.0,0,27477,...,1.0,11,True,0,1.0,PARTIAL_TEMPORAL_REFERENCE,0,2100,True,True

    timestamp_reference_class  session_count
0  PARTIAL_TEMPORAL_REFERENCE          22795
1     TIE_FREE_FULL_REFERENCE             26

             metric   value
0        Tie groups  325210
1   Median tie size       2
2      P90 tie size       3
3      P95 tie size       3
4      P99 tie size       5
5  Maximum tie size      74

    tie_group_size  tie_group_count
0                2           281975
1                3            34155
2                4             4490
3                5             2642
4                6              659
5                7              494
6                8              157
7                9              175
8               10               67
9               11               67
10              12               28
11              13               48
12              14               16
13              15               24
14              16               13

In [36]:
n_sessions = len(ordering_calibration_session_audit)
n_rows = int(ordering_corpus["n_turns"])

source_id_exact_sessions = int(ordering_calibration_session_audit["source_id_exact_match"].sum())
candidate_exact_sessions = int(ordering_calibration_session_audit["candidate_timestamp_id_matches_source"].sum())
source_index_failures = int((~ordering_calibration_session_audit["source_index_contiguous"]).sum())

source_id_pairs = int(ordering_corpus["id_source_pair_count"]); source_id_inv = int(ordering_corpus["id_source_inversions"])
source_time_pairs = int(ordering_corpus["source_timestamp_comparable_pairs"]); source_time_inv = int(ordering_corpus["source_timestamp_inversions"])
id_time_pairs = int(ordering_corpus["id_timestamp_comparable_pairs"]); id_time_inv = int(ordering_corpus["id_timestamp_inversions"])
tie_pairs = int(ordering_corpus["within_tie_pair_count"]); tie_inv = int(ordering_corpus["within_tie_source_id_inversions"])
candidate_inv = int(ordering_corpus["candidate_source_inversions"])

source_id_agreement = 1.0 if source_id_pairs == 0 else 1.0 - source_id_inv / source_id_pairs
source_time_agreement = 1.0 if source_time_pairs == 0 else 1.0 - source_time_inv / source_time_pairs
id_time_agreement = 1.0 if id_time_pairs == 0 else 1.0 - id_time_inv / id_time_pairs
within_tie_agreement = 1.0 if tie_pairs == 0 else 1.0 - tie_inv / tie_pairs
candidate_source_agreement = 1.0 if source_id_pairs == 0 else 1.0 - candidate_inv / source_id_pairs

sessions_min_zero = int(ordering_calibration_session_audit["starts_at_zero"].sum())
sessions_first_zero = int(ordering_calibration_session_audit["first_source_timestamp_zero"].sum())
sessions_source_time_clean = int(ordering_calibration_session_audit["source_timestamp_inversions"].eq(0).sum())
sessions_id_time_clean = int(ordering_calibration_session_audit["id_timestamp_inversions"].eq(0).sum())
sessions_tie_id_clean = int(ordering_calibration_session_audit["within_tie_source_id_inversions"].eq(0).sum())

id_duplicate_rows = int(id_corpus.get("duplicate_raw_id_rows", 0))
id_collision_review = bool(globals().get("UTTERANCE_ID_COLLISION_REVIEW_REQUIRED", False))
OBSERVED_ROLLOVER_REQUIRED = source_time_inv > 0
RELATIVE_SESSION_CLOCK_STRONG = sessions_min_zero == n_sessions and sessions_first_zero == n_sessions and source_time_inv == 0

ID_FALLBACK_ELIGIBLE = (
    source_id_exact_sessions == n_sessions and id_time_inv == 0 and id_duplicate_rows == 0 and not id_collision_review
)
ID_FALLBACK_CONFIDENCE = "MEDIUM" if ID_FALLBACK_ELIGIBLE else "LOW"
SOURCE_ORDER_FALLBACK_CONFIDENCE = "MEDIUM" if source_time_inv == 0 else "LOW"
TIMESTAMP_PRIMARY_CONFIDENCE = "HIGH" if source_time_inv == 0 and id_time_inv == 0 else "MEDIUM"

ORDERING_SYSTEMIC_CONFLICT = min(source_id_agreement, source_time_agreement, id_time_agreement, within_tie_agreement) < ORDERING_REVIEW_THRESHOLD
ORDERING_REVIEW_REQUIRED = (
    source_id_exact_sessions < n_sessions or candidate_exact_sessions < n_sessions or
    source_time_inv > 0 or id_time_inv > 0 or tie_inv > 0
)

ordering_calibration_checks = pd.DataFrame([
    check_row("All transcript sessions were ordering-calibrated", n_sessions == len(TRANSCRIPT_FILES), f"{n_sessions} / {len(TRANSCRIPT_FILES)}"),
    check_row("Ordering row census matches raw corpus", n_rows == TOTAL_RAW_ROWS, f"{n_rows} / {TOTAL_RAW_ROWS}"),
    check_row("Source row indices are contiguous in every session", source_index_failures == 0, source_index_failures),
    check_row("Source and utterance-ID chronology meet calibration threshold", source_id_agreement >= ORDERING_REVIEW_THRESHOLD, f"{source_id_agreement:.9f}"),
    check_row("Source order respects strict timestamp chronology", source_time_agreement >= ORDERING_REVIEW_THRESHOLD, f"{source_time_agreement:.9f}"),
    check_row("Utterance-ID order respects strict timestamp chronology", id_time_agreement >= ORDERING_REVIEW_THRESHOLD, f"{id_time_agreement:.9f}"),
    check_row("ID ordering inside timestamp ties meets calibration threshold", within_tie_agreement >= ORDERING_REVIEW_THRESHOLD, f"{within_tie_agreement:.9f}"),
    check_row("No unresolved systemic ordering contradiction", not ORDERING_SYSTEMIC_CONFLICT, ORDERING_SYSTEMIC_CONFLICT),
    check_row("No observed midnight rollover requires application", not OBSERVED_ROLLOVER_REQUIRED, OBSERVED_ROLLOVER_REQUIRED),
    check_row("Calibration engine is deterministic", ORDERING_CALIBRATION_DETERMINISTIC, ORDERING_CALIBRATION_DETERMINISTIC),
    check_row("All ordering synthetic tests passed", ordering_calibration_tests["passed"].all(), int((~ordering_calibration_tests["passed"]).sum()))
])

ordering_gate_failures = ordering_calibration_checks[~ordering_calibration_checks["passed"]]
ORDERING_VALIDITY_CALIBRATED = ordering_gate_failures.empty

ordering_calibration_summary = pd.DataFrame({
    "item": [
        "Calibration version", "Sessions", "Rows", "Source-ID exact sessions", "Timestamp+ID candidate exact sessions",
        "Source-ID pairwise agreement", "Source-Time strict agreement", "ID-Time strict agreement", "Within-tie ID-Source agreement",
        "Candidate-Source pairwise agreement", "Timestamp tie groups", "Timestamp tie rows",
        "Source-Time inversions", "ID-Time inversions", "Within-tie ID inversions",
        "Sessions min timestamp = 0", "Sessions first timestamp = 0", "Relative session clock evidence strong",
        "Observed rollover required", "ID fallback eligible", "ID fallback confidence",
        "Source fallback confidence", "Timestamp primary confidence", "Ordering review required",
        "ORDERING_CALIBRATION_CONFIG_SHA256", "ORDERING_VALIDITY_CALIBRATED"
    ],
    "value": [
        ORDERING_CALIBRATION_VERSION, n_sessions, n_rows, source_id_exact_sessions, candidate_exact_sessions,
        source_id_agreement, source_time_agreement, id_time_agreement, within_tie_agreement,
        candidate_source_agreement, int(ordering_corpus["timestamp_tie_group_count"]), int(ordering_corpus["timestamp_tie_rows"]),
        source_time_inv, id_time_inv, tie_inv, sessions_min_zero, sessions_first_zero, RELATIVE_SESSION_CLOCK_STRONG,
        OBSERVED_ROLLOVER_REQUIRED, ID_FALLBACK_ELIGIBLE, ID_FALLBACK_CONFIDENCE,
        SOURCE_ORDER_FALLBACK_CONFIDENCE, TIMESTAMP_PRIMARY_CONFIDENCE, ORDERING_REVIEW_REQUIRED,
        ORDERING_CALIBRATION_CONFIG_SHA256, ORDERING_VALIDITY_CALIBRATED
    ]
})

display(ordering_calibration_checks)
display(ordering_calibration_summary)

assert ORDERING_VALIDITY_CALIBRATED, (
    "Section 2.10 failed.\n\n" + ordering_gate_failures[["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 68)
print("TRACE THE ACE — ORDERING VALIDITY CALIBRATED")
print("=" * 68)
print(f"Sessions                 : {n_sessions:,}")
print(f"Rows                     : {n_rows:,}")
print(f"Source-ID exact          : {source_id_exact_sessions:,}/{n_sessions:,}")
print(f"Timestamp+ID exact       : {candidate_exact_sessions:,}/{n_sessions:,}")
print(f"Source-ID agreement      : {source_id_agreement:.9f}")
print(f"Source-Time agreement    : {source_time_agreement:.9f}")
print(f"ID-Time agreement        : {id_time_agreement:.9f}")
print(f"Within-tie agreement     : {within_tie_agreement:.9f}")
print(f"ID-Time inversions       : {id_time_inv:,}")
print(f"Within-tie inversions    : {tie_inv:,}")
print(f"Relative clock strong    : {RELATIVE_SESSION_CLOCK_STRONG}")
print(f"Rollover required        : {OBSERVED_ROLLOVER_REQUIRED}")
print(f"ID fallback eligible     : {ID_FALLBACK_ELIGIBLE} ({ID_FALLBACK_CONFIDENCE})")
print(f"Review required          : {ORDERING_REVIEW_REQUIRED}")
print(f"ORDERING CALIBRATED      : {ORDERING_VALIDITY_CALIBRATED}")
print("=" * 68)

,check,passed,detail
0,All transcript sessions were ordering-calibrated,True,22821 / 22821
1,Ordering row census matches raw corpus,True,6139854 / 6139854
2,Source row indices are contiguous in every ses...,True,0
3,Source and utterance-ID chronology meet calibr...,True,1.000000000
4,Source order respects strict timestamp chronology,True,1.000000000
5,Utterance-ID order respects strict timestamp c...,True,1.000000000
6,ID ordering inside timestamp ties meets calibr...,True,1.000000000
7,No unresolved systemic ordering contradiction,True,False
8,No observed midnight rollover requires applica...,True,False
9,Calibration engine is deterministic,True,True
10,All ordering synthetic tests passed,True,0

,item,value
0,Calibration version,1.0
1,Sessions,22821
2,Rows,6139854
3,Source-ID exact sessions,22821
4,Timestamp+ID candidate exact sessions,22821
5,Source-ID pairwise agreement,1.0
6,Source-Time strict agreement,1.0
7,ID-Time strict agreement,1.0
8,Within-tie ID-Source agreement,1.0
9,Candidate-Source pairwise agreement,1.0
10,Timestamp tie groups,325210
11,Timestamp tie rows,717014
12,Source-Time inversions,0
13,ID-Time inversions,0
14,Within-tie ID inversions,0
15,Sessions min timestamp = 0,22821
16,Sessions first timestamp = 0,22821
17,Relative session clock evidence strong,True
18,Observed rollover required,False
19,ID fallback eligible,True
20,ID fallback confidence,MEDIUM
21,Source fallback confidence,MEDIUM
22,Timestamp primary confidence,HIGH
23,Ordering review required,False
24,ORDERING_CALIBRATION_CONFIG_SHA256,c8f9ebfe6de959246ddce0cfefbfe4185f872ca8f97368...
25,ORDERING_VALIDITY_CALIBRATED,True

====================================================================
TRACE THE ACE — ORDERING VALIDITY CALIBRATED
====================================================================
Sessions                 : 22,821
Rows                     : 6,139,854
Source-ID exact          : 22,821/22,821
Timestamp+ID exact       : 22,821/22,821
Source-ID agreement      : 1.000000000
Source-Time agreement    : 1.000000000
ID-Time agreement        : 1.000000000
Within-tie agreement     : 1.000000000
ID-Time inversions       : 0
Within-tie inversions    : 0
Relative clock strong    : True
Rollover required        : False
ID fallback eligible     : True (MEDIUM)
Review required          : False
ORDERING CALIBRATED      : True
====================================================================

# Section 2.11 — Deterministic Ordering Policy

This section freezes the deterministic session-level ordering policy from the calibrated evidence.
Timestamp is the primary temporal signal and valid utterance ID resolves timestamp ties.
Physical source order is retained as the final deterministic tie-breaker.
Timestamp ties are not treated as ordering failures when the calibrated ID tie-breaker is usable.
If timestamps are unusable, the entire session may fall back to calibrated utterance-ID order.
If both timestamp and ID evidence are unusable, the entire session falls back to physical source order.
No row-wise mixing of ordering strategies is allowed within a session.
No midnight rollover is silently invented for the current corpus.
Final `turn_index` and structural turn metadata remain deferred to later parser stages.
The section ends with `DETERMINISTIC_ORDERING_READY`.

In [37]:
assert ORDERING_VALIDITY_CALIBRATED, "Section 2.10 must pass before Section 2.11."

ORDERING_POLICY_VERSION = "1.0"
ORDERING_POLICY_CONFIG = {
    "version": ORDERING_POLICY_VERSION, "calibration_version": ORDERING_CALIBRATION_VERSION,
    "calibration_sha256": ORDERING_CALIBRATION_CONFIG_SHA256,
    "primary_method": "TIMESTAMP_PRIMARY",
    "primary_keys": ["timestamp_order_value", "utterance_id", "source_file_relative", "source_row_index"],
    "timestamp_tie_breaker": "UTTERANCE_ID_WHEN_LOCALLY_USABLE_AND_SOURCE_CORROBORATED",
    "final_tie_breaker": ["source_file_relative", "source_row_index"],
    "id_fallback_enabled": bool(ID_FALLBACK_ELIGIBLE), "id_fallback_max_confidence": "MEDIUM",
    "source_fallback_confidence": "LOW", "row_wise_strategy_mixing": False,
    "automatic_rollover_current_corpus": False, "turn_index_assignment": "DEFER_TO_2.14",
    "full_corpus_application": "DEFER_TO_2.16", "label_blind": True
}
ORDERING_POLICY_CONFIG_SHA256 = canonical_json_hash(ORDERING_POLICY_CONFIG)

def order_session_rows(raw_ids, raw_timestamps, source_indices=None, relative_file="session.csv"):
    n = len(raw_ids)
    if len(raw_timestamps) != n: raise ValueError("ID and timestamp lengths differ.")
    source_indices = list(range(n)) if source_indices is None else list(source_indices)
    if len(source_indices) != n or sorted(source_indices) != list(range(n)): raise ValueError("Source indices must be unique and contiguous from zero.")

    id_result = annotate_session_ids(raw_ids); id_rows = id_result["rows"]
    ts_rows = [parse_timestamp(x) for x in raw_timestamps]
    parsed_ids = [x["utterance_id"] for x in id_rows]; parsed_times = [x["timestamp"] for x in ts_rows]

    ids_usable = all(x["utterance_id_status"] == "VALID" for x in id_rows)
    all_times_valid = all(x["timestamp_status"] == "VALID" for x in ts_rows)
    source_order = sorted(range(n), key=lambda i: (relative_file, source_indices[i]))

    id_order = sorted(range(n), key=lambda i: (parsed_ids[i], relative_file, source_indices[i])) if ids_usable else None
    id_source_exact = ids_usable and id_order == source_order

    regressions = 0
    if all_times_valid:
        regressions = sum(parsed_times[i] < parsed_times[i - 1] for i in range(1, n))

    tie_count = 0
    if all_times_valid:
        tie_count = sum(c > 1 for c in Counter(parsed_times).values())

    timestamp_usable = all_times_valid and regressions == 0

    if timestamp_usable:
        if tie_count == 0:
            ordered = sorted(range(n), key=lambda i: (parsed_times[i], relative_file, source_indices[i]))
            method, confidence, issue, reason = "TIMESTAMP_PRIMARY", "HIGH", False, "STRICT_TIMESTAMP_ORDER"
        elif ids_usable and id_source_exact:
            ordered = sorted(range(n), key=lambda i: (parsed_times[i], parsed_ids[i], relative_file, source_indices[i]))
            method, confidence, issue, reason = "TIMESTAMP_PRIMARY", "HIGH", False, "TIMESTAMP_WITH_CALIBRATED_ID_TIEBREAK"
        else:
            ordered = sorted(range(n), key=lambda i: (parsed_times[i], relative_file, source_indices[i]))
            method, confidence, issue, reason = "TIMESTAMP_PRIMARY", "MEDIUM", True, "TIMESTAMP_WITH_SOURCE_TIEBREAK"
    elif ID_FALLBACK_ELIGIBLE and ids_usable and id_source_exact:
        ordered = id_order
        method, confidence, issue, reason = "UTTERANCE_ID_FALLBACK", "MEDIUM", True, "TIMESTAMP_UNUSABLE_ID_SOURCE_CORROBORATED"
    else:
        ordered = source_order
        method, confidence, issue, reason = "SOURCE_ORDER_FALLBACK", "LOW", True, "TIMESTAMP_AND_ID_NOT_JOINTLY_USABLE"

    day_offsets = [0 if x["timestamp_status"] == "VALID" else None for x in ts_rows]
    order_values = [x["timestamp"] if x["timestamp_status"] == "VALID" else None for x in ts_rows]
    rollover_flags = [False] * n

    return {
        "ordered_positions": ordered, "ordered_source_row_indices": [source_indices[i] for i in ordered],
        "ordering_method": method, "ordering_confidence": confidence, "ordering_issue_flag": issue,
        "fallback_used": method != "TIMESTAMP_PRIMARY", "ordering_reason": reason,
        "timestamp_day_offset": day_offsets, "timestamp_order_value": order_values,
        "timestamp_rollover_flag": rollover_flags, "timestamp_regressions": regressions,
        "timestamp_tie_groups": tie_count, "ids_usable": ids_usable,
        "id_source_exact": id_source_exact, "timestamp_usable": timestamp_usable
    }

def ordering_test(name, raw_ids, raw_times, expected):
    result = order_session_rows(raw_ids, raw_times)
    passed = all(result.get(k) == v for k, v in expected.items())
    return {"test": name, "passed": passed, "method": result["ordering_method"],
            "confidence": result["ordering_confidence"], "issue": result["ordering_issue_flag"],
            "order": result["ordered_source_row_indices"], "reason": result["ordering_reason"]}

ordering_policy_tests = pd.DataFrame([
    ordering_test("O01_UNIQUE_TIME", ["0","1","2"], ["00:00:00","00:00:01","00:00:02"],
                  {"ordering_method":"TIMESTAMP_PRIMARY","ordering_confidence":"HIGH","ordering_issue_flag":False,"ordered_source_row_indices":[0,1,2]}),
    ordering_test("O02_TIMESTAMP_TIE", ["0","1","2"], ["00:00:00","00:00:00","00:00:01"],
                  {"ordering_method":"TIMESTAMP_PRIMARY","ordering_confidence":"HIGH","ordering_issue_flag":False,"ordered_source_row_indices":[0,1,2]}),
    ordering_test("O03_MULTIPLE_TIES", ["0","1","2","3","4"], ["00:00:00","00:00:00","00:00:01","00:00:02","00:00:02"],
                  {"ordering_method":"TIMESTAMP_PRIMARY","ordering_confidence":"HIGH","ordered_source_row_indices":[0,1,2,3,4]}),
    ordering_test("O04_ALL_TIMES_TIED", ["0","1","2"], ["00:00:05","00:00:05","00:00:05"],
                  {"ordering_method":"TIMESTAMP_PRIMARY","ordering_confidence":"HIGH","ordered_source_row_indices":[0,1,2]}),
    ordering_test("O05_ONE_TIME_MISSING", ["0","1","2"], ["00:00:00","","00:00:02"],
                  {"ordering_method":"UTTERANCE_ID_FALLBACK","ordering_confidence":"MEDIUM","ordering_issue_flag":True}),
    ordering_test("O06_ALL_TIMES_MISSING", ["0","1","2"], ["","",""],
                  {"ordering_method":"UTTERANCE_ID_FALLBACK","ordering_confidence":"MEDIUM","ordering_issue_flag":True}),
    ordering_test("O07_BAD_TIMESTAMP", ["0","1","2"], ["00:00:00","BAD","00:00:02"],
                  {"ordering_method":"UTTERANCE_ID_FALLBACK","ordering_confidence":"MEDIUM","ordering_issue_flag":True}),
    ordering_test("O08_BAD_ID_AND_TIME", ["0","BAD","2"], ["","",""],
                  {"ordering_method":"SOURCE_ORDER_FALLBACK","ordering_confidence":"LOW","ordered_source_row_indices":[0,1,2]}),
    ordering_test("O09_DUPLICATE_ID_FALLBACK", ["0","0","1"], ["","",""],
                  {"ordering_method":"SOURCE_ORDER_FALLBACK","ordering_confidence":"LOW","ordered_source_row_indices":[0,1,2]}),
    ordering_test("O10_BACKWARD_TIME", ["0","1","2"], ["00:00:10","00:00:05","00:00:12"],
                  {"ordering_method":"UTTERANCE_ID_FALLBACK","ordering_confidence":"MEDIUM","timestamp_regressions":1}),
    ordering_test("O11_TIE_ID_SOURCE_CONFLICT", ["1","0","2"], ["00:00:00","00:00:00","00:00:01"],
                  {"ordering_method":"TIMESTAMP_PRIMARY","ordering_confidence":"MEDIUM","ordering_issue_flag":True,"ordered_source_row_indices":[0,1,2]}),
    ordering_test("O12_UNIQUE_TIME_BAD_ID", ["0","BAD","2"], ["00:00:00","00:00:01","00:00:02"],
                  {"ordering_method":"TIMESTAMP_PRIMARY","ordering_confidence":"HIGH","ordered_source_row_indices":[0,1,2]})
])

repeat_a = order_session_rows(["0","1","2","3"], ["00:00:00","00:00:00","00:00:01","00:00:01"])
repeat_b = order_session_rows(["0","1","2","3"], ["00:00:00","00:00:00","00:00:01","00:00:01"])
ORDERING_POLICY_DETERMINISTIC = repeat_a == repeat_b

display(ordering_policy_tests)
assert ordering_policy_tests["passed"].all(), "Deterministic ordering synthetic tests failed."
assert ORDERING_POLICY_DETERMINISTIC, "Ordering policy is non-deterministic."

,test,passed,method,confidence,issue,order,reason
0,O01_UNIQUE_TIME,True,TIMESTAMP_PRIMARY,HIGH,False,"[0, 1, 2]",STRICT_TIMESTAMP_ORDER
1,O02_TIMESTAMP_TIE,True,TIMESTAMP_PRIMARY,HIGH,False,"[0, 1, 2]",TIMESTAMP_WITH_CALIBRATED_ID_TIEBREAK
2,O03_MULTIPLE_TIES,True,TIMESTAMP_PRIMARY,HIGH,False,"[0, 1, 2, 3, 4]",TIMESTAMP_WITH_CALIBRATED_ID_TIEBREAK
3,O04_ALL_TIMES_TIED,True,TIMESTAMP_PRIMARY,HIGH,False,"[0, 1, 2]",TIMESTAMP_WITH_CALIBRATED_ID_TIEBREAK
4,O05_ONE_TIME_MISSING,True,UTTERANCE_ID_FALLBACK,MEDIUM,True,"[0, 1, 2]",TIMESTAMP_UNUSABLE_ID_SOURCE_CORROBORATED
5,O06_ALL_TIMES_MISSING,True,UTTERANCE_ID_FALLBACK,MEDIUM,True,"[0, 1, 2]",TIMESTAMP_UNUSABLE_ID_SOURCE_CORROBORATED
6,O07_BAD_TIMESTAMP,True,UTTERANCE_ID_FALLBACK,MEDIUM,True,"[0, 1, 2]",TIMESTAMP_UNUSABLE_ID_SOURCE_CORROBORATED
7,O08_BAD_ID_AND_TIME,True,SOURCE_ORDER_FALLBACK,LOW,True,"[0, 1, 2]",TIMESTAMP_AND_ID_NOT_JOINTLY_USABLE
8,O09_DUPLICATE_ID_FALLBACK,True,SOURCE_ORDER_FALLBACK,LOW,True,"[0, 1, 2]",TIMESTAMP_AND_ID_NOT_JOINTLY_USABLE
9,O10_BACKWARD_TIME,True,UTTERANCE_ID_FALLBACK,MEDIUM,True,"[0, 1, 2]",TIMESTAMP_UNUSABLE_ID_SOURCE_CORROBORATED
10,O11_TIE_ID_SOURCE_CONFLICT,True,TIMESTAMP_PRIMARY,MEDIUM,True,"[0, 1, 2]",TIMESTAMP_WITH_SOURCE_TIEBREAK
11,O12_UNIQUE_TIME_BAD_ID,True,TIMESTAMP_PRIMARY,HIGH,False,"[0, 1, 2]",STRICT_TIMESTAMP_ORDER

In [38]:
def choose_ordering_smoke_files(audit):
    selected = set()

    tie_free = audit[audit["timestamp_reference_class"] == "TIE_FREE_FULL_REFERENCE"].sort_values("relative_file")
    partial = audit[audit["timestamp_reference_class"] == "PARTIAL_TEMPORAL_REFERENCE"].sort_values("relative_file")
    if not tie_free.empty: selected.add(tie_free.iloc[0]["relative_file"])
    if not partial.empty: selected.add(partial.iloc[0]["relative_file"])

    selected.add(audit.loc[audit["n_turns"].idxmin(), "relative_file"])
    selected.add(audit.loc[audit["n_turns"].idxmax(), "relative_file"])
    selected.add(audit.loc[audit["max_tie_group_size"].idxmax(), "relative_file"])

    p99_tie = int(tie_size_summary.loc[tie_size_summary["metric"] == "P99 tie size", "value"].iloc[0])
    p99_candidates = audit[audit["max_tie_group_size"] >= p99_tie].sort_values(["max_tie_group_size","relative_file"])
    if not p99_candidates.empty: selected.add(p99_candidates.iloc[0]["relative_file"])

    return sorted(selected)

def audit_real_ordering(relative_file):
    path = TRANSCRIPT_ROOT / Path(relative_file)
    reconstructed = reconstruct_raw_file(path, expected_session_id=Path(relative_file).stem)
    table = reconstructed["raw_table"]

    source_indices = [int(x) for x in table.column("source_row_index").to_pylist()]
    raw_ids = table.column("utterance_id_raw").to_pylist()
    raw_times = table.column("timestamp_raw").to_pylist()
    result = order_session_rows(raw_ids, raw_times, source_indices, relative_file)

    return {
        "relative_file": relative_file, "rows": len(source_indices),
        "timestamp_tie_groups": result["timestamp_tie_groups"], "ordering_method": result["ordering_method"],
        "ordering_confidence": result["ordering_confidence"], "ordering_issue_flag": result["ordering_issue_flag"],
        "fallback_used": result["fallback_used"], "source_order_preserved": result["ordered_source_row_indices"] == source_indices,
        "all_day_offsets_zero": all(x == 0 for x in result["timestamp_day_offset"]),
        "no_rollover_flags": not any(result["timestamp_rollover_flag"]),
        "passed": result["ordering_method"] == "TIMESTAMP_PRIMARY" and result["ordering_confidence"] == "HIGH"
                  and not result["ordering_issue_flag"] and not result["fallback_used"]
                  and result["ordered_source_row_indices"] == source_indices
                  and all(x == 0 for x in result["timestamp_day_offset"])
                  and not any(result["timestamp_rollover_flag"])
    }

REAL_ORDERING_FILES = choose_ordering_smoke_files(ordering_calibration_session_audit)
ordering_real_smoke_audit = pd.DataFrame([audit_real_ordering(f) for f in REAL_ORDERING_FILES])

display(ordering_real_smoke_audit)

,relative_file,rows,timestamp_tie_groups,ordering_method,ordering_confidence,ordering_issue_flag,fallback_used,source_order_preserved,all_day_offsets_zero,no_rollover_flags,passed
0,aaaedit.csv,254,24,TIMESTAMP_PRIMARY,HIGH,False,False,True,True,True,True
1,aayjyjr.csv,76,0,TIMESTAMP_PRIMARY,HIGH,False,False,True,True,True,True
2,bvnewyc.csv,622,46,TIMESTAMP_PRIMARY,HIGH,False,False,True,True,True,True
3,jlntsbf.csv,15,0,TIMESTAMP_PRIMARY,HIGH,False,False,True,True,True,True
4,mvkburc.csv,582,52,TIMESTAMP_PRIMARY,HIGH,False,False,True,True,True,True

In [39]:
allowed_methods = set(STATUS_VOCABULARIES["ordering_method"])
allowed_confidence = set(STATUS_VOCABULARIES["ordering_confidence"])

synthetic_failures = int((~ordering_policy_tests["passed"]).sum())
real_failures = int((~ordering_real_smoke_audit["passed"]).sum())

CURRENT_CORPUS_ORDERING_CERTIFIED = all([
    source_id_exact_sessions == n_sessions, candidate_exact_sessions == n_sessions,
    source_time_inv == 0, id_time_inv == 0, tie_inv == 0,
    not OBSERVED_ROLLOVER_REQUIRED, not ORDERING_REVIEW_REQUIRED
])

ordering_policy_checks = pd.DataFrame([
    check_row("Ordering calibration is ready", ORDERING_VALIDITY_CALIBRATED, ORDERING_VALIDITY_CALIBRATED),
    check_row("Primary method belongs to frozen domain", ORDERING_POLICY_CONFIG["primary_method"] in allowed_methods, ORDERING_POLICY_CONFIG["primary_method"]),
    check_row("All required ordering methods exist in frozen domain",
              {"TIMESTAMP_PRIMARY","UTTERANCE_ID_FALLBACK","SOURCE_ORDER_FALLBACK"}.issubset(allowed_methods), sorted(allowed_methods)),
    check_row("Required confidence levels exist in frozen domain", {"HIGH","MEDIUM","LOW"}.issubset(allowed_confidence), sorted(allowed_confidence)),
    check_row("Current corpus chronology is fully certified", CURRENT_CORPUS_ORDERING_CERTIFIED, CURRENT_CORPUS_ORDERING_CERTIFIED),
    check_row("Current corpus requires no rollover", not OBSERVED_ROLLOVER_REQUIRED, OBSERVED_ROLLOVER_REQUIRED),
    check_row("ID fallback is empirically eligible", ID_FALLBACK_ELIGIBLE, ID_FALLBACK_ELIGIBLE),
    check_row("ID fallback never receives HIGH confidence", ORDERING_POLICY_CONFIG["id_fallback_max_confidence"] == "MEDIUM", ORDERING_POLICY_CONFIG["id_fallback_max_confidence"]),
    check_row("Row-wise strategy mixing is prohibited", not ORDERING_POLICY_CONFIG["row_wise_strategy_mixing"], ORDERING_POLICY_CONFIG["row_wise_strategy_mixing"]),
    check_row("Turn-index assignment remains deferred", ORDERING_POLICY_CONFIG["turn_index_assignment"] == "DEFER_TO_2.14", ORDERING_POLICY_CONFIG["turn_index_assignment"]),
    check_row("Full application remains deferred to production parse", ORDERING_POLICY_CONFIG["full_corpus_application"] == "DEFER_TO_2.16", ORDERING_POLICY_CONFIG["full_corpus_application"]),
    check_row("Ordering policy is label-blind", ORDERING_POLICY_CONFIG["label_blind"], ORDERING_POLICY_CONFIG["label_blind"]),
    check_row("All synthetic ordering tests passed", synthetic_failures == 0, synthetic_failures),
    check_row("All real ordering smoke tests passed", real_failures == 0, real_failures),
    check_row("Ordering policy is deterministic", ORDERING_POLICY_DETERMINISTIC, ORDERING_POLICY_DETERMINISTIC)
])

ordering_policy_failures = ordering_policy_checks[~ordering_policy_checks["passed"]]
DETERMINISTIC_ORDERING_READY = ordering_policy_failures.empty

ordering_policy_summary = pd.DataFrame({
    "item": [
        "Ordering policy version", "Primary method", "Primary confidence",
        "Primary sort key", "Timestamp tie-breaker", "Final tie-breaker",
        "Current corpus sessions certified", "Expected timestamp-primary sessions",
        "Expected ID-fallback sessions", "Expected source-fallback sessions",
        "Current rollover applications", "ID fallback eligible", "ID fallback max confidence",
        "Synthetic tests", "Passed synthetic tests", "Real smoke files", "Real smoke failures",
        "Row-wise mixing allowed", "Final turn index created here",
        "ORDERING_POLICY_CONFIG_SHA256", "DETERMINISTIC_ORDERING_READY"
    ],
    "value": [
        ORDERING_POLICY_VERSION, "TIMESTAMP_PRIMARY", "HIGH",
        "timestamp → utterance_id → source_file_relative → source_row_index",
        "UTTERANCE_ID", "SOURCE_FILE + SOURCE_ROW",
        n_sessions if CURRENT_CORPUS_ORDERING_CERTIFIED else 0,
        n_sessions if CURRENT_CORPUS_ORDERING_CERTIFIED else None, 0 if CURRENT_CORPUS_ORDERING_CERTIFIED else None,
        0 if CURRENT_CORPUS_ORDERING_CERTIFIED else None, 0,
        ID_FALLBACK_ELIGIBLE, "MEDIUM", len(ordering_policy_tests),
        int(ordering_policy_tests["passed"].sum()), len(ordering_real_smoke_audit), real_failures,
        False, False, ORDERING_POLICY_CONFIG_SHA256, DETERMINISTIC_ORDERING_READY
    ]
})

display(ordering_policy_checks)
display(ordering_policy_summary)

assert DETERMINISTIC_ORDERING_READY, (
    "Section 2.11 failed.\n\n" + ordering_policy_failures[["check","detail"]].to_string(index=False)
)

print("\n" + "=" * 68)
print("TRACE THE ACE — DETERMINISTIC ORDERING POLICY READY")
print("=" * 68)
print(f"Primary method       : TIMESTAMP_PRIMARY")
print(f"Primary confidence   : HIGH")
print(f"Certified sessions   : {n_sessions:,}/{n_sessions:,}")
print(f"Expected primary     : {n_sessions:,}")
print(f"Expected ID fallback : 0")
print(f"Expected source fall.: 0")
print(f"Rollover applications: 0")
print(f"Synthetic tests      : {int(ordering_policy_tests['passed'].sum())}/{len(ordering_policy_tests)}")
print(f"Real smoke tests     : {len(ordering_real_smoke_audit)-real_failures}/{len(ordering_real_smoke_audit)}")
print(f"Policy deterministic : {ORDERING_POLICY_DETERMINISTIC}")
print(f"ORDERING READY       : {DETERMINISTIC_ORDERING_READY}")
print("=" * 68)

,check,passed,detail
0,Ordering calibration is ready,True,True
1,Primary method belongs to frozen domain,True,TIMESTAMP_PRIMARY
2,All required ordering methods exist in frozen ...,True,"[SOURCE_ORDER_FALLBACK, TIMESTAMP_PRIMARY, UTT..."
3,Required confidence levels exist in frozen domain,True,"[HIGH, LOW, MEDIUM]"
4,Current corpus chronology is fully certified,True,True
5,Current corpus requires no rollover,True,False
6,ID fallback is empirically eligible,True,True
7,ID fallback never receives HIGH confidence,True,MEDIUM
8,Row-wise strategy mixing is prohibited,True,False
9,Turn-index assignment remains deferred,True,DEFER_TO_2.14
10,Full application remains deferred to productio...,True,DEFER_TO_2.16
11,Ordering policy is label-blind,True,True
12,All synthetic ordering tests passed,True,0
13,All real ordering smoke tests passed,True,0
14,Ordering policy is deterministic,True,True

,item,value
0,Ordering policy version,1.0
1,Primary method,TIMESTAMP_PRIMARY
2,Primary confidence,HIGH
3,Primary sort key,timestamp → utterance_id → source_file_relativ...
4,Timestamp tie-breaker,UTTERANCE_ID
5,Final tie-breaker,SOURCE_FILE + SOURCE_ROW
6,Current corpus sessions certified,22821
7,Expected timestamp-primary sessions,22821
8,Expected ID-fallback sessions,0
9,Expected source-fallback sessions,0
10,Current rollover applications,0
11,ID fallback eligible,True
12,ID fallback max confidence,MEDIUM
13,Synthetic tests,12
14,Passed synthetic tests,12
15,Real smoke files,5
16,Real smoke failures,0
17,Row-wise mixing allowed,False
18,Final turn index created here,False
19,ORDERING_POLICY_CONFIG_SHA256,ad32a87bfa6c2e5ff99ff45e1ff6d7173a1ad982a38786...
20,DETERMINISTIC_ORDERING_READY,True

====================================================================
TRACE THE ACE — DETERMINISTIC ORDERING POLICY READY
====================================================================
Primary method       : TIMESTAMP_PRIMARY
Primary confidence   : HIGH
Certified sessions   : 22,821/22,821
Expected primary     : 22,821
Expected ID fallback : 0
Expected source fall.: 0
Rollover applications: 0
Synthetic tests      : 12/12
Real smoke tests     : 5/5
Policy deterministic : True
ORDERING READY       : True
====================================================================

# Section 2.12 — Ordering Conflict Audit

This section documents ordering comparability, conflicts, and residual uncertainty after policy calibration.
Strict timestamp inequalities are temporal evidence; equal timestamps are unresolved ties, not conflicts.
Sessions are classified as `FULLY_COMPARABLE`, `PARTIALLY_COMPARABLE`, or `NOT_COMPARABLE`.
Timestamp–ID, timestamp–source, and ID–source conflicts are measured independently.
Timestamp ties remain informational when calibrated ID/source evidence resolves them safely.
Fallback use, rollover use, and ambiguous ordering are recorded separately from direct chronology conflicts.
Partial timestamp availability is compared only on rows and pairs that are actually comparable.
The exhaustive Section 2.10 session audit is reused, so transcript files are not rescanned here.
Synthetic tests validate the generic conflict-audit logic for future parser execution.
The section ends with `ORDERING_CONFLICT_AUDIT_READY`.

In [40]:
assert DETERMINISTIC_ORDERING_READY, "Section 2.11 must pass before Section 2.12."

ORDERING_CONFLICT_AUDIT_VERSION = "1.0"
ORDERING_CONFLICT_CONFIG = {
    "version": ORDERING_CONFLICT_AUDIT_VERSION, "timestamp_ties_are_conflicts": False,
    "strict_timestamp_pairs_only": True, "comparability": ["FULLY_COMPARABLE","PARTIALLY_COMPARABLE","NOT_COMPARABLE"],
    "conflicts": ["TIMESTAMP_ID_CONFLICT","TIMESTAMP_SOURCE_CONFLICT","ID_SOURCE_CONFLICT"],
    "information_flags": ["TIMESTAMP_TIE","MIDNIGHT_ROLLOVER","FALLBACK_USED"],
    "selected_policy": ORDERING_POLICY_CONFIG["primary_method"], "full_corpus_rescan": False
}
ORDERING_CONFLICT_CONFIG_SHA256 = canonical_json_hash(ORDERING_CONFLICT_CONFIG)

def audit_ordering_conflicts(raw_ids, raw_timestamps, source_indices=None, relative_file="session.csv", rollover_applied=False):
    n = len(raw_ids); source_indices = list(range(n)) if source_indices is None else list(source_indices)
    if len(raw_timestamps) != n or len(source_indices) != n: raise ValueError("Ordering vectors must have equal length.")

    ids = annotate_session_ids(raw_ids)["rows"]; times = [parse_timestamp(x) for x in raw_timestamps]
    selected = order_session_rows(raw_ids, raw_timestamps, source_indices, relative_file)

    valid_time_idx = [i for i,x in enumerate(times) if x["timestamp_status"] == "VALID"]
    valid_id_idx = [i for i,x in enumerate(ids) if x["utterance_id"] is not None]
    joint_idx = [i for i in valid_time_idx if ids[i]["utterance_id"] is not None]

    total_pairs = n * (n - 1) // 2
    valid_time_values = [times[i]["timestamp"] for i in valid_time_idx]
    time_counts = Counter(valid_time_values)
    tied_pairs = sum(c * (c - 1) // 2 for c in time_counts.values())
    timestamp_comparable_pairs = len(valid_time_idx) * (len(valid_time_idx) - 1) // 2 - tied_pairs
    temporal_pair_coverage = 0.0 if total_pairs == 0 else timestamp_comparable_pairs / total_pairs

    if n <= 1 or timestamp_comparable_pairs == 0: comparability = "NOT_COMPARABLE"
    elif len(valid_time_idx) == n and tied_pairs == 0: comparability = "FULLY_COMPARABLE"
    else: comparability = "PARTIALLY_COMPARABLE"

    source_time_values = [times[i]["timestamp"] for i in valid_time_idx]
    timestamp_source_inversions = count_inversions(source_time_values)

    id_order_joint = sorted(joint_idx, key=lambda i: (ids[i]["utterance_id"], source_indices[i]))
    id_time_values = [times[i]["timestamp"] for i in id_order_joint]
    timestamp_id_inversions = count_inversions(id_time_values)

    id_order = sorted(valid_id_idx, key=lambda i: (ids[i]["utterance_id"], source_indices[i]))
    id_source_sequence = [source_indices[i] for i in id_order]
    id_source_inversions = count_inversions(id_source_sequence)

    timestamp_tie = any(c > 1 for c in time_counts.values())
    timestamp_id_conflict = timestamp_id_inversions > 0
    timestamp_source_conflict = timestamp_source_inversions > 0
    id_source_conflict = id_source_inversions > 0
    fallback_used = bool(selected["fallback_used"])
    midnight_rollover = bool(rollover_applied or any(selected["timestamp_rollover_flag"]))
    selected_order_matches_source = selected["ordered_source_row_indices"] == sorted(source_indices)

    unresolved_tie = timestamp_tie and (
        not selected["ids_usable"] or
        (selected["ids_usable"] and not selected["id_source_exact"])
    )
    ambiguous_order = bool(
        selected["ordering_issue_flag"] or timestamp_id_conflict or
        timestamp_source_conflict or id_source_conflict or unresolved_tie
    )

    conflict_count = sum([timestamp_id_conflict, timestamp_source_conflict, id_source_conflict, ambiguous_order])
    information_flag_count = sum([timestamp_tie, midnight_rollover, fallback_used])

    return {
        "n_turns": n, "ordering_comparability": comparability,
        "comparison_row_count": len(valid_time_idx), "comparison_row_fraction": 0.0 if n == 0 else len(valid_time_idx) / n,
        "total_pair_count": total_pairs, "timestamp_comparable_pairs": timestamp_comparable_pairs,
        "temporal_pair_coverage": temporal_pair_coverage, "timestamp_id_inversions": timestamp_id_inversions,
        "timestamp_source_inversions": timestamp_source_inversions, "id_source_inversions": id_source_inversions,
        "timestamp_id_conflict": timestamp_id_conflict, "timestamp_source_conflict": timestamp_source_conflict,
        "id_source_conflict": id_source_conflict, "timestamp_tie": timestamp_tie,
        "timestamp_tie_group_count": sum(c > 1 for c in time_counts.values()),
        "timestamp_tie_rows": sum(c for c in time_counts.values() if c > 1),
        "midnight_rollover": midnight_rollover, "fallback_used": fallback_used,
        "ambiguous_order": ambiguous_order, "selected_order_matches_source": selected_order_matches_source,
        "ordering_method": selected["ordering_method"], "ordering_confidence": selected["ordering_confidence"],
        "conflict_count": conflict_count, "information_flag_count": information_flag_count
    }

def conflict_test(name, ids, times, expected, rollover=False):
    result = audit_ordering_conflicts(ids, times, rollover_applied=rollover)
    passed = all(result.get(k) == v for k,v in expected.items())
    return {"test":name, "passed":passed, "comparability":result["ordering_comparability"],
            "conflicts":result["conflict_count"], "tie":result["timestamp_tie"],
            "fallback":result["fallback_used"], "ambiguous":result["ambiguous_order"]}

ordering_conflict_tests = pd.DataFrame([
    conflict_test("F01_FULLY_COMPARABLE", ["0","1","2"], ["00:00:00","00:00:01","00:00:02"],
                  {"ordering_comparability":"FULLY_COMPARABLE","conflict_count":0,"timestamp_tie":False}),
    conflict_test("F02_TIE_RESOLVED", ["0","1","2"], ["00:00:00","00:00:00","00:00:01"],
                  {"ordering_comparability":"PARTIALLY_COMPARABLE","timestamp_tie":True,"timestamp_id_conflict":False,"ambiguous_order":False}),
    conflict_test("F03_TIMESTAMP_ID_CONFLICT", ["0","2","1"], ["00:00:00","00:00:01","00:00:02"],
                  {"timestamp_id_conflict":True,"ambiguous_order":True}),
    conflict_test("F04_TIMESTAMP_SOURCE_CONFLICT", ["0","2","1"], ["00:00:00","00:00:02","00:00:01"],
                  {"timestamp_source_conflict":True,"ambiguous_order":True}),
    conflict_test("F05_ID_SOURCE_CONFLICT", ["0","2","1"], ["00:00:00","00:00:00","00:00:00"],
                  {"id_source_conflict":True,"ambiguous_order":True}),
    conflict_test("F06_PARTIAL_TIMESTAMP", ["0","1","2"], ["00:00:00","","00:00:02"],
                  {"ordering_comparability":"PARTIALLY_COMPARABLE","fallback_used":True,"ambiguous_order":True}),
    conflict_test("F07_NO_VALID_TIMESTAMP", ["0","1","2"], ["","",""],
                  {"ordering_comparability":"NOT_COMPARABLE","fallback_used":True}),
    conflict_test("F08_ALL_TIMES_TIED", ["0","1","2"], ["00:00:05","00:00:05","00:00:05"],
                  {"ordering_comparability":"NOT_COMPARABLE","timestamp_tie":True,"ambiguous_order":False}),
    conflict_test("F09_ID_FALLBACK", ["0","1","2"], ["","BAD",""],
                  {"fallback_used":True,"ordering_method":"UTTERANCE_ID_FALLBACK","ambiguous_order":True}),
    conflict_test("F10_SOURCE_FALLBACK", ["0","BAD","2"], ["","",""],
                  {"fallback_used":True,"ordering_method":"SOURCE_ORDER_FALLBACK","ambiguous_order":True}),
    conflict_test("F11_ROLLOVER_FLAG", ["0","1"], ["00:00:00","00:00:01"],
                  {"midnight_rollover":True}, rollover=True)
])

det_a = audit_ordering_conflicts(["0","1","2"], ["00:00:00","00:00:00","00:00:01"])
det_b = audit_ordering_conflicts(["0","1","2"], ["00:00:00","00:00:00","00:00:01"])
ordering_conflict_tests.loc[len(ordering_conflict_tests)] = {
    "test":"F12_DETERMINISTIC", "passed":det_a == det_b, "comparability":det_a["ordering_comparability"],
    "conflicts":det_a["conflict_count"], "tie":det_a["timestamp_tie"],
    "fallback":det_a["fallback_used"], "ambiguous":det_a["ambiguous_order"]
}
ORDERING_CONFLICT_DETERMINISTIC = det_a == det_b

display(ordering_conflict_tests)
assert ordering_conflict_tests["passed"].all(), "Ordering conflict synthetic tests failed."
assert ORDERING_CONFLICT_DETERMINISTIC, "Ordering conflict audit is non-deterministic."

,test,passed,comparability,conflicts,tie,fallback,ambiguous
0,F01_FULLY_COMPARABLE,True,FULLY_COMPARABLE,0,False,False,False
1,F02_TIE_RESOLVED,True,PARTIALLY_COMPARABLE,0,True,False,False
2,F03_TIMESTAMP_ID_CONFLICT,True,FULLY_COMPARABLE,3,False,False,True
3,F04_TIMESTAMP_SOURCE_CONFLICT,True,FULLY_COMPARABLE,3,False,True,True
4,F05_ID_SOURCE_CONFLICT,True,NOT_COMPARABLE,2,True,False,True
5,F06_PARTIAL_TIMESTAMP,True,PARTIALLY_COMPARABLE,1,False,True,True
6,F07_NO_VALID_TIMESTAMP,True,NOT_COMPARABLE,1,False,True,True
7,F08_ALL_TIMES_TIED,True,NOT_COMPARABLE,0,True,False,False
8,F09_ID_FALLBACK,True,NOT_COMPARABLE,1,False,True,True
9,F10_SOURCE_FALLBACK,True,NOT_COMPARABLE,1,False,True,True
10,F11_ROLLOVER_FLAG,True,FULLY_COMPARABLE,0,False,False,False
11,F12_DETERMINISTIC,True,PARTIALLY_COMPARABLE,0,True,False,False

In [41]:
def derive_conflict_row(row):
    n = int(row["n_turns"]); total_pairs = int(row["id_source_pair_count"])
    comparable_pairs = int(row["source_timestamp_comparable_pairs"])
    reference = row["timestamp_reference_class"]

    if n <= 1 or comparable_pairs == 0: comparability = "NOT_COMPARABLE"
    elif reference == "TIE_FREE_FULL_REFERENCE": comparability = "FULLY_COMPARABLE"
    else: comparability = "PARTIALLY_COMPARABLE"

    timestamp_id_conflict = int(row["id_timestamp_inversions"]) > 0
    timestamp_source_conflict = int(row["source_timestamp_inversions"]) > 0
    id_source_conflict = int(row["id_source_inversions"]) > 0
    timestamp_tie = int(row["timestamp_tie_group_count"]) > 0
    selected_match = bool(row["candidate_timestamp_id_matches_source"])

    fallback_used = False
    midnight_rollover = False
    unresolved_tie = timestamp_tie and int(row["within_tie_source_id_inversions"]) > 0
    ambiguous_order = bool(timestamp_id_conflict or timestamp_source_conflict or id_source_conflict or unresolved_tie or not selected_match)

    return {
        "session_id":row["session_id"], "relative_file":row["relative_file"], "n_turns":n,
        "ordering_comparability":comparability, "comparison_row_count":n, "comparison_row_fraction":1.0,
        "total_pair_count":total_pairs, "timestamp_comparable_pairs":comparable_pairs,
        "temporal_pair_coverage":0.0 if total_pairs == 0 else comparable_pairs / total_pairs,
        "timestamp_id_conflict":timestamp_id_conflict, "timestamp_source_conflict":timestamp_source_conflict,
        "id_source_conflict":id_source_conflict, "timestamp_tie":timestamp_tie,
        "timestamp_tie_group_count":int(row["timestamp_tie_group_count"]),
        "timestamp_tie_rows":int(row["timestamp_tie_rows"]), "midnight_rollover":midnight_rollover,
        "fallback_used":fallback_used, "ambiguous_order":ambiguous_order,
        "selected_order_matches_source":selected_match,
        "conflict_count":sum([timestamp_id_conflict,timestamp_source_conflict,id_source_conflict,ambiguous_order]),
        "information_flag_count":sum([timestamp_tie,midnight_rollover,fallback_used])
    }

ordering_conflict_session_audit = pd.DataFrame([
    derive_conflict_row(row) for _,row in ordering_calibration_session_audit.iterrows()
])

comparability_summary = (
    ordering_conflict_session_audit["ordering_comparability"]
    .value_counts().reindex(["FULLY_COMPARABLE","PARTIALLY_COMPARABLE","NOT_COMPARABLE"], fill_value=0)
    .rename_axis("ordering_comparability").reset_index(name="session_count")
)

ordering_conflict_summary = pd.DataFrame({
    "item":[
        "Sessions audited","FULLY_COMPARABLE sessions","PARTIALLY_COMPARABLE sessions","NOT_COMPARABLE sessions",
        "Timestamp-tie sessions","Timestamp-ID conflict sessions","Timestamp-Source conflict sessions",
        "ID-Source conflict sessions","Fallback-used sessions","Midnight-rollover sessions",
        "Ambiguous-order sessions","Selected-order mismatch sessions","Total timestamp tie groups","Total timestamp tie rows"
    ],
    "value":[
        len(ordering_conflict_session_audit),
        int((ordering_conflict_session_audit["ordering_comparability"]=="FULLY_COMPARABLE").sum()),
        int((ordering_conflict_session_audit["ordering_comparability"]=="PARTIALLY_COMPARABLE").sum()),
        int((ordering_conflict_session_audit["ordering_comparability"]=="NOT_COMPARABLE").sum()),
        int(ordering_conflict_session_audit["timestamp_tie"].sum()),
        int(ordering_conflict_session_audit["timestamp_id_conflict"].sum()),
        int(ordering_conflict_session_audit["timestamp_source_conflict"].sum()),
        int(ordering_conflict_session_audit["id_source_conflict"].sum()),
        int(ordering_conflict_session_audit["fallback_used"].sum()),
        int(ordering_conflict_session_audit["midnight_rollover"].sum()),
        int(ordering_conflict_session_audit["ambiguous_order"].sum()),
        int((~ordering_conflict_session_audit["selected_order_matches_source"]).sum()),
        int(ordering_conflict_session_audit["timestamp_tie_group_count"].sum()),
        int(ordering_conflict_session_audit["timestamp_tie_rows"].sum())
    ]
})

display(ordering_conflict_session_audit.head(10))
display(comparability_summary)
display(ordering_conflict_summary)

,session_id,relative_file,n_turns,ordering_comparability,comparison_row_count,comparison_row_fraction,total_pair_count,timestamp_comparable_pairs,temporal_pair_coverage,timestamp_id_conflict,...,id_source_conflict,timestamp_tie,timestamp_tie_group_count,timestamp_tie_rows,midnight_rollover,fallback_used,ambiguous_order,selected_order_matches_source,conflict_count,information_flag_count
0,aaaedit,aaaedit.csv,254,PARTIALLY_COMPARABLE,254,1.0,32131,32089,0.998693,False,...,False,True,24,55,False,False,False,True,0,1
1,aaaptjd,aaaptjd.csv,360,PARTIALLY_COMPARABLE,360,1.0,64620,64605,0.999768,False,...,False,True,15,30,False,False,False,True,0,1
2,aabkeov,aabkeov.csv,281,PARTIALLY_COMPARABLE,281,1.0,39340,39330,0.999746,False,...,False,True,10,20,False,False,False,True,0,1
3,aacggvb,aacggvb.csv,235,PARTIALLY_COMPARABLE,235,1.0,27495,27455,0.998545,False,...,False,True,29,63,False,False,False,True,0,1
4,aadexbc,aadexbc.csv,104,PARTIALLY_COMPARABLE,104,1.0,5356,5354,0.999627,False,...,False,True,2,4,False,False,False,True,0,1
5,aadinwu,aadinwu.csv,233,PARTIALLY_COMPARABLE,233,1.0,27028,27004,0.999112,False,...,False,True,18,39,False,False,False,True,0,1
6,aadljmq,aadljmq.csv,372,PARTIALLY_COMPARABLE,372,1.0,69006,68984,0.999681,False,...,False,True,22,44,False,False,False,True,0,1
7,aadmino,aadmino.csv,195,PARTIALLY_COMPARABLE,195,1.0,18915,18909,0.999683,False,...,False,True,6,12,False,False,False,True,0,1
8,aadsgow,aadsgow.csv,265,PARTIALLY_COMPARABLE,265,1.0,34980,34940,0.998856,False,...,False,True,20,48,False,False,False,True,0,1
9,aadylxv,aadylxv.csv,235,PARTIALLY_COMPARABLE,235,1.0,27495,27477,0.999345,False,...,False,True,11,25,False,False,False,True,0,1

  ordering_comparability  session_count
0       FULLY_COMPARABLE             26
1   PARTIALLY_COMPARABLE          22795
2         NOT_COMPARABLE              0

                                  item   value
0                     Sessions audited   22821
1            FULLY_COMPARABLE sessions      26
2        PARTIALLY_COMPARABLE sessions   22795
3              NOT_COMPARABLE sessions       0
4               Timestamp-tie sessions   22795
5       Timestamp-ID conflict sessions       0
6   Timestamp-Source conflict sessions       0
7          ID-Source conflict sessions       0
8               Fallback-used sessions       0
9           Midnight-rollover sessions       0
10            Ambiguous-order sessions       0
11    Selected-order mismatch sessions       0
12          Total timestamp tie groups  325210
13            Total timestamp tie rows  717014

In [42]:
allowed_comparability = set(STATUS_VOCABULARIES["ordering_comparability"])

timestamp_id_conflicts = int(ordering_conflict_session_audit["timestamp_id_conflict"].sum())
timestamp_source_conflicts = int(ordering_conflict_session_audit["timestamp_source_conflict"].sum())
id_source_conflicts = int(ordering_conflict_session_audit["id_source_conflict"].sum())
fallback_sessions = int(ordering_conflict_session_audit["fallback_used"].sum())
rollover_sessions = int(ordering_conflict_session_audit["midnight_rollover"].sum())
ambiguous_sessions = int(ordering_conflict_session_audit["ambiguous_order"].sum())
tie_sessions = int(ordering_conflict_session_audit["timestamp_tie"].sum())
selected_mismatch_sessions = int((~ordering_conflict_session_audit["selected_order_matches_source"]).sum())

expected_timestamp_id_conflicts = int(ordering_calibration_session_audit["id_timestamp_inversions"].gt(0).sum())
expected_timestamp_source_conflicts = int(ordering_calibration_session_audit["source_timestamp_inversions"].gt(0).sum())
expected_id_source_conflicts = int(ordering_calibration_session_audit["id_source_inversions"].gt(0).sum())
expected_selected_mismatches = int((~ordering_calibration_session_audit["candidate_timestamp_id_matches_source"]).sum())
expected_tie_sessions = int(ordering_calibration_session_audit["timestamp_tie_group_count"].gt(0).sum())

ordering_conflict_checks = pd.DataFrame([
    check_row("Deterministic ordering policy is ready", DETERMINISTIC_ORDERING_READY, DETERMINISTIC_ORDERING_READY),
    check_row("All calibrated sessions are conflict-audited", len(ordering_conflict_session_audit) == n_sessions, f"{len(ordering_conflict_session_audit)} / {n_sessions}"),
    check_row("Comparability values belong to frozen domain", set(ordering_conflict_session_audit["ordering_comparability"]).issubset(allowed_comparability), sorted(set(ordering_conflict_session_audit["ordering_comparability"]))),
    check_row("Timestamp-ID conflicts reconcile with calibration", timestamp_id_conflicts == expected_timestamp_id_conflicts, f"audit={timestamp_id_conflicts}, calibration={expected_timestamp_id_conflicts}"),
    check_row("Timestamp-Source conflicts reconcile with calibration", timestamp_source_conflicts == expected_timestamp_source_conflicts, f"audit={timestamp_source_conflicts}, calibration={expected_timestamp_source_conflicts}"),
    check_row("ID-Source conflicts reconcile with calibration", id_source_conflicts == expected_id_source_conflicts, f"audit={id_source_conflicts}, calibration={expected_id_source_conflicts}"),
    check_row("Timestamp-tie sessions reconcile with calibration", tie_sessions == expected_tie_sessions, f"audit={tie_sessions}, calibration={expected_tie_sessions}"),
    check_row("Selected-order mismatches reconcile with calibration", selected_mismatch_sessions == expected_selected_mismatches, f"audit={selected_mismatch_sessions}, calibration={expected_selected_mismatches}"),
    check_row("Current certified corpus has no chronology conflicts", timestamp_id_conflicts + timestamp_source_conflicts + id_source_conflicts == 0, timestamp_id_conflicts + timestamp_source_conflicts + id_source_conflicts),
    check_row("Current corpus uses no fallback", fallback_sessions == 0, fallback_sessions),
    check_row("Current corpus applies no rollover", rollover_sessions == 0, rollover_sessions),
    check_row("Current corpus has no ambiguous ordering", ambiguous_sessions == 0, ambiguous_sessions),
    check_row("Current selected order matches source in every session", selected_mismatch_sessions == 0, selected_mismatch_sessions),
    check_row("Conflict audit is deterministic", ORDERING_CONFLICT_DETERMINISTIC, ORDERING_CONFLICT_DETERMINISTIC),
    check_row("All conflict synthetic tests passed", ordering_conflict_tests["passed"].all(), int((~ordering_conflict_tests["passed"]).sum()))
])

ordering_conflict_failures = ordering_conflict_checks[~ordering_conflict_checks["passed"]]
ORDERING_CONFLICT_AUDIT_READY = ordering_conflict_failures.empty

fully = int((ordering_conflict_session_audit["ordering_comparability"]=="FULLY_COMPARABLE").sum())
partially = int((ordering_conflict_session_audit["ordering_comparability"]=="PARTIALLY_COMPARABLE").sum())
not_comparable = int((ordering_conflict_session_audit["ordering_comparability"]=="NOT_COMPARABLE").sum())

ordering_conflict_final_summary = pd.DataFrame({
    "item":[
        "Conflict audit version","Sessions","FULLY_COMPARABLE","PARTIALLY_COMPARABLE","NOT_COMPARABLE",
        "Timestamp-tie sessions","Timestamp-ID conflicts","Timestamp-Source conflicts","ID-Source conflicts",
        "Fallback sessions","Rollover sessions","Ambiguous sessions","Selected-order mismatches",
        "Synthetic tests","Passed synthetic tests","ORDERING_CONFLICT_CONFIG_SHA256","ORDERING_CONFLICT_AUDIT_READY"
    ],
    "value":[
        ORDERING_CONFLICT_AUDIT_VERSION,n_sessions,fully,partially,not_comparable,tie_sessions,
        timestamp_id_conflicts,timestamp_source_conflicts,id_source_conflicts,fallback_sessions,
        rollover_sessions,ambiguous_sessions,selected_mismatch_sessions,len(ordering_conflict_tests),
        int(ordering_conflict_tests["passed"].sum()),ORDERING_CONFLICT_CONFIG_SHA256,ORDERING_CONFLICT_AUDIT_READY
    ]
})

display(ordering_conflict_checks)
display(ordering_conflict_final_summary)

assert ORDERING_CONFLICT_AUDIT_READY, (
    "Section 2.12 failed.\n\n" + ordering_conflict_failures[["check","detail"]].to_string(index=False)
)

print("\n" + "=" * 68)
print("TRACE THE ACE — ORDERING CONFLICT AUDIT READY")
print("=" * 68)
print(f"Sessions              : {n_sessions:,}")
print(f"FULLY comparable      : {fully:,}")
print(f"PARTIALLY comparable  : {partially:,}")
print(f"NOT comparable        : {not_comparable:,}")
print(f"Timestamp-tie sessions: {tie_sessions:,}")
print(f"Timestamp-ID conflicts: {timestamp_id_conflicts:,}")
print(f"Timestamp-src conflict: {timestamp_source_conflicts:,}")
print(f"ID-source conflicts   : {id_source_conflicts:,}")
print(f"Fallback sessions     : {fallback_sessions:,}")
print(f"Rollover sessions     : {rollover_sessions:,}")
print(f"Ambiguous sessions    : {ambiguous_sessions:,}")
print(f"Selected mismatches   : {selected_mismatch_sessions:,}")
print(f"CONFLICT AUDIT READY  : {ORDERING_CONFLICT_AUDIT_READY}")
print("=" * 68)

,check,passed,detail
0,Deterministic ordering policy is ready,True,True
1,All calibrated sessions are conflict-audited,True,22821 / 22821
2,Comparability values belong to frozen domain,True,"[FULLY_COMPARABLE, PARTIALLY_COMPARABLE]"
3,Timestamp-ID conflicts reconcile with calibration,True,"audit=0, calibration=0"
4,Timestamp-Source conflicts reconcile with cali...,True,"audit=0, calibration=0"
5,ID-Source conflicts reconcile with calibration,True,"audit=0, calibration=0"
6,Timestamp-tie sessions reconcile with calibration,True,"audit=22795, calibration=22795"
7,Selected-order mismatches reconcile with calib...,True,"audit=0, calibration=0"
8,Current certified corpus has no chronology con...,True,0
9,Current corpus uses no fallback,True,0
10,Current corpus applies no rollover,True,0
11,Current corpus has no ambiguous ordering,True,0
12,Current selected order matches source in every...,True,0
13,Conflict audit is deterministic,True,True
14,All conflict synthetic tests passed,True,0

,item,value
0,Conflict audit version,1.0
1,Sessions,22821
2,FULLY_COMPARABLE,26
3,PARTIALLY_COMPARABLE,22795
4,NOT_COMPARABLE,0
5,Timestamp-tie sessions,22795
6,Timestamp-ID conflicts,0
7,Timestamp-Source conflicts,0
8,ID-Source conflicts,0
9,Fallback sessions,0
10,Rollover sessions,0
11,Ambiguous sessions,0
12,Selected-order mismatches,0
13,Synthetic tests,12
14,Passed synthetic tests,12
15,ORDERING_CONFLICT_CONFIG_SHA256,695548c63ee5b3adc74c96386441cf2895e44642dc8d5c...
16,ORDERING_CONFLICT_AUDIT_READY,True

====================================================================
TRACE THE ACE — ORDERING CONFLICT AUDIT READY
====================================================================
Sessions              : 22,821
FULLY comparable      : 26
PARTIALLY comparable  : 22,795
NOT comparable        : 0
Timestamp-tie sessions: 22,795
Timestamp-ID conflicts: 0
Timestamp-src conflict: 0
ID-source conflicts   : 0
Fallback sessions     : 0
Rollover sessions     : 0
Ambiguous sessions    : 0
Selected mismatches   : 0
CONFLICT AUDIT READY  : True
====================================================================

# Section 2.13 — Physical & Logical Identity

This section separates physical source identity, exact raw evidence identity, and logical turn identity.
`source_row_uid` identifies the exact source file and zero-based data row using a machine-independent relative path.
`raw_field_hash` hashes the five exact decoded raw transcript fields without normalization.
`content_hash` records the exact raw utterance content independently of row or turn identity.
`turn_uid` identifies the logical utterance using session and parsed utterance ID when that identity is unambiguous.
Ambiguous or duplicate logical IDs use a provenance-safe fallback containing raw evidence and physical row identity.
All identity payloads use versioned canonical JSON, UTF-8, and SHA-256 rather than delimiter concatenation.
Absolute machine paths are prohibited from identity payloads.
Current corpus eligibility is established from previously exhaustive structural and ID audits.
No turn metadata or final candidate Parquet is created in this section.
The section ends with `IDENTITY_POLICY_READY`.

In [43]:
import hashlib, json
from pathlib import PurePosixPath

assert ORDERING_CONFLICT_AUDIT_READY, "Section 2.12 must pass before Section 2.13."

IDENTITY_POLICY_VERSION = "1.0"
SOURCE_ROW_UID_VERSION = "1.0"
RAW_FIELD_HASH_VERSION = "1.0"
CONTENT_HASH_VERSION = "1.0"
TURN_UID_VERSION = "1.0"
IDENTITY_HASH_ALGORITHM = "sha256"

IDENTITY_POLICY_CONFIG = {
    "version": IDENTITY_POLICY_VERSION, "algorithm": IDENTITY_HASH_ALGORITHM,
    "encoding": "utf-8", "serialization": "canonical_json",
    "json_policy": {"ensure_ascii": False, "sort_keys": True, "separators": [",", ":"], "allow_nan": False},
    "source_row_uid_version": SOURCE_ROW_UID_VERSION, "raw_field_hash_version": RAW_FIELD_HASH_VERSION,
    "content_hash_version": CONTENT_HASH_VERSION, "turn_uid_version": TURN_UID_VERSION,
    "absolute_paths_allowed": False, "clean_turn_identity": ["session_id", "utterance_id"],
    "fallback_turn_identity": ["session_id", "utterance_id_raw", "raw_field_hash", "source_row_uid"]
}

def canonical_identity_bytes(payload):
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")

def sha256_identity(domain, version, fields):
    payload = {"domain": domain, "version": version, "fields": fields}
    return hashlib.sha256(canonical_identity_bytes(payload)).hexdigest()

def normalize_identity_relative_path(relative_file):
    value = str(relative_file).replace("\\", "/")
    if value.startswith("/") or re.match(r"^[A-Za-z]:/", value): raise ValueError("Absolute paths are prohibited in identity payloads.")
    parts = PurePosixPath(value).parts
    if not parts or ".." in parts: raise ValueError("Identity path must be a safe relative path.")
    return PurePosixPath(*[p for p in parts if p not in ("", ".")]).as_posix()

def make_source_row_uid(file_sha256, source_file_relative, source_row_index):
    digest = str(file_sha256).lower()
    if not re.fullmatch(r"[0-9a-f]{64}", digest): raise ValueError("file_sha256 must be a 64-character SHA-256 hex digest.")
    if not isinstance(source_row_index, int) or source_row_index < 0: raise ValueError("source_row_index must be a non-negative integer.")
    fields = {"file_sha256": digest, "source_file_relative": normalize_identity_relative_path(source_file_relative), "source_row_index": source_row_index}
    return sha256_identity("source_row_uid", SOURCE_ROW_UID_VERSION, fields)

def make_raw_field_hash(session_id_raw, utterance_id_raw, role_raw, content_raw, timestamp_raw):
    fields = {"session_id_raw": session_id_raw, "utterance_id_raw": utterance_id_raw, "role_raw": role_raw, "content_raw": content_raw, "timestamp_raw": timestamp_raw}
    return sha256_identity("raw_field_hash", RAW_FIELD_HASH_VERSION, fields)

def make_content_hash(content_raw):
    return sha256_identity("content_hash", CONTENT_HASH_VERSION, {"content_raw": content_raw})

def make_turn_uid(session_id, utterance_id=None, clean_logical_id=True, utterance_id_raw=None, raw_field_hash=None, source_row_uid=None):
    if clean_logical_id:
        if not isinstance(session_id, str) or session_id == "" or not isinstance(utterance_id, int) or utterance_id < 0: raise ValueError("Clean turn identity requires non-empty session_id and non-negative integer utterance_id.")
        fields = {"identity_kind": "UNIQUE_LOGICAL_ID", "session_id": session_id, "utterance_id": utterance_id}
    else:
        if not isinstance(session_id, str) or session_id == "" or raw_field_hash is None or source_row_uid is None: raise ValueError("Fallback identity requires session_id, raw_field_hash, and source_row_uid.")
        fields = {"identity_kind": "AMBIGUOUS_SOURCE_ROW_FALLBACK", "session_id": session_id, "utterance_id_raw": utterance_id_raw,
                  "raw_field_hash": raw_field_hash, "source_row_uid": source_row_uid}
    return sha256_identity("turn_uid", TURN_UID_VERSION, fields)

def build_turn_identity(session_id, utterance_id, utterance_id_status, raw_row):
    source_uid = make_source_row_uid(raw_row["file_sha256"], raw_row["source_file_relative"], int(raw_row["source_row_index"]))
    raw_hash = make_raw_field_hash(raw_row["session_id_raw"], raw_row["utterance_id_raw"], raw_row["role_raw"], raw_row["content_raw"], raw_row["timestamp_raw"])
    content_hash = make_content_hash(raw_row["content_raw"]); clean = utterance_id_status == "VALID"
    turn_uid = make_turn_uid(session_id, utterance_id, True) if clean else make_turn_uid(
        session_id, clean_logical_id=False, utterance_id_raw=raw_row["utterance_id_raw"], raw_field_hash=raw_hash, source_row_uid=source_uid
    )
    return {"source_row_uid": source_uid, "raw_field_hash": raw_hash, "content_hash": content_hash, "turn_uid": turn_uid,
            "identity_mode": "CLEAN_LOGICAL_ID" if clean else "AMBIGUOUS_SOURCE_ROW_FALLBACK"}

IDENTITY_POLICY_CONFIG_SHA256 = hashlib.sha256(canonical_identity_bytes(IDENTITY_POLICY_CONFIG)).hexdigest()
HASH_RE = re.compile(r"^[0-9a-f]{64}$")

def identity_test(name, condition, detail):
    return {"test": name, "passed": bool(condition), "detail": detail}

FA, FB = "a" * 64, "b" * 64
s1 = make_source_row_uid(FA, "folder/session.csv", 5); s1_repeat = make_source_row_uid(FA, "folder/session.csv", 5)
s2 = make_source_row_uid(FA, "folder/session.csv", 6); s3 = make_source_row_uid(FA, "other/session.csv", 5)
s_windows = make_source_row_uid(FA, r"folder\session.csv", 5)
r1 = make_raw_field_hash("S1","2","student","x² ≤ ½","00:00:02")
r2 = make_raw_field_hash("S1","2","student","x² ≤ ½","00:00:02")
r_changed = make_raw_field_hash("S1","2","student","x² < ½","00:00:02")
r_empty = make_raw_field_hash("S1","2","student","","00:00:02")
r_none = make_raw_field_hash("S1","2","student",None,"00:00:02")
r_na = make_raw_field_hash("S1","2","student","NA","00:00:02")
r_missing = make_raw_field_hash("S1","2","student",None,"00:00:02")
t1 = make_turn_uid("S1", 2); t1_repeat = make_turn_uid("S1", 2)
t_other_session = make_turn_uid("S2", 2); t_other_id = make_turn_uid("S1", 3)
c_before, c_after = make_content_hash("4"), make_content_hash("5")
r_before = make_raw_field_hash("S1","2","student","4","00:00:02")
r_after = make_raw_field_hash("S1","2","student","5","00:00:02")
tf1 = make_turn_uid("S1", clean_logical_id=False, utterance_id_raw="5", raw_field_hash=r1, source_row_uid=s1)
tf2 = make_turn_uid("S1", clean_logical_id=False, utterance_id_raw="5", raw_field_hash=r1, source_row_uid=s2)

identity_tests = pd.DataFrame([
    identity_test("H01_SOURCE_REPEAT", s1 == s1_repeat, s1),
    identity_test("H02_SOURCE_ROW_DIFF", s1 != s2, f"{s1[:12]} != {s2[:12]}"),
    identity_test("H03_SOURCE_FILE_DIFF", s1 != s3, f"{s1[:12]} != {s3[:12]}"),
    identity_test("H04_PATH_SEPARATOR_INDEPENDENT", s1 == s_windows, s_windows),
    identity_test("H05_RAW_FIELDS_REPEAT", r1 == r2, r1),
    identity_test("H06_RAW_FIELD_CHANGE", r1 != r_changed, f"{r1[:12]} != {r_changed[:12]}"),
    identity_test("H07_EMPTY_NOT_NULL", r_empty != r_none, f"{r_empty[:12]} != {r_none[:12]}"),
    identity_test("H08_LITERAL_NA_NOT_NULL", r_na != r_missing, f"{r_na[:12]} != {r_missing[:12]}"),
    identity_test("H09_MATH_UNICODE_DETERMINISTIC", r1 == make_raw_field_hash("S1","2","student","x² ≤ ½","00:00:02"), r1),
    identity_test("H10_CLEAN_TURN_REPEAT", t1 == t1_repeat, t1),
    identity_test("H11_SESSION_CHANGES_TURN", t1 != t_other_session, f"{t1[:12]} != {t_other_session[:12]}"),
    identity_test("H12_ID_CHANGES_TURN", t1 != t_other_id, f"{t1[:12]} != {t_other_id[:12]}"),
    identity_test("H13_FALLBACK_PHYSICAL_ROWS_DIFFER", tf1 != tf2, f"{tf1[:12]} != {tf2[:12]}"),
    identity_test("H14_ALL_HASHES_SHA256", all(HASH_RE.fullmatch(x) for x in [s1,r1,t1,c_before,tf1]), "64-char lowercase hex"),
    identity_test("H15_CONTENT_CHANGE_PRESERVES_CLEAN_TURN", t1 == make_turn_uid("S1",2) and c_before != c_after and r_before != r_after,
                  "turn_uid=same; content_hash/raw_field_hash=changed")
])

display(identity_tests)
assert identity_tests["passed"].all(), "Identity-policy synthetic tests failed."

,test,passed,detail
0,H01_SOURCE_REPEAT,True,c04210c83f418e93c65346fecf67627d628ec1940de6ee...
1,H02_SOURCE_ROW_DIFF,True,c04210c83f41 != 07cf8c57eb72
2,H03_SOURCE_FILE_DIFF,True,c04210c83f41 != 27475ff3898b
3,H04_PATH_SEPARATOR_INDEPENDENT,True,c04210c83f418e93c65346fecf67627d628ec1940de6ee...
4,H05_RAW_FIELDS_REPEAT,True,012e41ad5a9e0a2edacd0a916dd7e2efe997f9ff3ae630...
5,H06_RAW_FIELD_CHANGE,True,012e41ad5a9e != 68971003fcc3
6,H07_EMPTY_NOT_NULL,True,dfa39b8396d5 != e55fa87997ab
7,H08_LITERAL_NA_NOT_NULL,True,de1b2cf8f46c != e55fa87997ab
8,H09_MATH_UNICODE_DETERMINISTIC,True,012e41ad5a9e0a2edacd0a916dd7e2efe997f9ff3ae630...
9,H10_CLEAN_TURN_REPEAT,True,b6054127cd055c564a05d300ef721589d79833534238a5...
10,H11_SESSION_CHANGES_TURN,True,b6054127cd05 != 6bd9b87abd00
11,H12_ID_CHANGES_TURN,True,b6054127cd05 != 13d150de63e7
12,H13_FALLBACK_PHYSICAL_ROWS_DIFFER,True,67f0591dea1e != f400007edf1b
13,H14_ALL_HASHES_SHA256,True,64-char lowercase hex
14,H15_CONTENT_CHANGE_PRESERVES_CLEAN_TURN,True,turn_uid=same; content_hash/raw_field_hash=cha...

In [44]:
def choose_identity_smoke_files(audit):
    selected = set()
    selected.add(audit.sort_values("relative_file").iloc[0]["relative_file"])
    selected.add(audit.loc[audit["n_turns"].idxmin(), "relative_file"])
    selected.add(audit.loc[audit["n_turns"].idxmax(), "relative_file"])
    selected.add(audit.loc[audit["max_tie_group_size"].idxmax(), "relative_file"])
    partial = audit[audit["timestamp_reference_class"] == "PARTIAL_TEMPORAL_REFERENCE"].sort_values("relative_file")
    if not partial.empty: selected.add(partial.iloc[len(partial)//2]["relative_file"])
    return sorted(selected)

def audit_real_identity(relative_file):
    path = TRANSCRIPT_ROOT / Path(relative_file); session_id = Path(relative_file).stem
    reconstructed = reconstruct_raw_file(path, expected_session_id=session_id); raw_rows = reconstructed["raw_table"].to_pylist()
    raw_ids = [row["utterance_id_raw"] for row in raw_rows]; id_rows = annotate_session_ids(raw_ids)["rows"]

    identities_a, identities_b = [], []
    for raw_row, id_row in zip(raw_rows, id_rows):
        identities_a.append(build_turn_identity(session_id, id_row["utterance_id"], id_row["utterance_id_status"], raw_row))
        identities_b.append(build_turn_identity(session_id, id_row["utterance_id"], id_row["utterance_id_status"], raw_row))

    source_uids = [x["source_row_uid"] for x in identities_a]; turn_uids = [x["turn_uid"] for x in identities_a]
    raw_hashes = [x["raw_field_hash"] for x in identities_a]; content_hashes = [x["content_hash"] for x in identities_a]
    all_hashes = source_uids + turn_uids + raw_hashes + content_hashes

    return {
        "relative_file": relative_file, "rows": len(raw_rows), "unique_source_row_uids": len(set(source_uids)),
        "unique_turn_uids": len(set(turn_uids)), "clean_identity_rows": sum(x["identity_mode"]=="CLEAN_LOGICAL_ID" for x in identities_a),
        "fallback_identity_rows": sum(x["identity_mode"]!="CLEAN_LOGICAL_ID" for x in identities_a),
        "all_hashes_valid": all(HASH_RE.fullmatch(x) for x in all_hashes),
        "source_uid_unique": len(set(source_uids)) == len(raw_rows), "turn_uid_unique": len(set(turn_uids)) == len(raw_rows),
        "repeat_run_exact": identities_a == identities_b,
        "raw_rows_unchanged": raw_rows == reconstructed["raw_table"].to_pylist()
    }

REAL_IDENTITY_FILES = choose_identity_smoke_files(ordering_calibration_session_audit)
identity_real_smoke_audit = pd.DataFrame([audit_real_identity(f) for f in REAL_IDENTITY_FILES])
identity_real_smoke_audit["passed"] = (
    identity_real_smoke_audit["source_uid_unique"] & identity_real_smoke_audit["turn_uid_unique"] &
    identity_real_smoke_audit["all_hashes_valid"] & identity_real_smoke_audit["repeat_run_exact"] &
    identity_real_smoke_audit["raw_rows_unchanged"] & identity_real_smoke_audit["fallback_identity_rows"].eq(0)
)

display(identity_real_smoke_audit)
assert identity_real_smoke_audit["passed"].all(), "Real-source identity smoke audit failed."

,relative_file,rows,unique_source_row_uids,unique_turn_uids,clean_identity_rows,fallback_identity_rows,all_hashes_valid,source_uid_unique,turn_uid_unique,repeat_run_exact,raw_rows_unchanged,passed
0,aaaedit.csv,254,254,254,254,0,True,True,True,True,True,True
1,bvnewyc.csv,622,622,622,622,0,True,True,True,True,True,True
2,gzuoxmy.csv,309,309,309,309,0,True,True,True,True,True,True
3,jlntsbf.csv,15,15,15,15,0,True,True,True,True,True,True
4,mvkburc.csv,582,582,582,582,0,True,True,True,True,True,True

In [45]:
synthetic_failures = int((~identity_tests["passed"]).sum())
real_failures = int((~identity_real_smoke_audit["passed"]).sum())

id_missing_rows = int(id_corpus["missing_rows"])
id_unparseable_rows = int(id_corpus["unparseable_rows"])
id_duplicate_rows = int(id_corpus["duplicate_raw_id_rows"])
id_collision_rows = int(id_corpus["natural_key_collision_rows"])

CURRENT_CORPUS_CLEAN_TURN_UID_ELIGIBLE = all([
    RAW_STRUCTURAL_AUDIT_READY, UTTERANCE_ID_PARSER_READY, ORDERING_CONFLICT_AUDIT_READY,
    id_missing_rows == 0, id_unparseable_rows == 0, id_duplicate_rows == 0, id_collision_rows == 0
])

EXPECTED_CLEAN_IDENTITY_ROWS = TOTAL_RAW_ROWS if CURRENT_CORPUS_CLEAN_TURN_UID_ELIGIBLE else None
EXPECTED_FALLBACK_IDENTITY_ROWS = 0 if CURRENT_CORPUS_CLEAN_TURN_UID_ELIGIBLE else None

identity_policy_checks = pd.DataFrame([
    check_row("Ordering conflict audit is ready", ORDERING_CONFLICT_AUDIT_READY, ORDERING_CONFLICT_AUDIT_READY),
    check_row("Identity algorithm is SHA-256", IDENTITY_HASH_ALGORITHM == "sha256", IDENTITY_HASH_ALGORITHM),
    check_row("Canonical JSON serialization is deterministic",
              canonical_identity_bytes({"b":"x","a":1}) == canonical_identity_bytes({"a":1,"b":"x"}), canonical_identity_bytes({"a":1,"b":"x"}).decode()),
    check_row("Absolute paths are prohibited", not IDENTITY_POLICY_CONFIG["absolute_paths_allowed"], IDENTITY_POLICY_CONFIG["absolute_paths_allowed"]),
    check_row("Current corpus has no missing utterance IDs", id_missing_rows == 0, id_missing_rows),
    check_row("Current corpus has no unparseable utterance IDs", id_unparseable_rows == 0, id_unparseable_rows),
    check_row("Current corpus has no duplicate utterance IDs", id_duplicate_rows == 0, id_duplicate_rows),
    check_row("Current corpus has no natural-key collisions", id_collision_rows == 0, id_collision_rows),
    check_row("Current corpus is eligible for clean logical turn identity", CURRENT_CORPUS_CLEAN_TURN_UID_ELIGIBLE, CURRENT_CORPUS_CLEAN_TURN_UID_ELIGIBLE),
    check_row("All synthetic identity tests passed", synthetic_failures == 0, synthetic_failures),
    check_row("All real identity smoke tests passed", real_failures == 0, real_failures),
    check_row("Identity configuration hash is valid SHA-256", bool(HASH_RE.fullmatch(IDENTITY_POLICY_CONFIG_SHA256)), IDENTITY_POLICY_CONFIG_SHA256)
])

identity_policy_failures = identity_policy_checks[~identity_policy_checks["passed"]]
IDENTITY_POLICY_READY = identity_policy_failures.empty

identity_policy_summary = pd.DataFrame({
    "item": [
        "Identity policy version", "Hash algorithm", "Source-row UID version", "Raw-field hash version",
        "Content hash version", "Turn UID version", "Current clean-ID eligible",
        "Expected clean identity rows", "Expected fallback identity rows", "Synthetic tests",
        "Passed synthetic tests", "Real smoke files", "Real smoke failures",
        "Absolute paths allowed", "IDENTITY_POLICY_CONFIG_SHA256", "IDENTITY_POLICY_READY"
    ],
    "value": [
        IDENTITY_POLICY_VERSION, "SHA256", SOURCE_ROW_UID_VERSION, RAW_FIELD_HASH_VERSION,
        CONTENT_HASH_VERSION, TURN_UID_VERSION, CURRENT_CORPUS_CLEAN_TURN_UID_ELIGIBLE,
        EXPECTED_CLEAN_IDENTITY_ROWS, EXPECTED_FALLBACK_IDENTITY_ROWS, len(identity_tests),
        int(identity_tests["passed"].sum()), len(identity_real_smoke_audit), real_failures,
        False, IDENTITY_POLICY_CONFIG_SHA256, IDENTITY_POLICY_READY
    ]
})

display(identity_policy_checks)
display(identity_policy_summary)

assert IDENTITY_POLICY_READY, (
    "Section 2.13 failed.\n\n" + identity_policy_failures[["check","detail"]].to_string(index=False)
)

print("\n" + "=" * 66)
print("TRACE THE ACE — PHYSICAL & LOGICAL IDENTITY READY")
print("=" * 66)
print(f"Hash algorithm        : SHA256")
print(f"Clean-ID eligible     : {CURRENT_CORPUS_CLEAN_TURN_UID_ELIGIBLE}")
print(f"Expected clean rows   : {EXPECTED_CLEAN_IDENTITY_ROWS:,}")
print(f"Expected fallback rows: {EXPECTED_FALLBACK_IDENTITY_ROWS:,}")
print(f"Synthetic tests       : {int(identity_tests['passed'].sum())}/{len(identity_tests)}")
print(f"Real smoke tests      : {len(identity_real_smoke_audit)-real_failures}/{len(identity_real_smoke_audit)}")
print(f"Absolute path used    : False")
print(f"IDENTITY READY        : {IDENTITY_POLICY_READY}")
print("=" * 66)

,check,passed,detail
0,Ordering conflict audit is ready,True,True
1,Identity algorithm is SHA-256,True,sha256
2,Canonical JSON serialization is deterministic,True,"{""a"":1,""b"":""x""}"
3,Absolute paths are prohibited,True,False
4,Current corpus has no missing utterance IDs,True,0
5,Current corpus has no unparseable utterance IDs,True,0
6,Current corpus has no duplicate utterance IDs,True,0
7,Current corpus has no natural-key collisions,True,0
8,Current corpus is eligible for clean logical t...,True,True
9,All synthetic identity tests passed,True,0
10,All real identity smoke tests passed,True,0
11,Identity configuration hash is valid SHA-256,True,61c44dc910943e78ea697187554120ce58c0ab5b7ccbda...

,item,value
0,Identity policy version,1.0
1,Hash algorithm,SHA256
2,Source-row UID version,1.0
3,Raw-field hash version,1.0
4,Content hash version,1.0
5,Turn UID version,1.0
6,Current clean-ID eligible,True
7,Expected clean identity rows,6139854
8,Expected fallback identity rows,0
9,Synthetic tests,15
10,Passed synthetic tests,15
11,Real smoke files,5
12,Real smoke failures,0
13,Absolute paths allowed,False
14,IDENTITY_POLICY_CONFIG_SHA256,61c44dc910943e78ea697187554120ce58c0ab5b7ccbda...
15,IDENTITY_POLICY_READY,True

==================================================================
TRACE THE ACE — PHYSICAL & LOGICAL IDENTITY READY
==================================================================
Hash algorithm        : SHA256
Clean-ID eligible     : True
Expected clean rows   : 6,139,854
Expected fallback rows: 0
Synthetic tests       : 15/15
Real smoke tests      : 5/5
Absolute path used    : False
IDENTITY READY        : True
==================================================================

# Section 2.14 — Structural Turn Metadata

This section derives deterministic structural metadata only after the final session ordering policy has been applied.
`turn_index` is the zero-based reconstructed conversation position and is distinct from physical `source_row_index`.
Relative turn position, role-specific turn index, adjacent roles, and speaker switches are derived from ordered roles.
Temporal gaps and elapsed time are trusted only for `TIMESTAMP_PRIMARY` sessions.
Equal timestamps produce valid zero-second gaps and are not treated as errors.
Fallback-ordered sessions do not receive fabricated temporal-gap metadata.
First and last turn flags must occur exactly once per non-empty session.
Role-specific indices must remain contiguous independently for every canonical role.
No transcript semantics, objective information, labels, or model features are used.
Full 6.14M-row metadata generation remains deferred to the production parser pass.
The section ends with `STRUCTURAL_METADATA_READY`.

In [46]:
assert IDENTITY_POLICY_READY, "Section 2.13 must pass before Section 2.14."

STRUCTURAL_METADATA_VERSION = "1.0"
ALLOWED_ROLES = set(STATUS_VOCABULARIES["canonical_role"])
ALLOWED_ORDERING_METHODS = set(STATUS_VOCABULARIES["ordering_method"])
ALLOWED_ORDERING_CONFIDENCE = set(STATUS_VOCABULARIES["ordering_confidence"])
ALLOWED_COMPARABILITY = set(STATUS_VOCABULARIES["ordering_comparability"])
ALLOWED_DURATION_STATUS = set(STATUS_VOCABULARIES["duration_status"])

required_duration_states = {"COMPLETE","PARTIAL_TIMESTAMP","UNRELIABLE_ORDER","UNAVAILABLE"}
assert required_duration_states.issubset(ALLOWED_DURATION_STATUS), f"Frozen duration-status vocabulary mismatch: {sorted(ALLOWED_DURATION_STATUS)}"

STRUCTURAL_METADATA_CONFIG = {
    "version": STRUCTURAL_METADATA_VERSION, "turn_index_base": 0,
    "relative_position_formula": "turn_index/(n_turns-1)", "single_turn_relative_position": 0.0,
    "role_turn_index_base": 0, "first_previous_role": None, "last_next_role": None,
    "first_turn_switch_flag": False, "temporal_metadata_requires_timestamp_primary": True,
    "zero_timestamp_gap_allowed": True, "negative_timestamp_gap_allowed": False,
    "full_corpus_application": "DEFER_TO_2.16", "label_blind": True
}
STRUCTURAL_METADATA_CONFIG_SHA256 = canonical_json_hash(STRUCTURAL_METADATA_CONFIG)

def build_structural_metadata(roles, timestamp_order_values, ordering_method, ordering_confidence, ordering_issue_flag,
                              ordering_comparability, timestamp_day_offsets=None, timestamp_rollover_flags=None):
    n = len(roles)
    if n == 0 or len(timestamp_order_values) != n: raise ValueError("Structural metadata requires a non-empty session with aligned vectors.")
    if ordering_method not in ALLOWED_ORDERING_METHODS or ordering_confidence not in ALLOWED_ORDERING_CONFIDENCE: raise ValueError("Ordering metadata is outside the frozen domain.")
    if ordering_comparability not in ALLOWED_COMPARABILITY or any(role not in ALLOWED_ROLES for role in roles): raise ValueError("Role/comparability value is outside the frozen domain.")

    timestamp_day_offsets = [0 if x is not None else None for x in timestamp_order_values] if timestamp_day_offsets is None else list(timestamp_day_offsets)
    timestamp_rollover_flags = [False] * n if timestamp_rollover_flags is None else list(timestamp_rollover_flags)
    if len(timestamp_day_offsets) != n or len(timestamp_rollover_flags) != n: raise ValueError("Timestamp structural vectors must have equal length.")

    role_counts = Counter(); rows = []; temporal_trusted = ordering_method == "TIMESTAMP_PRIMARY" and not ordering_issue_flag
    session_start = timestamp_order_values[0] if temporal_trusted else None

    for i, role in enumerate(roles):
        role_index = role_counts[role]; role_counts[role] += 1
        previous_role = roles[i - 1] if i > 0 else None; next_role = roles[i + 1] if i < n - 1 else None
        relative_position = 0.0 if n == 1 else i / (n - 1)

        gap = elapsed = None
        if temporal_trusted and timestamp_order_values[i] is not None:
            if session_start is not None:
                elapsed = timestamp_order_values[i] - session_start
                if elapsed < 0: raise ValueError("Negative elapsed time detected after timestamp-primary ordering.")
            if i > 0 and timestamp_order_values[i - 1] is not None:
                gap = timestamp_order_values[i] - timestamp_order_values[i - 1]
                if gap < 0: raise ValueError("Negative temporal gap detected after timestamp-primary ordering.")

        rows.append({
            "turn_index": i, "relative_turn_position": relative_position, "role_turn_index": role_index,
            "previous_role": previous_role, "next_role": next_role, "speaker_switch_flag": False if i == 0 else role != previous_role,
            "time_since_previous_turn": gap, "elapsed_from_session_start": elapsed,
            "first_turn_flag": i == 0, "last_turn_flag": i == n - 1,
            "timestamp_order_value": timestamp_order_values[i], "timestamp_day_offset": timestamp_day_offsets[i],
            "timestamp_rollover_flag": bool(timestamp_rollover_flags[i]), "ordering_method": ordering_method,
            "ordering_confidence": ordering_confidence, "ordering_issue_flag": bool(ordering_issue_flag),
            "ordering_comparability": ordering_comparability
        })
    return rows

def summarize_structural_session(rows):
    if not rows: raise ValueError("Session summary requires at least one turn.")
    roles = [row["role"] for row in rows] if "role" in rows[0] else None
    timestamps = [row["timestamp_order_value"] for row in rows]; valid_times = [x for x in timestamps if x is not None]
    method = rows[0]["ordering_method"]; issue = bool(rows[0]["ordering_issue_flag"])

    if issue or method != "TIMESTAMP_PRIMARY": duration_status, duration_seconds = "UNRELIABLE_ORDER", None
    elif len(valid_times) == len(rows):
        duration_status = "COMPLETE"; duration_seconds = timestamps[-1] - timestamps[0]
    elif valid_times: duration_status, duration_seconds = "PARTIAL_TIMESTAMP", None
    else: duration_status, duration_seconds = "UNAVAILABLE", None

    role_counter = Counter(roles) if roles is not None else Counter()
    return {
        "n_turns": len(rows), "n_student_turns": role_counter["student"], "n_tutor_turns": role_counter["tutor"],
        "n_background_turns": role_counter["background"], "n_unknown_roles": role_counter["unknown"],
        "first_valid_timestamp": next((x for x in timestamps if x is not None), None),
        "last_valid_timestamp": next((x for x in reversed(timestamps) if x is not None), None),
        "duration_seconds": duration_seconds, "duration_status": duration_status,
        "speaker_switch_count": sum(row["speaker_switch_flag"] for row in rows)
    }

def attach_roles(metadata_rows, roles):
    return [{**row, "role": role} for row, role in zip(metadata_rows, roles)]

def metadata_test(name, condition, detail):
    return {"test": name, "passed": bool(condition), "detail": detail}

m01 = attach_roles(build_structural_metadata(["tutor","student","tutor"], [0,1,2], "TIMESTAMP_PRIMARY","HIGH",False,"FULLY_COMPARABLE"), ["tutor","student","tutor"])
m02 = attach_roles(build_structural_metadata(["student"], [0], "TIMESTAMP_PRIMARY","HIGH",False,"FULLY_COMPARABLE"), ["student"])
m03 = attach_roles(build_structural_metadata(["tutor","tutor","tutor"], [0,1,2], "TIMESTAMP_PRIMARY","HIGH",False,"FULLY_COMPARABLE"), ["tutor"]*3)
m04 = attach_roles(build_structural_metadata(["tutor","student","tutor","student"], [0,1,2,3], "TIMESTAMP_PRIMARY","HIGH",False,"FULLY_COMPARABLE"), ["tutor","student","tutor","student"])
m05 = attach_roles(build_structural_metadata(["background","student"], [0,1], "TIMESTAMP_PRIMARY","HIGH",False,"FULLY_COMPARABLE"), ["background","student"])
m06 = attach_roles(build_structural_metadata(["unknown","tutor"], [0,1], "TIMESTAMP_PRIMARY","HIGH",False,"FULLY_COMPARABLE"), ["unknown","tutor"])
m07 = attach_roles(build_structural_metadata(["tutor","student","student"], [0,0,2], "TIMESTAMP_PRIMARY","HIGH",False,"PARTIALLY_COMPARABLE"), ["tutor","student","student"])
m15 = attach_roles(build_structural_metadata(["tutor","student","tutor"], [0,None,2], "UTTERANCE_ID_FALLBACK","MEDIUM",True,"PARTIALLY_COMPARABLE"), ["tutor","student","tutor"])

negative_gap_rejected = False
try: build_structural_metadata(["tutor","student"], [5,3], "TIMESTAMP_PRIMARY","HIGH",False,"FULLY_COMPARABLE")
except ValueError: negative_gap_rejected = True

repeat_a = build_structural_metadata(["tutor","student","student"], [0,0,2], "TIMESTAMP_PRIMARY","HIGH",False,"PARTIALLY_COMPARABLE")
repeat_b = build_structural_metadata(["tutor","student","student"], [0,0,2], "TIMESTAMP_PRIMARY","HIGH",False,"PARTIALLY_COMPARABLE")

structural_metadata_tests = pd.DataFrame([
    metadata_test("M01_NORMAL_SEQUENCE", [x["turn_index"] for x in m01] == [0,1,2], [x["turn_index"] for x in m01]),
    metadata_test("M02_SINGLE_TURN", m02[0]["relative_turn_position"] == 0.0 and m02[0]["first_turn_flag"] and m02[0]["last_turn_flag"], m02[0]),
    metadata_test("M03_SAME_ROLE", [x["speaker_switch_flag"] for x in m03] == [False,False,False], [x["speaker_switch_flag"] for x in m03]),
    metadata_test("M04_ALTERNATING_ROLES", [x["speaker_switch_flag"] for x in m04] == [False,True,True,True], [x["speaker_switch_flag"] for x in m04]),
    metadata_test("M05_BACKGROUND_ROLE", [x["role_turn_index"] for x in m05] == [0,0], [x["role_turn_index"] for x in m05]),
    metadata_test("M06_UNKNOWN_ROLE", m06[0]["role_turn_index"] == 0, m06[0]),
    metadata_test("M07_ZERO_TIME_GAP", m07[1]["time_since_previous_turn"] == 0, m07[1]),
    metadata_test("M08_POSITIVE_GAPS", [x["time_since_previous_turn"] for x in m01] == [None,1,1], [x["time_since_previous_turn"] for x in m01]),
    metadata_test("M09_RELATIVE_POSITION", [x["relative_turn_position"] for x in m01] == [0.0,0.5,1.0], [x["relative_turn_position"] for x in m01]),
    metadata_test("M10_ROLE_INDICES", [x["role_turn_index"] for x in m04] == [0,0,1,1], [x["role_turn_index"] for x in m04]),
    metadata_test("M11_ADJACENCY", m01[1]["previous_role"]=="tutor" and m01[1]["next_role"]=="tutor", m01[1]),
    metadata_test("M12_FIRST_LAST_COUNTS", sum(x["first_turn_flag"] for x in m04)==1 and sum(x["last_turn_flag"] for x in m04)==1, "1 first / 1 last"),
    metadata_test("M13_NEGATIVE_GAP_REJECTED", negative_gap_rejected, negative_gap_rejected),
    metadata_test("M14_DETERMINISTIC", repeat_a == repeat_b, repeat_a),
    metadata_test("M15_FALLBACK_NO_TEMPORAL_METADATA", all(x["time_since_previous_turn"] is None and x["elapsed_from_session_start"] is None for x in m15), "temporal metadata suppressed")
])

display(structural_metadata_tests)
assert structural_metadata_tests["passed"].all(), "Structural metadata synthetic tests failed."

,test,passed,detail
0,M01_NORMAL_SEQUENCE,True,"[0, 1, 2]"
1,M02_SINGLE_TURN,True,"{'turn_index': 0, 'relative_turn_position': 0...."
2,M03_SAME_ROLE,True,"[False, False, False]"
3,M04_ALTERNATING_ROLES,True,"[False, True, True, True]"
4,M05_BACKGROUND_ROLE,True,"[0, 0]"
5,M06_UNKNOWN_ROLE,True,"{'turn_index': 0, 'relative_turn_position': 0...."
6,M07_ZERO_TIME_GAP,True,"{'turn_index': 1, 'relative_turn_position': 0...."
7,M08_POSITIVE_GAPS,True,"[None, 1, 1]"
8,M09_RELATIVE_POSITION,True,"[0.0, 0.5, 1.0]"
9,M10_ROLE_INDICES,True,"[0, 0, 1, 1]"
10,M11_ADJACENCY,True,"{'turn_index': 1, 'relative_turn_position': 0...."
11,M12_FIRST_LAST_COUNTS,True,1 first / 1 last
12,M13_NEGATIVE_GAP_REJECTED,True,True
13,M14_DETERMINISTIC,True,"[{'turn_index': 0, 'relative_turn_position': 0..."
14,M15_FALLBACK_NO_TEMPORAL_METADATA,True,temporal metadata suppressed

In [47]:
def choose_structural_smoke_files(audit):
    selected = {
        audit.sort_values("relative_file").iloc[0]["relative_file"],
        audit.loc[audit["n_turns"].idxmin(), "relative_file"],
        audit.loc[audit["n_turns"].idxmax(), "relative_file"],
        audit.loc[audit["max_tie_group_size"].idxmax(), "relative_file"]
    }
    tie_free = audit[audit["timestamp_reference_class"]=="TIE_FREE_FULL_REFERENCE"].sort_values("relative_file")
    if not tie_free.empty: selected.add(tie_free.iloc[0]["relative_file"])
    return sorted(selected)

comparability_lookup = ordering_conflict_session_audit.set_index("relative_file")["ordering_comparability"].to_dict()

def audit_real_structural_metadata(relative_file):
    path = TRANSCRIPT_ROOT / Path(relative_file); session_id = Path(relative_file).stem
    reconstructed = reconstruct_raw_file(path, expected_session_id=session_id); table = reconstructed["raw_table"]
    raw_ids = table.column("utterance_id_raw").to_pylist(); raw_times = table.column("timestamp_raw").to_pylist()
    raw_roles = table.column("role_raw").to_pylist(); source_indices = [int(x) for x in table.column("source_row_index").to_pylist()]

    id_rows = annotate_session_ids(raw_ids)["rows"]; parsed_ids = [x["utterance_id"] for x in id_rows]
    roles = [canonicalize_role(x)["role"] for x in raw_roles]
    order = order_session_rows(raw_ids, raw_times, source_indices, relative_file); positions = order["ordered_positions"]

    ordered_roles = [roles[i] for i in positions]; ordered_times = [order["timestamp_order_value"][i] for i in positions]
    ordered_offsets = [order["timestamp_day_offset"][i] for i in positions]; ordered_rollovers = [order["timestamp_rollover_flag"][i] for i in positions]
    comparability = comparability_lookup[relative_file]

    metadata = build_structural_metadata(
        ordered_roles, ordered_times, order["ordering_method"], order["ordering_confidence"],
        order["ordering_issue_flag"], comparability, ordered_offsets, ordered_rollovers
    )
    metadata = attach_roles(metadata, ordered_roles); summary = summarize_structural_session(metadata)

    n = len(metadata); role_index_ok = True
    for role in set(ordered_roles):
        values = [row["role_turn_index"] for row in metadata if row["role"]==role]
        role_index_ok &= values == list(range(len(values)))

    adjacency_ok = all(
        row["previous_role"] == (ordered_roles[i-1] if i>0 else None) and
        row["next_role"] == (ordered_roles[i+1] if i<n-1 else None)
        for i,row in enumerate(metadata)
    )
    gaps = [row["time_since_previous_turn"] for row in metadata if row["time_since_previous_turn"] is not None]
    elapsed = [row["elapsed_from_session_start"] for row in metadata if row["elapsed_from_session_start"] is not None]

    return {
        "relative_file": relative_file, "rows": n, "ordering_method": order["ordering_method"],
        "ordering_confidence": order["ordering_confidence"], "comparability": comparability,
        "turn_index_contiguous": [x["turn_index"] for x in metadata] == list(range(n)),
        "relative_position_valid": all(0.0 <= x["relative_turn_position"] <= 1.0 for x in metadata),
        "role_index_contiguous": role_index_ok, "adjacency_valid": adjacency_ok,
        "temporal_gaps_nonnegative": all(x >= 0 for x in gaps),
        "elapsed_nondecreasing": all(elapsed[i] <= elapsed[i+1] for i in range(len(elapsed)-1)),
        "first_flag_count": sum(x["first_turn_flag"] for x in metadata),
        "last_flag_count": sum(x["last_turn_flag"] for x in metadata),
        "role_count_matches": summary["n_student_turns"] + summary["n_tutor_turns"] + summary["n_background_turns"] + summary["n_unknown_roles"] == n,
        "duration_status": summary["duration_status"], "duration_seconds": summary["duration_seconds"]
    }

REAL_STRUCTURAL_FILES = choose_structural_smoke_files(ordering_calibration_session_audit)
structural_metadata_real_smoke_audit = pd.DataFrame([audit_real_structural_metadata(f) for f in REAL_STRUCTURAL_FILES])

structural_metadata_real_smoke_audit["passed"] = (
    structural_metadata_real_smoke_audit["ordering_method"].eq("TIMESTAMP_PRIMARY") &
    structural_metadata_real_smoke_audit["ordering_confidence"].eq("HIGH") &
    structural_metadata_real_smoke_audit["turn_index_contiguous"] &
    structural_metadata_real_smoke_audit["relative_position_valid"] &
    structural_metadata_real_smoke_audit["role_index_contiguous"] &
    structural_metadata_real_smoke_audit["adjacency_valid"] &
    structural_metadata_real_smoke_audit["temporal_gaps_nonnegative"] &
    structural_metadata_real_smoke_audit["elapsed_nondecreasing"] &
    structural_metadata_real_smoke_audit["first_flag_count"].eq(1) &
    structural_metadata_real_smoke_audit["last_flag_count"].eq(1) &
    structural_metadata_real_smoke_audit["role_count_matches"] &
    structural_metadata_real_smoke_audit["duration_status"].eq("COMPLETE")
)

display(structural_metadata_real_smoke_audit)
assert structural_metadata_real_smoke_audit["passed"].all(), "Real structural-metadata smoke audit failed."

,relative_file,rows,ordering_method,ordering_confidence,comparability,turn_index_contiguous,relative_position_valid,role_index_contiguous,adjacency_valid,temporal_gaps_nonnegative,elapsed_nondecreasing,first_flag_count,last_flag_count,role_count_matches,duration_status,duration_seconds,passed
0,aaaedit.csv,254,TIMESTAMP_PRIMARY,HIGH,PARTIALLY_COMPARABLE,True,True,True,True,True,True,1,1,True,COMPLETE,2629,True
1,aayjyjr.csv,76,TIMESTAMP_PRIMARY,HIGH,FULLY_COMPARABLE,True,True,True,True,True,True,1,1,True,COMPLETE,2318,True
2,bvnewyc.csv,622,TIMESTAMP_PRIMARY,HIGH,PARTIALLY_COMPARABLE,True,True,True,True,True,True,1,1,True,COMPLETE,2890,True
3,jlntsbf.csv,15,TIMESTAMP_PRIMARY,HIGH,FULLY_COMPARABLE,True,True,True,True,True,True,1,1,True,COMPLETE,526,True
4,mvkburc.csv,582,TIMESTAMP_PRIMARY,HIGH,PARTIALLY_COMPARABLE,True,True,True,True,True,True,1,1,True,COMPLETE,2699,True

In [48]:
synthetic_failures = int((~structural_metadata_tests["passed"]).sum())
real_failures = int((~structural_metadata_real_smoke_audit["passed"]).sum())

current_role_issue_rows = int(role_mapping_table.loc[role_mapping_table["role_issue_flag"], "row_count"].sum())
current_timestamp_invalid_rows = int(timestamp_corpus["missing_rows"] + timestamp_corpus["unparseable_rows"] + timestamp_corpus["out_of_range_rows"])
current_order_ambiguous_sessions = int(ordering_conflict_session_audit["ambiguous_order"].sum())
current_fallback_sessions = int(ordering_conflict_session_audit["fallback_used"].sum())
current_rollover_sessions = int(ordering_conflict_session_audit["midnight_rollover"].sum())

CURRENT_CORPUS_STRUCTURAL_METADATA_ELIGIBLE = all([
    ORDERING_CONFLICT_AUDIT_READY, IDENTITY_POLICY_READY, current_role_issue_rows == 0,
    current_timestamp_invalid_rows == 0, current_order_ambiguous_sessions == 0,
    current_fallback_sessions == 0, current_rollover_sessions == 0
])

structural_metadata_checks = pd.DataFrame([
    check_row("Identity policy is ready", IDENTITY_POLICY_READY, IDENTITY_POLICY_READY),
    check_row("Ordering conflict audit is ready", ORDERING_CONFLICT_AUDIT_READY, ORDERING_CONFLICT_AUDIT_READY),
    check_row("Current corpus has no canonical role issues", current_role_issue_rows == 0, current_role_issue_rows),
    check_row("Current corpus has no invalid timestamps", current_timestamp_invalid_rows == 0, current_timestamp_invalid_rows),
    check_row("Current corpus has no ambiguous ordering", current_order_ambiguous_sessions == 0, current_order_ambiguous_sessions),
    check_row("Current corpus requires no ordering fallback", current_fallback_sessions == 0, current_fallback_sessions),
    check_row("Current corpus requires no rollover", current_rollover_sessions == 0, current_rollover_sessions),
    check_row("Current corpus is eligible for structural metadata", CURRENT_CORPUS_STRUCTURAL_METADATA_ELIGIBLE, CURRENT_CORPUS_STRUCTURAL_METADATA_ELIGIBLE),
    check_row("Temporal metadata requires trusted timestamp-primary ordering", STRUCTURAL_METADATA_CONFIG["temporal_metadata_requires_timestamp_primary"], True),
    check_row("Negative timestamp gaps are prohibited", not STRUCTURAL_METADATA_CONFIG["negative_timestamp_gap_allowed"], False),
    check_row("All synthetic structural tests passed", synthetic_failures == 0, synthetic_failures),
    check_row("All real structural smoke tests passed", real_failures == 0, real_failures)
])

structural_metadata_failures = structural_metadata_checks[~structural_metadata_checks["passed"]]
STRUCTURAL_METADATA_READY = structural_metadata_failures.empty

structural_metadata_policy_summary = pd.DataFrame({
    "item": [
        "Structural metadata version", "Current corpus eligible", "Expected production rows",
        "Expected production sessions", "Current role-issue rows", "Current invalid timestamp rows",
        "Current ambiguous sessions", "Current fallback sessions", "Current rollover sessions",
        "Synthetic tests", "Passed synthetic tests", "Real smoke files", "Real smoke failures",
        "Full corpus application", "STRUCTURAL_METADATA_CONFIG_SHA256", "STRUCTURAL_METADATA_READY"
    ],
    "value": [
        STRUCTURAL_METADATA_VERSION, CURRENT_CORPUS_STRUCTURAL_METADATA_ELIGIBLE, TOTAL_RAW_ROWS,
        len(TRANSCRIPT_FILES), current_role_issue_rows, current_timestamp_invalid_rows,
        current_order_ambiguous_sessions, current_fallback_sessions, current_rollover_sessions,
        len(structural_metadata_tests), int(structural_metadata_tests["passed"].sum()),
        len(structural_metadata_real_smoke_audit), real_failures, "DEFER_TO_2.16",
        STRUCTURAL_METADATA_CONFIG_SHA256, STRUCTURAL_METADATA_READY
    ]
})

display(structural_metadata_checks)
display(structural_metadata_policy_summary)

assert STRUCTURAL_METADATA_READY, (
    "Section 2.14 failed.\n\n" + structural_metadata_failures[["check","detail"]].to_string(index=False)
)

print("\n" + "=" * 68)
print("TRACE THE ACE — STRUCTURAL TURN METADATA READY")
print("=" * 68)
print(f"Current corpus eligible : {CURRENT_CORPUS_STRUCTURAL_METADATA_ELIGIBLE}")
print(f"Expected rows           : {TOTAL_RAW_ROWS:,}")
print(f"Expected sessions       : {len(TRANSCRIPT_FILES):,}")
print(f"Role issues             : {current_role_issue_rows:,}")
print(f"Invalid timestamps      : {current_timestamp_invalid_rows:,}")
print(f"Ambiguous sessions      : {current_order_ambiguous_sessions:,}")
print(f"Fallback sessions       : {current_fallback_sessions:,}")
print(f"Rollover sessions       : {current_rollover_sessions:,}")
print(f"Synthetic tests         : {int(structural_metadata_tests['passed'].sum())}/{len(structural_metadata_tests)}")
print(f"Real smoke tests        : {len(structural_metadata_real_smoke_audit)-real_failures}/{len(structural_metadata_real_smoke_audit)}")
print(f"STRUCTURAL READY        : {STRUCTURAL_METADATA_READY}")
print("=" * 68)

                                                check  passed detail
0                            Identity policy is ready    True   True
1                    Ordering conflict audit is ready    True   True
2         Current corpus has no canonical role issues    True      0
3            Current corpus has no invalid timestamps    True      0
4            Current corpus has no ambiguous ordering    True      0
5        Current corpus requires no ordering fallback    True      0
6                 Current corpus requires no rollover    True      0
7   Current corpus is eligible for structural meta...    True   True
8   Temporal metadata requires trusted timestamp-p...    True   True
9              Negative timestamp gaps are prohibited    True  False
10              All synthetic structural tests passed    True      0
11             All real structural smoke tests passed    True      0

,item,value
0,Structural metadata version,1.0
1,Current corpus eligible,True
2,Expected production rows,6139854
3,Expected production sessions,22821
4,Current role-issue rows,0
5,Current invalid timestamp rows,0
6,Current ambiguous sessions,0
7,Current fallback sessions,0
8,Current rollover sessions,0
9,Synthetic tests,15
10,Passed synthetic tests,15
11,Real smoke files,5
12,Real smoke failures,0
13,Full corpus application,DEFER_TO_2.16
14,STRUCTURAL_METADATA_CONFIG_SHA256,92c8a77c718614d430b57a628d01cd2e0a8fe87ed03c79...
15,STRUCTURAL_METADATA_READY,True

====================================================================
TRACE THE ACE — STRUCTURAL TURN METADATA READY
====================================================================
Current corpus eligible : True
Expected rows           : 6,139,854
Expected sessions       : 22,821
Role issues             : 0
Invalid timestamps      : 0
Ambiguous sessions      : 0
Fallback sessions       : 0
Rollover sessions       : 0
Synthetic tests         : 15/15
Real smoke tests        : 5/5
STRUCTURAL READY        : True
====================================================================

# Section 2.15 — Integrated Session Parser

This section combines all validated parser components into one deterministic end-to-end session parser.
Each transcript is reconstructed from the original source before normalization or structural derivation.
Role, utterance ID, timestamp, ordering, identity, and structural metadata use the previously validated policies.
Physical provenance, raw evidence identity, and logical turn identity remain independently traceable.
Turn candidates must match the frozen 52-field Arrow schema exactly.
Session candidates must match the frozen 31-field Arrow schema exactly.
Raw and normalized transcript hashes are deterministic and order-sensitive.
Local invariants verify row conservation, ordering, identity uniqueness, raw traceability, and schema compatibility.
The parser remains label-blind and receives no objective, target, fold statistic, prior, prediction, or model output.
Synthetic and representative real sessions are validated before the full production parse.
The section ends with `INTEGRATED_PARSER_READY`.

In [49]:
# ============================================================
# 2.15.1 — INTEGRATED PARSER ENGINE
# ============================================================

import re
import json
import hashlib
import inspect
from pathlib import Path
from collections import Counter

import pandas as pd
import pyarrow as pa


assert STRUCTURAL_METADATA_READY, "Section 2.14 must pass first."
assert IDENTITY_POLICY_READY, "Section 2.13 must pass first."
assert ORDERING_CONFLICT_AUDIT_READY, "Section 2.12 must pass first."
assert isinstance(TURN_CANDIDATE_SCHEMA, pa.Schema) and len(TURN_CANDIDATE_SCHEMA) == 52
assert isinstance(SESSION_CANDIDATE_SCHEMA, pa.Schema) and len(SESSION_CANDIDATE_SCHEMA) == 31


INTEGRATED_PARSER_VERSION = "1.0"
TRANSCRIPT_HASH_VERSION = "1.0"

EXPECTED_SESSION_FIELDS = {
    "session_id", "source_file_relative", "file_sha256", "source_raw_row_count", "n_turns",
    "n_student_turns", "n_tutor_turns", "n_background_turns", "n_unknown_roles",
    "first_valid_timestamp", "last_valid_timestamp", "duration_seconds", "duration_status",
    "timestamp_issue_count", "utterance_id_issue_count", "ordering_issue_count",
    "unknown_role_count", "empty_content_count", "ordering_method", "ordering_confidence",
    "ordering_comparability", "fallback_order_used", "timestamp_tie_count",
    "timestamp_id_conflict", "timestamp_source_conflict", "id_source_conflict",
    "midnight_rollover_count", "ambiguous_order_flag", "raw_transcript_hash",
    "normalized_transcript_hash", "quality_warning_count"
}

assert set(SESSION_CANDIDATE_SCHEMA.names) == EXPECTED_SESSION_FIELDS, (
    "Frozen SESSION_CANDIDATE_SCHEMA differs from the verified 31-field contract.\n"
    f"Missing: {sorted(EXPECTED_SESSION_FIELDS - set(SESSION_CANDIDATE_SCHEMA.names))}\n"
    f"Extra: {sorted(set(SESSION_CANDIDATE_SCHEMA.names) - EXPECTED_SESSION_FIELDS)}"
)


def resolve_text_normalizer():
    preferred = [
        "normalize_text_math_safe", "normalize_math_safe_text", "math_safe_normalize_text",
        "normalize_content_math_safe", "normalize_text_nfc", "normalize_text"
    ]

    for name in preferred:
        fn = globals().get(name)
        if callable(fn):
            return name, fn

    candidates = [
        (name, fn) for name, fn in globals().items()
        if callable(fn)
        and "normal" in name.lower()
        and ("text" in name.lower() or "content" in name.lower())
        and not name.startswith(("integration_", "resolve_", "run_", "audit_"))
        and "test" not in name.lower()
    ]

    if len(candidates) == 1:
        return candidates[0]

    raise RuntimeError(
        f"Section 2.6 text normalizer could not be uniquely resolved: "
        f"{[name for name, _ in candidates]}"
    )


TEXT_NORMALIZER_NAME, TEXT_NORMALIZER = resolve_text_normalizer()


def integration_normalize_text(raw):
    result = TEXT_NORMALIZER(raw)

    if isinstance(result, str):
        return result

    if isinstance(result, dict):
        for key in ["text_norm", "normalized_text", "normalized", "text"]:
            if key in result and isinstance(result[key], str):
                return result[key]

    if isinstance(result, (tuple, list)) and result and isinstance(result[0], str):
        return result[0]

    raise TypeError(
        f"Unsupported output from {TEXT_NORMALIZER_NAME}: "
        f"{type(result).__name__}"
    )


def integration_role(raw):
    result = canonicalize_role(raw)
    role = result.get("role", result.get("mapped_role"))

    if role is None:
        raise RuntimeError("Role mapper did not return a canonical role.")

    status = result.get(
        "role_status",
        result.get("status", "VALID" if role != "unknown" else "UNKNOWN")
    )

    issue = bool(
        result.get(
            "role_issue_flag",
            result.get("issue", role == "unknown")
        )
    )

    return {
        "role": role,
        "role_status": status,
        "role_issue_flag": issue
    }


def is_blank_raw(value):
    return value is None or str(value).strip() == ""


def canonical_hash(domain, version, fields):
    payload = {
        "domain": domain,
        "version": version,
        "fields": fields
    }

    raw = json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False
    ).encode("utf-8")

    return hashlib.sha256(raw).hexdigest()


def ordered_sequence_hash(domain, items):
    return canonical_hash(
        domain,
        TRANSCRIPT_HASH_VERSION,
        {"items": items}
    )


def integrated_candidate_hash(table, domain):
    return canonical_hash(
        domain,
        INTEGRATED_PARSER_VERSION,
        {
            "schema": str(table.schema),
            "rows": table.to_pylist()
        }
    )


def project_record_to_schema(values, schema, label):
    unresolved = [
        field.name for field in schema
        if not field.nullable
        and (field.name not in values or values[field.name] is None)
    ]

    if unresolved:
        raise RuntimeError(
            f"{label} has unresolved non-null fields: {unresolved}"
        )

    return {
        field.name: values.get(field.name)
        for field in schema
    }


def build_integrated_id_state(raw_ids):
    parsed = annotate_session_ids(raw_ids)["rows"]

    raw_counts = Counter(raw_ids)
    parsed_counts = Counter(
        row.get("utterance_id")
        for row in parsed
        if row.get("utterance_id") is not None
    )

    output = []

    for raw_id, row in zip(raw_ids, parsed):
        parsed_id = row.get("utterance_id")

        status = row.get(
            "utterance_id_status",
            row.get("base_status", "UNPARSEABLE")
        )

        duplicate_raw = (
            not is_blank_raw(raw_id)
            and raw_counts[raw_id] > 1
        )

        parsed_collision = (
            parsed_id is not None
            and parsed_counts[parsed_id] > 1
        )

        natural_collision = (
            parsed_collision
            and not duplicate_raw
        )

        issue = (
            status != "VALID"
            or duplicate_raw
            or parsed_collision
        )

        output.append({
            **row,
            "utterance_id_status": status,
            "duplicate_utterance_id_flag": duplicate_raw,
            "natural_key_collision_flag": natural_collision,
            "utterance_id_issue_flag": issue,
            "clean_logical_identity": (
                status == "VALID"
                and not duplicate_raw
                and not parsed_collision
            )
        })

    return output


def build_integrated_turn_identity(session_id, id_state, raw_row):
    identity_status = (
        "VALID"
        if id_state["clean_logical_identity"]
        else "AMBIGUOUS"
    )

    return build_turn_identity(
        session_id,
        id_state.get("utterance_id"),
        identity_status,
        raw_row
    )


def build_turn_values(raw, norm, ids, role_info, ts, identity, meta, session_id, duplicate_raw_field):
    content = raw["content_raw"]

    return {
        "session_id": session_id,
        "turn_uid": identity["turn_uid"],
        "source_row_uid": identity["source_row_uid"],
        "turn_index": meta["turn_index"],

        "session_id_raw": raw["session_id_raw"],
        "utterance_id_raw": raw["utterance_id_raw"],
        "utterance_id": ids.get("utterance_id"),
        "utterance_id_status": ids["utterance_id_status"],

        "missing_session_id_flag": is_blank_raw(raw["session_id_raw"]),
        "missing_utterance_id_flag": is_blank_raw(raw["utterance_id_raw"]),
        "missing_role_flag": is_blank_raw(raw["role_raw"]),
        "missing_content_flag": is_blank_raw(content),
        "missing_timestamp_flag": is_blank_raw(raw["timestamp_raw"]),

        "duplicate_utterance_id_flag": bool(ids["duplicate_utterance_id_flag"]),
        "natural_key_collision_flag": bool(ids["natural_key_collision_flag"]),
        "leading_zero_flag": bool(ids.get("leading_zero_flag", False)),
        "utterance_id_issue_flag": bool(ids["utterance_id_issue_flag"]),

        "role_raw": raw["role_raw"],
        "role": role_info["role"],
        "role_status": role_info["role_status"],
        "role_mapping_status": role_info["role_status"],
        "role_issue_flag": bool(role_info["role_issue_flag"]),

        "content_raw": content,
        "text_norm": norm,

        "empty_content_flag": is_blank_raw(content),
        "whitespace_only_content_flag": content != "" and str(content).strip() == "",
        "empty_after_normalization_flag": str(norm).strip() == "",
        "contains_unclear_flag": "[UNCLEAR]" in str(content),
        "unclear_flag": "[UNCLEAR]" in str(content),

        "duplicate_raw_field_flag": bool(duplicate_raw_field),
        "duplicate_raw_row_flag": bool(duplicate_raw_field),
        "duplicate_raw_fields_flag": bool(duplicate_raw_field),
        "duplicate_raw_logical_fields_flag": bool(duplicate_raw_field),

        "text_changed_flag": norm != content,
        "text_normalization_changed_flag": norm != content,

        "content_char_count": len(content),
        "content_chars": len(content),
        "content_line_count": content.count("\n") + 1,
        "content_lines": content.count("\n") + 1,

        "timestamp_raw": raw["timestamp_raw"],
        "timestamp": ts["timestamp"],
        "timestamp_status": ts["timestamp_status"],
        "timestamp_kind": ts["timestamp_kind"],
        "timestamp_precision": ts["timestamp_precision"],
        "timezone_status": ts["timezone_status"],
        "timestamp_issue_flag": ts["timestamp_status"] != "VALID",
        "timestamp_formatting_variant": bool(ts.get("formatting_variant", False)),

        "timestamp_day_offset": meta["timestamp_day_offset"],
        "timestamp_order_value": meta["timestamp_order_value"],
        "timestamp_rollover_flag": bool(meta["timestamp_rollover_flag"]),

        "ordering_method": meta["ordering_method"],
        "ordering_confidence": meta["ordering_confidence"],
        "ordering_issue_flag": bool(meta["ordering_issue_flag"]),
        "ordering_comparability": meta["ordering_comparability"],

        "relative_turn_position": meta["relative_turn_position"],
        "role_turn_index": meta["role_turn_index"],
        "previous_role": meta["previous_role"],
        "next_role": meta["next_role"],
        "speaker_switch_flag": bool(meta["speaker_switch_flag"]),
        "speaker_switch": bool(meta["speaker_switch_flag"]),
        "time_since_previous_turn": meta["time_since_previous_turn"],
        "elapsed_from_session_start": meta["elapsed_from_session_start"],

        "first_turn_flag": bool(meta["first_turn_flag"]),
        "last_turn_flag": bool(meta["last_turn_flag"]),
        "is_first_turn": bool(meta["first_turn_flag"]),
        "is_last_turn": bool(meta["last_turn_flag"]),

        "source_file_relative": raw["source_file_relative"],
        "source_row_index": int(raw["source_row_index"]),
        "file_sha256": raw["file_sha256"],

        "raw_field_hash": identity["raw_field_hash"],
        "raw_row_hash": identity["raw_field_hash"],
        "content_hash": identity["content_hash"],
        "turn_uid_version": TURN_UID_VERSION,
        "identity_mode": identity["identity_mode"]
    }


def parse_reconstructed_session(raw_rows, expected_session_id, relative_file):
    if not raw_rows:
        raise ValueError("Integrated parser does not accept an empty transcript.")

    source_indices = [int(row["source_row_index"]) for row in raw_rows]

    if source_indices != list(range(len(raw_rows))):
        raise ValueError("Source row indices are not contiguous from zero.")

    raw_sessions = {
        row["session_id_raw"]
        for row in raw_rows
    }

    if raw_sessions != {expected_session_id}:
        raise ValueError(
            f"Internal session mismatch: expected={expected_session_id}, "
            f"observed={sorted(raw_sessions)}"
        )

    file_hashes = {
        row["file_sha256"]
        for row in raw_rows
    }

    if len(file_hashes) != 1:
        raise ValueError(
            "A session contains multiple source-file hashes."
        )

    raw_ids = [
        row["utterance_id_raw"]
        for row in raw_rows
    ]

    raw_times = [
        row["timestamp_raw"]
        for row in raw_rows
    ]

    id_rows = build_integrated_id_state(raw_ids)

    timestamp_rows = [
        parse_timestamp(value)
        for value in raw_times
    ]

    role_rows = [
        integration_role(row["role_raw"])
        for row in raw_rows
    ]

    text_norms = [
        integration_normalize_text(row["content_raw"])
        for row in raw_rows
    ]

    order = order_session_rows(
        raw_ids,
        raw_times,
        source_indices,
        relative_file
    )

    conflict = audit_ordering_conflicts(
        raw_ids,
        raw_times,
        source_indices,
        relative_file
    )

    positions = order["ordered_positions"]

    identities = [
        build_integrated_turn_identity(
            expected_session_id,
            id_rows[i],
            raw_rows[i]
        )
        for i in range(len(raw_rows))
    ]

    raw_field_counts = Counter(
        identity["raw_field_hash"]
        for identity in identities
    )

    ordered_roles = [
        role_rows[i]["role"]
        for i in positions
    ]

    ordered_times = [
        order["timestamp_order_value"][i]
        for i in positions
    ]

    ordered_offsets = [
        order["timestamp_day_offset"][i]
        for i in positions
    ]

    ordered_rollovers = [
        order["timestamp_rollover_flag"][i]
        for i in positions
    ]

    metadata = build_structural_metadata(
        ordered_roles,
        ordered_times,
        order["ordering_method"],
        order["ordering_confidence"],
        order["ordering_issue_flag"],
        conflict["ordering_comparability"],
        ordered_offsets,
        ordered_rollovers
    )

    structural_summary = summarize_structural_session(
        attach_roles(
            metadata,
            ordered_roles
        )
    )

    turn_records = []

    for new_position, physical_position in enumerate(positions):
        raw = raw_rows[physical_position]
        ids = id_rows[physical_position]
        ts = timestamp_rows[physical_position]
        role_info = role_rows[physical_position]
        norm = text_norms[physical_position]
        identity = identities[physical_position]
        meta = metadata[new_position]

        duplicate_raw_field = (
            raw_field_counts[
                identity["raw_field_hash"]
            ] > 1
        )

        values = build_turn_values(
            raw,
            norm,
            ids,
            role_info,
            ts,
            identity,
            meta,
            expected_session_id,
            duplicate_raw_field
        )

        turn_records.append(
            project_record_to_schema(
                values,
                TURN_CANDIDATE_SCHEMA,
                "TURN_CANDIDATE_SCHEMA"
            )
        )

    turn_table = pa.Table.from_pylist(
        turn_records,
        schema=TURN_CANDIDATE_SCHEMA
    )

    raw_transcript_hash = ordered_sequence_hash(
        "raw_transcript_hash",
        [
            identities[i]["raw_field_hash"]
            for i in positions
        ]
    )

    normalized_transcript_hash = ordered_sequence_hash(
        "normalized_transcript_hash",
        [
            {
                "role": role_rows[i]["role"],
                "text_norm": text_norms[i]
            }
            for i in positions
        ]
    )

    timestamp_issue_count = sum(
        row["timestamp_status"] != "VALID"
        for row in timestamp_rows
    )

    utterance_id_issue_count = sum(
        row["utterance_id_issue_flag"]
        for row in id_rows
    )

    unknown_role_count = sum(
        row["role"] == "unknown"
        for row in role_rows
    )

    empty_content_count = sum(
        is_blank_raw(row["content_raw"])
        for row in raw_rows
    )

    ordering_issue_count = int(
        bool(order["ordering_issue_flag"])
    )

    fallback_order_used = bool(
        order["fallback_used"]
    )

    timestamp_tie_count = int(
        conflict["timestamp_tie_group_count"]
    )

    timestamp_id_conflict = bool(
        conflict["timestamp_id_conflict"]
    )

    timestamp_source_conflict = bool(
        conflict["timestamp_source_conflict"]
    )

    id_source_conflict = bool(
        conflict["id_source_conflict"]
    )

    midnight_rollover_count = int(
        max(
            [
                0 if value is None else int(value)
                for value in order["timestamp_day_offset"]
            ],
            default=0
        )
    )

    ambiguous_order_flag = bool(
        conflict["ambiguous_order"]
    )

    quality_warning_count = int(
        timestamp_issue_count
        + utterance_id_issue_count
        + unknown_role_count
        + empty_content_count
        + ordering_issue_count
        + int(fallback_order_used)
        + int(timestamp_id_conflict)
        + int(timestamp_source_conflict)
        + int(id_source_conflict)
        + midnight_rollover_count
        + int(ambiguous_order_flag)
    )

    session_values = {
        "session_id": expected_session_id,
        "source_file_relative": relative_file,
        "file_sha256": next(iter(file_hashes)),
        "source_raw_row_count": len(raw_rows),

        "n_turns": len(raw_rows),
        "n_student_turns": structural_summary["n_student_turns"],
        "n_tutor_turns": structural_summary["n_tutor_turns"],
        "n_background_turns": structural_summary["n_background_turns"],
        "n_unknown_roles": structural_summary["n_unknown_roles"],

        "first_valid_timestamp": structural_summary["first_valid_timestamp"],
        "last_valid_timestamp": structural_summary["last_valid_timestamp"],
        "duration_seconds": structural_summary["duration_seconds"],
        "duration_status": structural_summary["duration_status"],

        "timestamp_issue_count": timestamp_issue_count,
        "utterance_id_issue_count": utterance_id_issue_count,
        "ordering_issue_count": ordering_issue_count,
        "unknown_role_count": unknown_role_count,
        "empty_content_count": empty_content_count,

        "ordering_method": order["ordering_method"],
        "ordering_confidence": order["ordering_confidence"],
        "ordering_comparability": conflict["ordering_comparability"],
        "fallback_order_used": fallback_order_used,

        "timestamp_tie_count": timestamp_tie_count,
        "timestamp_id_conflict": timestamp_id_conflict,
        "timestamp_source_conflict": timestamp_source_conflict,
        "id_source_conflict": id_source_conflict,
        "midnight_rollover_count": midnight_rollover_count,
        "ambiguous_order_flag": ambiguous_order_flag,

        "raw_transcript_hash": raw_transcript_hash,
        "normalized_transcript_hash": normalized_transcript_hash,
        "quality_warning_count": quality_warning_count
    }

    session_record = project_record_to_schema(
        session_values,
        SESSION_CANDIDATE_SCHEMA,
        "SESSION_CANDIDATE_SCHEMA"
    )

    session_table = pa.Table.from_pylist(
        [session_record],
        schema=SESSION_CANDIDATE_SCHEMA
    )

    turns = turn_table.to_pylist()
    failures = []

    if len(turns) != len(raw_rows):
        failures.append("ROW_CONSERVATION")

    if [row["turn_index"] for row in turns] != list(range(len(turns))):
        failures.append("TURN_INDEX")

    if len({row["source_row_uid"] for row in turns}) != len(turns):
        failures.append("SOURCE_ROW_UID")

    if len({row["turn_uid"] for row in turns}) != len(turns):
        failures.append("TURN_UID")

    role_total = (
        session_record["n_student_turns"]
        + session_record["n_tutor_turns"]
        + session_record["n_background_turns"]
        + session_record["n_unknown_roles"]
    )

    if role_total != len(turns):
        failures.append("ROLE_ACCOUNTING")

    raw_by_index = {
        int(row["source_row_index"]): row
        for row in raw_rows
    }

    traceability_ok = all(
        row["session_id_raw"]
        == raw_by_index[int(row["source_row_index"])]["session_id_raw"]

        and row["utterance_id_raw"]
        == raw_by_index[int(row["source_row_index"])]["utterance_id_raw"]

        and row["role_raw"]
        == raw_by_index[int(row["source_row_index"])]["role_raw"]

        and row["content_raw"]
        == raw_by_index[int(row["source_row_index"])]["content_raw"]

        and row["timestamp_raw"]
        == raw_by_index[int(row["source_row_index"])]["timestamp_raw"]

        for row in turns
    )

    if not traceability_ok:
        failures.append("RAW_TRACEABILITY")

    first_field = (
        "first_turn_flag"
        if "first_turn_flag" in TURN_CANDIDATE_SCHEMA.names
        else "is_first_turn"
    )

    last_field = (
        "last_turn_flag"
        if "last_turn_flag" in TURN_CANDIDATE_SCHEMA.names
        else "is_last_turn"
    )

    if sum(bool(row[first_field]) for row in turns) != 1:
        failures.append("FIRST_TURN")

    if sum(bool(row[last_field]) for row in turns) != 1:
        failures.append("LAST_TURN")

    if failures:
        raise RuntimeError(
            f"Integrated invariants failed for "
            f"{expected_session_id}: {failures}"
        )

    audit = {
        "session_id": expected_session_id,
        "raw_rows": len(raw_rows),
        "candidate_turns": len(turns),
        "ordering_method": order["ordering_method"],
        "ordering_confidence": order["ordering_confidence"],
        "ordering_comparability": conflict["ordering_comparability"],
        "timestamp_issues": timestamp_issue_count,
        "id_issues": utterance_id_issue_count,
        "unknown_roles": unknown_role_count,
        "empty_contents": empty_content_count,
        "fallback_used": fallback_order_used,
        "ambiguous_order": ambiguous_order_flag,
        "traceability_ok": traceability_ok,
        "local_invariant_failures": 0,
        "turn_table_hash": integrated_candidate_hash(
            turn_table,
            "integrated_turn_table"
        ),
        "session_table_hash": integrated_candidate_hash(
            session_table,
            "integrated_session_table"
        )
    }

    return {
        "turn_table": turn_table,
        "session_record": session_record,
        "session_table": session_table,
        "audit": audit
    }


def parse_session_candidate(path, expected_session_id=None):
    path = Path(path)

    expected_session_id = (
        expected_session_id
        if expected_session_id is not None
        else path.stem
    )

    reconstructed = reconstruct_raw_file(
        path,
        expected_session_id=expected_session_id
    )

    raw_rows = reconstructed[
        "raw_table"
    ].to_pylist()

    relative_file = (
        raw_rows[0]["source_file_relative"]
        if raw_rows
        else path.name
    )

    return parse_reconstructed_session(
        raw_rows,
        expected_session_id,
        relative_file
    )


INTEGRATED_PARSER_CONFIG = {
    "version": INTEGRATED_PARSER_VERSION,
    "text_normalizer": TEXT_NORMALIZER_NAME,
    "turn_schema_fields": TURN_CANDIDATE_SCHEMA.names,
    "session_schema_fields": SESSION_CANDIDATE_SCHEMA.names,
    "turn_schema_field_count": len(TURN_CANDIDATE_SCHEMA),
    "session_schema_field_count": len(SESSION_CANDIDATE_SCHEMA),
    "transcript_hash_version": TRANSCRIPT_HASH_VERSION,
    "timestamp_tie_count_semantics": "tie_group_count",
    "quality_warning_count_semantics": "sum_of_supported_issue_events",
    "label_blind": True,
    "full_corpus_application": "DEFER_TO_2.16"
}

INTEGRATED_PARSER_CONFIG_SHA256 = canonical_hash(
    "integrated_parser_config",
    INTEGRATED_PARSER_VERSION,
    INTEGRATED_PARSER_CONFIG
)


print("Integrated parser version :", INTEGRATED_PARSER_VERSION)
print("Text normalizer           :", TEXT_NORMALIZER_NAME)
print("Frozen turn fields        :", len(TURN_CANDIDATE_SCHEMA))
print("Frozen session fields     :", len(SESSION_CANDIDATE_SCHEMA))
print("Session schema contract   : VERIFIED")

Integrated parser version : 1.0
Text normalizer           : normalize_text
Frozen turn fields        : 52
Frozen session fields     : 31
Session schema contract   : VERIFIED

In [50]:
# ============================================================
# 2.15.2 — END-TO-END CONTRACT TESTS
# ============================================================

def make_synthetic_raw_rows(session_id, rows):
    relative_file = f"synthetic/{session_id}.csv"

    payload = {
        "session_id": session_id,
        "relative_file": relative_file,
        "rows": rows
    }

    file_sha256 = hashlib.sha256(
        json.dumps(
            payload,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":")
        ).encode("utf-8")
    ).hexdigest()

    return [
        {
            "session_id_raw": session_id,
            "utterance_id_raw": "" if uid is None else str(uid),
            "role_raw": "" if role is None else str(role),
            "content_raw": "" if content is None else str(content),
            "timestamp_raw": "" if timestamp is None else str(timestamp),
            "source_file_relative": relative_file,
            "source_row_index": i,
            "file_sha256": file_sha256
        }
        for i, (uid, role, content, timestamp) in enumerate(rows)
    ]


def run_integrated_case(name, rows, expected):
    try:
        result = parse_reconstructed_session(
            make_synthetic_raw_rows(name, rows),
            name,
            f"synthetic/{name}.csv"
        )

        audit = result["audit"]
        turns = result["turn_table"].to_pylist()
        session = result["session_record"]

        checks = {
            "row_conservation":
                len(turns) == len(rows),

            "turn_schema":
                result["turn_table"].schema
                == TURN_CANDIDATE_SCHEMA,

            "session_schema":
                result["session_table"].schema
                == SESSION_CANDIDATE_SCHEMA,

            "method":
                audit["ordering_method"]
                == expected.get(
                    "method",
                    audit["ordering_method"]
                ),

            "confidence":
                audit["ordering_confidence"]
                == expected.get(
                    "confidence",
                    audit["ordering_confidence"]
                ),

            "timestamp_issues":
                audit["timestamp_issues"]
                == expected.get(
                    "timestamp_issues",
                    audit["timestamp_issues"]
                ),

            "id_issues":
                audit["id_issues"]
                == expected.get(
                    "id_issues",
                    audit["id_issues"]
                ),

            "unknown_roles":
                audit["unknown_roles"]
                == expected.get(
                    "unknown_roles",
                    audit["unknown_roles"]
                ),

            "empty_contents":
                audit["empty_contents"]
                == expected.get(
                    "empty_contents",
                    audit["empty_contents"]
                ),

            "fallback":
                audit["fallback_used"]
                == expected.get(
                    "fallback",
                    audit["fallback_used"]
                ),

            "traceability":
                audit["traceability_ok"],

            "role_accounting":
                session["n_student_turns"]
                + session["n_tutor_turns"]
                + session["n_background_turns"]
                + session["n_unknown_roles"]
                == len(turns)
        }

        if expected.get(
            "temporal_suppressed",
            False
        ):
            checks["temporal_suppressed"] = all(
                row.get(
                    "time_since_previous_turn"
                ) is None
                and row.get(
                    "elapsed_from_session_start"
                ) is None
                for row in turns
            )

        failed_checks = [
            key
            for key, value in checks.items()
            if not value
        ]

        return {
            "test": name,
            "passed": len(failed_checks) == 0,
            "method": audit["ordering_method"],
            "confidence": audit["ordering_confidence"],
            "timestamp_issues": audit["timestamp_issues"],
            "id_issues": audit["id_issues"],
            "unknown_roles": audit["unknown_roles"],
            "empty_contents": audit["empty_contents"],
            "fallback": audit["fallback_used"],
            "failed_checks": failed_checks,
            "error_type": "",
            "error_message": ""
        }

    except Exception as exc:
        return {
            "test": name,
            "passed": False,
            "method": "ERROR",
            "confidence": "ERROR",
            "timestamp_issues": None,
            "id_issues": None,
            "unknown_roles": None,
            "empty_contents": None,
            "fallback": None,
            "failed_checks": ["EXCEPTION"],
            "error_type": type(exc).__name__,
            "error_message": str(exc)
        }


synthetic_cases = [
    (
        "E01_CLEAN_STANDARD",
        [
            ("0", "tutor", "What is 2+2?", "00:00:00"),
            ("1", "student", "4", "00:00:01"),
            ("2", "tutor", "Good.", "00:00:02")
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "fallback": False
        }
    ),

    (
        "E02_TIMESTAMP_TIES",
        [
            ("0", "tutor", "Question", "00:00:00"),
            ("1", "student", "Answer", "00:00:00"),
            ("2", "tutor", "Next", "00:00:01")
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "fallback": False
        }
    ),

    (
        "E03_ALL_TIMES_TIED",
        [
            ("0", "tutor", "A", "00:00:05"),
            ("1", "student", "B", "00:00:05"),
            ("2", "tutor", "C", "00:00:05")
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "fallback": False
        }
    ),

    (
        "E04_ONE_TIMESTAMP_MISSING",
        [
            ("0", "tutor", "A", "00:00:00"),
            ("1", "student", "B", None),
            ("2", "tutor", "C", "00:00:02")
        ],
        {
            "method": "UTTERANCE_ID_FALLBACK",
            "confidence": "MEDIUM",
            "timestamp_issues": 1,
            "fallback": True,
            "temporal_suppressed": True
        }
    ),

    (
        "E05_MALFORMED_TIMESTAMP",
        [
            ("0", "tutor", "A", "00:00:00"),
            ("1", "student", "B", "BAD"),
            ("2", "tutor", "C", "00:00:02")
        ],
        {
            "method": "UTTERANCE_ID_FALLBACK",
            "confidence": "MEDIUM",
            "timestamp_issues": 1,
            "fallback": True,
            "temporal_suppressed": True
        }
    ),

    (
        "E06_UNKNOWN_ROLE",
        [
            ("0", "tutor", "A", "00:00:00"),
            ("1", "teacher", "B", "00:00:01"),
            ("2", "student", "C", "00:00:02")
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "unknown_roles": 1,
            "fallback": False
        }
    ),

    (
        "E07_DUPLICATE_ID",
        [
            ("0", "tutor", "A", "00:00:00"),
            ("0", "student", "B", "00:00:01"),
            ("2", "tutor", "C", "00:00:02")
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "id_issues": 2,
            "fallback": False
        }
    ),

    (
        "E08_EMPTY_CONTENT",
        [
            ("0", "tutor", "", "00:00:00"),
            ("1", "student", "4", "00:00:01")
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "empty_contents": 1,
            "fallback": False
        }
    ),

    (
        "E09_MULTILINE_MATH",
        [
            (
                "0",
                "tutor",
                "Solve:\nx² ≤ ½",
                "00:00:00"
            ),
            (
                "1",
                "student",
                "x² ≤ ½",
                "00:00:01"
            )
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "fallback": False
        }
    ),

    (
        "E10_LARGE_CONTENT",
        [
            (
                "0",
                "tutor",
                "A" * 10000,
                "00:00:00"
            ),
            (
                "1",
                "student",
                "B",
                "00:00:01"
            )
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "fallback": False
        }
    ),

    (
        "E11_ALL_TIMESTAMPS_MISSING",
        [
            ("0", "tutor", "A", None),
            ("1", "student", "B", None),
            ("2", "tutor", "C", None)
        ],
        {
            "method": "UTTERANCE_ID_FALLBACK",
            "confidence": "MEDIUM",
            "timestamp_issues": 3,
            "fallback": True,
            "temporal_suppressed": True
        }
    ),

    (
        "E12_SINGLE_TURN",
        [
            (
                "0",
                "student",
                "Only answer",
                "00:00:00"
            )
        ],
        {
            "method": "TIMESTAMP_PRIMARY",
            "confidence": "HIGH",
            "fallback": False
        }
    )
]


integrated_synthetic_tests = pd.DataFrame([
    run_integrated_case(
        name,
        rows,
        expected
    )
    for name, rows, expected in synthetic_cases
])

display(integrated_synthetic_tests)


synthetic_failures = integrated_synthetic_tests[
    ~integrated_synthetic_tests["passed"]
]

if not synthetic_failures.empty:
    display(
        synthetic_failures[
            [
                "test",
                "failed_checks",
                "error_type",
                "error_message"
            ]
        ]
    )

assert synthetic_failures.empty, (
    "Integrated synthetic end-to-end tests failed."
)


def choose_integrated_real_files(audit):
    selected = {
        audit.sort_values(
            "relative_file"
        ).iloc[0]["relative_file"],

        audit.loc[
            audit["n_turns"].idxmin(),
            "relative_file"
        ],

        audit.loc[
            audit["n_turns"].idxmax(),
            "relative_file"
        ],

        audit.loc[
            audit["max_tie_group_size"].idxmax(),
            "relative_file"
        ]
    }

    tie_free = audit[
        audit["timestamp_reference_class"]
        == "TIE_FREE_FULL_REFERENCE"
    ].sort_values("relative_file")

    if not tie_free.empty:
        selected.add(
            tie_free.iloc[0][
                "relative_file"
            ]
        )

    ordered = audit.sort_values(
        "relative_file"
    ).reset_index(drop=True)

    for q in [0.25, 0.50, 0.75]:
        selected.add(
            ordered.iloc[
                int(
                    (len(ordered) - 1) * q
                )
            ]["relative_file"]
        )

    return sorted(selected)


def audit_integrated_real(relative_file):
    path = TRANSCRIPT_ROOT / Path(relative_file)

    run_a = parse_session_candidate(path)
    run_b = parse_session_candidate(path)

    turns = run_a[
        "turn_table"
    ].to_pylist()

    raw_rows = reconstruct_raw_file(
        path,
        expected_session_id=Path(
            relative_file
        ).stem
    )["raw_table"].to_pylist()

    raw_map = {
        int(row["source_row_index"]): row
        for row in raw_rows
    }

    traceability = all(
        row["session_id_raw"]
        == raw_map[int(row["source_row_index"])]["session_id_raw"]

        and row["utterance_id_raw"]
        == raw_map[int(row["source_row_index"])]["utterance_id_raw"]

        and row["role_raw"]
        == raw_map[int(row["source_row_index"])]["role_raw"]

        and row["content_raw"]
        == raw_map[int(row["source_row_index"])]["content_raw"]

        and row["timestamp_raw"]
        == raw_map[int(row["source_row_index"])]["timestamp_raw"]

        for row in turns
    )

    session = run_a[
        "session_record"
    ]

    role_accounting = (
        session["n_student_turns"]
        + session["n_tutor_turns"]
        + session["n_background_turns"]
        + session["n_unknown_roles"]
        == len(turns)
    )

    return {
        "relative_file": relative_file,
        "rows": len(turns),

        "ordering_method":
            run_a["audit"][
                "ordering_method"
            ],

        "ordering_confidence":
            run_a["audit"][
                "ordering_confidence"
            ],

        "turn_schema_exact":
            run_a["turn_table"].schema
            == TURN_CANDIDATE_SCHEMA,

        "session_schema_exact":
            run_a["session_table"].schema
            == SESSION_CANDIDATE_SCHEMA,

        "row_conservation":
            len(turns)
            == len(raw_rows),

        "turn_index_contiguous":
            [
                row["turn_index"]
                for row in turns
            ]
            == list(
                range(len(turns))
            ),

        "source_uid_unique":
            len({
                row["source_row_uid"]
                for row in turns
            })
            == len(turns),

        "turn_uid_unique":
            len({
                row["turn_uid"]
                for row in turns
            })
            == len(turns),

        "role_accounting":
            role_accounting,

        "traceability_exact":
            traceability,

        "repeat_turn_hash":
            run_a["audit"][
                "turn_table_hash"
            ]
            == run_b["audit"][
                "turn_table_hash"
            ],

        "repeat_session_hash":
            run_a["audit"][
                "session_table_hash"
            ]
            == run_b["audit"][
                "session_table_hash"
            ],

        "local_failures":
            run_a["audit"][
                "local_invariant_failures"
            ]
    }


REAL_INTEGRATED_FILES = choose_integrated_real_files(
    ordering_calibration_session_audit
)

integrated_real_audit = pd.DataFrame([
    audit_integrated_real(
        relative_file
    )
    for relative_file in REAL_INTEGRATED_FILES
])


integrated_real_audit["passed"] = (
    integrated_real_audit[
        "ordering_method"
    ].eq("TIMESTAMP_PRIMARY")

    & integrated_real_audit[
        "ordering_confidence"
    ].eq("HIGH")

    & integrated_real_audit[
        "turn_schema_exact"
    ]

    & integrated_real_audit[
        "session_schema_exact"
    ]

    & integrated_real_audit[
        "row_conservation"
    ]

    & integrated_real_audit[
        "turn_index_contiguous"
    ]

    & integrated_real_audit[
        "source_uid_unique"
    ]

    & integrated_real_audit[
        "turn_uid_unique"
    ]

    & integrated_real_audit[
        "role_accounting"
    ]

    & integrated_real_audit[
        "traceability_exact"
    ]

    & integrated_real_audit[
        "repeat_turn_hash"
    ]

    & integrated_real_audit[
        "repeat_session_hash"
    ]

    & integrated_real_audit[
        "local_failures"
    ].eq(0)
)


display(integrated_real_audit)


assert integrated_real_audit[
    "passed"
].all(), (
    "Integrated real-session end-to-end audit failed."
)

,test,passed,method,confidence,timestamp_issues,id_issues,unknown_roles,empty_contents,fallback,failed_checks,error_type,error_message
0,E01_CLEAN_STANDARD,True,TIMESTAMP_PRIMARY,HIGH,0,0,0,0,False,[],,
1,E02_TIMESTAMP_TIES,True,TIMESTAMP_PRIMARY,HIGH,0,0,0,0,False,[],,
2,E03_ALL_TIMES_TIED,True,TIMESTAMP_PRIMARY,HIGH,0,0,0,0,False,[],,
3,E04_ONE_TIMESTAMP_MISSING,True,UTTERANCE_ID_FALLBACK,MEDIUM,1,0,0,0,True,[],,
4,E05_MALFORMED_TIMESTAMP,True,UTTERANCE_ID_FALLBACK,MEDIUM,1,0,0,0,True,[],,
5,E06_UNKNOWN_ROLE,True,TIMESTAMP_PRIMARY,HIGH,0,0,1,0,False,[],,
6,E07_DUPLICATE_ID,True,TIMESTAMP_PRIMARY,HIGH,0,2,0,0,False,[],,
7,E08_EMPTY_CONTENT,True,TIMESTAMP_PRIMARY,HIGH,0,0,0,1,False,[],,
8,E09_MULTILINE_MATH,True,TIMESTAMP_PRIMARY,HIGH,0,0,0,0,False,[],,
9,E10_LARGE_CONTENT,True,TIMESTAMP_PRIMARY,HIGH,0,0,0,0,False,[],,
10,E11_ALL_TIMESTAMPS_MISSING,True,UTTERANCE_ID_FALLBACK,MEDIUM,3,0,0,0,True,[],,
11,E12_SINGLE_TURN,True,TIMESTAMP_PRIMARY,HIGH,0,0,0,0,False,[],,

,relative_file,rows,ordering_method,ordering_confidence,turn_schema_exact,session_schema_exact,row_conservation,turn_index_contiguous,source_uid_unique,turn_uid_unique,role_accounting,traceability_exact,repeat_turn_hash,repeat_session_hash,local_failures,passed
0,aaaedit.csv,254,TIMESTAMP_PRIMARY,HIGH,True,True,True,True,True,True,True,True,True,True,0,True
1,aayjyjr.csv,76,TIMESTAMP_PRIMARY,HIGH,True,True,True,True,True,True,True,True,True,True,0,True
2,bvnewyc.csv,622,TIMESTAMP_PRIMARY,HIGH,True,True,True,True,True,True,True,True,True,True,0,True
3,dmutook.csv,217,TIMESTAMP_PRIMARY,HIGH,True,True,True,True,True,True,True,True,True,True,0,True
4,gzupluu.csv,305,TIMESTAMP_PRIMARY,HIGH,True,True,True,True,True,True,True,True,True,True,0,True
5,jlntsbf.csv,15,TIMESTAMP_PRIMARY,HIGH,True,True,True,True,True,True,True,True,True,True,0,True
6,klpfjsf.csv,327,TIMESTAMP_PRIMARY,HIGH,True,True,True,True,True,True,True,True,True,True,0,True
7,mvkburc.csv,582,TIMESTAMP_PRIMARY,HIGH,True,True,True,True,True,True,True,True,True,True,0,True

In [51]:
# ============================================================
# 2.15.3 — FINAL INTEGRATION GATE
# ============================================================

def schema_binding_table(schema, record, schema_name):
    return pd.DataFrame([
        {
            "schema": schema_name,
            "field": field.name,
            "arrow_type": str(field.type),
            "nullable": field.nullable,
            "resolved": field.name in record,
            "value_is_null": record.get(
                field.name
            ) is None
        }
        for field in schema
    ])


example_result = parse_session_candidate(
    TRANSCRIPT_ROOT
    / Path(
        REAL_INTEGRATED_FILES[0]
    )
)


turn_example = example_result[
    "turn_table"
].to_pylist()[0]

session_example = example_result[
    "session_record"
]


turn_schema_binding = schema_binding_table(
    TURN_CANDIDATE_SCHEMA,
    turn_example,
    "TURN_CANDIDATE_SCHEMA"
)

session_schema_binding = schema_binding_table(
    SESSION_CANDIDATE_SCHEMA,
    session_example,
    "SESSION_CANDIDATE_SCHEMA"
)


integration_schema_binding = pd.concat(
    [
        turn_schema_binding,
        session_schema_binding
    ],
    ignore_index=True
)


forbidden_names = {
    "target",
    "label",
    "is_correct",
    "objective",
    "objective_raw",
    "learning_objective",
    "fold",
    "prior",
    "objective_prior",
    "oof",
    "prediction",
    "baseline_prediction"
}


parser_parameters = (
    set(
        inspect.signature(
            parse_session_candidate
        ).parameters
    )
    |
    set(
        inspect.signature(
            parse_reconstructed_session
        ).parameters
    )
)


forbidden_parameters_found = sorted(
    parser_parameters
    & forbidden_names
)


ORDER_HASH_SENSITIVE = (
    ordered_sequence_hash(
        "ORDER_TEST",
        ["A", "B", "C"]
    )
    !=
    ordered_sequence_hash(
        "ORDER_TEST",
        ["A", "C", "B"]
    )
)


synthetic_failure_count = int(
    (
        ~integrated_synthetic_tests[
            "passed"
        ]
    ).sum()
)


real_failure_count = int(
    (
        ~integrated_real_audit[
            "passed"
        ]
    ).sum()
)


session_required_nulls = [
    field.name
    for field in SESSION_CANDIDATE_SCHEMA
    if not field.nullable
    and session_example.get(
        field.name
    ) is None
]


turn_required_nulls = [
    field.name
    for field in TURN_CANDIDATE_SCHEMA
    if not field.nullable
    and turn_example.get(
        field.name
    ) is None
]


integration_checks = pd.DataFrame([
    check_row(
        "Structural metadata policy is ready",
        STRUCTURAL_METADATA_READY,
        STRUCTURAL_METADATA_READY
    ),

    check_row(
        "Identity policy is ready",
        IDENTITY_POLICY_READY,
        IDENTITY_POLICY_READY
    ),

    check_row(
        "Ordering conflict audit is ready",
        ORDERING_CONFLICT_AUDIT_READY,
        ORDERING_CONFLICT_AUDIT_READY
    ),

    check_row(
        "Frozen turn schema contains 52 fields",
        len(
            TURN_CANDIDATE_SCHEMA
        ) == 52,
        len(
            TURN_CANDIDATE_SCHEMA
        )
    ),

    check_row(
        "Frozen session schema contains 31 fields",
        len(
            SESSION_CANDIDATE_SCHEMA
        ) == 31,
        len(
            SESSION_CANDIDATE_SCHEMA
        )
    ),

    check_row(
        "Frozen session field names match verified contract",
        set(
            SESSION_CANDIDATE_SCHEMA.names
        )
        == EXPECTED_SESSION_FIELDS,
        len(
            SESSION_CANDIDATE_SCHEMA.names
        )
    ),

    check_row(
        "Turn candidate has no unresolved required fields",
        len(
            turn_required_nulls
        ) == 0,
        turn_required_nulls
    ),

    check_row(
        "Session candidate has no unresolved required fields",
        len(
            session_required_nulls
        ) == 0,
        session_required_nulls
    ),

    check_row(
        "Integrated turn output matches frozen Arrow schema",
        example_result[
            "turn_table"
        ].schema
        == TURN_CANDIDATE_SCHEMA,
        True
    ),

    check_row(
        "Integrated session output matches frozen Arrow schema",
        example_result[
            "session_table"
        ].schema
        == SESSION_CANDIDATE_SCHEMA,
        True
    ),

    check_row(
        "Integrated parser exposes no label or model inputs",
        len(
            forbidden_parameters_found
        ) == 0,
        forbidden_parameters_found
    ),

    check_row(
        "Transcript hashing is order-sensitive",
        ORDER_HASH_SENSITIVE,
        ORDER_HASH_SENSITIVE
    ),

    check_row(
        "All synthetic end-to-end tests passed",
        synthetic_failure_count == 0,
        synthetic_failure_count
    ),

    check_row(
        "All real end-to-end tests passed",
        real_failure_count == 0,
        real_failure_count
    ),

    check_row(
        "All tested real sessions preserve row counts",
        integrated_real_audit[
            "row_conservation"
        ].all(),
        int(
            (
                ~integrated_real_audit[
                    "row_conservation"
                ]
            ).sum()
        )
    ),

    check_row(
        "All tested real sessions preserve raw traceability",
        integrated_real_audit[
            "traceability_exact"
        ].all(),
        int(
            (
                ~integrated_real_audit[
                    "traceability_exact"
                ]
            ).sum()
        )
    ),

    check_row(
        "All tested source-row identities are unique",
        integrated_real_audit[
            "source_uid_unique"
        ].all(),
        int(
            (
                ~integrated_real_audit[
                    "source_uid_unique"
                ]
            ).sum()
        )
    ),

    check_row(
        "All tested logical turn identities are unique",
        integrated_real_audit[
            "turn_uid_unique"
        ].all(),
        int(
            (
                ~integrated_real_audit[
                    "turn_uid_unique"
                ]
            ).sum()
        )
    ),

    check_row(
        "All tested role counts reconcile with turns",
        integrated_real_audit[
            "role_accounting"
        ].all(),
        int(
            (
                ~integrated_real_audit[
                    "role_accounting"
                ]
            ).sum()
        )
    ),

    check_row(
        "All tested integrated parses are deterministic",
        (
            integrated_real_audit[
                "repeat_turn_hash"
            ]
            &
            integrated_real_audit[
                "repeat_session_hash"
            ]
        ).all(),
        int(
            (
                ~(
                    integrated_real_audit[
                        "repeat_turn_hash"
                    ]
                    &
                    integrated_real_audit[
                        "repeat_session_hash"
                    ]
                )
            ).sum()
        )
    )
])


integration_failures = integration_checks[
    ~integration_checks[
        "passed"
    ]
]


INTEGRATED_PARSER_READY = (
    integration_failures.empty
)


integrated_parser_summary = pd.DataFrame({
    "item": [
        "Integrated parser version",
        "Text normalizer",
        "Turn schema fields",
        "Session schema fields",
        "Session non-null fields",
        "Synthetic E2E tests",
        "Passed synthetic E2E tests",
        "Real E2E sessions",
        "Real E2E failures",
        "Forbidden parser inputs",
        "Order-sensitive transcript hashes",
        "Full corpus application",
        "INTEGRATED_PARSER_CONFIG_SHA256",
        "INTEGRATED_PARSER_READY"
    ],

    "value": [
        INTEGRATED_PARSER_VERSION,
        TEXT_NORMALIZER_NAME,
        len(
            TURN_CANDIDATE_SCHEMA
        ),
        len(
            SESSION_CANDIDATE_SCHEMA
        ),
        sum(
            not field.nullable
            for field
            in SESSION_CANDIDATE_SCHEMA
        ),
        len(
            integrated_synthetic_tests
        ),
        int(
            integrated_synthetic_tests[
                "passed"
            ].sum()
        ),
        len(
            integrated_real_audit
        ),
        real_failure_count,
        len(
            forbidden_parameters_found
        ),
        ORDER_HASH_SENSITIVE,
        "DEFER_TO_2.16",
        INTEGRATED_PARSER_CONFIG_SHA256,
        INTEGRATED_PARSER_READY
    ]
})


display(
    integration_schema_binding
)

display(
    integration_checks
)

display(
    integrated_parser_summary
)


assert INTEGRATED_PARSER_READY, (
    "Section 2.15 failed.\n\n"
    + integration_failures[
        [
            "check",
            "detail"
        ]
    ].to_string(
        index=False
    )
)


print("\n" + "=" * 70)
print("TRACE THE ACE — INTEGRATED SESSION PARSER READY")
print("=" * 70)

print(
    f"Turn schema             : "
    f"{len(TURN_CANDIDATE_SCHEMA)}/52"
)

print(
    f"Session schema          : "
    f"{len(SESSION_CANDIDATE_SCHEMA)}/31"
)

print(
    f"Session required fields : "
    f"{sum(not f.nullable for f in SESSION_CANDIDATE_SCHEMA)}/28"
)

print(
    f"Synthetic E2E tests     : "
    f"{int(integrated_synthetic_tests['passed'].sum())}/"
    f"{len(integrated_synthetic_tests)}"
)

print(
    f"Real E2E sessions       : "
    f"{len(integrated_real_audit) - real_failure_count}/"
    f"{len(integrated_real_audit)}"
)

print(
    f"Forbidden parser inputs : "
    f"{len(forbidden_parameters_found)}"
)

print(
    f"Order-sensitive hashing : "
    f"{ORDER_HASH_SENSITIVE}"
)

print(
    f"Full production parse   : "
    f"DEFERRED TO 2.16"
)

print(
    f"INTEGRATED PARSER READY : "
    f"{INTEGRATED_PARSER_READY}"
)

print("=" * 70)

,schema,field,arrow_type,nullable,resolved,value_is_null
0,TURN_CANDIDATE_SCHEMA,session_id,string,False,True,False
1,TURN_CANDIDATE_SCHEMA,turn_uid,string,False,True,False
2,TURN_CANDIDATE_SCHEMA,source_row_uid,string,False,True,False
3,TURN_CANDIDATE_SCHEMA,turn_index,int32,False,True,False
4,TURN_CANDIDATE_SCHEMA,session_id_raw,string,False,True,False
...,...,...,...,...,...,...
78,SESSION_CANDIDATE_SCHEMA,midnight_rollover_count,int32,False,True,False
79,SESSION_CANDIDATE_SCHEMA,ambiguous_order_flag,bool,False,True,False
80,SESSION_CANDIDATE_SCHEMA,raw_transcript_hash,string,False,True,False
81,SESSION_CANDIDATE_SCHEMA,normalized_transcript_hash,string,False,True,False
82,SESSION_CANDIDATE_SCHEMA,quality_warning_count,int32,False,True,False

                                                check  passed detail
0                 Structural metadata policy is ready    True   True
1                            Identity policy is ready    True   True
2                    Ordering conflict audit is ready    True   True
3               Frozen turn schema contains 52 fields    True     52
4            Frozen session schema contains 31 fields    True     31
5   Frozen session field names match verified cont...    True     31
6    Turn candidate has no unresolved required fields    True     []
7   Session candidate has no unresolved required f...    True     []
8   Integrated turn output matches frozen Arrow sc...    True   True
9   Integrated session output matches frozen Arrow...    True   True
10  Integrated parser exposes no label or model in...    True     []
11              Transcript hashing is order-sensitive    True   True
12              All synthetic end-to-end tests passed    True      0
13                   All real end-to-end tests passed    True      0
14       All tested real sessions preserve row counts    True      0
15  All tested real sessions preserve raw traceabi...    True      0
16        All tested source-row identities are unique    True      0
17      All tested logical turn identities are unique    True      0
18        All tested role counts reconcile with turns    True      0
19     All tested integrated parses are deterministic    True      0

,item,value
0,Integrated parser version,1.0
1,Text normalizer,normalize_text
2,Turn schema fields,52
3,Session schema fields,31
4,Session non-null fields,28
5,Synthetic E2E tests,12
6,Passed synthetic E2E tests,12
7,Real E2E sessions,8
8,Real E2E failures,0
9,Forbidden parser inputs,0
10,Order-sensitive transcript hashes,True
11,Full corpus application,DEFER_TO_2.16
12,INTEGRATED_PARSER_CONFIG_SHA256,83d9f86ad2fba7d921dd0cfb864872ee7607f28e209066...
13,INTEGRATED_PARSER_READY,True

======================================================================
TRACE THE ACE — INTEGRATED SESSION PARSER READY
======================================================================
Turn schema             : 52/52
Session schema          : 31/31
Session required fields : 28/28
Synthetic E2E tests     : 12/12
Real E2E sessions       : 8/8
Forbidden parser inputs : 0
Order-sensitive hashing : True
Full production parse   : DEFERRED TO 2.16
INTEGRATED PARSER READY : True
======================================================================

# Section 2.16 — Full-Corpus Streaming Production Parse

This section executes the certified integrated parser across the complete transcript corpus.
All transcript files are processed in deterministic relative-path order and one session is parsed at a time.
The frozen 52-field turn schema and 31-field session schema are enforced during every write.
Source file hashes are checked against the previously audited per-file fingerprints before data is committed.
Parsed sessions are written in bounded Parquet parts to avoid loading the full corpus into memory.
A checkpoint allows a failed or interrupted run to resume only under the identical parser and source contract.
No target, objective, fold statistic, prediction, or model-derived information enters this production pass.
Temporary parts are validated before being compacted into the two candidate Parquet artifacts.
Final files are reopened, row counts and schemas are verified, hashed, and only then atomically promoted.
Candidate outputs remain non-canonical until the independent integrity notebook certifies them.
The section ends with `PRODUCTION_PARSE_READY`.

In [52]:
# ============================================================
# 2.16.1 — PRODUCTION CONTRACT & ENTRY GATE
# ============================================================

import os, re, gc, json, time, shutil, hashlib
from pathlib import Path, PurePosixPath
from datetime import datetime, timezone

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

assert INTEGRATED_PARSER_READY, "Section 2.15 must pass before production parsing."
assert len(TURN_CANDIDATE_SCHEMA) == 52 and len(SESSION_CANDIDATE_SCHEMA) == 31

PRODUCTION_PARSE_VERSION = "1.0"
PRODUCTION_BATCH_SESSIONS = 250
PRODUCTION_PROGRESS_EVERY = 2500
PRODUCTION_ALLOW_FINAL_OVERWRITE = False

# ---------- Resolve frozen contract and output root ----------

def resolve_contract_and_output():
    contract = globals().get("data_contract", globals().get("DATA_CONTRACT"))
    contract_path = globals().get("DATA_CONTRACT_PATH", globals().get("data_contract_path"))

    if contract is None and contract_path is not None and Path(contract_path).exists():
        with open(contract_path, "r", encoding="utf-8") as f:
            contract = json.load(f)

    if contract is None:
        candidates = []
        if "PHASE1_ROOT" in globals(): candidates.append(Path(PHASE1_ROOT) / "data_contract.json")
        if "INVENTORY_OUTPUT_DIR" in globals(): candidates.append(Path(INVENTORY_OUTPUT_DIR).parent / "data_contract.json")
        contract_path = next((p for p in candidates if p.exists()), None)
        if contract_path is not None:
            with open(contract_path, "r", encoding="utf-8") as f: contract = json.load(f)

    assert isinstance(contract, dict), "Could not resolve the frozen data_contract.json."
    if contract_path is None:
        if "PHASE1_ROOT" in globals(): contract_path = Path(PHASE1_ROOT) / "data_contract.json"
        elif "INVENTORY_OUTPUT_DIR" in globals(): contract_path = Path(INVENTORY_OUTPUT_DIR).parent / "data_contract.json"
        else: raise RuntimeError("Could not resolve the Phase-1 output root.")

    root = Path(contract_path).parent
    return Path(contract_path), contract, root / "02_turn_parser"

DATA_CONTRACT_PATH_216, DATA_CONTRACT_216, PARSER_OUTPUT_DIR = resolve_contract_and_output()
PARSER_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TURNS_FINAL = PARSER_OUTPUT_DIR / "turns_candidate.parquet"
SESSIONS_FINAL = PARSER_OUTPUT_DIR / "sessions_candidate.parquet"
PRODUCTION_TMP_ROOT = PARSER_OUTPUT_DIR / ".production_tmp"
TURN_PART_DIR = PRODUCTION_TMP_ROOT / "turn_parts"
SESSION_PART_DIR = PRODUCTION_TMP_ROOT / "session_parts"
CHECKPOINT_PATH = PRODUCTION_TMP_ROOT / "checkpoint.json"
TURNS_TMP = PRODUCTION_TMP_ROOT / "turns_candidate.tmp.parquet"
SESSIONS_TMP = PRODUCTION_TMP_ROOT / "sessions_candidate.tmp.parquet"

EXPECTED_FILES = int(DATA_CONTRACT_216["source_binding"]["expected_transcript_file_count"])
EXPECTED_SESSIONS = int(DATA_CONTRACT_216["source_binding"]["expected_session_count"])
EXPECTED_TURNS = int(TOTAL_RAW_ROWS)
CONTRACT_TRANSCRIPT_SHA256 = DATA_CONTRACT_216["source_binding"]["transcript_directory_sha256"]

# ---------- Resolve frozen per-file hashes from previous exhaustive audits ----------

def normalize_relative_file(value):
    text = str(value).replace("\\", "/")
    p = Path(text)
    if p.is_absolute():
        try: text = p.relative_to(Path(TRANSCRIPT_ROOT)).as_posix()
        except ValueError: text = p.name
    return PurePosixPath(text).as_posix()

def resolve_frozen_source_hashes():
    path_names = ["relative_file", "relative_path", "source_file_relative"]
    hash_names = ["file_sha256", "sha256", "content_sha256"]
    candidates = []

    for name, obj in list(globals().items()):
        if isinstance(obj, pd.DataFrame) and len(obj) == EXPECTED_FILES:
            path_col = next((c for c in path_names if c in obj.columns), None)
            hash_col = next((c for c in hash_names if c in obj.columns), None)
            if path_col and hash_col:
                temp = obj[[path_col, hash_col]].dropna().copy()
                temp[path_col] = temp[path_col].map(normalize_relative_file)
                temp[hash_col] = temp[hash_col].astype(str).str.lower()
                valid = temp[hash_col].str.fullmatch(r"[0-9a-f]{64}").all()
                if valid and temp[path_col].nunique() == EXPECTED_FILES:
                    score = 3 * ("inventory" in name.lower()) + 2 * ("manifest" in name.lower()) + ("audit" in name.lower())
                    candidates.append((score, name, dict(zip(temp[path_col], temp[hash_col]))))

        if isinstance(obj, dict) and len(obj) == EXPECTED_FILES:
            try:
                normalized = {normalize_relative_file(k): str(v).lower() for k, v in obj.items()}
                valid = len(normalized) == EXPECTED_FILES and all(re.fullmatch(r"[0-9a-f]{64}", v) for v in normalized.values())
                if valid: candidates.append((1, name, normalized))
            except Exception:
                pass

    if not candidates: return None, None
    candidates.sort(key=lambda x: (-x[0], x[1]))
    return candidates[0][1], candidates[0][2]

FROZEN_HASH_SOURCE, FROZEN_SOURCE_HASHES = resolve_frozen_source_hashes()
assert FROZEN_SOURCE_HASHES is not None, (
    "Could not resolve the frozen 22,821-file SHA256 map from previous parser audits. "
    "A full per-file fingerprint table must be available before production parsing."
)

# ---------- Freeze deterministic source list and production signature ----------

current_files = sorted(
    normalize_relative_file(p.relative_to(TRANSCRIPT_ROOT))
    for p in Path(TRANSCRIPT_ROOT).rglob("*.csv")
)

frozen_files = sorted(FROZEN_SOURCE_HASHES)
source_membership_match = current_files == frozen_files

TURN_SCHEMA_SHA256 = canonical_hash(
    "turn_candidate_schema", "1.0",
    [(f.name, str(f.type), f.nullable) for f in TURN_CANDIDATE_SCHEMA]
)

SESSION_SCHEMA_SHA256 = canonical_hash(
    "session_candidate_schema", "1.0",
    [(f.name, str(f.type), f.nullable) for f in SESSION_CANDIDATE_SCHEMA]
)

FROZEN_SOURCE_MANIFEST_SHA256 = canonical_hash(
    "frozen_transcript_file_manifest", "1.0",
    [{"relative_file": f, "file_sha256": FROZEN_SOURCE_HASHES[f]} for f in frozen_files]
)

PRODUCTION_CONFIG = {
    "version": PRODUCTION_PARSE_VERSION,
    "integrated_parser_config_sha256": INTEGRATED_PARSER_CONFIG_SHA256,
    "turn_schema_sha256": TURN_SCHEMA_SHA256,
    "session_schema_sha256": SESSION_SCHEMA_SHA256,
    "frozen_source_manifest_sha256": FROZEN_SOURCE_MANIFEST_SHA256,
    "expected_files": EXPECTED_FILES,
    "expected_sessions": EXPECTED_SESSIONS,
    "expected_turns": EXPECTED_TURNS,
    "batch_sessions": PRODUCTION_BATCH_SESSIONS
}

PRODUCTION_SIGNATURE = canonical_hash("production_parse_config", PRODUCTION_PARSE_VERSION, PRODUCTION_CONFIG)

production_entry_checks = pd.DataFrame([
    check_row("Integrated parser is certified", INTEGRATED_PARSER_READY, INTEGRATED_PARSER_READY),
    check_row("Transcript file count matches contract", len(current_files) == EXPECTED_FILES, f"{len(current_files)} / {EXPECTED_FILES}"),
    check_row("Transcript source membership matches frozen inventory", source_membership_match, f"{len(current_files)} files"),
    check_row("Expected session count matches file count", EXPECTED_SESSIONS == EXPECTED_FILES, f"{EXPECTED_SESSIONS} / {EXPECTED_FILES}"),
    check_row("Expected turn census is frozen", EXPECTED_TURNS == 6139854, EXPECTED_TURNS),
    check_row("Turn schema remains frozen", len(TURN_CANDIDATE_SCHEMA) == 52, len(TURN_CANDIDATE_SCHEMA)),
    check_row("Session schema remains frozen", len(SESSION_CANDIDATE_SCHEMA) == 31, len(SESSION_CANDIDATE_SCHEMA)),
    check_row("Frozen per-file SHA256 map is complete", len(FROZEN_SOURCE_HASHES) == EXPECTED_FILES, len(FROZEN_SOURCE_HASHES)),
    check_row("Final outputs are protected from accidental overwrite",
              PRODUCTION_ALLOW_FINAL_OVERWRITE or (not TURNS_FINAL.exists() and not SESSIONS_FINAL.exists()),
              f"turns_exists={TURNS_FINAL.exists()}, sessions_exists={SESSIONS_FINAL.exists()}")
])

PRODUCTION_ENTRY_READY = production_entry_checks["passed"].all()
display(production_entry_checks)

assert PRODUCTION_ENTRY_READY, (
    "Section 2.16 production entry gate failed.\n\n"
    + production_entry_checks.loc[~production_entry_checks["passed"], ["check", "detail"]].to_string(index=False)
)

print("\n" + "=" * 68)
print("TRACE THE ACE — PRODUCTION PARSE CONTRACT READY")
print("=" * 68)
print(f"Transcript files       : {EXPECTED_FILES:,}")
print(f"Expected sessions      : {EXPECTED_SESSIONS:,}")
print(f"Expected turns         : {EXPECTED_TURNS:,}")
print(f"Turn schema            : {len(TURN_CANDIDATE_SCHEMA)} fields")
print(f"Session schema         : {len(SESSION_CANDIDATE_SCHEMA)} fields")
print(f"Frozen hash source     : {FROZEN_HASH_SOURCE}")
print(f"Batch size             : {PRODUCTION_BATCH_SESSIONS} sessions")
print(f"PRODUCTION ENTRY READY : {PRODUCTION_ENTRY_READY}")
print("=" * 68)

,check,passed,detail
0,Integrated parser is certified,True,True
1,Transcript file count matches contract,True,22821 / 22821
2,Transcript source membership matches frozen in...,True,22821 files
3,Expected session count matches file count,True,22821 / 22821
4,Expected turn census is frozen,True,6139854
5,Turn schema remains frozen,True,52
6,Session schema remains frozen,True,31
7,Frozen per-file SHA256 map is complete,True,22821
8,Final outputs are protected from accidental ov...,True,"turns_exists=False, sessions_exists=False"

====================================================================
TRACE THE ACE — PRODUCTION PARSE CONTRACT READY
====================================================================
Transcript files       : 22,821
Expected sessions      : 22,821
Expected turns         : 6,139,854
Turn schema            : 52 fields
Session schema         : 31 fields
Frozen hash source     : raw_format_file_profile
Batch size             : 250 sessions
PRODUCTION ENTRY READY : True
====================================================================

In [52]:
# ============================================================
# 2.16.2 — FULL-CORPUS STREAMING PARSE
# ============================================================

def save_checkpoint(state):
    CHECKPOINT_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = CHECKPOINT_PATH.with_suffix(".json.tmp")
    with open(tmp, "w", encoding="utf-8") as f: json.dump(state, f, indent=2, sort_keys=True)
    os.replace(tmp, CHECKPOINT_PATH)

def write_part(turn_tables, session_tables, part_index):
    turn_table = pa.concat_tables(turn_tables)
    session_table = pa.concat_tables(session_tables)

    assert turn_table.schema == TURN_CANDIDATE_SCHEMA
    assert session_table.schema == SESSION_CANDIDATE_SCHEMA

    turn_path = TURN_PART_DIR / f"turns_part_{part_index:05d}.parquet"
    session_path = SESSION_PART_DIR / f"sessions_part_{part_index:05d}.parquet"

    pq.write_table(turn_table, turn_path, compression="zstd", use_dictionary=True, row_group_size=100000)
    pq.write_table(session_table, session_path, compression="zstd", use_dictionary=True, row_group_size=10000)

    return len(turn_table), len(session_table)

# ---------- Initialize or safely resume ----------

if CHECKPOINT_PATH.exists():
    with open(CHECKPOINT_PATH, "r", encoding="utf-8") as f: production_state = json.load(f)

    assert production_state["production_signature"] == PRODUCTION_SIGNATURE, "Checkpoint belongs to a different parser/source contract."
    assert production_state["frozen_source_manifest_sha256"] == FROZEN_SOURCE_MANIFEST_SHA256, "Checkpoint source fingerprint mismatch."

    completed_files = int(production_state["completed_files"])
    completed_turns = int(production_state["completed_turns"])
    completed_sessions = int(production_state["completed_sessions"])
    source_verified = int(production_state["source_verified"])
    part_index = int(production_state["part_count"])

    for i in range(part_index):
        assert (TURN_PART_DIR / f"turns_part_{i:05d}.parquet").exists(), f"Missing committed turn part {i}."
        assert (SESSION_PART_DIR / f"sessions_part_{i:05d}.parquet").exists(), f"Missing committed session part {i}."

    for p in TURN_PART_DIR.glob("turns_part_*.parquet"):
        idx = int(re.search(r"(\d+)$", p.stem).group(1))
        if idx >= part_index: p.unlink()

    for p in SESSION_PART_DIR.glob("sessions_part_*.parquet"):
        idx = int(re.search(r"(\d+)$", p.stem).group(1))
        if idx >= part_index: p.unlink()

    print(f"Resuming production parse from file {completed_files:,}/{EXPECTED_FILES:,}.")

else:
    if PRODUCTION_TMP_ROOT.exists(): shutil.rmtree(PRODUCTION_TMP_ROOT)

    TURN_PART_DIR.mkdir(parents=True, exist_ok=True)
    SESSION_PART_DIR.mkdir(parents=True, exist_ok=True)

    completed_files = completed_turns = completed_sessions = source_verified = part_index = 0
    production_state = {
        "production_signature": PRODUCTION_SIGNATURE,
        "frozen_source_manifest_sha256": FROZEN_SOURCE_MANIFEST_SHA256,
        "completed_files": 0, "completed_turns": 0, "completed_sessions": 0,
        "source_verified": 0, "part_count": 0,
        "started_at_utc": datetime.now(timezone.utc).isoformat()
    }
    save_checkpoint(production_state)
    print("Starting a new production parse.")

# ---------- Stream corpus ----------

turn_buffer, session_buffer = [], []
started = time.time()

for file_index in range(completed_files, EXPECTED_FILES):
    relative_file = frozen_files[file_index]
    source_path = Path(TRANSCRIPT_ROOT) / Path(relative_file)
    expected_session_id = Path(relative_file).stem

    result = parse_session_candidate(source_path, expected_session_id=expected_session_id)
    turn_table = result["turn_table"]
    session_table = result["session_table"]
    session_record = result["session_record"]

    assert turn_table.schema == TURN_CANDIDATE_SCHEMA, f"Turn schema drift: {relative_file}"
    assert session_table.schema == SESSION_CANDIDATE_SCHEMA, f"Session schema drift: {relative_file}"
    assert len(session_table) == 1, f"Expected one session row: {relative_file}"
    assert len(turn_table) == int(session_record["source_raw_row_count"]) == int(session_record["n_turns"]), f"Row conservation failure: {relative_file}"
    assert session_record["session_id"] == expected_session_id, f"Session identity failure: {relative_file}"

    current_sha = str(session_record["file_sha256"]).lower()
    expected_sha = FROZEN_SOURCE_HASHES[relative_file]
    assert current_sha == expected_sha, f"Source SHA256 drift detected: {relative_file}"

    turn_buffer.append(turn_table)
    session_buffer.append(session_table)

    completed_files += 1
    completed_turns += len(turn_table)
    completed_sessions += 1
    source_verified += 1

    flush_now = len(session_buffer) >= PRODUCTION_BATCH_SESSIONS or completed_files == EXPECTED_FILES

    if flush_now:
        written_turns, written_sessions = write_part(turn_buffer, session_buffer, part_index)
        assert written_turns == sum(len(t) for t in turn_buffer)
        assert written_sessions == len(session_buffer)

        part_index += 1
        turn_buffer.clear()
        session_buffer.clear()
        gc.collect()

        production_state.update({
            "completed_files": completed_files,
            "completed_turns": completed_turns,
            "completed_sessions": completed_sessions,
            "source_verified": source_verified,
            "part_count": part_index,
            "updated_at_utc": datetime.now(timezone.utc).isoformat()
        })
        save_checkpoint(production_state)

    if completed_files % PRODUCTION_PROGRESS_EVERY == 0 or completed_files == EXPECTED_FILES:
        elapsed = (time.time() - started) / 60
        print(
            f"Parsed {completed_files:,}/{EXPECTED_FILES:,} files | "
            f"Turns {completed_turns:,} | Parts {part_index:,} | "
            f"Elapsed {elapsed:.1f} min"
        )

FULL_STREAM_PARSE_COMPLETE = (
    completed_files == EXPECTED_FILES
    and completed_sessions == EXPECTED_SESSIONS
    and completed_turns == EXPECTED_TURNS
    and source_verified == EXPECTED_FILES
)

stream_parse_summary = pd.DataFrame({
    "item": [
        "Files expected", "Files parsed", "Sessions expected", "Sessions parsed",
        "Turns expected", "Turns parsed", "Source hashes verified",
        "Parquet part pairs", "Parse failures", "FULL_STREAM_PARSE_COMPLETE"
    ],
    "value": [
        EXPECTED_FILES, completed_files, EXPECTED_SESSIONS, completed_sessions,
        EXPECTED_TURNS, completed_turns, source_verified,
        part_index, 0, FULL_STREAM_PARSE_COMPLETE
    ]
})

display(stream_parse_summary)

assert FULL_STREAM_PARSE_COMPLETE, (
    "Full streaming parse did not reconcile with the frozen corpus census."
)

Starting a new production parse.
Parsed 2,500/22,821 files | Turns 664,944 | Parts 10 | Elapsed 1.4 min
Parsed 5,000/22,821 files | Turns 1,336,554 | Parts 20 | Elapsed 3.0 min
Parsed 7,500/22,821 files | Turns 2,012,198 | Parts 30 | Elapsed 4.5 min
Parsed 10,000/22,821 files | Turns 2,692,417 | Parts 40 | Elapsed 6.1 min
Parsed 12,500/22,821 files | Turns 3,364,873 | Parts 50 | Elapsed 7.7 min
Parsed 15,000/22,821 files | Turns 4,034,815 | Parts 60 | Elapsed 9.2 min
Parsed 17,500/22,821 files | Turns 4,710,356 | Parts 70 | Elapsed 10.7 min
Parsed 20,000/22,821 files | Turns 5,377,157 | Parts 80 | Elapsed 12.2 min
Parsed 22,500/22,821 files | Turns 6,052,016 | Parts 90 | Elapsed 13.7 min
Parsed 22,821/22,821 files | Turns 6,139,854 | Parts 92 | Elapsed 13.9 min

                         item    value
0              Files expected    22821
1                Files parsed    22821
2           Sessions expected    22821
3             Sessions parsed    22821
4              Turns expected  6139854
5                Turns parsed  6139854
6      Source hashes verified    22821
7          Parquet part pairs       92
8              Parse failures        0
9  FULL_STREAM_PARSE_COMPLETE     True

In [53]:
# ============================================================
# 2.16 — RELEASE STALE WINDOWS FILE HANDLES
# ============================================================

import gc

handle_names = [
    "turn_pf", "session_pf", "turn_verify", "session_verify",
    "parquet", "turn_metadata", "session_metadata"
]

closed_handles = []

for name in handle_names:
    obj = globals().get(name)

    if obj is not None:
        try:
            if hasattr(obj, "close"):
                obj.close()
        except Exception:
            pass

        globals().pop(name, None)
        closed_handles.append(name)

gc.collect()

print("Released objects :", closed_handles)
print("TURNS_TMP exists :", TURNS_TMP.exists())
print("SESSIONS_TMP exists:", SESSIONS_TMP.exists())

Released objects : []
TURNS_TMP exists : False
SESSIONS_TMP exists: False

In [55]:
from pathlib import Path

print("=" * 80)
print("2.16.3 PRE-PROMOTION ARTIFACT DIAGNOSTIC")
print("=" * 80)

print(f"FULL_STREAM_PARSE_COMPLETE = {FULL_STREAM_PARSE_COMPLETE!r}")

print(f"\nTURNS_TMP:")
print(f"  value  = {TURNS_TMP}")
print(f"  exists = {TURNS_TMP.exists()}")
print(f"  parent = {TURNS_TMP.parent}")
print(f"  parent exists = {TURNS_TMP.parent.exists()}")

print(f"\nSESSIONS_TMP:")
print(f"  value  = {SESSIONS_TMP}")
print(f"  exists = {SESSIONS_TMP.exists()}")
print(f"  parent = {SESSIONS_TMP.parent}")
print(f"  parent exists = {SESSIONS_TMP.parent.exists()}")

if TURNS_TMP.parent.exists():
    print("\nTMP DIRECTORY CONTENTS:")
    for p in sorted(TURNS_TMP.parent.iterdir()):
        print(" ", p.name)

================================================================================
2.16.3 PRE-PROMOTION ARTIFACT DIAGNOSTIC
================================================================================
FULL_STREAM_PARSE_COMPLETE = True

TURNS_TMP:
  value  = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\turns_candidate.tmp.parquet
  exists = False
  parent = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp
  parent exists = True

SESSIONS_TMP:
  value  = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\sessions_candidate.tmp.parquet
  exists = False
  parent = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp
  parent exists = True

TMP DIRECTORY CONTENTS:
  checkpoint.json
  session_parts
  turn_parts

In [60]:
# ============================================================
# RECOVERY — RELEASE WINDOWS PARQUET HANDLES
# ============================================================

import gc
import os
from pathlib import Path

print("=" * 80)
print("RECOVERY — WINDOWS PARQUET HANDLE RELEASE")
print("=" * 80)

# Release any known local references from the previous
# consolidation attempt.

for _name in [
    "stage_pf",
    "final_pf",
    "turn_consolidation",
    "session_consolidation",
]:
    if _name in globals():
        try:
            obj = globals()[_name]

            if hasattr(obj, "close"):
                obj.close()

        except Exception:
            pass

        try:
            del globals()[_name]
        except Exception:
            pass


gc.collect()
gc.collect()

print("Parquet handles released.")

================================================================================
RECOVERY — WINDOWS PARQUET HANDLE RELEASE
================================================================================
Parquet handles released.

In [1]:
from pathlib import Path

BUILD_TMP = Path(
    r"D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\turns_candidate.tmp.parquet.build.tmp"
)

print("=" * 80)
print("POST-KERNEL-RESTART FILE LOCK CHECK")
print("=" * 80)

print("Exists:", BUILD_TMP.exists())

if BUILD_TMP.exists():
    print(
        "Size MB:",
        round(BUILD_TMP.stat().st_size / 1024**2, 2)
    )

================================================================================
POST-KERNEL-RESTART FILE LOCK CHECK
================================================================================
Exists: True
Size MB: 1132.62

In [55]:
# ============================================================
# 2.16.2R — RESTORE COMPLETED STREAMING-PARSE STATE
# ============================================================

from pathlib import Path
import json
import gc

print("=" * 80)
print("2.16.2R — RESTORE COMPLETED STREAMING-PARSE STATE")
print("=" * 80)


# ------------------------------------------------------------
# 1. Locate checkpoint
# ------------------------------------------------------------

assert PRODUCTION_TMP_ROOT.exists(), (
    f"Production temp root not found: {PRODUCTION_TMP_ROOT}"
)

CHECKPOINT_PATH = (
    PRODUCTION_TMP_ROOT / "checkpoint.json"
)

assert CHECKPOINT_PATH.exists(), (
    f"Parser checkpoint not found: {CHECKPOINT_PATH}"
)


# ------------------------------------------------------------
# 2. Load checkpoint
# ------------------------------------------------------------

with open(
    CHECKPOINT_PATH,
    "r",
    encoding="utf-8",
) as f:

    production_state = json.load(f)


print("\nCheckpoint:")
for key, value in production_state.items():
    print(f"  {key}: {value}")


# ------------------------------------------------------------
# 3. Restore expected completion state
# ------------------------------------------------------------

completed_files = int(
    production_state["completed_files"]
)

completed_sessions = int(
    production_state["completed_sessions"]
)

completed_turns = int(
    production_state["completed_turns"]
)

source_verified = int(
    production_state["source_verified"]
)

part_count = int(
    production_state["part_count"]
)


# ------------------------------------------------------------
# 4. Verify against frozen expected values
# ------------------------------------------------------------

assert completed_files == EXPECTED_FILES, (
    f"Checkpoint files mismatch: "
    f"{completed_files} != {EXPECTED_FILES}"
)

assert completed_sessions == EXPECTED_SESSIONS, (
    f"Checkpoint sessions mismatch: "
    f"{completed_sessions} != {EXPECTED_SESSIONS}"
)

assert completed_turns == EXPECTED_TURNS, (
    f"Checkpoint turns mismatch: "
    f"{completed_turns} != {EXPECTED_TURNS}"
)

assert source_verified == EXPECTED_FILES, (
    f"Checkpoint source verification mismatch: "
    f"{source_verified} != {EXPECTED_FILES}"
)

assert part_count > 0, (
    "Checkpoint contains no production parts."
)


# ------------------------------------------------------------
# 5. Verify actual part directories
# ------------------------------------------------------------

assert TURN_PART_DIR.exists(), (
    f"Turn part directory missing: {TURN_PART_DIR}"
)

assert SESSION_PART_DIR.exists(), (
    f"Session part directory missing: {SESSION_PART_DIR}"
)


turn_parts = sorted(
    TURN_PART_DIR.glob(
        "turns_part_*.parquet"
    )
)

session_parts = sorted(
    SESSION_PART_DIR.glob(
        "sessions_part_*.parquet"
    )
)


print("\nFilesystem parts:")
print(
    f"  Turn parts    : {len(turn_parts):,}"
)

print(
    f"  Session parts : {len(session_parts):,}"
)

assert len(turn_parts) == part_count, (
    f"Turn part count mismatch: "
    f"{len(turn_parts)} != {part_count}"
)

assert len(session_parts) == part_count, (
    f"Session part count mismatch: "
    f"{len(session_parts)} != {part_count}"
)


# ------------------------------------------------------------
# 6. Restore streaming-complete flag
# ------------------------------------------------------------

FULL_STREAM_PARSE_COMPLETE = (
    completed_files == EXPECTED_FILES
    and
    completed_sessions == EXPECTED_SESSIONS
    and
    completed_turns == EXPECTED_TURNS
    and
    source_verified == EXPECTED_FILES
    and
    len(turn_parts) == part_count
    and
    len(session_parts) == part_count
)


print("\n" + "=" * 80)
print("RESTORED STREAMING STATE")
print("=" * 80)

print(
    f"Completed files       : "
    f"{completed_files:,}/{EXPECTED_FILES:,}"
)

print(
    f"Completed sessions    : "
    f"{completed_sessions:,}/{EXPECTED_SESSIONS:,}"
)

print(
    f"Completed turns       : "
    f"{completed_turns:,}/{EXPECTED_TURNS:,}"
)

print(
    f"Source verified       : "
    f"{source_verified:,}/{EXPECTED_FILES:,}"
)

print(
    f"Turn parts            : "
    f"{len(turn_parts):,}"
)

print(
    f"Session parts         : "
    f"{len(session_parts):,}"
)

print(
    f"Part count checkpoint : "
    f"{part_count:,}"
)

print(
    f"FULL_STREAM_PARSE_COMPLETE : "
    f"{FULL_STREAM_PARSE_COMPLETE}"
)

print("=" * 80)


assert FULL_STREAM_PARSE_COMPLETE, (
    "Checkpoint does not prove a complete streaming parse."
)

================================================================================
2.16.2R — RESTORE COMPLETED STREAMING-PARSE STATE
================================================================================

Checkpoint:
  completed_files: 22821
  completed_sessions: 22821
  completed_turns: 6139854
  frozen_source_manifest_sha256: 5e7b5295758161951f142f57211fcc741cda09fb984a6b38788df60245338807
  part_count: 92
  production_signature: 65439dde10608145711face0013629ba1c159907ca5286349790c4edd8edeaec
  source_verified: 22821
  started_at_utc: 2026-08-12T14:07:08.004024+00:00
  updated_at_utc: 2026-08-12T14:21:02.852028+00:00

Filesystem parts:
  Turn parts    : 92
  Session parts : 92

================================================================================
RESTORED STREAMING STATE
================================================================================
Completed files       : 22,821/22,821
Completed sessions    : 22,821/22,821
Completed turns       : 6,139,854/6,139,854
Source verified       : 22,821/22,821
Turn parts            : 92
Session parts         : 92
Part count checkpoint : 92
FULL_STREAM_PARSE_COMPLETE : True
================================================================================

In [58]:
# ============================================================
# 2.16.2B — ROBUST WINDOWS-SAFE PART CONSOLIDATION
#
# Strategy:
#   Parent notebook
#       ↓
#   Child Python process builds + closes parquet
#       ↓
#   Child process exits
#       ↓
#   Parent verifies + promotes
#
# This avoids Windows file-handle retention inside the
# notebook kernel.
# ============================================================

import os
import sys
import json
import gc
import subprocess
import tempfile
from pathlib import Path

import pyarrow.parquet as pq


print("=" * 80)
print("2.16.2B — ROBUST WINDOWS-SAFE PART CONSOLIDATION")
print("=" * 80)


# ------------------------------------------------------------
# 1. Preconditions
# ------------------------------------------------------------

assert FULL_STREAM_PARSE_COMPLETE, (
    "Streaming parse is not complete."
)

assert PRODUCTION_TMP_ROOT.exists(), (
    f"Production temp root missing: {PRODUCTION_TMP_ROOT}"
)

assert TURN_PART_DIR.exists(), (
    f"Turn part directory missing: {TURN_PART_DIR}"
)

assert SESSION_PART_DIR.exists(), (
    f"Session part directory missing: {SESSION_PART_DIR}"
)


# ------------------------------------------------------------
# 2. Discover parts
# ------------------------------------------------------------

turn_parts = sorted(
    TURN_PART_DIR.glob("turns_part_*.parquet")
)

session_parts = sorted(
    SESSION_PART_DIR.glob("sessions_part_*.parquet")
)

print("\nPart inventory:")
print(f"  Turn parts    : {len(turn_parts):,}")
print(f"  Session parts : {len(session_parts):,}")


assert len(turn_parts) == len(session_parts)

assert len(turn_parts) == int(
    production_state["part_count"]
)


# ------------------------------------------------------------
# 3. Verify row counts from part metadata
# ------------------------------------------------------------

turn_rows_total = 0
session_rows_total = 0

for p in turn_parts:

    pf = pq.ParquetFile(p)

    try:
        turn_rows_total += int(
            pf.metadata.num_rows
        )
    finally:
        if hasattr(pf, "close"):
            pf.close()

    del pf


for p in session_parts:

    pf = pq.ParquetFile(p)

    try:
        session_rows_total += int(
            pf.metadata.num_rows
        )
    finally:
        if hasattr(pf, "close"):
            pf.close()

    del pf


gc.collect()
gc.collect()


print("\nPart accounting:")
print(
    f"  Turn rows from parts    : "
    f"{turn_rows_total:,}"
)

print(
    f"  Session rows from parts : "
    f"{session_rows_total:,}"
)

print(
    f"  Expected turns          : "
    f"{EXPECTED_TURNS:,}"
)

print(
    f"  Expected sessions       : "
    f"{EXPECTED_SESSIONS:,}"
)


assert turn_rows_total == EXPECTED_TURNS

assert session_rows_total == EXPECTED_SESSIONS


# ------------------------------------------------------------
# 4. Child-process consolidation script
# ------------------------------------------------------------

CHILD_SCRIPT = r'''
import sys
import gc
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq


parts_dir = Path(sys.argv[1])
output_path = Path(sys.argv[2])
expected_rows = int(sys.argv[3])
label = sys.argv[4]


parts = sorted(
    parts_dir.glob(
        f"{label}_part_*.parquet"
    )
)

if not parts:
    raise RuntimeError(
        f"No {label} parquet parts found."
    )


# ------------------------------------------------------------
# Read schema from first part
# ------------------------------------------------------------

first_pf = pq.ParquetFile(
    parts[0]
)

try:
    schema = first_pf.schema_arrow
finally:
    if hasattr(first_pf, "close"):
        first_pf.close()

del first_pf
gc.collect()


# ------------------------------------------------------------
# Build temporary artifact
# ------------------------------------------------------------

build_path = Path(
    str(output_path)
    + ".build.tmp"
)

if build_path.exists():
    build_path.unlink()


writer = None
total_rows = 0


try:

    for part_index, part_path in enumerate(parts):

        pf = pq.ParquetFile(
            part_path
        )

        try:

            if pf.schema_arrow != schema:
                raise RuntimeError(
                    f"{label} schema mismatch: "
                    f"{part_path.name}"
                )

            if writer is None:

                writer = pq.ParquetWriter(
                    build_path,
                    schema,
                    compression="zstd",
                    use_dictionary=True,
                )

            for batch in pf.iter_batches(
                batch_size=100_000
            ):

                table = pa.Table.from_batches(
                    [batch],
                    schema=schema,
                )

                writer.write_table(
                    table,
                    row_group_size=batch.num_rows,
                )

                total_rows += (
                    batch.num_rows
                )

                del table
                del batch

        finally:

            if hasattr(pf, "close"):
                pf.close()

            del pf
            gc.collect()

        if (
            (part_index + 1) % 10 == 0
            or
            (part_index + 1) == len(parts)
        ):

            print(
                f"{label}: "
                f"{part_index + 1:,}/"
                f"{len(parts):,} parts | "
                f"{total_rows:,} rows",
                flush=True,
            )

finally:

    if writer is not None:
        writer.close()

    writer = None

    gc.collect()
    gc.collect()


# ------------------------------------------------------------
# Verify build artifact
# ------------------------------------------------------------

if not build_path.exists():
    raise RuntimeError(
        f"{label} build artifact missing."
    )


verify_pf = pq.ParquetFile(
    build_path
)

try:

    actual_rows = int(
        verify_pf.metadata.num_rows
    )

    actual_schema = (
        verify_pf.schema_arrow
    )

    if actual_rows != expected_rows:
        raise RuntimeError(
            f"{label} row mismatch: "
            f"{actual_rows} != {expected_rows}"
        )

    if actual_schema != schema:
        raise RuntimeError(
            f"{label} final schema mismatch."
        )

finally:

    if hasattr(verify_pf, "close"):
        verify_pf.close()

    del verify_pf
    gc.collect()
    gc.collect()


print(
    f"{label} BUILD COMPLETE: "
    f"{actual_rows:,} rows",
    flush=True,
)

# IMPORTANT:
# Do NOT rename here.
# Child process exits after all native handles close.
'''


# ------------------------------------------------------------
# 5. Helper — run consolidation in isolated process
# ------------------------------------------------------------

def run_child_consolidation(
    parts_dir,
    output_path,
    expected_rows,
    label,
):

    parts_dir = Path(parts_dir)
    output_path = Path(output_path)

    command = [
        sys.executable,
        "-c",
        CHILD_SCRIPT,
        str(parts_dir),
        str(output_path),
        str(expected_rows),
        label,
    ]

    print(
        f"\nStarting isolated {label} "
        "consolidation process..."
    )

    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
    )

    print(result.stdout)

    if result.returncode != 0:

        print(result.stderr)

        raise RuntimeError(
            f"{label} consolidation child process failed "
            f"with exit code {result.returncode}."
        )

    assert output_path.with_suffix(
        output_path.suffix + ".build.tmp"
    ).exists(), (
        f"{label} build artifact was not created."
    )


# ------------------------------------------------------------
# 6. Turn consolidation
# ------------------------------------------------------------

run_child_consolidation(
    parts_dir=TURN_PART_DIR,
    output_path=TURNS_TMP,
    expected_rows=EXPECTED_TURNS,
    label="turns",
)


# ------------------------------------------------------------
# 7. Child process has exited.
#    Its file handles are now gone.
# ------------------------------------------------------------

gc.collect()
gc.collect()


TURN_BUILD_TMP = Path(
    str(TURNS_TMP)
    + ".build.tmp"
)

assert TURN_BUILD_TMP.exists()


# ------------------------------------------------------------
# 8. Parent-process promotion
# ------------------------------------------------------------

if TURNS_TMP.exists():

    TURNS_TMP.unlink()

os.replace(
    TURN_BUILD_TMP,
    TURNS_TMP,
)


# ------------------------------------------------------------
# 9. Turn final verification
# ------------------------------------------------------------

turn_pf = pq.ParquetFile(
    TURNS_TMP
)

try:

    turn_final_rows = int(
        turn_pf.metadata.num_rows
    )

    turn_final_schema = (
        turn_pf.schema_arrow
    )

finally:

    if hasattr(turn_pf, "close"):
        turn_pf.close()

    del turn_pf
    gc.collect()


assert (
    turn_final_rows
    ==
    EXPECTED_TURNS
)

assert (
    turn_final_schema
    ==
    TURN_CANDIDATE_SCHEMA
)


print(
    f"TURN CONSOLIDATED: "
    f"{turn_final_rows:,} rows"
)


# ------------------------------------------------------------
# 10. Session consolidation
# ------------------------------------------------------------

run_child_consolidation(
    parts_dir=SESSION_PART_DIR,
    output_path=SESSIONS_TMP,
    expected_rows=EXPECTED_SESSIONS,
    label="sessions",
)


gc.collect()
gc.collect()


SESSION_BUILD_TMP = Path(
    str(SESSIONS_TMP)
    + ".build.tmp"
)

assert SESSION_BUILD_TMP.exists()


if SESSIONS_TMP.exists():

    SESSIONS_TMP.unlink()


os.replace(
    SESSION_BUILD_TMP,
    SESSIONS_TMP,
)


# ------------------------------------------------------------
# 11. Session final verification
# ------------------------------------------------------------

session_pf = pq.ParquetFile(
    SESSIONS_TMP
)

try:

    session_final_rows = int(
        session_pf.metadata.num_rows
    )

    session_final_schema = (
        session_pf.schema_arrow
    )

finally:

    if hasattr(session_pf, "close"):
        session_pf.close()

    del session_pf
    gc.collect()


assert (
    session_final_rows
    ==
    EXPECTED_SESSIONS
)

assert (
    session_final_schema
    ==
    SESSION_CANDIDATE_SCHEMA
)


# ------------------------------------------------------------
# 12. Final state
# ------------------------------------------------------------

CONSOLIDATION_COMPLETE = (
    TURNS_TMP.exists()
    and
    SESSIONS_TMP.exists()
    and
    turn_final_rows == EXPECTED_TURNS
    and
    session_final_rows == EXPECTED_SESSIONS
)


print("\n" + "=" * 80)
print("2.16.2B — CONSOLIDATION COMPLETE")
print("=" * 80)

print(
    f"Turn artifact    : {TURNS_TMP}"
)

print(
    f"Turn rows        : "
    f"{turn_final_rows:,}"
)

print(
    f"Session artifact : {SESSIONS_TMP}"
)

print(
    f"Session rows     : "
    f"{session_final_rows:,}"
)

print(
    f"Turn exists      : "
    f"{TURNS_TMP.exists()}"
)

print(
    f"Session exists   : "
    f"{SESSIONS_TMP.exists()}"
)

print(
    f"CONSOLIDATION_COMPLETE : "
    f"{CONSOLIDATION_COMPLETE}"
)

print("=" * 80)

assert CONSOLIDATION_COMPLETE

================================================================================
2.16.2B — ROBUST WINDOWS-SAFE PART CONSOLIDATION
================================================================================

Part inventory:
  Turn parts    : 92
  Session parts : 92

Part accounting:
  Turn rows from parts    : 6,139,854
  Session rows from parts : 22,821
  Expected turns          : 6,139,854
  Expected sessions       : 22,821

Starting isolated turns consolidation process...
turns: 10/92 parts | 664,944 rows
turns: 20/92 parts | 1,336,554 rows
turns: 30/92 parts | 2,012,198 rows
turns: 40/92 parts | 2,692,417 rows
turns: 50/92 parts | 3,364,873 rows
turns: 60/92 parts | 4,034,815 rows
turns: 70/92 parts | 4,710,356 rows
turns: 80/92 parts | 5,377,157 rows
turns: 90/92 parts | 6,052,016 rows
turns: 92/92 parts | 6,139,854 rows
turns BUILD COMPLETE: 6,139,854 rows

TURN CONSOLIDATED: 6,139,854 rows

Starting isolated sessions consolidation process...
sessions: 10/92 parts | 2,500 rows
sessions: 20/92 parts | 5,000 rows
sessions: 30/92 parts | 7,500 rows
sessions: 40/92 parts | 10,000 rows
sessions: 50/92 parts | 12,500 rows
sessions: 60/92 parts | 15,000 rows
sessions: 70/92 parts | 17,500 rows
sessions: 80/92 parts | 20,000 rows
sessions: 90/92 parts | 22,500 rows
sessions: 92/92 parts | 22,821 rows
sessions BUILD COMPLETE: 22,821 rows


================================================================================
2.16.2B — CONSOLIDATION COMPLETE
================================================================================
Turn artifact    : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\turns_candidate.tmp.parquet
Turn rows        : 6,139,854
Session artifact : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\sessions_candidate.tmp.parquet
Session rows     : 22,821
Turn exists      : True
Session exists   : True
CONSOLIDATION_COMPLETE : True
================================================================================

In [59]:
# ============================================================
# 2.16.3 — WINDOWS-SAFE FINAL VERIFICATION & PROMOTION
# ============================================================

import os, gc, shutil, hashlib
import pyarrow.parquet as pq

assert FULL_STREAM_PARSE_COMPLETE, "Full streaming parse is not complete."
assert TURNS_TMP.exists() and SESSIONS_TMP.exists(), "Temporary candidate artifacts are missing."

def sha256_file(path, chunk_size=8 * 1024 * 1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            h.update(chunk)
    return h.hexdigest()

def verify_parquet(path, schema, expected_rows):
    metadata = pq.read_metadata(path)
    actual_schema = pq.read_schema(path)
    return {
        "rows": int(metadata.num_rows),
        "schema_ok": actual_schema == schema,
        "rows_ok": int(metadata.num_rows) == expected_rows,
        "sha256": sha256_file(path)
    }

def promote_windows_safe(source, final_path, schema, expected_rows):
    stage = final_path.parent / f".{final_path.name}.promotion.tmp"
    if stage.exists():
        stage.unlink()

    source_check = verify_parquet(source, schema, expected_rows)
    assert source_check["schema_ok"] and source_check["rows_ok"], f"Invalid temporary artifact: {source.name}"

    if final_path.exists():
        final_check = verify_parquet(final_path, schema, expected_rows)
        if final_check["sha256"] == source_check["sha256"]:
            return source_check, "ALREADY_VALID"
        raise RuntimeError(f"Existing final artifact differs from verified temporary artifact: {final_path}")

    shutil.copyfile(source, stage)
    stage_check = verify_parquet(stage, schema, expected_rows)

    assert stage_check["schema_ok"] and stage_check["rows_ok"], f"Promotion-stage validation failed: {stage.name}"
    assert stage_check["sha256"] == source_check["sha256"], f"Promotion-stage hash mismatch: {stage.name}"

    gc.collect()
    os.replace(stage, final_path)

    final_check = verify_parquet(final_path, schema, expected_rows)
    assert final_check["schema_ok"] and final_check["rows_ok"]
    assert final_check["sha256"] == source_check["sha256"]

    return final_check, "PROMOTED"


# ---------- Verify session accounting before promotion ----------

session_small = pq.read_table(
    SESSIONS_TMP,
    columns=[
        "session_id", "n_turns", "fallback_order_used",
        "ambiguous_order_flag", "midnight_rollover_count"
    ]
).to_pandas()

session_turn_sum = int(session_small["n_turns"].sum())
duplicate_sessions = int(session_small["session_id"].duplicated().sum())
fallback_sessions = int(session_small["fallback_order_used"].sum())
ambiguous_sessions = int(session_small["ambiguous_order_flag"].sum())
rollover_sessions = int((session_small["midnight_rollover_count"] > 0).sum())

pre_promotion_checks = pd.DataFrame([
    check_row("Temporary turn artifact exists", TURNS_TMP.exists(), TURNS_TMP.name),
    check_row("Temporary session artifact exists", SESSIONS_TMP.exists(), SESSIONS_TMP.name),
    check_row("Session n_turns reconciles with corpus", session_turn_sum == EXPECTED_TURNS, f"{session_turn_sum} / {EXPECTED_TURNS}"),
    check_row("Session IDs remain unique", duplicate_sessions == 0, duplicate_sessions)
])

display(pre_promotion_checks)
assert pre_promotion_checks["passed"].all(), "Pre-promotion validation failed."

del session_small
gc.collect()


# ---------- Windows-safe promotion ----------

turn_final_check, turn_promotion_status = promote_windows_safe(
    TURNS_TMP, TURNS_FINAL, TURN_CANDIDATE_SCHEMA, EXPECTED_TURNS
)

session_final_check, session_promotion_status = promote_windows_safe(
    SESSIONS_TMP, SESSIONS_FINAL, SESSION_CANDIDATE_SCHEMA, EXPECTED_SESSIONS
)

PRODUCTION_PARSE_READY = all([
    turn_final_check["rows_ok"],
    turn_final_check["schema_ok"],
    session_final_check["rows_ok"],
    session_final_check["schema_ok"],
    session_turn_sum == EXPECTED_TURNS,
    duplicate_sessions == 0
])


# ---------- Best-effort temporary cleanup ----------

gc.collect()
TEMP_CLEANUP_DEFERRED = False

try:
    shutil.rmtree(PRODUCTION_TMP_ROOT)
except PermissionError:
    TEMP_CLEANUP_DEFERRED = True


production_final_summary = pd.DataFrame({
    "item": [
        "Transcript files", "Candidate turns", "Candidate sessions",
        "Turn schema fields", "Session schema fields",
        "Duplicate sessions", "Fallback sessions", "Ambiguous sessions",
        "Rollover sessions", "Turn promotion", "Session promotion",
        "Turn artifact SHA256", "Session artifact SHA256",
        "Temporary cleanup deferred", "PRODUCTION_PARSE_READY"
    ],
    "value": [
        EXPECTED_FILES, turn_final_check["rows"], session_final_check["rows"],
        len(TURN_CANDIDATE_SCHEMA), len(SESSION_CANDIDATE_SCHEMA),
        duplicate_sessions, fallback_sessions, ambiguous_sessions,
        rollover_sessions, turn_promotion_status, session_promotion_status,
        turn_final_check["sha256"], session_final_check["sha256"],
        TEMP_CLEANUP_DEFERRED, PRODUCTION_PARSE_READY
    ]
})

display(production_final_summary)

assert PRODUCTION_PARSE_READY, "Final production artifacts failed verification."

print("\n" + "=" * 72)
print("TRACE THE ACE — FULL-CORPUS PRODUCTION PARSE COMPLETE")
print("=" * 72)
print(f"Transcript files        : {EXPECTED_FILES:,}/{EXPECTED_FILES:,}")
print(f"Candidate turns         : {turn_final_check['rows']:,}/{EXPECTED_TURNS:,}")
print(f"Candidate sessions      : {session_final_check['rows']:,}/{EXPECTED_SESSIONS:,}")
print(f"Turn schema             : {len(TURN_CANDIDATE_SCHEMA)}/52")
print(f"Session schema          : {len(SESSION_CANDIDATE_SCHEMA)}/31")
print(f"Duplicate sessions      : {duplicate_sessions:,}")
print(f"Fallback sessions       : {fallback_sessions:,}")
print(f"Ambiguous sessions      : {ambiguous_sessions:,}")
print(f"Rollover sessions       : {rollover_sessions:,}")
print(f"Turn promotion          : {turn_promotion_status}")
print(f"Session promotion       : {session_promotion_status}")
print(f"Temp cleanup deferred   : {TEMP_CLEANUP_DEFERRED}")
print(f"PRODUCTION PARSE READY  : {PRODUCTION_PARSE_READY}")
print("=" * 72)

,check,passed,detail
0,Temporary turn artifact exists,True,turns_candidate.tmp.parquet
1,Temporary session artifact exists,True,sessions_candidate.tmp.parquet
2,Session n_turns reconciles with corpus,True,6139854 / 6139854
3,Session IDs remain unique,True,0

,item,value
0,Transcript files,22821
1,Candidate turns,6139854
2,Candidate sessions,22821
3,Turn schema fields,52
4,Session schema fields,31
5,Duplicate sessions,0
6,Fallback sessions,0
7,Ambiguous sessions,0
8,Rollover sessions,0
9,Turn promotion,PROMOTED
10,Session promotion,PROMOTED
11,Turn artifact SHA256,926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed...
12,Session artifact SHA256,24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f...
13,Temporary cleanup deferred,False
14,PRODUCTION_PARSE_READY,True

========================================================================
TRACE THE ACE — FULL-CORPUS PRODUCTION PARSE COMPLETE
========================================================================
Transcript files        : 22,821/22,821
Candidate turns         : 6,139,854/6,139,854
Candidate sessions      : 22,821/22,821
Turn schema             : 52/52
Session schema          : 31/31
Duplicate sessions      : 0
Fallback sessions       : 0
Ambiguous sessions      : 0
Rollover sessions       : 0
Turn promotion          : PROMOTED
Session promotion       : PROMOTED
Temp cleanup deferred   : False
PRODUCTION PARSE READY  : True
========================================================================

# Section 2.17 — Full Corpus Parser Audit

This section independently audits the complete turn and session candidate artifacts produced in Section 2.16.
No transcript is reparsed and no target, objective, fold statistic, prediction, prior, or model information is used.
Only fields that actually exist in the frozen candidate schemas are consumed.
Text length, normalization change, `[UNCLEAR]`, speaker switching, and related diagnostics are derived from stored core evidence rather than assumed columns.
The audit verifies artifact identity, global row conservation, session coverage, turn identities, physical source identities, and sequence integrity.
Per-session turn counts, role counts, source-row counts, source files, and structural positions are independently reconstructed from the turn artifact.
Ordering, timestamp, ID, fallback, ambiguity, and rollover summaries are reconciled from the frozen session candidate table.
Structural distributions are reported without silently changing or deleting any evidence.
Candidate tables remain non-canonical until the independent integrity notebook certifies them.
The section ends with `CORPUS_PARSER_AUDIT_READY`.

In [60]:
# ============================================================
# 2.17.1 — SCHEMA-AWARE AUDIT ENTRY GATE
# ============================================================

import gc, hashlib
from collections import Counter

import numpy as np
import pandas as pd
import pyarrow.compute as pc
import pyarrow.parquet as pq

assert PRODUCTION_PARSE_READY, "Section 2.16 must pass before Section 2.17."
assert TURNS_FINAL.exists() and SESSIONS_FINAL.exists(), "Candidate artifacts are missing."

CORPUS_AUDIT_VERSION = "1.2"

def audit_check_217(check, passed, detail):
    return {"check":check, "passed":bool(passed), "detail":detail}

def sha256_file_217(path, chunk_size=8*1024*1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda:f.read(chunk_size), b""): h.update(chunk)
    return h.hexdigest()

def resolve_217(schema_names, label, *candidates, required=True):
    field = next((x for x in candidates if x in schema_names), None)
    if required and field is None:
        raise RuntimeError(f"Required semantic field '{label}' is absent. Candidates checked: {candidates}")
    return field

turn_names_217 = set(TURN_CANDIDATE_SCHEMA.names)
session_names_217 = set(SESSION_CANDIDATE_SCHEMA.names)

T217 = {
    "session":resolve_217(turn_names_217,"session_id","session_id"),
    "turn_uid":resolve_217(turn_names_217,"turn_uid","turn_uid"),
    "source_uid":resolve_217(turn_names_217,"source_row_uid","source_row_uid"),
    "turn_index":resolve_217(turn_names_217,"turn_index","turn_index"),
    "role":resolve_217(turn_names_217,"role","role"),
    "content_raw":resolve_217(turn_names_217,"raw content","content_raw"),
    "text_norm":resolve_217(turn_names_217,"normalized text","text_norm","content_norm","normalized_content"),
    "source_file":resolve_217(turn_names_217,"source file","source_file_relative"),
    "source_row":resolve_217(turn_names_217,"source row index","source_row_index"),
    "relative_pos":resolve_217(turn_names_217,"relative turn position","relative_turn_position"),
    "utterance_id":resolve_217(turn_names_217,"parsed utterance ID","utterance_id",required=False),
    "utterance_id_raw":resolve_217(turn_names_217,"raw utterance ID","utterance_id_raw",required=False),
    "timestamp_status":resolve_217(turn_names_217,"timestamp status","timestamp_status",required=False),
    "timestamp_kind":resolve_217(turn_names_217,"timestamp kind","timestamp_kind",required=False),
    "timestamp_precision":resolve_217(turn_names_217,"timestamp precision","timestamp_precision",required=False),
    "timezone_status":resolve_217(turn_names_217,"timezone status","timezone_status",required=False),
    "utterance_id_status":resolve_217(turn_names_217,"utterance-ID status","utterance_id_status",required=False),
    "speaker_switch":resolve_217(turn_names_217,"speaker-switch flag","speaker_switch_flag","speaker_switch",required=False),
    "first_turn":resolve_217(turn_names_217,"first-turn flag","first_turn_flag","is_first_turn",required=False),
    "last_turn":resolve_217(turn_names_217,"last-turn flag","last_turn_flag","is_last_turn",required=False),
    "unclear_flag":resolve_217(turn_names_217,"UNCLEAR flag","contains_unclear_flag","unclear_flag",required=False),
    "empty_norm_flag":resolve_217(turn_names_217,"empty-normalization flag","empty_after_normalization_flag",required=False)
}

SESSION_REQUIRED_217 = [
    "session_id","source_file_relative","source_raw_row_count","n_turns",
    "n_student_turns","n_tutor_turns","n_background_turns","n_unknown_roles",
    "duration_seconds","duration_status","timestamp_issue_count",
    "utterance_id_issue_count","ordering_issue_count","unknown_role_count",
    "empty_content_count","ordering_method","ordering_confidence",
    "ordering_comparability","fallback_order_used","timestamp_tie_count",
    "timestamp_id_conflict","timestamp_source_conflict","id_source_conflict",
    "midnight_rollover_count","ambiguous_order_flag","quality_warning_count"
]

missing_session_fields_217 = sorted(set(SESSION_REQUIRED_217) - session_names_217)

turn_meta_217 = pq.read_metadata(TURNS_FINAL)
session_meta_217 = pq.read_metadata(SESSIONS_FINAL)
turn_schema_disk_217 = pq.read_schema(TURNS_FINAL)
session_schema_disk_217 = pq.read_schema(SESSIONS_FINAL)

turn_sha256_217 = sha256_file_217(TURNS_FINAL)
session_sha256_217 = sha256_file_217(SESSIONS_FINAL)

previous_turn_hash_217 = globals().get("turns_candidate_sha256")
previous_session_hash_217 = globals().get("sessions_candidate_sha256")

optional_fields_217 = pd.DataFrame([
    {"audit_item":k,"resolved_field":v,"available":v is not None}
    for k,v in T217.items()
    if k not in {"session","turn_uid","source_uid","turn_index","role","content_raw","text_norm",
                 "source_file","source_row","relative_pos"}
])

entry_checks_217 = pd.DataFrame([
    audit_check_217("Production parse is certified", PRODUCTION_PARSE_READY, PRODUCTION_PARSE_READY),
    audit_check_217("Session audit fields are present", not missing_session_fields_217, missing_session_fields_217),
    audit_check_217("Turn schema matches frozen schema", turn_schema_disk_217 == TURN_CANDIDATE_SCHEMA, len(turn_schema_disk_217)),
    audit_check_217("Session schema matches frozen schema", session_schema_disk_217 == SESSION_CANDIDATE_SCHEMA, len(session_schema_disk_217)),
    audit_check_217("Turn row census matches production contract", turn_meta_217.num_rows == EXPECTED_TURNS, f"{turn_meta_217.num_rows:,}/{EXPECTED_TURNS:,}"),
    audit_check_217("Session row census matches production contract", session_meta_217.num_rows == EXPECTED_SESSIONS, f"{session_meta_217.num_rows:,}/{EXPECTED_SESSIONS:,}"),
    audit_check_217("Turn artifact hash is unchanged", previous_turn_hash_217 is None or turn_sha256_217 == previous_turn_hash_217,
                    "reference unavailable" if previous_turn_hash_217 is None else turn_sha256_217),
    audit_check_217("Session artifact hash is unchanged", previous_session_hash_217 is None or session_sha256_217 == previous_session_hash_217,
                    "reference unavailable" if previous_session_hash_217 is None else session_sha256_217)
])

entry_failures_217 = entry_checks_217.loc[~entry_checks_217["passed"]]
CORPUS_AUDIT_ENTRY_READY = entry_failures_217.empty

display(optional_fields_217)
display(entry_checks_217)

assert CORPUS_AUDIT_ENTRY_READY, (
    "Section 2.17 entry gate failed.\n\n"
    + entry_failures_217[["check","detail"]].to_string(index=False)
)

print("\n"+"="*70)
print("TRACE THE ACE — CORPUS AUDIT ENTRY READY")
print("="*70)
print(f"Candidate turns      : {turn_meta_217.num_rows:,}")
print(f"Candidate sessions   : {session_meta_217.num_rows:,}")
print(f"Turn schema          : {len(turn_schema_disk_217)}/52")
print(f"Session schema       : {len(session_schema_disk_217)}/31")
print(f"AUDIT ENTRY READY    : {CORPUS_AUDIT_ENTRY_READY}")
print("="*70)

             audit_item                  resolved_field  available
0          utterance_id                    utterance_id       True
1      utterance_id_raw                utterance_id_raw       True
2      timestamp_status                timestamp_status       True
3        timestamp_kind                  timestamp_kind       True
4   timestamp_precision             timestamp_precision       True
5       timezone_status                 timezone_status       True
6   utterance_id_status             utterance_id_status       True
7        speaker_switch                  speaker_switch       True
8            first_turn                   is_first_turn       True
9             last_turn                    is_last_turn       True
10         unclear_flag           contains_unclear_flag       True
11      empty_norm_flag  empty_after_normalization_flag       True

,check,passed,detail
0,Production parse is certified,True,True
1,Session audit fields are present,True,[]
2,Turn schema matches frozen schema,True,52
3,Session schema matches frozen schema,True,31
4,Turn row census matches production contract,True,"6,139,854/6,139,854"
5,Session row census matches production contract,True,"22,821/22,821"
6,Turn artifact hash is unchanged,True,reference unavailable
7,Session artifact hash is unchanged,True,reference unavailable

======================================================================
TRACE THE ACE — CORPUS AUDIT ENTRY READY
======================================================================
Candidate turns      : 6,139,854
Candidate sessions   : 22,821
Turn schema          : 52/52
Session schema       : 31/31
AUDIT ENTRY READY    : True
======================================================================

In [62]:
# ============================================================
# 2.17.2 — STREAMING TURN RECONSTRUCTION AUDIT
# ============================================================

core_scan_217 = [
    T217["session"],T217["turn_index"],T217["role"],T217["content_raw"],
    T217["text_norm"],T217["source_file"],T217["source_row"],T217["relative_pos"]
]

optional_scan_217 = [
    T217["utterance_id"],T217["utterance_id_raw"],T217["timestamp_status"],
    T217["timestamp_kind"],T217["timestamp_precision"],T217["timezone_status"],
    T217["utterance_id_status"],T217["speaker_switch"],T217["first_turn"],
    T217["last_turn"],T217["unclear_flag"],T217["empty_norm_flag"]
]

scan_columns_217 = list(dict.fromkeys(core_scan_217 + [x for x in optional_scan_217 if x]))

role_counts_217 = Counter()
optional_counts_217 = {
    key:Counter() for key in
    ["timestamp_status","timestamp_kind","timestamp_precision","timezone_status","utterance_id_status"]
    if T217[key] is not None
}

rows_scanned_217 = 0
text_changed_217 = unclear_rows_217 = empty_raw_217 = empty_norm_217 = 0
unclear_flag_mismatch_217 = empty_norm_flag_mismatch_217 = 0
speaker_switch_mismatch_217 = first_flag_mismatch_217 = last_flag_mismatch_217 = 0
session_reappearances_217 = duplicate_raw_id_rows_217 = duplicate_parsed_id_rows_217 = 0
session_rows_217, completed_sessions_217, current_217 = [], set(), None

def new_session_217(sid):
    return {
        "session_id":sid,"n":0,"turn_indices":set(),"source_indices":set(),
        "roles":Counter(),"source_files":set(),"raw_ids":set(),"parsed_ids":set(),
        "duplicate_raw_ids":0,"duplicate_parsed_ids":0,"previous_role":None,
        "speaker_switches":0,"first_flags":0,"last_flags":0,
        "pos_min":np.inf,"pos_max":-np.inf,"char_sum":0,"char_max":0
    }

def finish_session_217(s):
    n,ti,si = s["n"],s["turn_indices"],s["source_indices"]
    student = s["roles"].get("student",0)
    tutor = s["roles"].get("tutor",0)
    background = s["roles"].get("background",0)
    return {
        "session_id":s["session_id"],"n_turns_derived":n,
        "n_student_derived":student,"n_tutor_derived":tutor,
        "n_background_derived":background,"n_unknown_derived":n-student-tutor-background,
        "turn_index_contiguous":len(ti)==n and min(ti,default=0)==0 and max(ti,default=-1)==n-1,
        "source_index_contiguous":len(si)==n and min(si,default=0)==0 and max(si,default=-1)==n-1,
        "source_file_count":len(s["source_files"]),
        "source_file_derived":next(iter(s["source_files"])) if len(s["source_files"])==1 else None,
        "duplicate_raw_id_rows":s["duplicate_raw_ids"],
        "duplicate_parsed_id_rows":s["duplicate_parsed_ids"],
        "speaker_switches_derived":s["speaker_switches"],
        "first_flags_derived":s["first_flags"],"last_flags_derived":s["last_flags"],
        "position_min":None if s["pos_min"]==np.inf else s["pos_min"],
        "position_max":None if s["pos_max"]==-np.inf else s["pos_max"],
        "avg_content_chars":s["char_sum"]/n if n else np.nan,
        "max_content_chars":s["char_max"]
    }

pf_217 = pq.ParquetFile(TURNS_FINAL)

try:
    for batch_no_217,batch_217 in enumerate(
        pf_217.iter_batches(batch_size=131072, columns=scan_columns_217), start=1
    ):
        d = batch_217.to_pydict()

        for i in range(batch_217.num_rows):
            sid = d[T217["session"]][i]

            if current_217 is None:
                current_217 = new_session_217(sid)

            elif sid != current_217["session_id"]:
                session_rows_217.append(finish_session_217(current_217))
                completed_sessions_217.add(current_217["session_id"])

                if sid in completed_sessions_217:
                    session_reappearances_217 += 1

                current_217 = new_session_217(sid)

            idx = int(d[T217["turn_index"]][i])
            src_idx = int(d[T217["source_row"]][i])
            role = d[T217["role"]][i]
            source_file = d[T217["source_file"]][i]
            pos = d[T217["relative_pos"]][i]

            raw_text = "" if d[T217["content_raw"]][i] is None else str(d[T217["content_raw"]][i])
            norm_text = "" if d[T217["text_norm"]][i] is None else str(d[T217["text_norm"]][i])

            derived_unclear = "[UNCLEAR]" in norm_text
            derived_empty_norm = norm_text == ""
            derived_switch = current_217["previous_role"] is not None and current_217["previous_role"] != role

            current_217["n"] += 1
            current_217["turn_indices"].add(idx)
            current_217["source_indices"].add(src_idx)
            current_217["roles"][role] += 1
            current_217["source_files"].add(source_file)
            role_counts_217[role] += 1

            current_217["speaker_switches"] += int(derived_switch)
            current_217["previous_role"] = role

            if T217["first_turn"] is not None:
                current_217["first_flags"] += int(bool(d[T217["first_turn"]][i]))
                first_flag_mismatch_217 += int(bool(d[T217["first_turn"]][i]) != (idx==0))

            if T217["last_turn"] is not None:
                current_217["last_flags"] += int(bool(d[T217["last_turn"]][i]))

            if T217["speaker_switch"] is not None:
                speaker_switch_mismatch_217 += int(bool(d[T217["speaker_switch"]][i]) != derived_switch)

            if T217["unclear_flag"] is not None:
                unclear_flag_mismatch_217 += int(bool(d[T217["unclear_flag"]][i]) != derived_unclear)

            if T217["empty_norm_flag"] is not None:
                empty_norm_flag_mismatch_217 += int(bool(d[T217["empty_norm_flag"]][i]) != derived_empty_norm)

            if T217["utterance_id_raw"] is not None:
                raw_id = d[T217["utterance_id_raw"]][i]
                if raw_id is not None:
                    if raw_id in current_217["raw_ids"]:
                        current_217["duplicate_raw_ids"] += 1
                        duplicate_raw_id_rows_217 += 1
                    else:
                        current_217["raw_ids"].add(raw_id)

            if T217["utterance_id"] is not None:
                parsed_id = d[T217["utterance_id"]][i]
                if parsed_id is not None:
                    if parsed_id in current_217["parsed_ids"]:
                        current_217["duplicate_parsed_ids"] += 1
                        duplicate_parsed_id_rows_217 += 1
                    else:
                        current_217["parsed_ids"].add(parsed_id)

            if pos is not None:
                current_217["pos_min"] = min(current_217["pos_min"],float(pos))
                current_217["pos_max"] = max(current_217["pos_max"],float(pos))

            chars = len(raw_text)
            current_217["char_sum"] += chars
            current_217["char_max"] = max(current_217["char_max"],chars)

            rows_scanned_217 += 1
            text_changed_217 += int(raw_text != norm_text)
            unclear_rows_217 += int(derived_unclear)
            empty_raw_217 += int(raw_text.strip()=="")
            empty_norm_217 += int(derived_empty_norm)

            for key in optional_counts_217:
                optional_counts_217[key][d[T217[key]][i]] += 1

        if batch_no_217 % 10 == 0:
            print(
                f"Audited {rows_scanned_217:,}/{EXPECTED_TURNS:,} turns | "
                f"Closed sessions {len(session_rows_217):,}"
            )

    if current_217 is not None:
        session_rows_217.append(finish_session_217(current_217))
        completed_sessions_217.add(current_217["session_id"])

finally:
    pf_217.close()
    del pf_217
    gc.collect()

derived_sessions_217 = pd.DataFrame(session_rows_217)
derived_session_duplicates_217 = int(derived_sessions_217["session_id"].duplicated().sum())

assert derived_session_duplicates_217 == 0, (
    f"Derived turn artifact contains {derived_session_duplicates_217} duplicate session blocks."
)

sessions_217 = pq.read_table(SESSIONS_FINAL).to_pandas()
session_candidate_duplicates_217 = int(sessions_217["session_id"].duplicated().sum())

assert session_candidate_duplicates_217 == 0, (
    f"sessions_candidate contains {session_candidate_duplicates_217} duplicate session IDs."
)

session_compare_217 = sessions_217.merge(
    derived_sessions_217, on="session_id", how="outer",
    indicator=True, validate="one_to_one"
)

session_compare_217["turn_count_match"] = session_compare_217["n_turns"].eq(session_compare_217["n_turns_derived"])
session_compare_217["source_count_match"] = session_compare_217["source_raw_row_count"].eq(session_compare_217["n_turns_derived"])
session_compare_217["source_file_match"] = session_compare_217["source_file_relative"].eq(session_compare_217["source_file_derived"])

session_compare_217["role_count_match"] = (
    session_compare_217["n_student_turns"].eq(session_compare_217["n_student_derived"])
    & session_compare_217["n_tutor_turns"].eq(session_compare_217["n_tutor_derived"])
    & session_compare_217["n_background_turns"].eq(session_compare_217["n_background_derived"])
    & session_compare_217["n_unknown_roles"].eq(session_compare_217["n_unknown_derived"])
)

session_compare_217["position_valid"] = (
    session_compare_217["position_min"].ge(0)
    & session_compare_217["position_max"].le(1)
)

if T217["first_turn"] is not None:
    session_compare_217["first_flag_valid"] = session_compare_217["first_flags_derived"].eq(1)
else:
    session_compare_217["first_flag_valid"] = True

if T217["last_turn"] is not None:
    expected_last_217 = session_compare_217["n_turns_derived"] - 1
    session_compare_217["last_flag_valid"] = session_compare_217["last_flags_derived"].eq(1)
else:
    expected_last_217 = None
    session_compare_217["last_flag_valid"] = True

def exact_distinct_217(path, column):
    table = pq.read_table(path, columns=[column], memory_map=True)
    distinct = int(pc.count_distinct(table[column]).as_py())
    del table
    gc.collect()
    return distinct

turn_uid_distinct_217 = exact_distinct_217(TURNS_FINAL,T217["turn_uid"])
source_uid_distinct_217 = exact_distinct_217(TURNS_FINAL,T217["source_uid"])

stream_summary_217 = pd.DataFrame({
    "item":[
        "Turns scanned","Derived sessions","Session reappearances",
        "Unique turn_uid","Unique source_row_uid",
        "Duplicate raw utterance-ID rows","Duplicate parsed utterance-ID rows",
        "Normalization-changed rows","[UNCLEAR] rows",
        "Empty raw-content rows","Empty normalized rows",
        "Stored UNCLEAR-flag mismatches","Stored empty-normalization mismatches",
        "Stored speaker-switch mismatches"
    ],
    "value":[
        rows_scanned_217,len(derived_sessions_217),session_reappearances_217,
        turn_uid_distinct_217,source_uid_distinct_217,
        duplicate_raw_id_rows_217,duplicate_parsed_id_rows_217,
        text_changed_217,unclear_rows_217,empty_raw_217,empty_norm_217,
        unclear_flag_mismatch_217,empty_norm_flag_mismatch_217,
        speaker_switch_mismatch_217
    ]
})

display(stream_summary_217)

Audited 1,310,720/6,139,854 turns | Closed sessions 4,902
Audited 2,621,440/6,139,854 turns | Closed sessions 9,743
Audited 3,932,160/6,139,854 turns | Closed sessions 14,613
Audited 5,242,880/6,139,854 turns | Closed sessions 19,504

                                     item    value
0                           Turns scanned  6139854
1                        Derived sessions    22821
2                   Session reappearances        0
3                         Unique turn_uid  6139854
4                   Unique source_row_uid  6139854
5         Duplicate raw utterance-ID rows        0
6      Duplicate parsed utterance-ID rows        0
7              Normalization-changed rows        0
8                          [UNCLEAR] rows   180538
9                  Empty raw-content rows        0
10                  Empty normalized rows        0
11         Stored UNCLEAR-flag mismatches        0
12  Stored empty-normalization mismatches        0
13       Stored speaker-switch mismatches        0

In [63]:
# ============================================================
# 2.17.3 — RECONCILIATION, DISTRIBUTIONS & FINAL GATE
# ============================================================

def dist_217(name, values):
    s = pd.Series(values).dropna().astype(float)
    q = s.quantile([0,.01,.05,.25,.50,.75,.95,.99,1])
    return {
        "metric":name,"min":q.loc[0],"p01":q.loc[.01],"p05":q.loc[.05],
        "p25":q.loc[.25],"median":q.loc[.50],"p75":q.loc[.75],
        "p95":q.loc[.95],"p99":q.loc[.99],"max":q.loc[1]
    }

turn_only_217 = int((session_compare_217["_merge"]=="right_only").sum())
session_only_217 = int((session_compare_217["_merge"]=="left_only").sum())

student_turns_217 = int(role_counts_217.get("student",0))
tutor_turns_217 = int(role_counts_217.get("tutor",0))
background_turns_217 = int(role_counts_217.get("background",0))
unknown_turns_217 = int(rows_scanned_217-student_turns_217-tutor_turns_217-background_turns_217)

session_student_sum_217 = int(sessions_217["n_student_turns"].sum())
session_tutor_sum_217 = int(sessions_217["n_tutor_turns"].sum())
session_background_sum_217 = int(sessions_217["n_background_turns"].sum())
session_unknown_sum_217 = int(sessions_217["n_unknown_roles"].sum())
session_turn_sum_217 = int(sessions_217["n_turns"].sum())
session_source_sum_217 = int(sessions_217["source_raw_row_count"].sum())

timestamp_issue_sum_217 = int(sessions_217["timestamp_issue_count"].sum())
id_issue_sum_217 = int(sessions_217["utterance_id_issue_count"].sum())
ordering_issue_sum_217 = int(sessions_217["ordering_issue_count"].sum())
unknown_role_issue_sum_217 = int(sessions_217["unknown_role_count"].sum())
empty_content_sum_217 = int(sessions_217["empty_content_count"].sum())

fallback_sessions_217 = int(sessions_217["fallback_order_used"].sum())
ambiguous_sessions_217 = int(sessions_217["ambiguous_order_flag"].sum())
rollover_sessions_217 = int((sessions_217["midnight_rollover_count"]>0).sum())
tie_sessions_217 = int((sessions_217["timestamp_tie_count"]>0).sum())
tie_groups_217 = int(sessions_217["timestamp_tie_count"].sum())
warning_sessions_217 = int((sessions_217["quality_warning_count"]>0).sum())

ordering_method_217 = sessions_217["ordering_method"].value_counts(dropna=False).to_dict()
ordering_confidence_217 = sessions_217["ordering_confidence"].value_counts(dropna=False).to_dict()
ordering_comparability_217 = sessions_217["ordering_comparability"].value_counts(dropna=False).to_dict()

source_files_turn_217 = int(derived_sessions_217["source_file_derived"].nunique(dropna=True))
source_files_session_217 = int(sessions_217["source_file_relative"].nunique(dropna=True))

reconciliation_217 = pd.DataFrame([
    {"metric":"Turn rows vs production contract","left":rows_scanned_217,"right":EXPECTED_TURNS,
     "match":rows_scanned_217==EXPECTED_TURNS},

    {"metric":"Session rows vs production contract","left":len(derived_sessions_217),"right":EXPECTED_SESSIONS,
     "match":len(derived_sessions_217)==EXPECTED_SESSIONS},

    {"metric":"Session n_turns sum vs turn rows","left":session_turn_sum_217,"right":rows_scanned_217,
     "match":session_turn_sum_217==rows_scanned_217},

    {"metric":"Session source-row sum vs turn rows","left":session_source_sum_217,"right":rows_scanned_217,
     "match":session_source_sum_217==rows_scanned_217},

    {"metric":"Student role census","left":student_turns_217,"right":session_student_sum_217,
     "match":student_turns_217==session_student_sum_217},

    {"metric":"Tutor role census","left":tutor_turns_217,"right":session_tutor_sum_217,
     "match":tutor_turns_217==session_tutor_sum_217},

    {"metric":"Background role census","left":background_turns_217,"right":session_background_sum_217,
     "match":background_turns_217==session_background_sum_217},

    {"metric":"Unknown-role census","left":unknown_turns_217,"right":session_unknown_sum_217,
     "match":unknown_turns_217==session_unknown_sum_217},

    {"metric":"Source-file census from turns vs sessions","left":source_files_turn_217,"right":source_files_session_217,
     "match":source_files_turn_217==source_files_session_217},

    {"metric":"Source-file census vs production contract","left":source_files_session_217,"right":EXPECTED_FILES,
     "match":source_files_session_217==EXPECTED_FILES},

    {"metric":"Empty-content census","left":empty_raw_217,"right":empty_content_sum_217,
     "match":empty_raw_217==empty_content_sum_217}
])

session_compare_217["student_proportion"] = (
    session_compare_217["n_student_derived"]/session_compare_217["n_turns_derived"]
)
session_compare_217["tutor_proportion"] = (
    session_compare_217["n_tutor_derived"]/session_compare_217["n_turns_derived"]
)
session_compare_217["background_proportion"] = (
    session_compare_217["n_background_derived"]/session_compare_217["n_turns_derived"]
)
session_compare_217["speaker_switch_rate"] = np.where(
    session_compare_217["n_turns_derived"]>1,
    session_compare_217["speaker_switches_derived"]/(session_compare_217["n_turns_derived"]-1),
    0.0
)

structural_distribution_217 = pd.DataFrame([
    dist_217("turns_per_session",session_compare_217["n_turns_derived"]),
    dist_217("duration_seconds",session_compare_217["duration_seconds"]),
    dist_217("student_proportion",session_compare_217["student_proportion"]),
    dist_217("tutor_proportion",session_compare_217["tutor_proportion"]),
    dist_217("background_proportion",session_compare_217["background_proportion"]),
    dist_217("speaker_switch_rate",session_compare_217["speaker_switch_rate"]),
    dist_217("average_content_chars",session_compare_217["avg_content_chars"]),
    dist_217("maximum_content_chars",session_compare_217["max_content_chars"])
])

timestamp_status_valid_217 = True
if T217["timestamp_status"] is not None:
    status_counts = optional_counts_217["timestamp_status"]
    timestamp_status_valid_217 = (
        sum(status_counts.values())==EXPECTED_TURNS
        and status_counts.get("VALID",0)==EXPECTED_TURNS
    )

utterance_status_valid_217 = True
if T217["utterance_id_status"] is not None:
    status_counts = optional_counts_217["utterance_id_status"]
    utterance_status_valid_217 = (
        sum(status_counts.values())==EXPECTED_TURNS
        and status_counts.get("VALID",0)==EXPECTED_TURNS
    )

required_checks_217 = pd.DataFrame([
    audit_check_217("Corpus audit entry gate passed", CORPUS_AUDIT_ENTRY_READY, CORPUS_AUDIT_ENTRY_READY),
    audit_check_217("Every candidate turn was audited", rows_scanned_217==EXPECTED_TURNS, f"{rows_scanned_217:,}/{EXPECTED_TURNS:,}"),
    audit_check_217("Every candidate session was reconstructed", len(derived_sessions_217)==EXPECTED_SESSIONS, f"{len(derived_sessions_217):,}/{EXPECTED_SESSIONS:,}"),
    audit_check_217("No session reappears non-contiguously", session_reappearances_217==0, session_reappearances_217),
    audit_check_217("No duplicate session rows exist", session_candidate_duplicates_217==0, session_candidate_duplicates_217),
    audit_check_217("Turn/session ID coverage is exact", turn_only_217==0 and session_only_217==0, f"turn_only={turn_only_217}, session_only={session_only_217}"),

    audit_check_217("turn_uid is globally unique", turn_uid_distinct_217==EXPECTED_TURNS, f"{turn_uid_distinct_217:,}/{EXPECTED_TURNS:,}"),
    audit_check_217("source_row_uid is globally unique", source_uid_distinct_217==EXPECTED_TURNS, f"{source_uid_distinct_217:,}/{EXPECTED_TURNS:,}"),

    audit_check_217("Every session preserves turn count", session_compare_217["turn_count_match"].fillna(False).all(),
                    int((~session_compare_217["turn_count_match"].fillna(False)).sum())),
    audit_check_217("Every session preserves source-row count", session_compare_217["source_count_match"].fillna(False).all(),
                    int((~session_compare_217["source_count_match"].fillna(False)).sum())),
    audit_check_217("Every session preserves source file", session_compare_217["source_file_match"].fillna(False).all(),
                    int((~session_compare_217["source_file_match"].fillna(False)).sum())),
    audit_check_217("Every session preserves role counts", session_compare_217["role_count_match"].fillna(False).all(),
                    int((~session_compare_217["role_count_match"].fillna(False)).sum())),

    audit_check_217("Turn indices are contiguous and unique", session_compare_217["turn_index_contiguous"].fillna(False).all(),
                    int((~session_compare_217["turn_index_contiguous"].fillna(False)).sum())),
    audit_check_217("Source-row indices are contiguous and unique", session_compare_217["source_index_contiguous"].fillna(False).all(),
                    int((~session_compare_217["source_index_contiguous"].fillna(False)).sum())),
    audit_check_217("Relative turn positions remain in [0,1]", session_compare_217["position_valid"].fillna(False).all(),
                    int((~session_compare_217["position_valid"].fillna(False)).sum())),

    audit_check_217("No duplicate raw utterance IDs", T217["utterance_id_raw"] is None or duplicate_raw_id_rows_217==0,
                    "NOT_STORED" if T217["utterance_id_raw"] is None else duplicate_raw_id_rows_217),
    audit_check_217("No duplicate parsed utterance IDs", T217["utterance_id"] is None or duplicate_parsed_id_rows_217==0,
                    "NOT_STORED" if T217["utterance_id"] is None else duplicate_parsed_id_rows_217),

    audit_check_217("Stored first-turn flags agree when available", T217["first_turn"] is None or first_flag_mismatch_217==0,
                    "NOT_STORED" if T217["first_turn"] is None else first_flag_mismatch_217),
    audit_check_217("Each session has one stored first-turn flag when available", T217["first_turn"] is None or session_compare_217["first_flag_valid"].all(),
                    "NOT_STORED" if T217["first_turn"] is None else int((~session_compare_217["first_flag_valid"]).sum())),
    audit_check_217("Each session has one stored last-turn flag when available", T217["last_turn"] is None or session_compare_217["last_flag_valid"].all(),
                    "NOT_STORED" if T217["last_turn"] is None else int((~session_compare_217["last_flag_valid"]).sum())),

    audit_check_217("Stored speaker-switch flags agree when available", T217["speaker_switch"] is None or speaker_switch_mismatch_217==0,
                    "NOT_STORED" if T217["speaker_switch"] is None else speaker_switch_mismatch_217),
    audit_check_217("Stored [UNCLEAR] flags agree when available", T217["unclear_flag"] is None or unclear_flag_mismatch_217==0,
                    "NOT_STORED" if T217["unclear_flag"] is None else unclear_flag_mismatch_217),
    audit_check_217("Stored empty-normalization flags agree when available", T217["empty_norm_flag"] is None or empty_norm_flag_mismatch_217==0,
                    "NOT_STORED" if T217["empty_norm_flag"] is None else empty_norm_flag_mismatch_217),

    audit_check_217("Timestamp-status rows are valid when stored", timestamp_status_valid_217,
                    "NOT_STORED" if T217["timestamp_status"] is None else dict(optional_counts_217["timestamp_status"])),
    audit_check_217("Utterance-ID-status rows are valid when stored", utterance_status_valid_217,
                    "NOT_STORED" if T217["utterance_id_status"] is None else dict(optional_counts_217["utterance_id_status"])),

    audit_check_217("No timestamp issues are recorded", timestamp_issue_sum_217==0, timestamp_issue_sum_217),
    audit_check_217("No utterance-ID issues are recorded", id_issue_sum_217==0, id_issue_sum_217),
    audit_check_217("No ordering issues are recorded", ordering_issue_sum_217==0, ordering_issue_sum_217),
    audit_check_217("No unknown-role issues are recorded", unknown_role_issue_sum_217==0, unknown_role_issue_sum_217),

    audit_check_217("Ordering remains timestamp-primary", ordering_method_217=={"TIMESTAMP_PRIMARY":EXPECTED_SESSIONS}, ordering_method_217),
    audit_check_217("Ordering confidence remains HIGH", ordering_confidence_217=={"HIGH":EXPECTED_SESSIONS}, ordering_confidence_217),
    audit_check_217("No fallback, ambiguity, or rollover exists",
                    fallback_sessions_217==0 and ambiguous_sessions_217==0 and rollover_sessions_217==0,
                    f"fallback={fallback_sessions_217}, ambiguous={ambiguous_sessions_217}, rollover={rollover_sessions_217}"),

    audit_check_217("All cross-artifact reconciliations pass", reconciliation_217["match"].all(),
                    int((~reconciliation_217["match"]).sum()))
])

required_failures_217 = required_checks_217.loc[~required_checks_217["passed"]]
CORPUS_PARSER_AUDIT_READY = required_failures_217.empty

issue_summary_217 = pd.DataFrame([
    {"issue":"Required audit failures","severity":"BLOCKER","count":len(required_failures_217)},
    {"issue":"Timestamp tie groups","severity":"INFO","count":tie_groups_217},
    {"issue":"Sessions containing timestamp ties","severity":"INFO","count":tie_sessions_217},
    {"issue":"[UNCLEAR] transcript rows","severity":"INFO","count":unclear_rows_217},
    {"issue":"Normalization-changed rows","severity":"INFO","count":text_changed_217},
    {"issue":"Quality-warning sessions","severity":"WARNING","count":warning_sessions_217},
    {"issue":"Fallback sessions","severity":"WARNING","count":fallback_sessions_217},
    {"issue":"Ambiguous sessions","severity":"ERROR","count":ambiguous_sessions_217}
])

display(reconciliation_217)
display(structural_distribution_217)
display(issue_summary_217)
display(required_checks_217)

print("\nOrdering comparability:")
display(pd.DataFrame(
    {"ordering_comparability":list(ordering_comparability_217.keys()),
     "sessions":list(ordering_comparability_217.values())}
))

assert CORPUS_PARSER_AUDIT_READY, (
    "Section 2.17 failed.\n\n"
    + required_failures_217[["check","detail"]].to_string(index=False)
)

print("\n"+"="*74)
print("TRACE THE ACE — FULL CORPUS PARSER AUDIT COMPLETE")
print("="*74)
print(f"Turns audited           : {rows_scanned_217:,}/{EXPECTED_TURNS:,}")
print(f"Sessions audited        : {len(derived_sessions_217):,}/{EXPECTED_SESSIONS:,}")
print(f"Unique turn_uid         : {turn_uid_distinct_217:,}/{EXPECTED_TURNS:,}")
print(f"Unique source_row_uid   : {source_uid_distinct_217:,}/{EXPECTED_TURNS:,}")
print(f"Turn-index failures     : {int((~session_compare_217['turn_index_contiguous'].fillna(False)).sum()):,}")
print(f"Source-index failures   : {int((~session_compare_217['source_index_contiguous'].fillna(False)).sum()):,}")
print(f"Role-count failures     : {int((~session_compare_217['role_count_match'].fillna(False)).sum()):,}")
print(f"[UNCLEAR] rows          : {unclear_rows_217:,}")
print(f"Timestamp tie groups    : {tie_groups_217:,}")
print(f"Fallback sessions       : {fallback_sessions_217:,}")
print(f"Ambiguous sessions      : {ambiguous_sessions_217:,}")
print(f"Rollover sessions       : {rollover_sessions_217:,}")
print(f"Reconciliation failures : {int((~reconciliation_217['match']).sum()):,}")
print(f"Required failures       : {len(required_failures_217):,}")
print(f"CORPUS AUDIT READY      : {CORPUS_PARSER_AUDIT_READY}")
print("="*74)

                                       metric     left    right  match
0            Turn rows vs production contract  6139854  6139854   True
1         Session rows vs production contract    22821    22821   True
2            Session n_turns sum vs turn rows  6139854  6139854   True
3         Session source-row sum vs turn rows  6139854  6139854   True
4                         Student role census  2697152  2697152   True
5                           Tutor role census  3196001  3196001   True
6                      Background role census   246701   246701   True
7                         Unknown-role census        0        0   True
8   Source-file census from turns vs sessions    22821    22821   True
9   Source-file census vs production contract    22821    22821   True
10                       Empty-content census        0        0   True

,metric,min,p01,p05,p25,median,p75,p95,p99,max
0,turns_per_session,15.000000,93.000000,151.000000,222.000000,267.000000,316.000000,392.000000,451.000000,622.000000
1,duration_seconds,205.000000,1273.400000,1830.000000,2351.000000,2603.000000,2705.000000,2793.000000,2913.000000,3721.000000
2,student_proportion,0.000000,0.228868,0.328889,0.409962,0.445513,0.472789,0.505576,0.532407,0.810127
3,tutor_proportion,0.156250,0.436837,0.464497,0.495902,0.518405,0.545872,0.606383,0.701649,0.960481
4,background_proportion,0.000000,0.003236,0.007463,0.018957,0.031700,0.051383,0.096939,0.153680,0.703125
5,speaker_switch_rate,0.074010,0.521398,0.688623,0.793478,0.836120,0.868421,0.904110,0.924855,0.977778
6,average_content_chars,14.041667,40.394167,47.617188,58.267857,67.298969,78.599078,101.026515,125.510161,310.578947
7,maximum_content_chars,26.000000,252.000000,314.000000,412.000000,500.000000,610.000000,840.000000,1112.600000,1767.000000

                                issue severity   count
0             Required audit failures  BLOCKER       0
1                Timestamp tie groups     INFO  325210
2  Sessions containing timestamp ties     INFO   22795
3           [UNCLEAR] transcript rows     INFO  180538
4          Normalization-changed rows     INFO       0
5            Quality-warning sessions  WARNING       0
6                   Fallback sessions  WARNING       0
7                  Ambiguous sessions    ERROR       0

,check,passed,detail
0,Corpus audit entry gate passed,True,True
1,Every candidate turn was audited,True,"6,139,854/6,139,854"
2,Every candidate session was reconstructed,True,"22,821/22,821"
3,No session reappears non-contiguously,True,0
4,No duplicate session rows exist,True,0
5,Turn/session ID coverage is exact,True,"turn_only=0, session_only=0"
6,turn_uid is globally unique,True,"6,139,854/6,139,854"
7,source_row_uid is globally unique,True,"6,139,854/6,139,854"
8,Every session preserves turn count,True,0
9,Every session preserves source-row count,True,0
10,Every session preserves source file,True,0
11,Every session preserves role counts,True,0
12,Turn indices are contiguous and unique,True,0
13,Source-row indices are contiguous and unique,True,0
14,"Relative turn positions remain in [0,1]",True,0
15,No duplicate raw utterance IDs,True,0
16,No duplicate parsed utterance IDs,True,0
17,Stored first-turn flags agree when available,True,0
18,Each session has one stored first-turn flag wh...,True,0
19,Each session has one stored last-turn flag whe...,True,0
20,Stored speaker-switch flags agree when available,True,0
21,Stored [UNCLEAR] flags agree when available,True,0
22,Stored empty-normalization flags agree when av...,True,0
23,Timestamp-status rows are valid when stored,True,{'VALID': 6139854}
24,Utterance-ID-status rows are valid when stored,True,{'VALID': 6139854}
25,No timestamp issues are recorded,True,0
26,No utterance-ID issues are recorded,True,0
27,No ordering issues are recorded,True,0
28,No unknown-role issues are recorded,True,0
29,Ordering remains timestamp-primary,True,{'TIMESTAMP_PRIMARY': 22821}
30,Ordering confidence remains HIGH,True,{'HIGH': 22821}
31,"No fallback, ambiguity, or rollover exists",True,"fallback=0, ambiguous=0, rollover=0"
32,All cross-artifact reconciliations pass,True,0

Ordering comparability:

  ordering_comparability  sessions
0   PARTIALLY_COMPARABLE     22795
1       FULLY_COMPARABLE        26

==========================================================================
TRACE THE ACE — FULL CORPUS PARSER AUDIT COMPLETE
==========================================================================
Turns audited           : 6,139,854/6,139,854
Sessions audited        : 22,821/22,821
Unique turn_uid         : 6,139,854/6,139,854
Unique source_row_uid   : 6,139,854/6,139,854
Turn-index failures     : 0
Source-index failures   : 0
Role-count failures     : 0
[UNCLEAR] rows          : 180,538
Timestamp tie groups    : 325,210
Fallback sessions       : 0
Ambiguous sessions      : 0
Rollover sessions       : 0
Reconciliation failures : 0
Required failures       : 0
CORPUS AUDIT READY      : True
==========================================================================

# Section 2.18 — Determinism & Formal Reconstruction Audit

This section tests whether the certified parser is reproducible and whether promoted candidate rows can be traced back to raw transcript evidence.
A deterministic multi-condition session sample is selected from the full session candidate artifact.
Each selected raw transcript is parsed twice using the unchanged integrated parser.
Replay A, Replay B, and the promoted candidate artifacts are compared exactly under the frozen schemas.
Raw CSV records are independently reconstructed by `source_row_index` and compared with preserved raw candidate fields.
Source-file hashes, stable identities, transcript hashes, ordering, and session summaries are checked without repairing any data.
An independent order-sensitive audit digest is used as a negative control for sequence sensitivity.
Compact human-review panels expose beginning, middle, ending, and timestamp-tie evidence from selected sessions.
Failures are recorded as `passed=False` with an explicit cause rather than terminating the notebook.
The section ends with `DETERMINISM_RECONSTRUCTION_READY`.

In [64]:
# ============================================================
# 2.18.1 — ENTRY GATE & DETERMINISTIC SAMPLE SELECTION
# ============================================================

import csv, gc, json, hashlib
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq

DETERMINISM_AUDIT_VERSION = "1.0"
SAMPLE_TARGET_218 = 14

def check_218(check, passed, detail=""):
    return {"check":check, "passed":bool(passed), "detail":str(detail)}

def resolve_218(names, *candidates):
    return next((x for x in candidates if x in names), None)

def sha256_file_218(path, chunk_size=8*1024*1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda:f.read(chunk_size), b""): h.update(chunk)
    return h.hexdigest()

turn_names_218 = set(TURN_CANDIDATE_SCHEMA.names)
session_names_218 = set(SESSION_CANDIDATE_SCHEMA.names)

TURN_REQUIRED_218 = [
    "session_id","turn_uid","source_row_uid","turn_index","source_row_index",
    "source_file_relative","session_id_raw","utterance_id_raw",
    "role_raw","content_raw","timestamp_raw"
]
SESSION_REQUIRED_218 = [
    "session_id","source_file_relative","file_sha256","n_turns","duration_seconds",
    "timestamp_tie_count","ordering_method","ordering_confidence",
    "raw_transcript_hash","normalized_transcript_hash"
]

missing_turn_218 = sorted(set(TURN_REQUIRED_218)-turn_names_218)
missing_session_218 = sorted(set(SESSION_REQUIRED_218)-session_names_218)

T218 = {
    "text_norm":resolve_218(turn_names_218,"text_norm","content_norm","normalized_content"),
    "role":resolve_218(turn_names_218,"role"),
    "utterance_id":resolve_218(turn_names_218,"utterance_id"),
    "raw_field_hash":resolve_218(turn_names_218,"raw_field_hash"),
    "content_hash":resolve_218(turn_names_218,"content_hash")
}

production_ready_218 = bool(globals().get("PRODUCTION_PARSE_READY",False))
corpus_audit_ready_218 = bool(globals().get("CORPUS_PARSER_AUDIT_READY",False))
parser_available_218 = callable(globals().get("parse_session_candidate"))

entry_checks_218 = pd.DataFrame([
    check_218("Production parse is ready",production_ready_218,production_ready_218),
    check_218("Full corpus parser audit is ready",corpus_audit_ready_218,corpus_audit_ready_218),
    check_218("Integrated parser function is available",parser_available_218,parser_available_218),
    check_218("Turn candidate artifact exists",TURNS_FINAL.exists(),TURNS_FINAL),
    check_218("Session candidate artifact exists",SESSIONS_FINAL.exists(),SESSIONS_FINAL),
    check_218("Raw transcript root exists",Path(TRANSCRIPT_ROOT).exists(),TRANSCRIPT_ROOT),
    check_218("Required turn reconstruction fields exist",not missing_turn_218,missing_turn_218),
    check_218("Required session reconstruction fields exist",not missing_session_218,missing_session_218),
    check_218("Turn artifact schema remains exact",pq.read_schema(TURNS_FINAL)==TURN_CANDIDATE_SCHEMA,len(TURN_CANDIDATE_SCHEMA)),
    check_218("Session artifact schema remains exact",pq.read_schema(SESSIONS_FINAL)==SESSION_CANDIDATE_SCHEMA,len(SESSION_CANDIDATE_SCHEMA))
])

DETERMINISM_ENTRY_READY = entry_checks_218["passed"].all()
display(entry_checks_218)

sample_manifest_218 = pd.DataFrame()

if DETERMINISM_ENTRY_READY:
    sessions_218 = pq.read_table(SESSIONS_FINAL).to_pandas()
    sessions_218["student_prop"] = sessions_218["n_student_turns"]/sessions_218["n_turns"]
    sessions_218["tutor_prop"] = sessions_218["n_tutor_turns"]/sessions_218["n_turns"]
    sessions_218["background_prop"] = sessions_218["n_background_turns"]/sessions_218["n_turns"]

    selected_218 = {}

    def add_sample_218(row, reason):
        sid = str(row["session_id"])
        if sid not in selected_218: selected_218[sid] = {"row":row,"reasons":[reason]}
        elif reason not in selected_218[sid]["reasons"]: selected_218[sid]["reasons"].append(reason)

    ordered = sessions_218.sort_values(["n_turns","session_id"])
    add_sample_218(ordered.iloc[0],"shortest_session")
    add_sample_218(ordered.iloc[-1],"longest_session")

    median_turns = sessions_218["n_turns"].median()
    median_row = sessions_218.assign(
        _distance=(sessions_218["n_turns"]-median_turns).abs()
    ).sort_values(["_distance","session_id"]).iloc[0]
    add_sample_218(median_row,"median_size_session")

    valid_duration = sessions_218.dropna(subset=["duration_seconds"])
    if len(valid_duration):
        add_sample_218(valid_duration.sort_values(["duration_seconds","session_id"]).iloc[0],"minimum_duration")
        add_sample_218(valid_duration.sort_values(["duration_seconds","session_id"]).iloc[-1],"maximum_duration")

    add_sample_218(
        sessions_218.sort_values(["timestamp_tie_count","session_id"],ascending=[False,True]).iloc[0],
        "maximum_timestamp_ties"
    )
    add_sample_218(
        sessions_218.sort_values(["background_prop","session_id"],ascending=[False,True]).iloc[0],
        "background_heavy"
    )
    add_sample_218(
        sessions_218.sort_values(["student_prop","session_id"],ascending=[False,True]).iloc[0],
        "student_heavy"
    )
    add_sample_218(
        sessions_218.sort_values(["tutor_prop","session_id"],ascending=[False,True]).iloc[0],
        "tutor_heavy"
    )

    fill_order = sessions_218.assign(
        _stable_key=sessions_218["session_id"].astype(str).map(
            lambda x:hashlib.sha256(x.encode("utf-8")).hexdigest()
        )
    ).sort_values(["_stable_key","session_id"])

    for _,row in fill_order.iterrows():
        if len(selected_218)>=SAMPLE_TARGET_218: break
        add_sample_218(row,"stable_hash_sample")

    manifest_rows = []
    for sid,item in selected_218.items():
        row = item["row"]
        raw_path = Path(TRANSCRIPT_ROOT)/Path(str(row["source_file_relative"]).replace("\\","/"))
        manifest_rows.append({
            "session_id":sid,
            "reason_selected":" | ".join(item["reasons"]),
            "n_turns":int(row["n_turns"]),
            "duration_seconds":row["duration_seconds"],
            "timestamp_tie_count":int(row["timestamp_tie_count"]),
            "background_proportion":float(row["background_prop"]),
            "source_file_relative":row["source_file_relative"],
            "raw_file_exists":raw_path.exists()
        })

    sample_manifest_218 = pd.DataFrame(manifest_rows)
    sample_manifest_218["passed"] = sample_manifest_218["raw_file_exists"]
    sample_manifest_218["cause"] = np.where(
        sample_manifest_218["raw_file_exists"],"","Raw transcript file not found"
    )

display(sample_manifest_218)

print("\n"+"="*72)
print("TRACE THE ACE — DETERMINISM AUDIT ENTRY")
print("="*72)
print(f"Entry gate ready       : {DETERMINISM_ENTRY_READY}")
print(f"Sessions selected      : {len(sample_manifest_218)}")
print(f"Raw files unavailable  : {0 if sample_manifest_218.empty else int((~sample_manifest_218['raw_file_exists']).sum())}")
print("="*72)

,check,passed,detail
0,Production parse is ready,True,True
1,Full corpus parser audit is ready,True,True
2,Integrated parser function is available,True,True
3,Turn candidate artifact exists,True,D:\Competition\Trace-the-race-local\scratch_ma...
4,Session candidate artifact exists,True,D:\Competition\Trace-the-race-local\scratch_ma...
5,Raw transcript root exists,True,D:\Competition\Trace-the-race-local\Dataset\tr...
6,Required turn reconstruction fields exist,True,[]
7,Required session reconstruction fields exist,True,[]
8,Turn artifact schema remains exact,True,52
9,Session artifact schema remains exact,True,31

,session_id,reason_selected,n_turns,duration_seconds,timestamp_tie_count,background_proportion,source_file_relative,raw_file_exists,passed,cause
0,jlntsbf,shortest_session,15,526.0,0,0.000000,jlntsbf.csv,True,True,
1,bvnewyc,longest_session,622,2890.0,46,0.138264,bvnewyc.csv,True,True,
2,actkyuh,median_size_session,267,2681.0,8,0.011236,actkyuh.csv,True,True,
3,ksvduqc,minimum_duration,31,205.0,4,0.096774,ksvduqc.csv,True,True,
4,eafvzsi,maximum_duration,471,3721.0,29,0.036093,eafvzsi.csv,True,True,
5,egiejia,maximum_timestamp_ties,504,2688.0,56,0.053571,egiejia.csv,True,True,
6,mnvgsri,background_heavy,64,2634.0,19,0.703125,mnvgsri.csv,True,True,
7,kkvsvkj,student_heavy,79,2444.0,1,0.012658,kkvsvkj.csv,True,True,
8,mvkburc,tutor_heavy,582,2699.0,52,0.005155,mvkburc.csv,True,True,
9,exrphmf,stable_hash_sample,235,2704.0,20,0.034043,exrphmf.csv,True,True,
10,dcxwnrr,stable_hash_sample,205,1768.0,11,0.068293,dcxwnrr.csv,True,True,
11,kegxjly,stable_hash_sample,195,2683.0,3,0.020513,kegxjly.csv,True,True,
12,jenrefs,stable_hash_sample,230,2744.0,9,0.039130,jenrefs.csv,True,True,
13,cwpovtt,stable_hash_sample,252,2419.0,19,0.150794,cwpovtt.csv,True,True,

========================================================================
TRACE THE ACE — DETERMINISM AUDIT ENTRY
========================================================================
Entry gate ready       : True
Sessions selected      : 14
Raw files unavailable  : 0
========================================================================

In [65]:
# ============================================================
# 2.18.2 — REPLAY & FORMAL RECONSTRUCTION AUDIT
# ============================================================

replay_results_218 = []
promoted_sample_turns_218 = pa.table({})
promoted_sessions_218 = pa.table({})

def table_equal_218(a,b,schema):
    return (
        isinstance(a,pa.Table) and isinstance(b,pa.Table)
        and a.schema==schema and b.schema==schema
        and a.combine_chunks().equals(b.combine_chunks())
    )

def session_from_table_218(table,sid):
    if "session_id" not in table.column_names: return pa.table({})
    return table.filter(pc.equal(table["session_id"],sid)).combine_chunks()

def read_raw_csv_218(path):
    with open(path,"r",encoding="utf-8-sig",newline="") as f:
        reader = csv.DictReader(f)
        return list(reader.fieldnames or []),list(reader)

def raw_reconstruction_218(raw_path,promoted_turns):
    required_raw = ["session_id","utterance_id","role","content","timestamp"]
    try:
        header,rows = read_raw_csv_218(raw_path)
        missing = sorted(set(required_raw)-set(header))
        if missing: return False,f"Raw CSV missing columns: {missing}"

        candidate_rows = promoted_turns.to_pylist()
        by_source = {}
        for r in candidate_rows:
            idx = r.get("source_row_index")
            if idx is None or int(idx) in by_source:
                return False,"Invalid or duplicate source_row_index in candidate turns"
            by_source[int(idx)] = r

        if len(rows)!=len(candidate_rows):
            return False,f"Raw/candidate row mismatch: {len(rows)} vs {len(candidate_rows)}"

        mapping = {
            "session_id_raw":"session_id","utterance_id_raw":"utterance_id",
            "role_raw":"role","content_raw":"content","timestamp_raw":"timestamp"
        }

        for source_idx,raw in enumerate(rows):
            cand = by_source.get(source_idx)
            if cand is None: return False,f"Missing candidate source_row_index={source_idx}"
            for candidate_field,raw_field in mapping.items():
                if cand.get(candidate_field)!=raw.get(raw_field,""):
                    return False,f"Raw mismatch at source_row={source_idx}, field={candidate_field}"

        return True,"Exact raw-field reconstruction"
    except Exception as e:
        return False,f"{type(e).__name__}: {e}"

def audit_order_digest_218(table):
    fields = [
        x for x in ["source_row_index","turn_index","session_id_raw",
                    "utterance_id_raw","role_raw","content_raw","timestamp_raw"]
        if x in table.column_names
    ]
    rows = table.select(fields).to_pylist()
    payload = json.dumps(rows,ensure_ascii=False,sort_keys=True,separators=(",",":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()

if DETERMINISM_ENTRY_READY and not sample_manifest_218.empty:
    selected_ids_218 = sample_manifest_218["session_id"].astype(str).tolist()
    selected_set_218 = pa.array(selected_ids_218,type=pa.string())
    selected_batches_218 = []

    pf = pq.ParquetFile(TURNS_FINAL)
    try:
        for batch in pf.iter_batches(batch_size=131072):
            sid_col = batch.column(batch.schema.get_field_index("session_id"))
            mask = pc.is_in(sid_col,value_set=selected_set_218)
            if bool(pc.any(mask).as_py()):
                selected_batches_218.append(pa.Table.from_batches([batch]).filter(mask))
    except Exception as e:
        replay_results_218.append({
            "session_id":"__ARTIFACT_SCAN__","passed":False,
            "cause":f"{type(e).__name__}: {e}"
        })
    finally:
        pf.close()
        del pf
        gc.collect()

    if selected_batches_218:
        promoted_sample_turns_218 = pa.concat_tables(selected_batches_218).combine_chunks()
    promoted_sessions_218 = pq.read_table(SESSIONS_FINAL).combine_chunks()

    for _,sample in sample_manifest_218.iterrows():
        sid = str(sample["session_id"])
        causes = []

        result_row = {
            "session_id":sid,"reason_selected":sample["reason_selected"],
            "replay_a_b_turns":False,"replay_a_b_session":False,
            "replay_promoted_turns":False,"replay_promoted_session":False,
            "raw_reconstruction":False,"source_hash_match":False,
            "identity_replay_match":False,"transcript_hash_match":False,
            "order_digest_sensitive":False,"passed":False,"cause":""
        }

        try:
            raw_path = Path(TRANSCRIPT_ROOT)/Path(str(sample["source_file_relative"]).replace("\\","/"))
            promoted_turns = session_from_table_218(promoted_sample_turns_218,sid)
            promoted_session = session_from_table_218(promoted_sessions_218,sid)

            if not raw_path.exists(): causes.append("Raw transcript file missing")
            if promoted_turns.num_rows!=int(sample["n_turns"]):
                causes.append(f"Promoted turn count {promoted_turns.num_rows} != expected {sample['n_turns']}")
            if promoted_session.num_rows!=1:
                causes.append(f"Promoted session rows={promoted_session.num_rows}, expected 1")

            if not causes:
                replay_a = parse_session_candidate(raw_path,expected_session_id=sid)
                replay_b = parse_session_candidate(raw_path,expected_session_id=sid)

                turn_a = replay_a["turn_table"].combine_chunks()
                turn_b = replay_b["turn_table"].combine_chunks()
                session_a = replay_a["session_table"].combine_chunks()
                session_b = replay_b["session_table"].combine_chunks()

                result_row["replay_a_b_turns"] = table_equal_218(turn_a,turn_b,TURN_CANDIDATE_SCHEMA)
                result_row["replay_a_b_session"] = table_equal_218(session_a,session_b,SESSION_CANDIDATE_SCHEMA)
                result_row["replay_promoted_turns"] = table_equal_218(turn_a,promoted_turns,TURN_CANDIDATE_SCHEMA)
                result_row["replay_promoted_session"] = table_equal_218(session_a,promoted_session,SESSION_CANDIDATE_SCHEMA)

                raw_ok,raw_cause = raw_reconstruction_218(raw_path,promoted_turns)
                result_row["raw_reconstruction"] = raw_ok
                if not raw_ok: causes.append(raw_cause)

                promoted_session_row = promoted_session.to_pylist()[0]
                result_row["source_hash_match"] = (
                    sha256_file_218(raw_path)==str(promoted_session_row["file_sha256"]).lower()
                )

                identity_fields = [
                    x for x in ["turn_uid","source_row_uid","raw_field_hash","content_hash"]
                    if x in TURN_CANDIDATE_SCHEMA.names
                ]
                result_row["identity_replay_match"] = (
                    turn_a.select(identity_fields).equals(promoted_turns.select(identity_fields))
                )

                replay_session_row = session_a.to_pylist()[0]
                result_row["transcript_hash_match"] = all(
                    replay_session_row.get(x)==promoted_session_row.get(x)
                    for x in ["raw_transcript_hash","normalized_transcript_hash"]
                )

                digest_original = audit_order_digest_218(turn_a)
                if turn_a.num_rows>1:
                    reverse_idx = pa.array(list(range(turn_a.num_rows-1,-1,-1)),type=pa.int64())
                    digest_reversed = audit_order_digest_218(turn_a.take(reverse_idx))
                    result_row["order_digest_sensitive"] = digest_original!=digest_reversed
                else:
                    result_row["order_digest_sensitive"] = True

                boolean_checks = [
                    "replay_a_b_turns","replay_a_b_session",
                    "replay_promoted_turns","replay_promoted_session",
                    "raw_reconstruction","source_hash_match",
                    "identity_replay_match","transcript_hash_match",
                    "order_digest_sensitive"
                ]
                for name in boolean_checks:
                    if not result_row[name]: causes.append(name)

            result_row["passed"] = len(causes)==0
            result_row["cause"] = " | ".join(causes)

        except Exception as e:
            result_row["passed"] = False
            result_row["cause"] = f"{type(e).__name__}: {e}"

        replay_results_218.append(result_row)

replay_audit_218 = pd.DataFrame(replay_results_218)
display(replay_audit_218)

if len(replay_audit_218):
    print("\nReplay failures:")
    display(replay_audit_218.loc[
        ~replay_audit_218["passed"],
        [c for c in ["session_id","reason_selected","cause"] if c in replay_audit_218.columns]
    ])
else:
    print("Replay audit skipped because the entry gate was not ready.")

,session_id,reason_selected,replay_a_b_turns,replay_a_b_session,replay_promoted_turns,replay_promoted_session,raw_reconstruction,source_hash_match,identity_replay_match,transcript_hash_match,order_digest_sensitive,passed,cause
0,jlntsbf,shortest_session,True,True,True,True,True,True,True,True,True,True,
1,bvnewyc,longest_session,True,True,True,True,True,True,True,True,True,True,
2,actkyuh,median_size_session,True,True,True,True,True,True,True,True,True,True,
3,ksvduqc,minimum_duration,True,True,True,True,True,True,True,True,True,True,
4,eafvzsi,maximum_duration,True,True,True,True,True,True,True,True,True,True,
5,egiejia,maximum_timestamp_ties,True,True,True,True,True,True,True,True,True,True,
6,mnvgsri,background_heavy,True,True,True,True,True,True,True,True,True,True,
7,kkvsvkj,student_heavy,True,True,True,True,True,True,True,True,True,True,
8,mvkburc,tutor_heavy,True,True,True,True,True,True,True,True,True,True,
9,exrphmf,stable_hash_sample,True,True,True,True,True,True,True,True,True,True,
10,dcxwnrr,stable_hash_sample,True,True,True,True,True,True,True,True,True,True,
11,kegxjly,stable_hash_sample,True,True,True,True,True,True,True,True,True,True,
12,jenrefs,stable_hash_sample,True,True,True,True,True,True,True,True,True,True,
13,cwpovtt,stable_hash_sample,True,True,True,True,True,True,True,True,True,True,

Replay failures:

Empty DataFrame
Columns: [session_id, reason_selected, cause]
Index: []

In [66]:
# ============================================================
# 2.18.3 — HUMAN REVIEW & FINAL DETERMINISM GATE
# ============================================================

human_review_218 = pd.DataFrame()
tie_review_218 = pd.DataFrame()

def preview_218(value,limit=140):
    text = "" if value is None else str(value)
    text = text.replace("\r\n","↵").replace("\n","↵").replace("\r","↵")
    return text if len(text)<=limit else text[:limit]+"…"

if DETERMINISM_ENTRY_READY and promoted_sample_turns_218.num_rows:
    review_ids = []

    if len(sample_manifest_218):
        review_ids.append(str(sample_manifest_218.iloc[0]["session_id"]))

        longest = sample_manifest_218.sort_values(
            ["n_turns","session_id"],ascending=[False,True]
        ).iloc[0]["session_id"]
        review_ids.append(str(longest))

        tie_candidates = sample_manifest_218.loc[
            sample_manifest_218["timestamp_tie_count"]>0
        ].sort_values(["timestamp_tie_count","session_id"],ascending=[False,True])

        if len(tie_candidates):
            review_ids.append(str(tie_candidates.iloc[0]["session_id"]))

    review_ids = list(dict.fromkeys(review_ids))
    review_rows = []

    for sid in review_ids:
        table = session_from_table_218(promoted_sample_turns_218,sid)
        rows = table.to_pylist()
        n = len(rows)

        positions = sorted(set(
            list(range(min(3,n)))
            + list(range(max(0,n//2-1),min(n,n//2+2)))
            + list(range(max(0,n-3),n))
        ))

        session_info = sessions_218.loc[sessions_218["session_id"].astype(str)==sid].iloc[0]

        for pos in positions:
            r = rows[pos]
            review_rows.append({
                "session_id":sid,
                "window":"first" if pos<3 else ("last" if pos>=n-3 else "middle"),
                "turn_index":r.get("turn_index"),
                "source_row_index":r.get("source_row_index"),
                "timestamp_raw":r.get("timestamp_raw"),
                "utterance_id_raw":r.get("utterance_id_raw"),
                "role_raw":r.get("role_raw"),
                "role":r.get("role"),
                "ordering_method":session_info["ordering_method"],
                "content_raw_preview":preview_218(r.get("content_raw")),
                "text_norm_preview":preview_218(r.get(T218["text_norm"])) if T218["text_norm"] else ""
            })

    human_review_218 = pd.DataFrame(review_rows)

    tie_candidates = sample_manifest_218.loc[
        sample_manifest_218["timestamp_tie_count"]>0
    ].sort_values(["timestamp_tie_count","session_id"],ascending=[False,True])

    if len(tie_candidates):
        tie_sid = str(tie_candidates.iloc[0]["session_id"])
        tie_table = session_from_table_218(promoted_sample_turns_218,tie_sid)
        tie_df = tie_table.select([
            c for c in ["turn_index","source_row_index","timestamp_raw",
                        "utterance_id_raw","role_raw","role","content_raw"]
            if c in tie_table.column_names
        ]).to_pandas()

        duplicated = tie_df["timestamp_raw"].notna() & tie_df["timestamp_raw"].duplicated(keep=False)

        if duplicated.any():
            first_pos = int(np.flatnonzero(duplicated.to_numpy())[0])
            lo,hi = max(0,first_pos-2),min(len(tie_df),first_pos+4)
            tie_review_218 = tie_df.iloc[lo:hi].copy()
            tie_review_218["content_raw"] = tie_review_218["content_raw"].map(preview_218)
            tie_review_218.insert(0,"session_id",tie_sid)

display(human_review_218)

print("\nRepresentative timestamp-tie window:")
display(tie_review_218)

expected_samples_218 = len(sample_manifest_218)
replayed_samples_218 = (
    int((replay_audit_218["session_id"]!="__ARTIFACT_SCAN__").sum())
    if len(replay_audit_218) and "session_id" in replay_audit_218 else 0
)
replay_failures_218 = (
    int((~replay_audit_218["passed"]).sum())
    if len(replay_audit_218) and "passed" in replay_audit_218 else expected_samples_218
)

final_checks_218 = pd.DataFrame([
    check_218("Determinism audit entry gate passed",DETERMINISM_ENTRY_READY,
              "PASS" if DETERMINISM_ENTRY_READY else "See 2.18.1 entry checks"),

    check_218("Representative sample was created",expected_samples_218>=10,
              f"{expected_samples_218} sessions"),

    check_218("All selected raw files exist",
              bool(expected_samples_218) and sample_manifest_218["raw_file_exists"].all(),
              0 if sample_manifest_218.empty else int((~sample_manifest_218["raw_file_exists"]).sum())),

    check_218("Every selected session was replayed",replayed_samples_218==expected_samples_218,
              f"{replayed_samples_218}/{expected_samples_218}"),

    check_218("Replay A equals Replay B for every session",
              len(replay_audit_218)>0 and replay_audit_218.get("replay_a_b_turns",pd.Series(False,index=replay_audit_218.index)).all()
              and replay_audit_218.get("replay_a_b_session",pd.Series(False,index=replay_audit_218.index)).all(),
              "Exact frozen-schema comparison"),

    check_218("Fresh replay equals promoted artifacts",
              len(replay_audit_218)>0 and replay_audit_218.get("replay_promoted_turns",pd.Series(False,index=replay_audit_218.index)).all()
              and replay_audit_218.get("replay_promoted_session",pd.Series(False,index=replay_audit_218.index)).all(),
              "Turn + session candidate comparison"),

    check_218("Raw source reconstruction passes",
              len(replay_audit_218)>0 and replay_audit_218.get("raw_reconstruction",pd.Series(False,index=replay_audit_218.index)).all(),
              "source_row_index → raw CSV logical row"),

    check_218("Raw source hashes match candidate metadata",
              len(replay_audit_218)>0 and replay_audit_218.get("source_hash_match",pd.Series(False,index=replay_audit_218.index)).all(),
              "SHA256 comparison"),

    check_218("Stable identities reproduce exactly",
              len(replay_audit_218)>0 and replay_audit_218.get("identity_replay_match",pd.Series(False,index=replay_audit_218.index)).all(),
              "turn_uid/source_row_uid and stored identity hashes"),

    check_218("Transcript hashes reproduce exactly",
              len(replay_audit_218)>0 and replay_audit_218.get("transcript_hash_match",pd.Series(False,index=replay_audit_218.index)).all(),
              "raw + normalized transcript hashes"),

    check_218("Audit sequence digest is order-sensitive",
              len(replay_audit_218)>0 and replay_audit_218.get("order_digest_sensitive",pd.Series(False,index=replay_audit_218.index)).all(),
              "Original digest differs from reversed order"),

    check_218("No replay/reconstruction failures remain",replay_failures_218==0,
              f"{replay_failures_218} failed audit rows")
])

DETERMINISM_RECONSTRUCTION_READY = final_checks_218["passed"].all()

display(final_checks_218)

failed_checks_218 = final_checks_218.loc[~final_checks_218["passed"]]
failed_sessions_218 = (
    replay_audit_218.loc[~replay_audit_218["passed"],["session_id","cause"]]
    if len(replay_audit_218) and {"passed","session_id","cause"}.issubset(replay_audit_218.columns)
    else pd.DataFrame(columns=["session_id","cause"])
)

print("\n"+"="*76)
print("TRACE THE ACE — DETERMINISM & RECONSTRUCTION AUDIT")
print("="*76)
print(f"Sessions selected                : {expected_samples_218}")
print(f"Sessions replayed                : {replayed_samples_218}")
print(f"Replay/reconstruction failures   : {replay_failures_218}")
print(f"Required failed checks           : {len(failed_checks_218)}")
print(f"DETERMINISM RECONSTRUCTION READY : {DETERMINISM_RECONSTRUCTION_READY}")
print("="*76)

if len(failed_checks_218):
    print("\nFAILED CHECKS — notebook execution continues:")
    display(failed_checks_218)

if len(failed_sessions_218):
    print("\nFAILED SESSIONS — exact causes:")
    display(failed_sessions_218)

,session_id,window,turn_index,source_row_index,timestamp_raw,utterance_id_raw,role_raw,role,ordering_method,content_raw_preview,text_norm_preview
0,jlntsbf,first,0,0,00:00:00,0,tutor,tutor,TIMESTAMP_PRIMARY,"Hello, Gideon, can you hear me? Hello, can you...","Hello, Gideon, can you hear me? Hello, can you..."
1,jlntsbf,first,1,1,00:00:24,1,student,student,TIMESTAMP_PRIMARY,"No, but I can hear you. Can you check your mic...","No, but I can hear you. Can you check your mic..."
2,jlntsbf,first,2,2,00:00:29,2,tutor,tutor,TIMESTAMP_PRIMARY,"Yes, you have to check your speaker and microp...","Yes, you have to check your speaker and microp..."
3,jlntsbf,middle,6,6,00:01:57,6,student,student,TIMESTAMP_PRIMARY,"Yes, Gideon, can you hear me now? Can you plea...","Yes, Gideon, can you hear me now? Can you plea..."
4,jlntsbf,middle,7,7,00:02:58,7,tutor,tutor,TIMESTAMP_PRIMARY,"Can you please speak? Gideon, can you try to s...","Can you please speak? Gideon, can you try to s..."
5,jlntsbf,middle,8,8,00:03:28,8,tutor,tutor,TIMESTAMP_PRIMARY,"Can you hear me? Okay, so can you talk? Can yo...","Can you hear me? Okay, so can you talk? Can yo..."
6,jlntsbf,last,12,12,00:08:17,12,student,student,TIMESTAMP_PRIMARY,[unclear] [unclear],[unclear] [unclear]
7,jlntsbf,last,13,13,00:08:27,13,student,student,TIMESTAMP_PRIMARY,[unclear] [unclear],[unclear] [unclear]
8,jlntsbf,last,14,14,00:08:46,14,student,student,TIMESTAMP_PRIMARY,[unclear] It.,[unclear] It.
9,bvnewyc,first,0,0,00:00:00,0,student,student,TIMESTAMP_PRIMARY,Hello?,Hello?
10,bvnewyc,first,1,1,00:00:00,1,background,background,TIMESTAMP_PRIMARY,[unclear],[unclear]
11,bvnewyc,first,2,2,00:00:00,2,tutor,tutor,TIMESTAMP_PRIMARY,"Hello, Callum. Can you hear me?","Hello, Callum. Can you hear me?"
12,bvnewyc,middle,310,310,00:26:59,310,student,student,TIMESTAMP_PRIMARY,"Yes. Great. Okay, so now moving on to our next...","Yes. Great. Okay, so now moving on to our next..."
13,bvnewyc,middle,311,311,00:27:12,311,student,student,TIMESTAMP_PRIMARY,"Don't you just— yeah, you just plus the 4 and ...","Don't you just— yeah, you just plus the 4 and ..."
14,bvnewyc,middle,312,312,00:27:24,312,tutor,tutor,TIMESTAMP_PRIMARY,Exactly. You just go ahead and plus them up.,Exactly. You just go ahead and plus them up.
15,bvnewyc,last,619,619,00:47:59,619,tutor,tutor,TIMESTAMP_PRIMARY,"Alright. Okay, Callum. So 5 marks on this ques...","Alright. Okay, Callum. So 5 marks on this ques..."
16,bvnewyc,last,620,620,00:48:09,620,student,student,TIMESTAMP_PRIMARY,[unclear],[unclear]
17,bvnewyc,last,621,621,00:48:10,621,tutor,tutor,TIMESTAMP_PRIMARY,All right. And I will see you in our next sess...,All right. And I will see you in our next sess...
18,egiejia,first,0,0,00:00:00,0,background,background,TIMESTAMP_PRIMARY,[unclear],[unclear]
19,egiejia,first,1,1,00:00:00,1,tutor,tutor,TIMESTAMP_PRIMARY,Hello? Hello? Hello? Hello?,Hello? Hello? Hello? Hello?
20,egiejia,first,2,2,00:00:14,2,tutor,tutor,TIMESTAMP_PRIMARY,"Yeah, hello? Hello?","Yeah, hello? Hello?"
21,egiejia,middle,251,251,00:21:38,251,student,student,TIMESTAMP_PRIMARY,"Yeah, I'm tired. I woke up too early. Too early.","Yeah, I'm tired. I woke up too early. Too early."
22,egiejia,middle,252,252,00:21:43,252,tutor,tutor,TIMESTAMP_PRIMARY,Really? Why is that?,Really? Why is that?
23,egiejia,middle,253,253,00:21:45,253,student,student,TIMESTAMP_PRIMARY,I don't know. [unclear],I don't know. [unclear]
24,egiejia,last,501,501,00:44:44,501,student,student,TIMESTAMP_PRIMARY,Thank you.,Thank you.
25,egiejia,last,502,502,00:44:45,502,tutor,tutor,TIMESTAMP_PRIMARY,All right. Have an awesome week ahead.,All right. Have an awesome week ahead.
26,egiejia,last,503,503,00:44:48,503,tutor,tutor,TIMESTAMP_PRIMARY,All right. [unclear],All right. [unclear]

Representative timestamp-tie window:

,session_id,turn_index,source_row_index,timestamp_raw,utterance_id_raw,role_raw,role,content_raw
0,egiejia,0,0,00:00:00,0,background,background,[unclear]
1,egiejia,1,1,00:00:00,1,tutor,tutor,Hello? Hello? Hello? Hello?
2,egiejia,2,2,00:00:14,2,tutor,tutor,"Yeah, hello? Hello?"
3,egiejia,3,3,00:00:18,3,student,student,Hello? [unclear]

,check,passed,detail
0,Determinism audit entry gate passed,True,PASS
1,Representative sample was created,True,14 sessions
2,All selected raw files exist,True,0
3,Every selected session was replayed,True,14/14
4,Replay A equals Replay B for every session,True,Exact frozen-schema comparison
5,Fresh replay equals promoted artifacts,True,Turn + session candidate comparison
6,Raw source reconstruction passes,True,source_row_index → raw CSV logical row
7,Raw source hashes match candidate metadata,True,SHA256 comparison
8,Stable identities reproduce exactly,True,turn_uid/source_row_uid and stored identity ha...
9,Transcript hashes reproduce exactly,True,raw + normalized transcript hashes
10,Audit sequence digest is order-sensitive,True,Original digest differs from reversed order
11,No replay/reconstruction failures remain,True,0 failed audit rows

============================================================================
TRACE THE ACE — DETERMINISM & RECONSTRUCTION AUDIT
============================================================================
Sessions selected                : 14
Sessions replayed                : 14
Replay/reconstruction failures   : 0
Required failed checks           : 0
DETERMINISM RECONSTRUCTION READY : True
============================================================================

In [73]:
# ============================================================
# DEBUG — PRODUCTION HASH REFERENCE RESOLUTION
# ============================================================

from pathlib import Path
import hashlib
import json


print("=" * 80)
print("TRACE THE ACE — PRODUCTION HASH REFERENCE DIAGNOSTIC")
print("=" * 80)


# ------------------------------------------------------------
# 1. Current candidate artifact hashes
# ------------------------------------------------------------

def sha256_file(path, chunk_size=8 * 1024 * 1024):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(
            lambda: f.read(chunk_size),
            b"",
        ):
            h.update(chunk)

    return h.hexdigest()


current_turn_hash = sha256_file(TURNS_FINAL)
current_session_hash = sha256_file(SESSIONS_FINAL)

print("\nCURRENT ARTIFACT HASHES")

print(
    "Turn    :",
    current_turn_hash,
)

print(
    "Session :",
    current_session_hash,
)


# ------------------------------------------------------------
# 2. Search current Python state
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("HASH-LIKE RUNTIME VARIABLES")
print("=" * 80)

for name, value in sorted(
    globals().items()
):

    name_upper = name.upper()

    if (
        "HASH" in name_upper
        or
        "SHA" in name_upper
        or
        "FINGERPRINT" in name_upper
    ):

        if isinstance(
            value,
            (str, Path, bool, int, float)
        ):

            print(
                f"{name:45s} = {value}"
            )


# ------------------------------------------------------------
# 3. Search parser output tree for JSON artifacts
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("PARSER JSON ARTIFACTS")
print("=" * 80)

parser_root = Path(
    PARSER_OUTPUT_DIR
)

for path in sorted(
    parser_root.rglob("*.json")
):

    print(
        f"{path} | "
        f"{path.stat().st_size:,} bytes"
    )


# ------------------------------------------------------------
# 4. Inspect checkpoint if present
# ------------------------------------------------------------

checkpoint_path = (
    parser_root
    / ".production_tmp"
    / "checkpoint.json"
)

print("\n" + "=" * 80)
print("CHECKPOINT")
print("=" * 80)

if checkpoint_path.is_file():

    with open(
        checkpoint_path,
        "r",
        encoding="utf-8",
    ) as f:

        checkpoint = json.load(f)

    for key, value in checkpoint.items():

        print(
            f"{key:45s} = {value}"
        )

else:

    print(
        "No production checkpoint remains."
    )


# ------------------------------------------------------------
# 5. Search for stored hash values in JSON
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("STORED HASH MATCH SEARCH")
print("=" * 80)

target_hashes = {
    current_turn_hash,
    current_session_hash,
}

for json_path in sorted(
    parser_root.rglob("*.json")
):

    try:

        with open(
            json_path,
            "r",
            encoding="utf-8",
        ) as f:

            text = f.read()

    except Exception:

        continue

    matches = [
        h
        for h in target_hashes
        if h in text
    ]

    if matches:

        print(
            f"\nMATCH FOUND: {json_path}"
        )

        for h in matches:

            print(
                f"  {h}"
            )


print("\n" + "=" * 80)
print("HASH REFERENCE DIAGNOSTIC COMPLETE")
print("=" * 80)

================================================================================
TRACE THE ACE — PRODUCTION HASH REFERENCE DIAGNOSTIC
================================================================================

CURRENT ARTIFACT HASHES
Turn    : 926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed984de04946f59f5c37
Session : 24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f50821d70be5cc9d5e9

================================================================================
HASH-LIKE RUNTIME VARIABLES
================================================================================
CONTENT_HASH_VERSION                          = 1.0
CONTRACT_TRANSCRIPT_SHA256                    = 3f563b9911cd2f2e4d01dd5a457509ceaac6eb31ae880148034d7b2ca89402df
FROZEN_HASH_SOURCE                            = raw_format_file_profile
FROZEN_SOURCE_MANIFEST_SHA256                 = 5e7b5295758161951f142f57211fcc741cda09fb984a6b38788df60245338807
IDENTITY_HASH_ALGORITHM                       = sha256
IDENTITY_POLICY_CONFIG_SHA256                 = 61c44dc910943e78ea697187554120ce58c0ab5b7ccbda32d69a977e99d9e1db
INGESTION_CONFIG_SHA256                       = 36d325eec574ae589a98af56434e2e1d96ee0a6d5dc7631822f0943787ff784d
INTEGRATED_PARSER_CONFIG_SHA256               = 83d9f86ad2fba7d921dd0cfb864872ee7607f28e20906650cd6d82bffa2fdf41
INVENTORY_MANIFEST_SHA256                     = 00a54026236b7d353328b33bd7ceb7766f154134caff73cb52a03910017b8d3b
ORDERING_CALIBRATION_CONFIG_SHA256            = c8f9ebfe6de959246ddce0cfefbfe4185f872ca8f97368945bba795bd370164c
ORDERING_CONFLICT_CONFIG_SHA256               = 695548c63ee5b3adc74c96386441cf2895e44642dc8d5c86f609a808e84e91ae
ORDERING_POLICY_CONFIG_SHA256                 = ad32a87bfa6c2e5ff99ff45e1ff6d7173a1ad982a38786c69878369cb96d7cb7
ORDER_HASH_SENSITIVE                          = True
PARSER_SCHEMA_SHA256                          = 67452c0762daff1440e4917716445eb3e9fdf1b8eefceac7da87de069e34ace8
RAW_FIELD_HASH_VERSION                        = 1.0
ROLE_MAPPING_CONFIG_SHA256                    = e2309329e7735a252fd2a26a6c8b77d9e0ec9c1832631a3a4f19407e09debf32
SESSION_SCHEMA_SHA256                         = dbbf38f6bbfb4f9efa6b0b71d494020ec3820999b96be8c85b1618737135873d
STRUCTURAL_METADATA_CONFIG_SHA256             = 92c8a77c718614d430b57a628d01cd2e0a8fe87ed03c795e48e6b16350c32c56
TEXT_NORMALIZATION_CONFIG_SHA256              = 1cbe42467a346145e0dc24d407065c3c2b7c2b0814d0a4a6662155fcfa882315
TIMESTAMP_PARSER_CONFIG_SHA256                = e1833c23f225ce7f5a2308cce68d62c3aa620e4f4a5ea973659875c97c2bbe41
TRANSCRIPT_HASH_VERSION                       = 1.0
TURN_SCHEMA_SHA256                            = 7844015a99851b114bb796c346d6f79f3dcf744f5730e431ff15fc0a7073831d
UTTERANCE_ID_PARSER_CONFIG_SHA256             = e9760b9ee2fa8a21e5e75b45d3e6f9901ea3fe0675f396c478c13454997b0d7d
actual_contract_hash                          = 03d238a18c0aacf2e8f3c410b0ba0b2410e88cfe9a3816f1e14d2ff2a27cc5fa
actual_responses_hash                         = dc5e3f3926b8120947c43d77fa240ae3b631010d310d544431160b61c5ef3355
current_session_hash                          = 24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f50821d70be5cc9d5e9
current_session_hash_219                      = 24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f50821d70be5cc9d5e9
current_session_hash_error_219                =
current_turn_hash                             = 926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed984de04946f59f5c37
current_turn_hash_219                         = 926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed984de04946f59f5c37
current_turn_hash_error_219                   =
expected_contract_hash                        = 03d238a18c0aacf2e8f3c410b0ba0b2410e88cfe9a3816f1e14d2ff2a27cc5fa
expected_responses_hash                       = dc5e3f3926b8120947c43d77fa240ae3b631010d310d544431160b61c5ef3355
manifest_payload_sha256_219                   = 9e756812f3f7957fdc5cc92a80f327387757a1b45faee9ac54f8862d81144858
payload_hash_valid_219                        = False
real_hash_failures                            = 0
reloaded_schema_hash                          = 67452c0762daff1440e4917716445eb3e9fdf1b8eefceac7da87de069e34ace8
schema_hash_identical                         = True
session_manifest_hash_match_219               = False
session_sha256_217                            = 24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f50821d70be5cc9d5e9
source_directory_hash_219                     = 3f563b9911cd2f2e4d01dd5a457509ceaac6eb31ae880148034d7b2ca89402df
source_manifest_hash_219                      = 5e7b5295758161951f142f57211fcc741cda09fb984a6b38788df60245338807
turn_manifest_hash_match_219                  = False
turn_sha256_217                               = 926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed984de04946f59f5c37

================================================================================
PARSER JSON ARTIFACTS
================================================================================
D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\_work\parser_schema.json | 12,197 bytes

================================================================================
CHECKPOINT
================================================================================
No production checkpoint remains.

================================================================================
STORED HASH MATCH SEARCH
================================================================================

================================================================================
HASH REFERENCE DIAGNOSTIC COMPLETE
================================================================================

In [74]:
# ============================================================
# REPAIR — PERSIST PRODUCTION ARTIFACT HASH REFERENCES
# ============================================================

from pathlib import Path
import json
import hashlib


print("=" * 80)
print("TRACE THE ACE — PERSIST PRODUCTION ARTIFACT HASH REFERENCES")
print("=" * 80)


# ------------------------------------------------------------
# 1. SHA256 helper
# ------------------------------------------------------------

def sha256_file(path, chunk_size=8 * 1024 * 1024):

    digest = hashlib.sha256()

    with open(path, "rb") as f:

        for chunk in iter(
            lambda: f.read(chunk_size),
            b"",
        ):

            digest.update(chunk)

    return digest.hexdigest()


# ------------------------------------------------------------
# 2. Preconditions
# ------------------------------------------------------------

assert TURNS_FINAL.exists(), (
    f"Missing production turn artifact: {TURNS_FINAL}"
)

assert SESSIONS_FINAL.exists(), (
    f"Missing production session artifact: {SESSIONS_FINAL}"
)

assert PRODUCTION_PARSE_READY, (
    "PRODUCTION_PARSE_READY must be True."
)


# ------------------------------------------------------------
# 3. Recompute hashes from current promoted artifacts
# ------------------------------------------------------------

PRODUCTION_TURN_SHA256 = sha256_file(
    TURNS_FINAL
)

PRODUCTION_SESSION_SHA256 = sha256_file(
    SESSIONS_FINAL
)


print("\nProduction artifact hashes:")

print(
    "TURN    :",
    PRODUCTION_TURN_SHA256,
)

print(
    "SESSION :",
    PRODUCTION_SESSION_SHA256,
)


# ------------------------------------------------------------
# 4. Verify against hashes already reported by 2.16.3
# ------------------------------------------------------------

EXPECTED_TURN_SHA256 = (
    "926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed"
    "984de04946f59f5c37"
)

EXPECTED_SESSION_SHA256 = (
    "24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f"
    "50821d70be5cc9d5e9"
)

assert (
    PRODUCTION_TURN_SHA256
    ==
    EXPECTED_TURN_SHA256
), (
    "Current turn artifact hash does not match "
    "the verified 2.16.3 production hash."
)

assert (
    PRODUCTION_SESSION_SHA256
    ==
    EXPECTED_SESSION_SHA256
), (
    "Current session artifact hash does not match "
    "the verified 2.16.3 production hash."
)


# ------------------------------------------------------------
# 5. Persist immutable production reference
# ------------------------------------------------------------

PRODUCTION_REFERENCE_PATH = (
    Path(PARSER_OUTPUT_DIR)
    / "production_artifact_reference.json"
)


production_reference = {

    "artifact_contract_version": "1.0",

    "status": "PRODUCTION_REFERENCE",

    "canonical": False,

    "candidate_boundary": True,

    "turn_artifact": {
        "path": str(TURNS_FINAL),
        "sha256": PRODUCTION_TURN_SHA256,
        "rows": int(EXPECTED_TURNS),
    },

    "session_artifact": {
        "path": str(SESSIONS_FINAL),
        "sha256": PRODUCTION_SESSION_SHA256,
        "rows": int(EXPECTED_SESSIONS),
    },

    "source_manifest_sha256": (
        FROZEN_SOURCE_MANIFEST_SHA256
    ),

    "production_parse_ready": True,
}


# ------------------------------------------------------------
# 6. Atomic write
# ------------------------------------------------------------

reference_tmp = (
    PRODUCTION_REFERENCE_PATH.with_suffix(
        ".json.tmp"
    )
)

with open(
    reference_tmp,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        production_reference,
        f,
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )


# ------------------------------------------------------------
# 7. Round-trip verification
# ------------------------------------------------------------

with open(
    reference_tmp,
    "r",
    encoding="utf-8",
) as f:

    reference_check = json.load(f)


assert (
    reference_check["turn_artifact"]["sha256"]
    ==
    PRODUCTION_TURN_SHA256
)

assert (
    reference_check["session_artifact"]["sha256"]
    ==
    PRODUCTION_SESSION_SHA256
)

assert (
    reference_check["source_manifest_sha256"]
    ==
    FROZEN_SOURCE_MANIFEST_SHA256
)


# ------------------------------------------------------------
# 8. Promote
# ------------------------------------------------------------

import os

os.replace(
    reference_tmp,
    PRODUCTION_REFERENCE_PATH,
)


assert PRODUCTION_REFERENCE_PATH.exists()


print("\n" + "=" * 80)
print("PRODUCTION HASH REFERENCE: READY")
print("=" * 80)

print(
    f"Reference : {PRODUCTION_REFERENCE_PATH}"
)

print(
    f"Turn SHA  : {PRODUCTION_TURN_SHA256}"
)

print(
    f"Session SHA: {PRODUCTION_SESSION_SHA256}"
)

print(
    f"Source SHA : {FROZEN_SOURCE_MANIFEST_SHA256}"
)

print("=" * 80)

================================================================================
TRACE THE ACE — PERSIST PRODUCTION ARTIFACT HASH REFERENCES
================================================================================

Production artifact hashes:
TURN    : 926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed984de04946f59f5c37
SESSION : 24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f50821d70be5cc9d5e9

================================================================================
PRODUCTION HASH REFERENCE: READY
================================================================================
Reference : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\production_artifact_reference.json
Turn SHA  : 926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed984de04946f59f5c37
Session SHA: 24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f50821d70be5cc9d5e9
Source SHA : 5e7b5295758161951f142f57211fcc741cda09fb984a6b38788df60245338807
================================================================================

In [75]:
# ============================================================
# DEBUG — DOES 2.19.1 SEE THE PRODUCTION REFERENCE?
# ============================================================

print("=" * 80)
print("2.19 HASH REFERENCE VISIBILITY CHECK")
print("=" * 80)

for name in [
    "PRODUCTION_TURN_SHA256",
    "PRODUCTION_SESSION_SHA256",
    "PRODUCTION_ARTIFACT_REFERENCE_PATH",
    "PRODUCTION_REFERENCE_PATH",
    "TURN_PRODUCTION_SHA256",
    "SESSION_PRODUCTION_SHA256",
]:
    print(
        f"{name:40s} = "
        f"{globals().get(name, '<MISSING>')}"
    )

print("=" * 80)

================================================================================
2.19 HASH REFERENCE VISIBILITY CHECK
================================================================================
PRODUCTION_TURN_SHA256                   = 926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed984de04946f59f5c37
PRODUCTION_SESSION_SHA256                = 24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f50821d70be5cc9d5e9
PRODUCTION_ARTIFACT_REFERENCE_PATH       = <MISSING>
PRODUCTION_REFERENCE_PATH                = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\production_artifact_reference.json
TURN_PRODUCTION_SHA256                   = <MISSING>
SESSION_PRODUCTION_SHA256                = <MISSING>
================================================================================

In [76]:
# ============================================================
# DEBUG — 2.19.1 ACTUAL HASH REFERENCE EXPECTATIONS
# ============================================================

import inspect

print("=" * 80)
print("TRACE THE ACE — 2.19.1 HASH REFERENCE EXPECTATIONS")
print("=" * 80)

# Find variables/functions containing production/hash/reference
interesting = []

for name, value in globals().items():
    name_upper = name.upper()

    if any(
        token in name_upper
        for token in [
            "PRODUCTION",
            "TURN_HASH",
            "SESSION_HASH",
            "SHA256",
            "REFERENCE",
        ]
    ):
        interesting.append(name)

print("\nCurrent relevant symbols:")
for name in sorted(set(interesting)):
    print(f"  {name}")

print("\nPersisted reference:")
print(PRODUCTION_REFERENCE_PATH)

assert PRODUCTION_REFERENCE_PATH.exists()

with open(
    PRODUCTION_REFERENCE_PATH,
    "r",
    encoding="utf-8",
) as f:
    persisted_reference = json.load(f)

print("\nPersisted reference contents:")
display(
    pd.DataFrame([
        {
            "artifact": "turns",
            "sha256": persisted_reference[
                "turn_artifact"
            ]["sha256"],
            "rows": persisted_reference[
                "turn_artifact"
            ]["rows"],
        },
        {
            "artifact": "sessions",
            "sha256": persisted_reference[
                "session_artifact"
            ]["sha256"],
            "rows": persisted_reference[
                "session_artifact"
            ]["rows"],
        },
    ])
)

print("\n" + "=" * 80)

================================================================================
TRACE THE ACE — 2.19.1 HASH REFERENCE EXPECTATIONS
================================================================================

Current relevant symbols:
  CONTRACT_TRANSCRIPT_SHA256
  EXPECTED_SESSION_SHA256
  EXPECTED_TURN_SHA256
  FROZEN_SOURCE_MANIFEST_SHA256
  IDENTITY_POLICY_CONFIG_SHA256
  INGESTION_CONFIG_SHA256
  INTEGRATED_PARSER_CONFIG_SHA256
  INVENTORY_MANIFEST_SHA256
  ORDERING_CALIBRATION_CONFIG_SHA256
  ORDERING_CONFLICT_CONFIG_SHA256
  ORDERING_POLICY_CONFIG_SHA256
  PARSER_SCHEMA_SHA256
  PRODUCTION_ALLOW_FINAL_OVERWRITE
  PRODUCTION_BATCH_SESSIONS
  PRODUCTION_CONFIG
  PRODUCTION_ENTRY_READY
  PRODUCTION_PARSE_READY
  PRODUCTION_PARSE_VERSION
  PRODUCTION_PROGRESS_EVERY
  PRODUCTION_REFERENCE_PATH
  PRODUCTION_SESSION_SHA256
  PRODUCTION_SIGNATURE
  PRODUCTION_TMP_ROOT
  PRODUCTION_TURN_SHA256
  ROLE_MAPPING_CONFIG_SHA256
  SESSION_SCHEMA_SHA256
  STRUCTURAL_METADATA_CONFIG_SHA256
  TEXT_NORMALIZATION_CONFIG_SHA256
  TIMESTAMP_PARSER_CONFIG_SHA256
  TURN_SCHEMA_SHA256
  UTTERANCE_ID_PARSER_CONFIG_SHA256
  current_session_hash
  current_session_hash_219
  current_session_hash_error_219
  current_turn_hash
  current_turn_hash_219
  current_turn_hash_error_219
  duplicate_reference_rows
  manifest_payload_sha256_219
  previous_session_hash_217
  previous_turn_hash_217
  production_entry_checks
  production_final_summary
  production_ready_218
  production_reference
  production_session_hash_219
  production_state
  production_turn_hash_219
  reference_check
  reference_class_summary
  reference_tmp
  session_sha256_217
  sha256_bytes
  sha256_file
  sha256_file_217
  sha256_file_218
  sha256_file_219
  sha256_identity
  structural_missing_reference
  turn_sha256_217
  valid_sha256

Persisted reference:
D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\production_artifact_reference.json

Persisted reference contents:

   artifact                                             sha256     rows
0     turns  926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed...  6139854
1  sessions  24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f...    22821

================================================================================

# Section 2.19 — Parser Manifest & Final Parser Gate

This section freezes the certified parser state into a portable machine-readable manifest.
No transcript is reparsed and no candidate turn or session artifact is modified.
All upstream parser, production, corpus-audit, and determinism gates are rechecked before publication.
Candidate Parquet artifacts are reopened to verify their schemas, row counts, and current SHA256 fingerprints.
The manifest records source binding, frozen schemas, parser policies, production census, audit evidence, and artifact identities.
Only machine-derived results from the completed notebook stages are used for corpus statistics.
Artifact paths are stored relative to the parser output directory for portability.
Candidate artifacts are explicitly marked non-canonical because canonical certification belongs to the integrity notebook.
The JSON manifest is written through a temporary file, read back, and verified before atomic promotion.
The section ends with `PARSER_READY_FOR_INTEGRITY`.

In [83]:
# ============================================================
# 2.19.1 — FINAL CERTIFICATION SNAPSHOT
# ============================================================
#
# Purpose:
#   Freeze the parser certification state immediately before
#   parser_manifest.json publication.
#
# Important:
#   Production artifact hashes are loaded from the persisted
#   production_artifact_reference.json created after 2.16.3.
#
# This section MUST NOT:
#   - reparse transcripts
#   - rebuild parquet artifacts
#   - modify source fingerprints
#   - modify frozen folds
#   - depend on notebook-memory hash variables
#
# ============================================================

import os
import json
import gc
import hashlib
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


# ------------------------------------------------------------
# 1. Certification constants
# ------------------------------------------------------------

PARSER_MANIFEST_VERSION = "1.0"

PARSER_MANIFEST_PATH = (
    Path(PARSER_OUTPUT_DIR)
    / "parser_manifest.json"
)

PARSER_MANIFEST_TMP = (
    Path(PARSER_OUTPUT_DIR)
    / ".parser_manifest.json.tmp"
)


# ------------------------------------------------------------
# 2. Check helper
# ------------------------------------------------------------

def check_219(
    check,
    passed,
    detail="",
    cause="",
):
    return {
        "check": check,
        "passed": bool(passed),
        "detail": str(detail),
        "cause": str(cause),
    }


# ------------------------------------------------------------
# 3. SHA256 helper
# ------------------------------------------------------------

def sha256_file_219(
    path,
    chunk_size=8 * 1024 * 1024,
):

    h = hashlib.sha256()

    try:

        with open(path, "rb") as f:

            for chunk in iter(
                lambda: f.read(chunk_size),
                b"",
            ):
                h.update(chunk)

        return h.hexdigest(), ""

    except Exception as e:

        return (
            None,
            f"{type(e).__name__}: {e}",
        )


# ------------------------------------------------------------
# 4. Parquet artifact inspection
# ------------------------------------------------------------

def artifact_info_219(
    path,
    frozen_schema,
):

    info = {
        "exists": False,
        "readable": False,
        "rows": None,
        "schema_exact": False,
        "schema_fields": None,
        "sha256": None,
        "cause": "",
    }

    try:

        path = Path(path)

        info["exists"] = path.exists()

        if not info["exists"]:

            info["cause"] = (
                "Artifact does not exist"
            )

            return info

        metadata = pq.read_metadata(path)
        schema = pq.read_schema(path)

        info.update(
            {
                "readable": True,
                "rows": int(
                    metadata.num_rows
                ),
                "schema_exact": (
                    schema == frozen_schema
                ),
                "schema_fields": len(schema),
            }
        )

        info["sha256"], hash_error = (
            sha256_file_219(path)
        )

        if hash_error:
            info["cause"] = hash_error

    except Exception as e:

        info["cause"] = (
            f"{type(e).__name__}: {e}"
        )

    return info


# ------------------------------------------------------------
# 5. Runtime upstream gates
# ------------------------------------------------------------

g219 = globals()

upstream_219 = {
    "integrated_parser_ready": bool(
        g219.get(
            "INTEGRATED_PARSER_READY",
            False,
        )
    ),

    "production_parse_ready": bool(
        g219.get(
            "PRODUCTION_PARSE_READY",
            False,
        )
    ),

    "corpus_parser_audit_ready": bool(
        g219.get(
            "CORPUS_PARSER_AUDIT_READY",
            False,
        )
    ),

    "determinism_reconstruction_ready": bool(
        g219.get(
            "DETERMINISM_RECONSTRUCTION_READY",
            False,
        )
    ),
}


# ------------------------------------------------------------
# 6. Inspect promoted production artifacts
# ------------------------------------------------------------

turn_info_219 = artifact_info_219(
    TURNS_FINAL,
    TURN_CANDIDATE_SCHEMA,
)

session_info_219 = artifact_info_219(
    SESSIONS_FINAL,
    SESSION_CANDIDATE_SCHEMA,
)


# ------------------------------------------------------------
# 7. Load persisted production artifact reference
# ------------------------------------------------------------
#
# This is the critical repair.
#
# DO NOT use:
#
#   globals()["turns_candidate_sha256"]
#
# because notebook memory is not a durable certification source.
#
# ------------------------------------------------------------

PRODUCTION_REFERENCE_PATH_219 = (
    Path(PARSER_OUTPUT_DIR)
    / "production_artifact_reference.json"
)

production_turn_hash_219 = None
production_session_hash_219 = None

source_manifest_hash_219 = g219.get(
    "FROZEN_SOURCE_MANIFEST_SHA256"
)

source_directory_hash_219 = g219.get(
    "CONTRACT_TRANSCRIPT_SHA256"
)

production_reference_219 = None
production_reference_error_219 = ""

try:

    assert (
        PRODUCTION_REFERENCE_PATH_219.is_file()
    ), (
        "Persisted production artifact reference "
        "is missing: "
        f"{PRODUCTION_REFERENCE_PATH_219}"
    )

    with open(
        PRODUCTION_REFERENCE_PATH_219,
        "r",
        encoding="utf-8",
    ) as f:

        production_reference_219 = json.load(f)

    production_turn_hash_219 = (
        production_reference_219[
            "turn_artifact"
        ][
            "sha256"
        ]
    )

    production_session_hash_219 = (
        production_reference_219[
            "session_artifact"
        ][
            "sha256"
        ]
    )

except Exception as e:

    production_reference_error_219 = (
        f"{type(e).__name__}: {e}"
    )


# ------------------------------------------------------------
# 8. Validate persisted production reference
# ------------------------------------------------------------

production_reference_valid_219 = False

if (
    production_reference_219 is not None
    and
    production_reference_error_219 == ""
):

    production_reference_valid_219 = (
        production_reference_219.get(
            "artifact_contract_version"
        )
        == "1.0"

        and
        production_reference_219.get(
            "status"
        )
        == "PRODUCTION_REFERENCE"

        and
        production_reference_219.get(
            "production_parse_ready"
        )
        is True

        and
        production_reference_219.get(
            "source_manifest_sha256"
        )
        == source_manifest_hash_219

        and
        isinstance(
            production_turn_hash_219,
            str,
        )

        and
        len(
            production_turn_hash_219
        )
        == 64

        and
        isinstance(
            production_session_hash_219,
            str,
        )

        and
        len(
            production_session_hash_219
        )
        == 64
    )


print("=" * 80)
print(
    "TRACE THE ACE — PRODUCTION REFERENCE"
)
print("=" * 80)

print(
    f"Reference path : "
    f"{PRODUCTION_REFERENCE_PATH_219}"
)

print(
    f"Reference exists : "
    f"{PRODUCTION_REFERENCE_PATH_219.exists()}"
)

print(
    f"Turn production SHA256 : "
    f"{production_turn_hash_219}"
)

print(
    f"Session production SHA256 : "
    f"{production_session_hash_219}"
)

print(
    f"Source manifest SHA256 : "
    f"{source_manifest_hash_219}"
)

print(
    f"Reference valid : "
    f"{production_reference_valid_219}"
)

if production_reference_error_219:

    print(
        f"Reference error : "
        f"{production_reference_error_219}"
    )


# ------------------------------------------------------------
# 9. Read complete session artifact
# ------------------------------------------------------------

sessions_manifest_219 = pd.DataFrame()

session_read_error_219 = ""

try:

    sessions_manifest_219 = (
        pq.read_table(
            SESSIONS_FINAL
        ).to_pandas()
    )

except Exception as e:

    session_read_error_219 = (
        f"{type(e).__name__}: {e}"
    )


# ------------------------------------------------------------
# 10. Machine-derived session census
# ------------------------------------------------------------

if not sessions_manifest_219.empty:

    census_219 = {

        "turns_from_sessions": int(
            sessions_manifest_219[
                "n_turns"
            ].sum()
        ),

        "sessions": int(
            len(
                sessions_manifest_219
            )
        ),

        "student_turns": int(
            sessions_manifest_219[
                "n_student_turns"
            ].sum()
        ),

        "tutor_turns": int(
            sessions_manifest_219[
                "n_tutor_turns"
            ].sum()
        ),

        "background_turns": int(
            sessions_manifest_219[
                "n_background_turns"
            ].sum()
        ),

        "unknown_turns": int(
            sessions_manifest_219[
                "n_unknown_roles"
            ].sum()
        ),

        "timestamp_tie_groups": int(
            sessions_manifest_219[
                "timestamp_tie_count"
            ].sum()
        ),

        "timestamp_tie_sessions": int(
            (
                sessions_manifest_219[
                    "timestamp_tie_count"
                ]
                > 0
            ).sum()
        ),

        "fallback_sessions": int(
            sessions_manifest_219[
                "fallback_order_used"
            ].sum()
        ),

        "ambiguous_sessions": int(
            sessions_manifest_219[
                "ambiguous_order_flag"
            ].sum()
        ),

        "rollover_sessions": int(
            (
                sessions_manifest_219[
                    "midnight_rollover_count"
                ]
                > 0
            ).sum()
        ),

        "quality_warning_sessions": int(
            (
                sessions_manifest_219[
                    "quality_warning_count"
                ]
                > 0
            ).sum()
        ),
    }

    ordering_method_219 = (
        sessions_manifest_219[
            "ordering_method"
        ]
        .value_counts()
        .to_dict()
    )

    ordering_confidence_219 = (
        sessions_manifest_219[
            "ordering_confidence"
        ]
        .value_counts()
        .to_dict()
    )

    ordering_comparability_219 = (
        sessions_manifest_219[
            "ordering_comparability"
        ]
        .value_counts()
        .to_dict()
    )

else:

    census_219 = {}

    ordering_method_219 = {}
    ordering_confidence_219 = {}
    ordering_comparability_219 = {}


# ------------------------------------------------------------
# 11. 2.17 machine-derived text statistics
# ------------------------------------------------------------

text_stats_available_219 = all(
    name in g219
    for name in [
        "unclear_rows_217",
        "text_changed_217",
        "empty_raw_217",
        "empty_norm_217",
    ]
)


text_stats_219 = {

    "unclear_rows": (
        int(
            g219[
                "unclear_rows_217"
            ]
        )
        if "unclear_rows_217" in g219
        else None
    ),

    "normalization_changed_rows": (
        int(
            g219[
                "text_changed_217"
            ]
        )
        if "text_changed_217" in g219
        else None
    ),

    "empty_raw_content_rows": (
        int(
            g219[
                "empty_raw_217"
            ]
        )
        if "empty_raw_217" in g219
        else None
    ),

    "empty_normalized_rows": (
        int(
            g219[
                "empty_norm_217"
            ]
        )
        if "empty_norm_217" in g219
        else None
    ),
}


# ------------------------------------------------------------
# 12. Final certification checks
# ------------------------------------------------------------

snapshot_checks_219 = pd.DataFrame(

    [

        check_219(
            "Integrated parser gate passed",
            upstream_219[
                "integrated_parser_ready"
            ],
            upstream_219[
                "integrated_parser_ready"
            ],
            "Run/repair Section 2.15 if False",
        ),

        check_219(
            "Production parse gate passed",
            upstream_219[
                "production_parse_ready"
            ],
            upstream_219[
                "production_parse_ready"
            ],
            "Run/repair Section 2.16 if False",
        ),

        check_219(
            "Full corpus audit gate passed",
            upstream_219[
                "corpus_parser_audit_ready"
            ],
            upstream_219[
                "corpus_parser_audit_ready"
            ],
            "Run/repair Section 2.17 if False",
        ),

        check_219(
            "Determinism gate passed",
            upstream_219[
                "determinism_reconstruction_ready"
            ],
            upstream_219[
                "determinism_reconstruction_ready"
            ],
            "Run Section 2.18 Cell 3 if False",
        ),

        check_219(
            "Turn artifact is readable",
            turn_info_219[
                "readable"
            ],
            turn_info_219[
                "rows"
            ],
            turn_info_219[
                "cause"
            ],
        ),

        check_219(
            "Session artifact is readable",
            session_info_219[
                "readable"
            ],
            session_info_219[
                "rows"
            ],
            session_info_219[
                "cause"
            ],
        ),

        check_219(
            "Turn artifact schema is exact",
            turn_info_219[
                "schema_exact"
            ],
            turn_info_219[
                "schema_fields"
            ],
            "Frozen 52-field schema mismatch",
        ),

        check_219(
            "Session artifact schema is exact",
            session_info_219[
                "schema_exact"
            ],
            session_info_219[
                "schema_fields"
            ],
            "Frozen 31-field schema mismatch",
        ),

        check_219(
            "Turn row census is exact",
            (
                turn_info_219[
                    "rows"
                ]
                ==
                EXPECTED_TURNS
            ),
            (
                f"{turn_info_219['rows']}"
                f"/{EXPECTED_TURNS}"
            ),
            "Turn artifact row count changed",
        ),

        check_219(
            "Session row census is exact",
            (
                session_info_219[
                    "rows"
                ]
                ==
                EXPECTED_SESSIONS
            ),
            (
                f"{session_info_219['rows']}"
                f"/{EXPECTED_SESSIONS}"
            ),
            "Session artifact row count changed",
        ),

        check_219(
            "Session n_turns reconciles with turn artifact",
            (
                census_219.get(
                    "turns_from_sessions"
                )
                ==
                turn_info_219[
                    "rows"
                ]
            ),
            (
                f"{census_219.get('turns_from_sessions')}"
                f"/{turn_info_219['rows']}"
            ),
            "Session census no longer reconciles",
        ),

        # ----------------------------------------------------
        # Critical production identity checks
        # ----------------------------------------------------

        check_219(
            "Production artifact reference is valid",
            production_reference_valid_219,
            (
                "Persisted production reference "
                "is valid"
                if production_reference_valid_219
                else production_reference_error_219
            ),
            "Repair production_artifact_reference.json",
        ),

        check_219(
            "Turn artifact SHA256 matches production",
            (
                production_reference_valid_219
                and
                production_turn_hash_219
                is not None
                and
                turn_info_219[
                    "sha256"
                ]
                ==
                production_turn_hash_219
            ),
            turn_info_219[
                "sha256"
            ],
            "Production hash unavailable or artifact changed",
        ),

        check_219(
            "Session artifact SHA256 matches production",
            (
                production_reference_valid_219
                and
                production_session_hash_219
                is not None
                and
                session_info_219[
                    "sha256"
                ]
                ==
                production_session_hash_219
            ),
            session_info_219[
                "sha256"
            ],
            "Production hash unavailable or artifact changed",
        ),

        check_219(
            "Frozen source-manifest fingerprint is available",
            (
                isinstance(
                    source_manifest_hash_219,
                    str,
                )
                and
                len(
                    source_manifest_hash_219
                )
                == 64
            ),
            source_manifest_hash_219,
            "Section 2.16 source fingerprint is unavailable",
        ),

        check_219(
            "Production reference is bound to frozen source",
            (
                production_reference_valid_219
                and
                production_reference_219.get(
                    "source_manifest_sha256"
                )
                ==
                source_manifest_hash_219
            ),
            (
                production_reference_219.get(
                    "source_manifest_sha256"
                )
                if production_reference_219
                else None
            ),
            "Production reference is bound to a different source",
        ),

        check_219(
            "2.17 machine-derived text statistics are available",
            text_stats_available_219,
            text_stats_available_219,
            "Run Section 2.17 before manifest publication",
        ),
    ]
)


# ------------------------------------------------------------
# 13. Certification state
# ------------------------------------------------------------

CERTIFICATION_SNAPSHOT_READY = (
    snapshot_checks_219[
        "passed"
    ].all()
)


# ------------------------------------------------------------
# 14. Display certification table
# ------------------------------------------------------------

display(
    snapshot_checks_219
)


failed_snapshot_219 = (
    snapshot_checks_219.loc[
        ~snapshot_checks_219[
            "passed"
        ]
    ]
)


# ------------------------------------------------------------
# 15. Final certification summary
# ------------------------------------------------------------

print(
    "\n"
    + "=" * 74
)

print(
    "TRACE THE ACE — FINAL PARSER "
    "CERTIFICATION SNAPSHOT"
)

print(
    "=" * 74
)

print(
    f"Turn artifact rows           : "
    f"{turn_info_219['rows']}"
)

print(
    f"Session artifact rows        : "
    f"{session_info_219['rows']}"
)

print(
    f"Turn artifact SHA256 stable  : "
    f"{turn_info_219['sha256'] == production_turn_hash_219}"
)

print(
    f"Session SHA256 stable        : "
    f"{session_info_219['sha256'] == production_session_hash_219}"
)

print(
    f"Production reference valid  : "
    f"{production_reference_valid_219}"
)

print(
    f"Upstream gates passed        : "
    f"{sum(upstream_219.values())}/4"
)

print(
    f"CERTIFICATION SNAPSHOT READY : "
    f"{CERTIFICATION_SNAPSHOT_READY}"
)

print(
    "=" * 74
)


# ------------------------------------------------------------
# 16. Failure display
# ------------------------------------------------------------

if len(
    failed_snapshot_219
):

    print(
        "\nFAILED SNAPSHOT CHECKS"
        " — execution continues:"
    )

    display(
        failed_snapshot_219[
            [
                "check",
                "detail",
                "cause",
            ]
        ]
    )

else:

    print(
        "\nALL 2.19.1 CERTIFICATION CHECKS PASSED."
    )

    print(
        "Safe to continue to Section 2.19.2."
    )


# ------------------------------------------------------------
# 17. Cleanup
# ------------------------------------------------------------

gc.collect()

================================================================================
TRACE THE ACE — PRODUCTION REFERENCE
================================================================================
Reference path : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\production_artifact_reference.json
Reference exists : True
Turn production SHA256 : 926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed984de04946f59f5c37
Session production SHA256 : 24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f50821d70be5cc9d5e9
Source manifest SHA256 : 5e7b5295758161951f142f57211fcc741cda09fb984a6b38788df60245338807
Reference valid : True

,check,passed,detail,cause
0,Integrated parser gate passed,True,True,Run/repair Section 2.15 if False
1,Production parse gate passed,True,True,Run/repair Section 2.16 if False
2,Full corpus audit gate passed,True,True,Run/repair Section 2.17 if False
3,Determinism gate passed,True,True,Run Section 2.18 Cell 3 if False
4,Turn artifact is readable,True,6139854,
5,Session artifact is readable,True,22821,
6,Turn artifact schema is exact,True,52,Frozen 52-field schema mismatch
7,Session artifact schema is exact,True,31,Frozen 31-field schema mismatch
8,Turn row census is exact,True,6139854/6139854,Turn artifact row count changed
9,Session row census is exact,True,22821/22821,Session artifact row count changed
10,Session n_turns reconciles with turn artifact,True,6139854/6139854,Session census no longer reconciles
11,Production artifact reference is valid,True,Persisted production reference is valid,Repair production_artifact_reference.json
12,Turn artifact SHA256 matches production,True,926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed...,Production hash unavailable or artifact changed
13,Session artifact SHA256 matches production,True,24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f...,Production hash unavailable or artifact changed
14,Frozen source-manifest fingerprint is available,True,5e7b5295758161951f142f57211fcc741cda09fb984a6b...,Section 2.16 source fingerprint is unavailable
15,Production reference is bound to frozen source,True,5e7b5295758161951f142f57211fcc741cda09fb984a6b...,Production reference is bound to a different s...
16,2.17 machine-derived text statistics are avail...,True,True,Run Section 2.17 before manifest publication

==========================================================================
TRACE THE ACE — FINAL PARSER CERTIFICATION SNAPSHOT
==========================================================================
Turn artifact rows           : 6139854
Session artifact rows        : 22821
Turn artifact SHA256 stable  : True
Session SHA256 stable        : True
Production reference valid  : True
Upstream gates passed        : 4/4
CERTIFICATION SNAPSHOT READY : True
==========================================================================

ALL 2.19.1 CERTIFICATION CHECKS PASSED.
Safe to continue to Section 2.19.2.

0

In [84]:
# ============================================================
# 2.19.2 — BUILD & SAFELY WRITE PARSER MANIFEST
# ============================================================

def json_safe_219(value):
    if isinstance(value,dict): return {str(k):json_safe_219(v) for k,v in value.items()}
    if isinstance(value,(list,tuple,set)): return [json_safe_219(v) for v in value]
    if isinstance(value,Path): return value.as_posix()
    if isinstance(value,(np.integer,)): return int(value)
    if isinstance(value,(np.floating,)): return None if np.isnan(value) else float(value)
    if isinstance(value,(np.bool_,)): return bool(value)
    if isinstance(value,float) and np.isnan(value): return None
    return value

def canonical_json_219(value):
    return json.dumps(json_safe_219(value),ensure_ascii=False,sort_keys=True,separators=(",",":"),allow_nan=False)

def payload_hash_219(payload):
    return hashlib.sha256(canonical_json_219(payload).encode("utf-8")).hexdigest()

def schema_payload_219(schema):
    return [{"name":f.name,"type":str(f.type),"nullable":bool(f.nullable)} for f in schema]

def schema_definition_hash_219(schema):
    return hashlib.sha256(canonical_json_219(schema_payload_219(schema)).encode("utf-8")).hexdigest()

sample_ids_219 = []
replay_summary_219 = {"selected_sessions":None,"replayed_sessions":None,"failed_sessions":None,"failed_checks":None}

if "sample_manifest_218" in g219 and isinstance(g219["sample_manifest_218"],pd.DataFrame):
    sample_ids_219 = g219["sample_manifest_218"]["session_id"].astype(str).tolist()

if "replay_audit_218" in g219 and isinstance(g219["replay_audit_218"],pd.DataFrame):
    ra = g219["replay_audit_218"]
    replay_summary_219["selected_sessions"] = len(sample_ids_219)
    replay_summary_219["replayed_sessions"] = int((ra["session_id"]!="__ARTIFACT_SCAN__").sum()) if "session_id" in ra else len(ra)
    replay_summary_219["failed_sessions"] = int((~ra["passed"]).sum()) if "passed" in ra else None

if "failed_checks_218" in g219 and isinstance(g219["failed_checks_218"],pd.DataFrame):
    replay_summary_219["failed_checks"] = int(len(g219["failed_checks_218"]))

parser_version_219 = str(
    g219.get("INTEGRATED_PARSER_VERSION",
    g219.get("PARSER_VERSION",
    g219.get("PRODUCTION_PARSE_VERSION","1.0")))
)

contract_219 = g219.get("DATA_CONTRACT_216",g219.get("data_contract",g219.get("DATA_CONTRACT",{})))
contract_version_219 = contract_219.get("contract_version") if isinstance(contract_219,dict) else None

manifest_payload_219 = {
    "identity":{
        "project":"Trace the Ace",
        "phase":"01_data_foundation",
        "notebook":"02_turn_parser",
        "artifact_status":"CANDIDATE",
        "canonical":False,
        "canonical_authority":"03_data_integrity.ipynb",
        "parser_version":parser_version_219,
        "manifest_version":PARSER_MANIFEST_VERSION,
        "data_contract_version":contract_version_219,
        "created_at_utc":datetime.now(timezone.utc).isoformat()
    },

    "source_binding":{
        "expected_transcript_files":int(EXPECTED_FILES),
        "expected_sessions":int(EXPECTED_SESSIONS),
        "expected_logical_rows":int(EXPECTED_TURNS),
        "frozen_source_manifest_sha256":source_manifest_hash_219,
        "contract_transcript_directory_sha256":source_directory_hash_219
    },

    "schemas":{
        "turn_candidate":{
            "field_count":len(TURN_CANDIDATE_SCHEMA),
            "schema_definition_sha256":schema_definition_hash_219(TURN_CANDIDATE_SCHEMA),
            "production_schema_sha256":g219.get("TURN_SCHEMA_SHA256"),
            "fields":schema_payload_219(TURN_CANDIDATE_SCHEMA)
        },
        "session_candidate":{
            "field_count":len(SESSION_CANDIDATE_SCHEMA),
            "schema_definition_sha256":schema_definition_hash_219(SESSION_CANDIDATE_SCHEMA),
            "production_schema_sha256":g219.get("SESSION_SCHEMA_SHA256"),
            "fields":schema_payload_219(SESSION_CANDIDATE_SCHEMA)
        }
    },

    "parser_policy":{
        "raw_evidence_preserved":True,
        "label_blind":True,
        "text_normalization":{"unicode_form":"NFC","math_safe":True,"raw_text_retained":True},
        "roles":{"canonical_roles":["student","tutor","background"],"content_based_role_guessing":False},
        "timestamps":{"family":"TIME_HMS","precision":"SECOND","timezone":"NOT_APPLICABLE"},
        "ordering":{
            "primary":"TIMESTAMP_PRIMARY",
            "tie_breaker":"utterance_id",
            "final_tie_breaker":"source_file + source_row",
            "primary_confidence":"HIGH"
        },
        "identity":{"physical":"source_row_uid","logical":"turn_uid","supporting_hashes":["raw_field_hash","content_hash"]}
    },

    "production_census":{
        **census_219,
        "ordering_method":ordering_method_219,
        "ordering_confidence":ordering_confidence_219,
        "ordering_comparability":ordering_comparability_219,
        "text_characteristics":text_stats_219
    },

    "certification":{
        **upstream_219,
        "corpus_required_failures":int(len(g219["required_failures_217"])) if "required_failures_217" in g219 else None,
        "determinism":replay_summary_219,
        "determinism_sample_session_ids":sample_ids_219
    },

    "artifacts":{
        "turns_candidate":{
            "relative_path":Path(TURNS_FINAL).name,
            "rows":turn_info_219["rows"],
            "schema_fields":turn_info_219["schema_fields"],
            "sha256":turn_info_219["sha256"]
        },
        "sessions_candidate":{
            "relative_path":Path(SESSIONS_FINAL).name,
            "rows":session_info_219["rows"],
            "schema_fields":session_info_219["schema_fields"],
            "sha256":session_info_219["sha256"]
        }
    }
}

manifest_payload_219 = json_safe_219(manifest_payload_219)
manifest_payload_sha256_219 = payload_hash_219(manifest_payload_219)

parser_manifest_219 = {
    "manifest_payload":manifest_payload_219,
    "manifest_payload_sha256":manifest_payload_sha256_219
}

MANIFEST_WRITE_READY = False
manifest_write_cause_219 = ""

if not CERTIFICATION_SNAPSHOT_READY:
    manifest_write_cause_219 = "Certification snapshot is not ready; manifest was not published."
else:
    try:
        PARSER_OUTPUT_DIR.mkdir(parents=True,exist_ok=True)
        if PARSER_MANIFEST_TMP.exists(): PARSER_MANIFEST_TMP.unlink()

        with open(PARSER_MANIFEST_TMP,"w",encoding="utf-8",newline="\n") as f:
            json.dump(parser_manifest_219,f,ensure_ascii=False,indent=2,sort_keys=True,allow_nan=False)
            f.write("\n")

        with open(PARSER_MANIFEST_TMP,"r",encoding="utf-8") as f:
            tmp_roundtrip_219 = json.load(f)

        if tmp_roundtrip_219 != parser_manifest_219:
            manifest_write_cause_219 = "Temporary manifest read-back differs from written payload."
        elif payload_hash_219(tmp_roundtrip_219["manifest_payload"]) != tmp_roundtrip_219["manifest_payload_sha256"]:
            manifest_write_cause_219 = "Temporary manifest payload SHA256 verification failed."
        else:
            os.replace(PARSER_MANIFEST_TMP,PARSER_MANIFEST_PATH)
            MANIFEST_WRITE_READY = True

    except Exception as e:
        manifest_write_cause_219 = f"{type(e).__name__}: {e}"
        try:
            if PARSER_MANIFEST_TMP.exists(): PARSER_MANIFEST_TMP.unlink()
        except Exception:
            pass

manifest_write_checks_219 = pd.DataFrame([
    check_219("Certification snapshot permits publication",CERTIFICATION_SNAPSHOT_READY,CERTIFICATION_SNAPSHOT_READY,
              "Resolve failed checks from Cell 1"),
    check_219("Manifest payload SHA256 was created",len(manifest_payload_sha256_219)==64,
              manifest_payload_sha256_219,"Payload fingerprint failure"),
    check_219("Manifest was safely written and promoted",MANIFEST_WRITE_READY,PARSER_MANIFEST_PATH,
              manifest_write_cause_219),
    check_219("Candidate status is explicitly non-canonical",
              manifest_payload_219["identity"]["artifact_status"]=="CANDIDATE"
              and manifest_payload_219["identity"]["canonical"] is False,
              f"{manifest_payload_219['identity']['artifact_status']} / canonical={manifest_payload_219['identity']['canonical']}",
              "Candidate/canonical boundary is incorrect")
])

display(manifest_write_checks_219)

print("\n"+"="*72)
print("TRACE THE ACE — PARSER MANIFEST WRITE")
print("="*72)
print(f"Manifest path          : {PARSER_MANIFEST_PATH}")
print(f"Payload SHA256         : {manifest_payload_sha256_219}")
print(f"Safe write completed   : {MANIFEST_WRITE_READY}")
print("="*72)

if not MANIFEST_WRITE_READY:
    print(f"\nManifest publication cause: {manifest_write_cause_219}")

,check,passed,detail,cause
0,Certification snapshot permits publication,True,True,Resolve failed checks from Cell 1
1,Manifest payload SHA256 was created,True,b37fef18f652f6b25eb02766347f35f819d25433a0ccc0...,Payload fingerprint failure
2,Manifest was safely written and promoted,True,D:\Competition\Trace-the-race-local\scratch_ma...,
3,Candidate status is explicitly non-canonical,True,CANDIDATE / canonical=False,Candidate/canonical boundary is incorrect

========================================================================
TRACE THE ACE — PARSER MANIFEST WRITE
========================================================================
Manifest path          : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\parser_manifest.json
Payload SHA256         : b37fef18f652f6b25eb02766347f35f819d25433a0ccc07511f1035f7e8ee9ae
Safe write completed   : True
========================================================================

In [85]:
# ============================================================
# 2.19.3 — MANIFEST ROUNDTRIP & FINAL PARSER GATE
# ============================================================

loaded_manifest_219 = None
manifest_read_error_219 = ""

if MANIFEST_WRITE_READY:
    try:
        with open(PARSER_MANIFEST_PATH,"r",encoding="utf-8") as f:
            loaded_manifest_219 = json.load(f)
    except Exception as e:
        manifest_read_error_219 = f"{type(e).__name__}: {e}"

manifest_readable_219 = isinstance(loaded_manifest_219,dict)
payload_hash_valid_219 = False
turn_manifest_hash_match_219 = False
session_manifest_hash_match_219 = False
upstream_manifest_valid_219 = False
candidate_boundary_valid_219 = False
schema_manifest_valid_219 = False
source_binding_valid_219 = False

if manifest_readable_219:
    try:
        payload_219 = loaded_manifest_219["manifest_payload"]
        stored_payload_hash_219 = loaded_manifest_219["manifest_payload_sha256"]

        payload_hash_valid_219 = payload_hash_219(payload_219)==stored_payload_hash_219

        turn_manifest_hash_match_219 = (
            payload_219["artifacts"]["turns_candidate"]["sha256"]==turn_info_219["sha256"]
            and turn_info_219["sha256"]==production_turn_hash_219
        )
        session_manifest_hash_match_219 = (
            payload_219["artifacts"]["sessions_candidate"]["sha256"]==session_info_219["sha256"]
            and session_info_219["sha256"]==production_session_hash_219
        )

        cert_219 = payload_219["certification"]
        upstream_manifest_valid_219 = all([
            cert_219.get("integrated_parser_ready") is True,
            cert_219.get("production_parse_ready") is True,
            cert_219.get("corpus_parser_audit_ready") is True,
            cert_219.get("determinism_reconstruction_ready") is True,
            cert_219.get("corpus_required_failures")==0,
            cert_219.get("determinism",{}).get("failed_sessions")==0,
            cert_219.get("determinism",{}).get("failed_checks")==0
        ])

        candidate_boundary_valid_219 = (
            payload_219["identity"].get("artifact_status")=="CANDIDATE"
            and payload_219["identity"].get("canonical") is False
            and payload_219["identity"].get("canonical_authority")=="03_data_integrity.ipynb"
        )

        schema_manifest_valid_219 = (
            payload_219["schemas"]["turn_candidate"]["field_count"]==52
            and payload_219["schemas"]["session_candidate"]["field_count"]==31
            and payload_219["schemas"]["turn_candidate"]["schema_definition_sha256"]==schema_definition_hash_219(TURN_CANDIDATE_SCHEMA)
            and payload_219["schemas"]["session_candidate"]["schema_definition_sha256"]==schema_definition_hash_219(SESSION_CANDIDATE_SCHEMA)
        )

        source_binding_valid_219 = (
            payload_219["source_binding"]["expected_transcript_files"]==EXPECTED_FILES
            and payload_219["source_binding"]["expected_sessions"]==EXPECTED_SESSIONS
            and payload_219["source_binding"]["expected_logical_rows"]==EXPECTED_TURNS
            and payload_219["source_binding"]["frozen_source_manifest_sha256"]==source_manifest_hash_219
            and isinstance(source_manifest_hash_219,str) and len(source_manifest_hash_219)==64
        )

    except Exception as e:
        manifest_read_error_219 = f"{type(e).__name__}: {e}"

current_turn_hash_219,current_turn_hash_error_219 = sha256_file_219(TURNS_FINAL)
current_session_hash_219,current_session_hash_error_219 = sha256_file_219(SESSIONS_FINAL)

final_checks_219 = pd.DataFrame([
    check_219("All upstream notebook gates remain passed",all(upstream_219.values()),upstream_219,
              "One or more Sections 2.15–2.18 are not certified"),
    check_219("Certification snapshot passed",CERTIFICATION_SNAPSHOT_READY,CERTIFICATION_SNAPSHOT_READY,
              "See Cell 1 failed checks"),
    check_219("Manifest write completed",MANIFEST_WRITE_READY,MANIFEST_WRITE_READY,
              manifest_write_cause_219),
    check_219("Published manifest is readable",manifest_readable_219,PARSER_MANIFEST_PATH,
              manifest_read_error_219),
    check_219("Manifest payload SHA256 verifies",payload_hash_valid_219,
              loaded_manifest_219.get("manifest_payload_sha256") if manifest_readable_219 else None,
              "Manifest content fingerprint mismatch"),

    check_219("Turn artifact SHA256 remains stable",
              current_turn_hash_219==production_turn_hash_219==turn_info_219["sha256"],
              current_turn_hash_219,current_turn_hash_error_219 or "Artifact fingerprint changed"),
    check_219("Session artifact SHA256 remains stable",
              current_session_hash_219==production_session_hash_219==session_info_219["sha256"],
              current_session_hash_219,current_session_hash_error_219 or "Artifact fingerprint changed"),

    check_219("Manifest turn artifact identity matches",turn_manifest_hash_match_219,
              turn_info_219["sha256"],"Manifest and promoted turn artifact differ"),
    check_219("Manifest session artifact identity matches",session_manifest_hash_match_219,
              session_info_219["sha256"],"Manifest and promoted session artifact differ"),

    check_219("Manifest source binding is complete",source_binding_valid_219,
              source_manifest_hash_219,"Source corpus lineage mismatch or missing fingerprint"),
    check_219("Manifest frozen schemas verify",schema_manifest_valid_219,
              "52 turn fields / 31 session fields","Schema manifest mismatch"),
    check_219("Manifest certification block is fully clean",upstream_manifest_valid_219,
              upstream_manifest_valid_219,"Upstream/replay failure recorded in manifest"),
    check_219("Candidate/non-canonical boundary is explicit",candidate_boundary_valid_219,
              candidate_boundary_valid_219,"Notebook 2 must not publish canonical artifacts")
])

PARSER_READY_FOR_INTEGRITY = final_checks_219["passed"].all()
failed_final_219 = final_checks_219.loc[~final_checks_219["passed"]]

display(final_checks_219)

print("\n"+"="*78)
print("TRACE THE ACE — FINAL TURN PARSER GATE")
print("="*78)
print(f"Candidate turns              : {turn_info_219['rows']:,}/{EXPECTED_TURNS:,}")
print(f"Candidate sessions           : {session_info_219['rows']:,}/{EXPECTED_SESSIONS:,}")
print(f"Turn schema                  : {turn_info_219['schema_fields']}/52")
print(f"Session schema               : {session_info_219['schema_fields']}/31")
print(f"Manifest payload verified    : {payload_hash_valid_219}")
print(f"Turn artifact hash verified  : {turn_manifest_hash_match_219}")
print(f"Session artifact hash verified: {session_manifest_hash_match_219}")
print(f"Source binding verified      : {source_binding_valid_219}")
print(f"Upstream certifications     : {sum(upstream_219.values())}/4")
print(f"Final failed checks          : {len(failed_final_219)}")
print(f"PARSER READY FOR INTEGRITY   : {PARSER_READY_FOR_INTEGRITY}")
print("="*78)

if len(failed_final_219):
    print("\nFAILED FINAL CHECKS — notebook execution continues:")
    display(failed_final_219[["check","detail","cause"]])
else:
    print("\nCandidate parser artifacts are certified for independent integrity review.")
    print("They remain CANDIDATE and are not canonical until 03_data_integrity.ipynb passes.")

,check,passed,detail,cause
0,All upstream notebook gates remain passed,True,"{'integrated_parser_ready': True, 'production_...",One or more Sections 2.15–2.18 are not certified
1,Certification snapshot passed,True,True,See Cell 1 failed checks
2,Manifest write completed,True,True,
3,Published manifest is readable,True,D:\Competition\Trace-the-race-local\scratch_ma...,
4,Manifest payload SHA256 verifies,True,b37fef18f652f6b25eb02766347f35f819d25433a0ccc0...,Manifest content fingerprint mismatch
5,Turn artifact SHA256 remains stable,True,926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed...,Artifact fingerprint changed
6,Session artifact SHA256 remains stable,True,24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f...,Artifact fingerprint changed
7,Manifest turn artifact identity matches,True,926179f0b1813821a185c6b33ea87a1e0ef8285f53f0ed...,Manifest and promoted turn artifact differ
8,Manifest session artifact identity matches,True,24159fc6786cdd25ca7966e4dd0acf74d0aec0f97fdc5f...,Manifest and promoted session artifact differ
9,Manifest source binding is complete,True,5e7b5295758161951f142f57211fcc741cda09fb984a6b...,Source corpus lineage mismatch or missing fing...
10,Manifest frozen schemas verify,True,52 turn fields / 31 session fields,Schema manifest mismatch
11,Manifest certification block is fully clean,True,True,Upstream/replay failure recorded in manifest
12,Candidate/non-canonical boundary is explicit,True,True,Notebook 2 must not publish canonical artifacts

==============================================================================
TRACE THE ACE — FINAL TURN PARSER GATE
==============================================================================
Candidate turns              : 6,139,854/6,139,854
Candidate sessions           : 22,821/22,821
Turn schema                  : 52/52
Session schema               : 31/31
Manifest payload verified    : True
Turn artifact hash verified  : True
Session artifact hash verified: True
Source binding verified      : True
Upstream certifications     : 4/4
Final failed checks          : 0
PARSER READY FOR INTEGRITY   : True
==============================================================================

Candidate parser artifacts are certified for independent integrity review.
They remain CANDIDATE and are not canonical until 03_data_integrity.ipynb passes.

In [70]:
# ============================================================
# DEBUG — 02 TURN PARSER MANIFEST / LINEAGE STATE
# ============================================================

from pathlib import Path
import json

print("=" * 80)
print("TRACE THE ACE — 02 TURN PARSER MANIFEST DIAGNOSTIC")
print("=" * 80)


# ------------------------------------------------------------
# 1. Print relevant runtime variables
# ------------------------------------------------------------

names = [
    "PARSER_ROOT",
    "PARSER_OUTPUT_DIR",
    "PARSER_MANIFEST_PATH",
    "PRODUCTION_MANIFEST_PATH",
    "RUN_MANIFEST_PATH",
    "TURN_PART_DIR",
    "SESSION_PART_DIR",
    "TURNS_FINAL",
    "SESSIONS_FINAL",
    "TURNS_TMP",
    "SESSIONS_TMP",
    "FULL_STREAM_PARSE_COMPLETE",
    "PRODUCTION_PARSE_READY",
]

print("\nRuntime variables:")

for name in names:

    value = globals().get(
        name,
        "<MISSING>",
    )

    print(
        f"{name:32s} = {value}"
    )


# ------------------------------------------------------------
# 2. Inspect parser directories
# ------------------------------------------------------------

candidate_dirs = []

for name in [
    "PARSER_ROOT",
    "PARSER_OUTPUT_DIR",
    "PRODUCTION_TMP_ROOT",
]:

    value = globals().get(name)

    if value not in [None, "<MISSING>"]:

        path = Path(value)

        if path.exists():

            candidate_dirs.append(path)


print("\nExisting parser directories:")

for path in candidate_dirs:

    print(f"\n[{path}]")

    for child in sorted(path.iterdir()):

        print(
            f"  {child.name}"
        )


# ------------------------------------------------------------
# 3. Search parser area for manifest-like files
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("MANIFEST FILE SEARCH")
print("=" * 80)

search_roots = set(candidate_dirs)

manifest_files = []

for root in search_roots:

    for path in root.rglob("*"):

        if not path.is_file():
            continue

        name = path.name.lower()

        if (
            "manifest" in name
            or
            "checkpoint" in name
        ):

            manifest_files.append(path)


if manifest_files:

    for path in sorted(
        set(manifest_files)
    ):

        print(
            f"{path} | "
            f"{path.stat().st_size:,} bytes"
        )

else:

    print(
        "NO manifest/checkpoint files found."
    )


# ------------------------------------------------------------
# 4. Search entire Phase-1 output tree
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("PHASE-1 MANIFEST SEARCH")
print("=" * 80)

phase1_root = Path(
    globals().get(
        "PHASE1_ROOT",
        Path.cwd(),
    )
)

print(
    f"Search root: {phase1_root}"
)

for path in sorted(
    phase1_root.rglob("*manifest*.json")
):

    print(path)


print("=" * 80)

================================================================================
TRACE THE ACE — 02 TURN PARSER MANIFEST DIAGNOSTIC
================================================================================

Runtime variables:
PARSER_ROOT                      = <MISSING>
PARSER_OUTPUT_DIR                = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser
PARSER_MANIFEST_PATH             = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\parser_manifest.json
PRODUCTION_MANIFEST_PATH         = <MISSING>
RUN_MANIFEST_PATH                = <MISSING>
TURN_PART_DIR                    = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\turn_parts
SESSION_PART_DIR                 = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\session_parts
TURNS_FINAL                      = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\turns_candidate.parquet
SESSIONS_FINAL                   = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\sessions_candidate.parquet
TURNS_TMP                        = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\turns_candidate.tmp.parquet
SESSIONS_TMP                     = D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\.production_tmp\sessions_candidate.tmp.parquet
FULL_STREAM_PARSE_COMPLETE       = True
PRODUCTION_PARSE_READY           = True

Existing parser directories:

[D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser]
  _work
  sessions_candidate.parquet
  turns_candidate.parquet

================================================================================
MANIFEST FILE SEARCH
================================================================================
NO manifest/checkpoint files found.

================================================================================
PHASE-1 MANIFEST SEARCH
================================================================================
Search root: D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation
D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\01_inventory\inventory_manifest.json
D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\01_inventory\run_manifest.json
D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\03_integrity\phase1_manifest.json
================================================================================

In [71]:
# ============================================================
# DEBUG — SECTION 2.15 → 2.19 READINESS
# ============================================================

print("=" * 80)
print("TRACE THE ACE — 02 PARSER FINALIZATION READINESS")
print("=" * 80)

required_state = [
    "INTEGRATED_PARSER_READY",
    "PRODUCTION_PARSE_READY",
    "CORPUS_PARSER_AUDIT_READY",
    "DETERMINISM_RECONSTRUCTION_READY",
    "CERTIFICATION_SNAPSHOT_READY",
    "MANIFEST_WRITE_READY",
    "PARSER_READY_FOR_INTEGRITY",
]

for name in required_state:
    print(
        f"{name:38s} = "
        f"{globals().get(name, '<MISSING>')!r}"
    )

print("\nRelevant artifact state:")

for name in [
    "TURNS_FINAL",
    "SESSIONS_FINAL",
    "PARSER_MANIFEST_PATH",
]:

    value = globals().get(name, "<MISSING>")

    if value == "<MISSING>":
        print(f"{name:30s} = <MISSING>")
    else:
        path = Path(value)

        print(
            f"{name:30s} = "
            f"exists={path.exists()} | "
            f"{path}"
        )

print("\nFinal gate dependency summary:")

for name in [
    "INTEGRATED_PARSER_READY",
    "PRODUCTION_PARSE_READY",
    "CORPUS_PARSER_AUDIT_READY",
    "DETERMINISM_RECONSTRUCTION_READY",
]:

    value = globals().get(name, False)

    print(
        f"{name:38s} : "
        f"{'PASS' if value else 'BLOCKED'}"
    )

print("=" * 80)

================================================================================
TRACE THE ACE — 02 PARSER FINALIZATION READINESS
================================================================================
INTEGRATED_PARSER_READY                = True
PRODUCTION_PARSE_READY                 = True
CORPUS_PARSER_AUDIT_READY              = True
DETERMINISM_RECONSTRUCTION_READY       = np.True_
CERTIFICATION_SNAPSHOT_READY           = np.False_
MANIFEST_WRITE_READY                   = False
PARSER_READY_FOR_INTEGRITY             = np.False_

Relevant artifact state:
TURNS_FINAL                    = exists=True | D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\turns_candidate.parquet
SESSIONS_FINAL                 = exists=True | D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\sessions_candidate.parquet
PARSER_MANIFEST_PATH           = exists=False | D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\02_turn_parser\parser_manifest.json

Final gate dependency summary:
INTEGRATED_PARSER_READY                : PASS
PRODUCTION_PARSE_READY                 : PASS
CORPUS_PARSER_AUDIT_READY              : PASS
DETERMINISM_RECONSTRUCTION_READY       : PASS
================================================================================