In [1]:
# ==============================================================================
# TRACE THE ACE — TEST POPULATION LOCK
# CELL 0 — ENVIRONMENT + FROZEN TRAINING POPULATION CONTRACT
# ==============================================================================

from pathlib import Path
import json
import platform
import sys

import pandas as pd


print("=" * 100)
print("TRACE THE ACE — TEST POPULATION LOCK")
print("CELL 0 — ENVIRONMENT + FROZEN TRAINING POPULATION CONTRACT")
print("=" * 100)


# ==============================================================================
# 1. PROJECT ROOT
# ==============================================================================

PROJECT_ROOT = Path(
    r"D:\Competition\Trace-the-race-local"
).resolve()

assert PROJECT_ROOT.exists(), (
    f"PROJECT_ROOT does not exist:\n{PROJECT_ROOT}"
)

assert PROJECT_ROOT.is_dir(), (
    f"PROJECT_ROOT is not a directory:\n{PROJECT_ROOT}"
)

print("\nPROJECT ROOT")
print("-" * 100)
print(
    f"PROJECT_ROOT : {PROJECT_ROOT}"
)
print(
    "Status       : PASS"
)


# ==============================================================================
# 2. SCRATCH ROOT
# ==============================================================================

SCRATCH_ROOT = (
    PROJECT_ROOT
    / "scratch_mastery_outputs"
)

assert SCRATCH_ROOT.exists(), (
    f"SCRATCH_ROOT does not exist:\n{SCRATCH_ROOT}"
)

assert SCRATCH_ROOT.is_dir(), (
    f"SCRATCH_ROOT is not a directory:\n{SCRATCH_ROOT}"
)

print(
    f"SCRATCH_ROOT : {SCRATCH_ROOT}"
)
print(
    "Status       : PASS"
)


# ==============================================================================
# 3. DATASET ROOT
# ==============================================================================

DATASET_ROOT = (
    PROJECT_ROOT
    / "Dataset"
)

assert DATASET_ROOT.exists(), (
    f"Dataset directory not found:\n{DATASET_ROOT}"
)

assert DATASET_ROOT.is_dir(), (
    f"Dataset root is not a directory:\n{DATASET_ROOT}"
)

print(
    f"DATASET_ROOT : {DATASET_ROOT}"
)
print(
    "Status       : PASS"
)


# ==============================================================================
# 4. CANONICAL DATA FOUNDATION
# ==============================================================================

CANONICAL_ROOT = (
    SCRATCH_ROOT
    / "01_data_foundation"
    / "03_integrity"
    / "canonical"
)

RESPONSES_PATH = (
    CANONICAL_ROOT
    / "responses.parquet"
)

SESSIONS_PATH = (
    CANONICAL_ROOT
    / "sessions.parquet"
)

TURNS_PATH = (
    CANONICAL_ROOT
    / "turns.parquet"
)

OBJECTIVES_PATH = (
    CANONICAL_ROOT
    / "objectives.parquet"
)


print("\n" + "=" * 100)
print("CANONICAL DATA FOUNDATION")
print("=" * 100)

for name, path in [
    ("responses", RESPONSES_PATH),
    ("sessions", SESSIONS_PATH),
    ("turns", TURNS_PATH),
    ("objectives", OBJECTIVES_PATH),
]:

    print(
        f"{name:12s}: "
        f"{'FOUND' if path.exists() else 'MISSING'}"
    )

    assert path.exists(), (
        f"Required canonical artifact missing:\n{path}"
    )


print(
    "\nCanonical artifacts : PASS"
)


# ==============================================================================
# 5. LOAD CANONICAL RESPONSE POPULATION
# ==============================================================================

responses = pd.read_parquet(
    RESPONSES_PATH,
    engine="pyarrow",
)

assert len(responses) == 35_072, (
    f"Unexpected canonical response population: "
    f"{len(responses):,}"
)

assert "response_id" in responses.columns, (
    "Canonical responses missing response_id."
)

assert (
    responses["response_id"]
    .notna()
    .all()
), (
    "Canonical response_id contains nulls."
)

assert (
    responses["response_id"]
    .astype(str)
    .is_unique
), (
    "Canonical response_id is not unique."
)


CANONICAL_RESPONSE_IDS = set(
    responses[
        "response_id"
    ]
    .astype(str)
)


print("\n" + "=" * 100)
print("CANONICAL RESPONSE POPULATION")
print("=" * 100)

print(
    f"Rows               : {len(responses):,}"
)

print(
    f"Unique response_id : "
    f"{len(CANONICAL_RESPONSE_IDS):,}"
)

print(
    "Response population : PASS"
)


# ==============================================================================
# 6. CANONICAL SESSION POPULATION
# ==============================================================================

sessions = pd.read_parquet(
    SESSIONS_PATH,
    engine="pyarrow",
)

assert len(sessions) == 22_821, (
    f"Unexpected session population: "
    f"{len(sessions):,}"
)

assert "session_id" in sessions.columns, (
    "Canonical sessions missing session_id."
)

assert (
    sessions["session_id"]
    .astype(str)
    .is_unique
), (
    "Canonical session_id is not unique."
)


CANONICAL_SESSION_IDS = set(
    sessions[
        "session_id"
    ]
    .astype(str)
)


print(
    f"Sessions           : {len(sessions):,}"
)

print(
    "Session population : PASS"
)


# ==============================================================================
# 7. CANONICAL OBJECTIVE POPULATION
# ==============================================================================

objectives = pd.read_parquet(
    OBJECTIVES_PATH,
    engine="pyarrow",
)

assert len(objectives) == 398, (
    f"Unexpected objective population: "
    f"{len(objectives):,}"
)

assert "objective_uid" in objectives.columns, (
    "Canonical objectives missing objective_uid."
)

assert (
    objectives["objective_uid"]
    .astype(str)
    .is_unique
), (
    "Canonical objective_uid is not unique."
)


CANONICAL_OBJECTIVE_IDS = set(
    objectives[
        "objective_uid"
    ]
    .astype(str)
)


print(
    f"Objectives         : {len(objectives):,}"
)

print(
    "Objective population : PASS"
)


# ==============================================================================
# 8. PREVIOUS TEST-POPULATION FORENSIC ARTIFACT
#
# Cell 16 already established:
#
#     strong candidates = 0
#     test-named files  = 0
#     submission-like   = 0
#     test auto-lock    = NO
#
# This cell only verifies that the forensic record exists.
# ==============================================================================

TEST_DISCOVERY_ROOT = (
    SCRATCH_ROOT
    / "09C"
    / "final_test_discovery"
)

CELL16_FORENSIC_PATH = (
    TEST_DISCOVERY_ROOT
    / "cell16_dataset_forensic.parquet"
)

CELL16_SUMMARY_PATH = (
    TEST_DISCOVERY_ROOT
    / "cell16_dataset_forensic.json"
)


print("\n" + "=" * 100)
print("PREVIOUS TEST FORENSIC ARTIFACTS")
print("=" * 100)

print(
    f"Forensic parquet : "
    f"{CELL16_FORENSIC_PATH}"
)

print(
    f"Forensic summary : "
    f"{CELL16_SUMMARY_PATH}"
)

assert CELL16_FORENSIC_PATH.exists(), (
    "Cell 16 forensic parquet is missing."
)

assert CELL16_SUMMARY_PATH.exists(), (
    "Cell 16 forensic summary is missing."
)

print(
    "\nCell 16 forensic artifacts : PASS"
)


# ==============================================================================
# 9. LOAD CELL 16 FORENSIC SUMMARY
# ==============================================================================

with open(
    CELL16_SUMMARY_PATH,
    "r",
    encoding="utf-8",
) as f:

    cell16_summary = json.load(f)


print("\n" + "=" * 100)
print("CELL 16 FORENSIC DECISION")
print("=" * 100)

print(
    json.dumps(
        cell16_summary,
        indent=2,
        ensure_ascii=False,
        sort_keys=True,
    )[:5000]
)


# ==============================================================================
# 10. LOAD CELL 16 FORENSIC TABLE
# ==============================================================================

cell16_forensic = pd.read_parquet(
    CELL16_FORENSIC_PATH,
    engine="pyarrow",
)

assert isinstance(
    cell16_forensic,
    pd.DataFrame,
), (
    "Cell 16 forensic artifact did not load as DataFrame."
)

assert len(cell16_forensic) > 0, (
    "Cell 16 forensic artifact is empty."
)

print(
    f"\nCell 16 forensic rows : "
    f"{len(cell16_forensic):,}"
)

print(
    "Cell 16 forensic reload : PASS"
)


# ==============================================================================
# 11. TEST LOCK MUST NOT ALREADY EXIST
#
# We intentionally do NOT allow Cell 0 to silently reuse an old
# guessed/experimental test population.
#
# Cell 1 will discover candidates.
# Cell 2 will perform the hard population lock.
# ==============================================================================

KNOWN_TEST_LOCK_PATHS = [
    (
        SCRATCH_ROOT
        / "09C"
        / "test_population"
        / "outputs"
        / "locked_test_population.parquet"
    ),
    (
        SCRATCH_ROOT
        / "09C"
        / "final_test"
        / "locked_test_population.parquet"
    ),
]


existing_test_locks = [
    path
    for path in KNOWN_TEST_LOCK_PATHS
    if path.exists()
]


print("\n" + "=" * 100)
print("EXISTING TEST LOCK GUARD")
print("=" * 100)

if existing_test_locks:

    print(
        "Existing test-lock artifacts detected:"
    )

    for path in existing_test_locks:
        print(
            f"  - {path}"
        )

else:

    print(
        "No prior production test lock found."
    )


# Do not fail merely because an old artifact exists.
# The next cells must explicitly validate it.
print(
    "\nExisting-lock discovery : COMPLETE"
)


# ==============================================================================
# 12. TRAINING POPULATION IMMUTABILITY SNAPSHOT
# ==============================================================================

TRAINING_POPULATION_CONTRACT = {
    "responses": 35_072,
    "sessions": 22_821,
    "objectives": 398,
    "canonical_response_ids": len(
        CANONICAL_RESPONSE_IDS
    ),
    "canonical_session_ids": len(
        CANONICAL_SESSION_IDS
    ),
    "canonical_objective_ids": len(
        CANONICAL_OBJECTIVE_IDS
    ),
}


# ==============================================================================
# 13. GLOBAL FLAGS FOR CELL 1
# ==============================================================================

TEST_LOCK_CELL_0_READY = True

CANONICAL_TRAINING_POPULATION_LOCKED = True

TEST_POPULATION_LOCKED = False

PRODUCTION_INFERENCE_STARTED = False


# ==============================================================================
# 14. FINAL STATUS
# ==============================================================================

print("\n" + "=" * 100)
print("TRACE THE ACE — CELL 0 FINAL STATUS")
print("=" * 100)

print(
    "Project root                 : PASS"
)

print(
    "Dataset root                 : PASS"
)

print(
    "Canonical responses          : PASS"
)

print(
    "Canonical sessions           : PASS"
)

print(
    "Canonical objectives         : PASS"
)

print(
    "Canonical response count     : 35,072"
)

print(
    "Canonical session count      : 22,821"
)

print(
    "Canonical objective count    : 398"
)

print(
    "Cell 16 forensic artifacts   : PASS"
)

print(
    "Training population lock     : PASS"
)

print(
    "Test population lock         : NOT YET"
)

print(
    "Production inference         : NOT STARTED"
)

print(
    "\nCELL 0 COMPLETE — PASS"
)

====================================================================================================
TRACE THE ACE — TEST POPULATION LOCK
CELL 0 — ENVIRONMENT + FROZEN TRAINING POPULATION CONTRACT
====================================================================================================

PROJECT ROOT
----------------------------------------------------------------------------------------------------
PROJECT_ROOT : D:\Competition\Trace-the-race-local
Status       : PASS
SCRATCH_ROOT : D:\Competition\Trace-the-race-local\scratch_mastery_outputs
Status       : PASS
DATASET_ROOT : D:\Competition\Trace-the-race-local\Dataset
Status       : PASS

====================================================================================================
CANONICAL DATA FOUNDATION
====================================================================================================
responses   : FOUND
sessions    : FOUND
turns       : FOUND
objectives  : FOUND

Canonical artifacts : PASS

====================================================================================================
CANONICAL RESPONSE POPULATION
====================================================================================================
Rows               : 35,072
Unique response_id : 35,072
Response population : PASS
Sessions           : 22,821
Session population : PASS
Objectives         : 398
Objective population : PASS

====================================================================================================
PREVIOUS TEST FORENSIC ARTIFACTS
====================================================================================================
Forensic parquet : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell16_dataset_forensic.parquet
Forensic summary : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell16_dataset_forensic.json

Cell 16 forensic artifacts : PASS

====================================================================================================
CELL 16 FORENSIC DECISION
====================================================================================================
{
  "auto_locked": false,
  "canonical_response_count": 35072,
  "dataset_file_count": 22823,
  "prediction_started": false,
  "status": "PASS",
  "strong_test_candidate_count": 0,
  "test_population_status": "NO_STRONG_CANDIDATE",
  "training_started": false
}

Cell 16 forensic rows : 22,823
Cell 16 forensic reload : PASS

====================================================================================================
EXISTING TEST LOCK GUARD
====================================================================================================
No prior production test lock found.

Existing-lock discovery : COMPLETE

====================================================================================================
TRACE THE ACE — CELL 0 FINAL STATUS
====================================================================================================
Project root                 : PASS
Dataset root                 : PASS
Canonical responses          : PASS
Canonical sessions           : PASS
Canonical objectives         : PASS
Canonical response count     : 35,072
Canonical session count      : 22,821
Canonical objective count    : 398
Cell 16 forensic artifacts   : PASS
Training population lock     : PASS
Test population lock         : NOT YET
Production inference         : NOT STARTED

CELL 0 COMPLETE — PASS

In [2]:
# =============================================================================
# TRACE THE ACE — TEST POPULATION LOCK
# CELL 1 — DATASET CANDIDATE INVENTORY
# =============================================================================

from pathlib import Path
import json
import hashlib
import os
import time

import pandas as pd


print("=" * 100)
print("TRACE THE ACE — TEST POPULATION LOCK")
print("CELL 1 — DATASET CANDIDATE INVENTORY")
print("=" * 100)


# =============================================================================
# 1. PROJECT PATHS
# =============================================================================

PROJECT_ROOT = Path(
    r"D:\Competition\Trace-the-race-local"
)

DATASET_ROOT = PROJECT_ROOT / "Dataset"

SCRATCH_ROOT = (
    PROJECT_ROOT
    / "scratch_mastery_outputs"
)

CELL_ROOT = (
    SCRATCH_ROOT
    / "09C"
    / "final_test_discovery"
    / "cell1"
)

CELL_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

INVENTORY_PATH = (
    CELL_ROOT
    / "cell1_dataset_candidate_inventory.parquet"
)

SUMMARY_PATH = (
    CELL_ROOT
    / "cell1_dataset_candidate_inventory.json"
)


assert PROJECT_ROOT.exists(), (
    f"PROJECT_ROOT not found:\n{PROJECT_ROOT}"
)

assert DATASET_ROOT.exists(), (
    f"DATASET_ROOT not found:\n{DATASET_ROOT}"
)


print("\nPROJECT ROOT")
print("-" * 80)
print(f"PROJECT_ROOT : {PROJECT_ROOT}")
print(f"Status       : PASS")

print("\nDATASET ROOT")
print("-" * 80)
print(f"DATASET_ROOT : {DATASET_ROOT}")
print(f"Status       : PASS")


# =============================================================================
# 2. CANONICAL IDENTITY TABLES
# =============================================================================
# These are ONLY used to establish identity overlap.
# They are NOT used to select a test candidate by filename.
# =============================================================================

CANONICAL_ROOT = (
    SCRATCH_ROOT
    / "01_data_foundation"
)

# Search for canonical artifacts without assuming a single historical path.
canonical_candidates = {
    "responses": list(SCRATCH_ROOT.rglob("responses.parquet")),
    "turns": list(SCRATCH_ROOT.rglob("turns.parquet")),
    "sessions": list(SCRATCH_ROOT.rglob("sessions.parquet")),
    "objectives": list(SCRATCH_ROOT.rglob("objectives.parquet")),
}


def choose_unique_canonical(name, paths):
    """
    Prefer a path that is inside a canonical/frozen/foundation directory.
    If multiple candidates remain, require explicit uniqueness.
    """
    if not paths:
        raise FileNotFoundError(
            f"Canonical {name}.parquet not found under:\n{SCRATCH_ROOT}"
        )

    preferred = [
        p for p in paths
        if any(
            token in str(p).lower()
            for token in [
                "canonical",
                "foundation",
                "data_foundation",
                "03_data_integrity",
            ]
        )
    ]

    if len(preferred) == 1:
        return preferred[0]

    if len(paths) == 1:
        return paths[0]

    raise RuntimeError(
        f"Multiple canonical candidates found for {name}:\n"
        + "\n".join(str(p) for p in paths)
    )


CANONICAL_PATHS = {
    name: choose_unique_canonical(name, paths)
    for name, paths in canonical_candidates.items()
}

print("\nCANONICAL ARTIFACTS")
print("-" * 80)

for name, path in CANONICAL_PATHS.items():
    print(f"{name:<12}: {path}")


# =============================================================================
# 3. LOAD CANONICAL IDENTITIES
# =============================================================================

responses = pd.read_parquet(
    CANONICAL_PATHS["responses"],
    columns=[
        c for c in [
            "response_id",
            "session_id",
            "objective_uid",
            "objective_raw",
            "target",
            "fold",
        ]
        if c in pd.read_parquet(
            CANONICAL_PATHS["responses"],
            engine="pyarrow",
        ).columns
    ],
)

sessions = pd.read_parquet(
    CANONICAL_PATHS["sessions"],
    columns=[
        c for c in [
            "session_id",
        ]
        if c in pd.read_parquet(
            CANONICAL_PATHS["sessions"],
            engine="pyarrow",
        ).columns
    ],
)

objectives = pd.read_parquet(
    CANONICAL_PATHS["objectives"],
)

assert "response_id" in responses.columns
assert "session_id" in responses.columns

CANONICAL_RESPONSE_IDS = set(
    responses["response_id"]
    .astype(str)
)

CANONICAL_SESSION_IDS = set(
    responses["session_id"]
    .astype(str)
)

if "objective_uid" in responses.columns:
    CANONICAL_OBJECTIVE_IDS = set(
        responses["objective_uid"]
        .dropna()
        .astype(str)
    )
else:
    CANONICAL_OBJECTIVE_IDS = set()


print("\nCANONICAL IDENTITY POPULATION")
print("-" * 80)
print(
    f"Response IDs   : {len(CANONICAL_RESPONSE_IDS):,}"
)
print(
    f"Session IDs    : {len(CANONICAL_SESSION_IDS):,}"
)
print(
    f"Objective IDs  : {len(CANONICAL_OBJECTIVE_IDS):,}"
)


assert len(CANONICAL_RESPONSE_IDS) == 35_072
assert len(CANONICAL_SESSION_IDS) == 22_821

print("Canonical identity contract : PASS")


# =============================================================================
# 4. FILE DISCOVERY
# =============================================================================

ALLOWED_EXTENSIONS = {
    ".parquet",
    ".csv",
    ".json",
    ".jsonl",
}

print("\nDATASET FILE DISCOVERY")
print("-" * 80)

all_files = []

for path in DATASET_ROOT.rglob("*"):
    if not path.is_file():
        continue

    if path.suffix.lower() not in ALLOWED_EXTENSIONS:
        continue

    all_files.append(path)

all_files = sorted(
    all_files,
    key=lambda p: str(p).lower()
)

print(
    f"Candidate files discovered : {len(all_files):,}"
)

assert len(all_files) > 0, (
    "No supported tabular/JSON files found in Dataset/"
)

print("File discovery : PASS")


# =============================================================================
# 5. HELPERS
# =============================================================================

def safe_columns_parquet(path):
    try:
        import pyarrow.parquet as pq

        return list(
            pq.ParquetFile(path)
            .schema
            .names
        )
    except Exception:
        return []


def safe_row_count_parquet(path):
    try:
        import pyarrow.parquet as pq

        return int(
            pq.ParquetFile(path)
            .metadata
            .num_rows
        )
    except Exception:
        return None


def inspect_file(path):
    suffix = path.suffix.lower()

    result = {
        "path": str(path),
        "relative_path": str(
            path.relative_to(PROJECT_ROOT)
        ),
        "filename": path.name,
        "extension": suffix,
        "size_bytes": int(path.stat().st_size),
        "rows": None,
        "columns": None,
        "column_names": None,
        "readable": False,
        "read_error": None,

        "has_response_id": False,
        "has_session_id": False,
        "has_objective_uid": False,
        "has_objective_raw": False,
        "has_target": False,
        "has_fold": False,

        "response_overlap_count": 0,
        "session_overlap_count": 0,
        "objective_overlap_count": 0,

        "response_overlap_rate": 0.0,
        "session_overlap_rate": 0.0,
        "objective_overlap_rate": 0.0,

        "target_like_columns": None,
        "identity_like_columns": None,

        "candidate_class": "UNREADABLE",
    }

    try:
        # ---------------------------------------------------------------------
        # Parquet: metadata first, avoiding full read whenever possible.
        # ---------------------------------------------------------------------
        if suffix == ".parquet":

            cols = safe_columns_parquet(path)
            rows = safe_row_count_parquet(path)

            result["columns"] = len(cols)
            result["column_names"] = cols
            result["rows"] = rows
            result["readable"] = True

            lower_to_original = {
                c.lower(): c
                for c in cols
            }

            response_col = lower_to_original.get(
                "response_id"
            )

            session_col = lower_to_original.get(
                "session_id"
            )

            objective_col = lower_to_original.get(
                "objective_uid"
            )

            target_cols = [
                c for c in cols
                if any(
                    token in c.lower()
                    for token in [
                        "target",
                        "label",
                        "answer",
                        "ground_truth",
                    ]
                )
            ]

            identity_cols = [
                c for c in cols
                if any(
                    token in c.lower()
                    for token in [
                        "response_id",
                        "session_id",
                        "objective_uid",
                        "turn_uid",
                    ]
                )
            ]

            result["has_response_id"] = (
                response_col is not None
            )

            result["has_session_id"] = (
                session_col is not None
            )

            result["has_objective_uid"] = (
                objective_col is not None
            )

            result["has_objective_raw"] = (
                "objective_raw" in lower_to_original
            )

            result["has_target"] = (
                len(target_cols) > 0
            )

            result["has_fold"] = (
                "fold" in lower_to_original
            )

            result["target_like_columns"] = (
                target_cols
            )

            result["identity_like_columns"] = (
                identity_cols
            )

            # -----------------------------------------------------------------
            # Only load identity columns for overlap calculation.
            # -----------------------------------------------------------------

            read_cols = []

            if response_col:
                read_cols.append(response_col)

            if session_col:
                read_cols.append(session_col)

            if objective_col:
                read_cols.append(objective_col)

            if read_cols:

                df_ids = pd.read_parquet(
                    path,
                    columns=read_cols,
                )

                if response_col:
                    vals = set(
                        df_ids[response_col]
                        .dropna()
                        .astype(str)
                    )

                    overlap = (
                        vals
                        & CANONICAL_RESPONSE_IDS
                    )

                    result[
                        "response_overlap_count"
                    ] = len(overlap)

                    result[
                        "response_overlap_rate"
                    ] = (
                        len(overlap) / len(vals)
                        if vals
                        else 0.0
                    )

                if session_col:
                    vals = set(
                        df_ids[session_col]
                        .dropna()
                        .astype(str)
                    )

                    overlap = (
                        vals
                        & CANONICAL_SESSION_IDS
                    )

                    result[
                        "session_overlap_count"
                    ] = len(overlap)

                    result[
                        "session_overlap_rate"
                    ] = (
                        len(overlap) / len(vals)
                        if vals
                        else 0.0
                    )

                if objective_col:
                    vals = set(
                        df_ids[objective_col]
                        .dropna()
                        .astype(str)
                    )

                    overlap = (
                        vals
                        & CANONICAL_OBJECTIVE_IDS
                    )

                    result[
                        "objective_overlap_count"
                    ] = len(overlap)

                    result[
                        "objective_overlap_rate"
                    ] = (
                        len(overlap) / len(vals)
                        if vals
                        else 0.0
                    )

        # ---------------------------------------------------------------------
        # CSV / JSON / JSONL
        # ---------------------------------------------------------------------

        elif suffix == ".csv":

            header = pd.read_csv(
                path,
                nrows=0,
            )

            cols = list(header.columns)

            result["columns"] = len(cols)
            result["column_names"] = cols
            result["readable"] = True

            lower_to_original = {
                c.lower(): c
                for c in cols
            }

            result["has_response_id"] = (
                "response_id" in lower_to_original
            )

            result["has_session_id"] = (
                "session_id" in lower_to_original
            )

            result["has_objective_uid"] = (
                "objective_uid" in lower_to_original
            )

            result["has_objective_raw"] = (
                "objective_raw" in lower_to_original
            )

            target_cols = [
                c for c in cols
                if any(
                    token in c.lower()
                    for token in [
                        "target",
                        "label",
                        "answer",
                        "ground_truth",
                    ]
                )
            ]

            result["has_target"] = (
                len(target_cols) > 0
            )

            result["has_fold"] = (
                "fold" in lower_to_original
            )

            result["target_like_columns"] = target_cols

            result["identity_like_columns"] = [
                c for c in cols
                if any(
                    token in c.lower()
                    for token in [
                        "response_id",
                        "session_id",
                        "objective_uid",
                        "turn_uid",
                    ]
                )
            ]

            # Row count only; identity overlap can be evaluated later
            # for shortlisted candidates.

            result["rows"] = int(
                sum(
                    1
                    for _ in open(
                        path,
                        "rb",
                    )
                )
                - 1
            )

        else:
            # JSON/JSONL: lightweight structural inspection.
            with open(
                path,
                "r",
                encoding="utf-8",
                errors="replace",
            ) as f:

                first_nonempty = None

                for line in f:
                    line = line.strip()

                    if line:
                        first_nonempty = line
                        break

            if first_nonempty:

                if suffix == ".jsonl":
                    obj = json.loads(
                        first_nonempty
                    )

                else:
                    with open(
                        path,
                        "r",
                        encoding="utf-8",
                        errors="replace",
                    ) as f:
                        data = json.load(f)

                    if isinstance(data, dict):
                        obj = data
                    elif isinstance(data, list) and data:
                        obj = data[0]
                    else:
                        obj = {}

                if isinstance(obj, dict):

                    cols = list(
                        obj.keys()
                    )

                    result["columns"] = len(cols)
                    result["column_names"] = cols
                    result["readable"] = True

                    lower_to_original = {
                        c.lower(): c
                        for c in cols
                    }

                    result[
                        "has_response_id"
                    ] = (
                        "response_id"
                        in lower_to_original
                    )

                    result[
                        "has_session_id"
                    ] = (
                        "session_id"
                        in lower_to_original
                    )

                    result[
                        "has_objective_uid"
                    ] = (
                        "objective_uid"
                        in lower_to_original
                    )

                    result[
                        "has_objective_raw"
                    ] = (
                        "objective_raw"
                        in lower_to_original
                    )

                    result["has_target"] = any(
                        any(
                            token in c.lower()
                            for token in [
                                "target",
                                "label",
                                "answer",
                                "ground_truth",
                            ]
                        )
                        for c in cols
                    )

                    result["has_fold"] = (
                        "fold"
                        in lower_to_original
                    )

                    result[
                        "target_like_columns"
                    ] = [
                        c for c in cols
                        if any(
                            token in c.lower()
                            for token in [
                                "target",
                                "label",
                                "answer",
                                "ground_truth",
                            ]
                        )
                    ]

                    result[
                        "identity_like_columns"
                    ] = [
                        c for c in cols
                        if any(
                            token in c.lower()
                            for token in [
                                "response_id",
                                "session_id",
                                "objective_uid",
                                "turn_uid",
                            ]
                        )
                    ]

    except Exception as exc:
        result["read_error"] = repr(exc)
        result["readable"] = False

    # -------------------------------------------------------------------------
    # Conservative classification.
    #
    # IMPORTANT:
    # This is NOT the final test lock.
    # -------------------------------------------------------------------------

    if not result["readable"]:
        result["candidate_class"] = "UNREADABLE"

    elif result["has_target"]:
        result["candidate_class"] = "LIKELY_TRAINING_OR_LABELLED"

    elif (
        result["has_response_id"]
        and result["has_session_id"]
        and result["has_objective_uid"]
    ):
        result["candidate_class"] = "IDENTITY_CANDIDATE"

    elif (
        result["has_response_id"]
        or result["has_session_id"]
        or result["has_objective_uid"]
    ):
        result["candidate_class"] = "PARTIAL_IDENTITY"

    else:
        result["candidate_class"] = "NON_IDENTITY"

    return result


# =============================================================================
# 6. RUN INVENTORY
# =============================================================================

print("\nRUNNING FILE INSPECTION")
print("-" * 80)

start_time = time.time()

records = []

for idx, path in enumerate(all_files, start=1):

    records.append(
        inspect_file(path)
    )

    if idx % 500 == 0:
        elapsed = time.time() - start_time

        print(
            f"Inspected {idx:,} / {len(all_files):,}"
            f" | elapsed={elapsed:.1f}s"
        )

inventory = pd.DataFrame(records)

print(
    f"\nInspection complete : "
    f"{len(inventory):,} files"
)

print(
    f"Elapsed              : "
    f"{time.time() - start_time:.1f}s"
)


# =============================================================================
# 7. INVENTORY INTEGRITY
# =============================================================================

assert len(inventory) == len(all_files)

assert inventory["path"].is_unique, (
    "Duplicate inventory paths detected."
)

assert inventory["readable"].sum() > 0

print("\nINVENTORY CONTRACT")
print("-" * 80)
print(
    f"Files discovered : {len(all_files):,}"
)
print(
    f"Files inspected  : {len(inventory):,}"
)
print(
    f"Readable         : "
    f"{int(inventory['readable'].sum()):,}"
)
print(
    f"Unreadable       : "
    f"{int((~inventory['readable']).sum()):,}"
)

print("Inventory contract : PASS")


# =============================================================================
# 8. CANDIDATE SUMMARY
# =============================================================================

class_counts = (
    inventory["candidate_class"]
    .value_counts()
    .rename_axis("candidate_class")
    .reset_index(name="files")
)

print("\nCANDIDATE CLASS SUMMARY")
print("-" * 80)

print(
    class_counts.to_string(
        index=False
    )
)


# =============================================================================
# 9. IDENTITY CANDIDATES
# =============================================================================

identity_candidates = inventory[
    inventory["candidate_class"]
    .isin([
        "IDENTITY_CANDIDATE",
        "PARTIAL_IDENTITY",
    ])
].copy()

identity_candidates = identity_candidates.sort_values(
    [
        "has_response_id",
        "has_session_id",
        "has_objective_uid",
        "has_target",
        "rows",
    ],
    ascending=[
        False,
        False,
        False,
        True,
        False,
    ],
)

print("\nIDENTITY CANDIDATES")
print("-" * 80)

print(
    f"Identity candidates : "
    f"{len(identity_candidates):,}"
)

display_columns = [
    "relative_path",
    "rows",
    "columns",
    "has_response_id",
    "has_session_id",
    "has_objective_uid",
    "has_target",
    "has_fold",
    "response_overlap_count",
    "session_overlap_count",
    "objective_overlap_count",
    "candidate_class",
]

available_display_columns = [
    c for c in display_columns
    if c in identity_candidates.columns
]

if len(identity_candidates):
    display(
        identity_candidates[
            available_display_columns
        ].head(100)
    )


# =============================================================================
# 10. POSSIBLE TEST CANDIDATE VIEW
# =============================================================================
# This is deliberately conservative.
#
# A file is NOT locked as test merely because it:
#   - has no target
#   - has response_id
#
# This view is only for Cell 2 forensic analysis.
# =============================================================================

possible_test = inventory[
    (
        inventory["readable"]
        &
        (~inventory["has_target"])
        &
        (
            inventory["has_response_id"]
            |
            inventory["has_session_id"]
            |
            inventory["has_objective_uid"]
        )
    )
].copy()

possible_test["identity_score"] = (
    possible_test["has_response_id"].astype(int)
    + possible_test["has_session_id"].astype(int)
    + possible_test["has_objective_uid"].astype(int)
)

possible_test = possible_test.sort_values(
    [
        "identity_score",
        "response_overlap_count",
        "session_overlap_count",
        "rows",
    ],
    ascending=[
        False,
        False,
        False,
        False,
    ],
)

print("\nPOSSIBLE TEST CANDIDATES")
print("-" * 80)

print(
    f"Possible candidates : "
    f"{len(possible_test):,}"
)

if len(possible_test):

    display(
        possible_test[
            [
                "relative_path",
                "rows",
                "columns",
                "has_response_id",
                "has_session_id",
                "has_objective_uid",
                "has_target",
                "response_overlap_count",
                "session_overlap_count",
                "objective_overlap_count",
                "identity_score",
                "candidate_class",
            ]
        ].head(100)
    )


# =============================================================================
# 11. WRITE INVENTORY ARTIFACT
# =============================================================================

inventory.to_parquet(
    INVENTORY_PATH,
    index=False,
)

assert INVENTORY_PATH.exists()

print("\nINVENTORY ARTIFACT")
print("-" * 80)
print(
    f"Inventory : {INVENTORY_PATH}"
)
print("Write : PASS")


# =============================================================================
# 12. WRITE SUMMARY
# =============================================================================

summary = {
    "cell": "12_test_population_lock_cell1",
    "status": "PASS",

    "project_root": str(PROJECT_ROOT),
    "dataset_root": str(DATASET_ROOT),

    "files_discovered": int(
        len(all_files)
    ),

    "files_inspected": int(
        len(inventory)
    ),

    "readable_files": int(
        inventory["readable"].sum()
    ),

    "unreadable_files": int(
        (~inventory["readable"]).sum()
    ),

    "identity_candidates": int(
        len(identity_candidates)
    ),

    "possible_test_candidates": int(
        len(possible_test)
    ),

    "canonical_population": {
        "responses": len(
            CANONICAL_RESPONSE_IDS
        ),
        "sessions": len(
            CANONICAL_SESSION_IDS
        ),
        "objectives": len(
            CANONICAL_OBJECTIVE_IDS
        ),
    },

    "test_population_locked": False,

    "production_inference_started": False,

    "submission_generated": False,

    "next_cell": (
        "Cell 2 — candidate identity overlap "
        "and structural forensic audit"
    ),

    "inventory_artifact": str(
        INVENTORY_PATH
    ),
}

with open(
    SUMMARY_PATH,
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        summary,
        f,
        indent=2,
    )


assert SUMMARY_PATH.exists()

print(
    f"Summary    : {SUMMARY_PATH}"
)
print("Summary write : PASS")


# =============================================================================
# 13. FINAL STATUS
# =============================================================================

print("\n" + "=" * 100)
print("TRACE THE ACE — CELL 1 FINAL STATUS")
print("=" * 100)

print(
    f"Dataset discovery          : PASS"
)

print(
    f"File inspection            : PASS"
)

print(
    f"Identity candidate audit   : PASS"
)

print(
    f"Possible test candidates  : "
    f"{len(possible_test):,}"
)

print(
    "Test population lock       : NOT YET"
)

print(
    "Production inference       : NOT STARTED"
)

print(
    "Submission generation      : NOT STARTED"
)

print("-" * 100)

print(
    "CELL 1 COMPLETE — PASS"
)

print(
    "IMPORTANT: No test population was locked in Cell 1."
)
print(
    "Cell 2 must perform candidate identity/structural forensic audit."
)

print("=" * 100)

====================================================================================================
TRACE THE ACE — TEST POPULATION LOCK
CELL 1 — DATASET CANDIDATE INVENTORY
====================================================================================================

PROJECT ROOT
--------------------------------------------------------------------------------
PROJECT_ROOT : D:\Competition\Trace-the-race-local
Status       : PASS

DATASET ROOT
--------------------------------------------------------------------------------
DATASET_ROOT : D:\Competition\Trace-the-race-local\Dataset
Status       : PASS

CANONICAL ARTIFACTS
--------------------------------------------------------------------------------
responses   : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\03_integrity\canonical\responses.parquet
turns       : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\03_integrity\canonical\turns.parquet
sessions    : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\03_integrity\canonical\sessions.parquet
objectives  : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\01_data_foundation\03_integrity\canonical\objectives.parquet

CANONICAL IDENTITY POPULATION
--------------------------------------------------------------------------------
Response IDs   : 35,072
Session IDs    : 22,821
Objective IDs  : 398
Canonical identity contract : PASS

DATASET FILE DISCOVERY
--------------------------------------------------------------------------------
Candidate files discovered : 22,823
File discovery : PASS

RUNNING FILE INSPECTION
--------------------------------------------------------------------------------
Inspected 500 / 22,823 | elapsed=2.7s
Inspected 1,000 / 22,823 | elapsed=5.5s
Inspected 1,500 / 22,823 | elapsed=8.3s
Inspected 2,000 / 22,823 | elapsed=11.1s
Inspected 2,500 / 22,823 | elapsed=13.7s
Inspected 3,000 / 22,823 | elapsed=16.4s
Inspected 3,500 / 22,823 | elapsed=19.1s
Inspected 4,000 / 22,823 | elapsed=21.8s
Inspected 4,500 / 22,823 | elapsed=24.5s
Inspected 5,000 / 22,823 | elapsed=27.2s
Inspected 5,500 / 22,823 | elapsed=29.8s
Inspected 6,000 / 22,823 | elapsed=32.5s
Inspected 6,500 / 22,823 | elapsed=35.2s
Inspected 7,000 / 22,823 | elapsed=37.9s
Inspected 7,500 / 22,823 | elapsed=40.7s
Inspected 8,000 / 22,823 | elapsed=43.5s
Inspected 8,500 / 22,823 | elapsed=46.2s
Inspected 9,000 / 22,823 | elapsed=49.1s
Inspected 9,500 / 22,823 | elapsed=52.0s
Inspected 10,000 / 22,823 | elapsed=54.8s
Inspected 10,500 / 22,823 | elapsed=57.6s
Inspected 11,000 / 22,823 | elapsed=60.6s
Inspected 11,500 / 22,823 | elapsed=63.4s
Inspected 12,000 / 22,823 | elapsed=66.2s
Inspected 12,500 / 22,823 | elapsed=69.0s
Inspected 13,000 / 22,823 | elapsed=71.8s
Inspected 13,500 / 22,823 | elapsed=74.6s
Inspected 14,000 / 22,823 | elapsed=77.5s
Inspected 14,500 / 22,823 | elapsed=80.3s
Inspected 15,000 / 22,823 | elapsed=83.1s
Inspected 15,500 / 22,823 | elapsed=85.9s
Inspected 16,000 / 22,823 | elapsed=88.6s
Inspected 16,500 / 22,823 | elapsed=91.4s
Inspected 17,000 / 22,823 | elapsed=94.3s
Inspected 17,500 / 22,823 | elapsed=97.2s
Inspected 18,000 / 22,823 | elapsed=100.0s
Inspected 18,500 / 22,823 | elapsed=102.8s
Inspected 19,000 / 22,823 | elapsed=105.7s
Inspected 19,500 / 22,823 | elapsed=108.4s
Inspected 20,000 / 22,823 | elapsed=111.2s
Inspected 20,500 / 22,823 | elapsed=114.0s
Inspected 21,000 / 22,823 | elapsed=116.9s
Inspected 21,500 / 22,823 | elapsed=119.7s
Inspected 22,000 / 22,823 | elapsed=122.4s
Inspected 22,500 / 22,823 | elapsed=125.2s

Inspection complete : 22,823 files
Elapsed              : 127.3s

INVENTORY CONTRACT
--------------------------------------------------------------------------------
Files discovered : 22,823
Files inspected  : 22,823
Readable         : 22,823
Unreadable       : 0
Inventory contract : PASS

CANDIDATE CLASS SUMMARY
--------------------------------------------------------------------------------
 candidate_class  files
PARTIAL_IDENTITY  22823

IDENTITY CANDIDATES
--------------------------------------------------------------------------------
Identity candidates : 22,823

,relative_path,rows,columns,has_response_id,has_session_id,has_objective_uid,has_target,has_fold,response_overlap_count,session_overlap_count,objective_overlap_count,candidate_class
0,Dataset\train_features_TMQTWsB.csv,35072,4,True,True,False,False,False,0,0,0,PARTIAL_IDENTITY
1,Dataset\train_labels_44ujmj2.csv,35072,2,True,False,False,False,False,0,0,0,PARTIAL_IDENTITY
2944,Dataset\train_transcripts\bvnewyc.csv,622,5,False,True,False,False,False,0,0,0,PARTIAL_IDENTITY
6306,Dataset\train_transcripts\dwcgsqm.csv,600,5,False,True,False,False,False,0,0,0,PARTIAL_IDENTITY
7307,Dataset\train_transcripts\emltsuv.csv,586,5,False,True,False,False,False,0,0,0,PARTIAL_IDENTITY
...,...,...,...,...,...,...,...,...,...,...,...,...
19748,Dataset\train_transcripts\mbnlerw.csv,479,5,False,True,False,False,False,0,0,0,PARTIAL_IDENTITY
8700,Dataset\train_transcripts\fiyryvd.csv,477,5,False,True,False,False,False,0,0,0,PARTIAL_IDENTITY
18245,Dataset\train_transcripts\ldppvqq.csv,477,5,False,True,False,False,False,0,0,0,PARTIAL_IDENTITY
20096,Dataset\train_transcripts\mhedblx.csv,477,5,False,True,False,False,False,0,0,0,PARTIAL_IDENTITY
15625,Dataset\train_transcripts\jooaqfk.csv,476,5,False,True,False,False,False,0,0,0,PARTIAL_IDENTITY

POSSIBLE TEST CANDIDATES
--------------------------------------------------------------------------------
Possible candidates : 22,823

,relative_path,rows,columns,has_response_id,has_session_id,has_objective_uid,has_target,response_overlap_count,session_overlap_count,objective_overlap_count,identity_score,candidate_class
0,Dataset\train_features_TMQTWsB.csv,35072,4,True,True,False,False,0,0,0,2,PARTIAL_IDENTITY
1,Dataset\train_labels_44ujmj2.csv,35072,2,True,False,False,False,0,0,0,1,PARTIAL_IDENTITY
2944,Dataset\train_transcripts\bvnewyc.csv,622,5,False,True,False,False,0,0,0,1,PARTIAL_IDENTITY
6306,Dataset\train_transcripts\dwcgsqm.csv,600,5,False,True,False,False,0,0,0,1,PARTIAL_IDENTITY
7307,Dataset\train_transcripts\emltsuv.csv,586,5,False,True,False,False,0,0,0,1,PARTIAL_IDENTITY
...,...,...,...,...,...,...,...,...,...,...,...,...
19748,Dataset\train_transcripts\mbnlerw.csv,479,5,False,True,False,False,0,0,0,1,PARTIAL_IDENTITY
8700,Dataset\train_transcripts\fiyryvd.csv,477,5,False,True,False,False,0,0,0,1,PARTIAL_IDENTITY
18245,Dataset\train_transcripts\ldppvqq.csv,477,5,False,True,False,False,0,0,0,1,PARTIAL_IDENTITY
20096,Dataset\train_transcripts\mhedblx.csv,477,5,False,True,False,False,0,0,0,1,PARTIAL_IDENTITY
15625,Dataset\train_transcripts\jooaqfk.csv,476,5,False,True,False,False,0,0,0,1,PARTIAL_IDENTITY

INVENTORY ARTIFACT
--------------------------------------------------------------------------------
Inventory : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell1\cell1_dataset_candidate_inventory.parquet
Write : PASS
Summary    : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell1\cell1_dataset_candidate_inventory.json
Summary write : PASS

====================================================================================================
TRACE THE ACE — CELL 1 FINAL STATUS
====================================================================================================
Dataset discovery          : PASS
File inspection            : PASS
Identity candidate audit   : PASS
Possible test candidates  : 22,823
Test population lock       : NOT YET
Production inference       : NOT STARTED
Submission generation      : NOT STARTED
----------------------------------------------------------------------------------------------------
CELL 1 COMPLETE — PASS
IMPORTANT: No test population was locked in Cell 1.
Cell 2 must perform candidate identity/structural forensic audit.
====================================================================================================

In [3]:
# =============================================================================
# TRACE THE ACE — TEST POPULATION LOCK
# CELL 2 — EXACT IDENTITY OVERLAP + CANDIDATE FORENSIC AUDIT
# =============================================================================

from pathlib import Path
import json
import numpy as np
import pandas as pd


print("=" * 100)
print("TRACE THE ACE — TEST POPULATION LOCK")
print("CELL 2 — EXACT IDENTITY OVERLAP + CANDIDATE FORENSIC AUDIT")
print("=" * 100)


# =============================================================================
# 0. DEPENDENCY GATE
# =============================================================================

assert "inventory" in globals(), (
    "Cell 1 dependency failed: inventory is missing."
)

assert "responses" in globals(), (
    "Cell 1 dependency failed: responses is missing."
)

assert "CANONICAL_RESPONSE_IDS" in globals(), (
    "Cell 1 dependency failed: canonical response IDs are missing."
)

assert "CANONICAL_SESSION_IDS" in globals(), (
    "Cell 1 dependency failed: canonical session IDs are missing."
)

assert "CANONICAL_OBJECTIVE_IDS" in globals(), (
    "Cell 1 dependency failed: canonical objective IDs are missing."
)


print("\nCell 1 dependency : PASS")


# =============================================================================
# 1. OUTPUT PATHS
# =============================================================================

CELL_ROOT = (
    SCRATCH_ROOT
    / "09C"
    / "final_test_discovery"
    / "cell2"
)

CELL_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

FORENSIC_PATH = (
    CELL_ROOT
    / "cell2_identity_forensic.parquet"
)

SUMMARY_PATH = (
    CELL_ROOT
    / "cell2_identity_forensic.json"
)

SHORTLIST_PATH = (
    CELL_ROOT
    / "cell2_candidate_shortlist.parquet"
)


# =============================================================================
# 2. CANONICAL POPULATION
# =============================================================================

CANONICAL_RESPONSE_COUNT = len(
    CANONICAL_RESPONSE_IDS
)

CANONICAL_SESSION_COUNT = len(
    CANONICAL_SESSION_IDS
)

CANONICAL_OBJECTIVE_COUNT = len(
    CANONICAL_OBJECTIVE_IDS
)


assert CANONICAL_RESPONSE_COUNT == 35_072
assert CANONICAL_SESSION_COUNT == 22_821
assert CANONICAL_OBJECTIVE_COUNT == 398


print("\n" + "=" * 100)
print("CANONICAL POPULATION")
print("=" * 100)

print(
    f"Responses  : {CANONICAL_RESPONSE_COUNT:,}"
)

print(
    f"Sessions   : {CANONICAL_SESSION_COUNT:,}"
)

print(
    f"Objectives : {CANONICAL_OBJECTIVE_COUNT:,}"
)

print(
    "Canonical population : PASS"
)


# =============================================================================
# 3. IDENTITY COLUMN EXTRACTION
# =============================================================================

def get_identity_columns(path):
    """
    Return the actual source columns that correspond to the canonical
    identity fields.

    Case-insensitive matching is allowed.
    No semantic guessing beyond exact field names.
    """

    columns = []

    try:

        suffix = path.suffix.lower()

        if suffix == ".parquet":

            import pyarrow.parquet as pq

            columns = (
                pq.ParquetFile(path)
                .schema
                .names
            )

        elif suffix == ".csv":

            columns = list(
                pd.read_csv(
                    path,
                    nrows=0,
                ).columns
            )

        else:

            return {}

    except Exception:

        return {}

    lower_map = {
        str(c).lower(): c
        for c in columns
    }

    return {
        "response_id": lower_map.get(
            "response_id"
        ),
        "session_id": lower_map.get(
            "session_id"
        ),
        "objective_uid": lower_map.get(
            "objective_uid"
        ),
    }


# =============================================================================
# 4. EXACT OVERLAP AUDIT
# =============================================================================

def audit_identity_overlap(path):
    """
    Read ONLY exact identity columns.

    This deliberately avoids loading arbitrary feature columns.
    """

    result = {
        "response_overlap_count": 0,
        "response_overlap_rate": 0.0,

        "session_overlap_count": 0,
        "session_overlap_rate": 0.0,

        "objective_overlap_count": 0,
        "objective_overlap_rate": 0.0,

        "response_unique_count": 0,
        "session_unique_count": 0,
        "objective_unique_count": 0,

        "identity_readable": False,
        "identity_error": None,
    }

    try:

        identity_cols = get_identity_columns(
            path
        )

        read_columns = [
            column
            for column in identity_cols.values()
            if column is not None
        ]

        if not read_columns:

            return result

        suffix = path.suffix.lower()

        if suffix == ".parquet":

            df = pd.read_parquet(
                path,
                columns=read_columns,
                engine="pyarrow",
            )

        elif suffix == ".csv":

            df = pd.read_csv(
                path,
                usecols=read_columns,
            )

        else:

            return result


        result["identity_readable"] = True


        # ---------------------------------------------------------------------
        # response_id
        # ---------------------------------------------------------------------

        response_col = identity_cols[
            "response_id"
        ]

        if response_col is not None:

            values = set(
                df[
                    response_col
                ]
                .dropna()
                .astype(str)
            )

            result[
                "response_unique_count"
            ] = len(values)

            overlap = (
                values
                & CANONICAL_RESPONSE_IDS
            )

            result[
                "response_overlap_count"
            ] = len(overlap)

            result[
                "response_overlap_rate"
            ] = (
                len(overlap) / len(values)
                if values
                else 0.0
            )


        # ---------------------------------------------------------------------
        # session_id
        # ---------------------------------------------------------------------

        session_col = identity_cols[
            "session_id"
        ]

        if session_col is not None:

            values = set(
                df[
                    session_col
                ]
                .dropna()
                .astype(str)
            )

            result[
                "session_unique_count"
            ] = len(values)

            overlap = (
                values
                & CANONICAL_SESSION_IDS
            )

            result[
                "session_overlap_count"
            ] = len(overlap)

            result[
                "session_overlap_rate"
            ] = (
                len(overlap) / len(values)
                if values
                else 0.0
            )


        # ---------------------------------------------------------------------
        # objective_uid
        # ---------------------------------------------------------------------

        objective_col = identity_cols[
            "objective_uid"
        ]

        if objective_col is not None:

            values = set(
                df[
                    objective_col
                ]
                .dropna()
                .astype(str)
            )

            result[
                "objective_unique_count"
            ] = len(values)

            overlap = (
                values
                & CANONICAL_OBJECTIVE_IDS
            )

            result[
                "objective_overlap_count"
            ] = len(overlap)

            result[
                "objective_overlap_rate"
            ] = (
                len(overlap) / len(values)
                if values
                else 0.0
            )

    except Exception as exc:

        result[
            "identity_error"
        ] = repr(exc)

    return result


# =============================================================================
# 5. SELECT INVENTORY CANDIDATES
# =============================================================================
# Cell 1 found every Dataset file to be PARTIAL_IDENTITY.
#
# We now audit only files which contain at least one exact identity field.
# =============================================================================

identity_inventory = inventory[
    (
        inventory["has_response_id"]
        |
        inventory["has_session_id"]
        |
        inventory["has_objective_uid"]
    )
].copy()

identity_inventory = (
    identity_inventory
    .reset_index(drop=True)
)


print("\n" + "=" * 100)
print("IDENTITY AUDIT INPUT")
print("=" * 100)

print(
    f"Identity-bearing files : "
    f"{len(identity_inventory):,}"
)

assert len(identity_inventory) > 0

print(
    "Identity audit input : PASS"
)


# =============================================================================
# 6. RUN EXACT OVERLAP AUDIT
# =============================================================================

print("\n" + "=" * 100)
print("RUNNING EXACT IDENTITY OVERLAP AUDIT")
print("=" * 100)


audit_records = []

for idx, row in identity_inventory.iterrows():

    path = Path(
        row["path"]
    )

    overlap_result = (
        audit_identity_overlap(
            path
        )
    )

    record = row.to_dict()

    record.update(
        overlap_result
    )

    audit_records.append(
        record
    )

    if (idx + 1) % 500 == 0:

        print(
            f"Audited "
            f"{idx + 1:,} / "
            f"{len(identity_inventory):,}"
        )


identity_forensic = pd.DataFrame(
    audit_records
)


assert len(
    identity_forensic
) == len(
    identity_inventory
)


print(
    "\nExact identity audit complete : PASS"
)


# =============================================================================
# 7. OVERLAP CLASSIFICATION
# =============================================================================

def classify_overlap(row):

    if not row["identity_readable"]:
        return "IDENTITY_UNREADABLE"

    response_overlap = int(
        row["response_overlap_count"]
    )

    session_overlap = int(
        row["session_overlap_count"]
    )

    objective_overlap = int(
        row["objective_overlap_count"]
    )

    has_response = bool(
        row["has_response_id"]
    )

    has_session = bool(
        row["has_session_id"]
    )

    has_objective = bool(
        row["has_objective_uid"]
    )

    has_target = bool(
        row["has_target"]
    )


    # -------------------------------------------------------------------------
    # Any target-bearing identity file is not a clean unseen-test candidate.
    # -------------------------------------------------------------------------

    if has_target:

        return "LABELLED_OR_TRAINING"


    # -------------------------------------------------------------------------
    # Exact full response overlap.
    # -------------------------------------------------------------------------

    if (
        has_response
        and
        response_overlap
        == row["response_unique_count"]
        and
        response_overlap > 0
    ):

        return "FULL_RESPONSE_OVERLAP"


    # -------------------------------------------------------------------------
    # Exact full session overlap.
    # -------------------------------------------------------------------------

    if (
        has_session
        and
        session_overlap
        == row["session_unique_count"]
        and
        session_overlap > 0
    ):

        return "FULL_SESSION_OVERLAP"


    # -------------------------------------------------------------------------
    # Partial canonical overlap.
    # -------------------------------------------------------------------------

    if (
        response_overlap > 0
        or session_overlap > 0
        or objective_overlap > 0
    ):

        return "PARTIAL_CANONICAL_OVERLAP"


    # -------------------------------------------------------------------------
    # Zero canonical identity overlap.
    # -------------------------------------------------------------------------

    if (
        response_overlap == 0
        and
        session_overlap == 0
        and
        objective_overlap == 0
    ):

        return "ZERO_CANONICAL_OVERLAP"


    return "AMBIGUOUS"


identity_forensic[
    "overlap_class"
] = identity_forensic.apply(
    classify_overlap,
    axis=1,
)


# =============================================================================
# 8. FORENSIC SUMMARY
# =============================================================================

print("\n" + "=" * 100)
print("IDENTITY OVERLAP SUMMARY")
print("=" * 100)

overlap_summary = (
    identity_forensic[
        "overlap_class"
    ]
    .value_counts()
    .rename_axis(
        "overlap_class"
    )
    .reset_index(
        name="files"
    )
)

print(
    overlap_summary.to_string(
        index=False
    )
)


# =============================================================================
# 9. ZERO-OVERLAP CANDIDATES
# =============================================================================

zero_overlap = identity_forensic[
    identity_forensic[
        "overlap_class"
    ]
    ==
    "ZERO_CANONICAL_OVERLAP"
].copy()


zero_overlap = zero_overlap.sort_values(
    [
        "has_response_id",
        "has_session_id",
        "has_objective_uid",
        "rows",
    ],
    ascending=[
        False,
        False,
        False,
        False,
    ],
)


print("\n" + "=" * 100)
print("ZERO-CANONICAL-OVERLAP CANDIDATES")
print("=" * 100)

print(
    f"Zero-overlap files : "
    f"{len(zero_overlap):,}"
)


if len(zero_overlap):

    display(
        zero_overlap[
            [
                "relative_path",
                "rows",
                "columns",
                "has_response_id",
                "has_session_id",
                "has_objective_uid",
                "has_target",
                "response_unique_count",
                "session_unique_count",
                "objective_unique_count",
                "overlap_class",
            ]
        ].head(200)
    )


# =============================================================================
# 10. HIGH-INTEREST UNLABELLED CANDIDATES
# =============================================================================
# This is a shortlist only.
#
# It does NOT mean these are test rows.
# =============================================================================

high_interest = identity_forensic[
    (
        ~identity_forensic["has_target"]
    )
    &
    (
        identity_forensic[
            "identity_readable"
        ]
    )
    &
    (
        identity_forensic[
            "overlap_class"
        ].isin([
            "ZERO_CANONICAL_OVERLAP",
            "PARTIAL_CANONICAL_OVERLAP",
        ])
    )
].copy()


high_interest[
    "candidate_score"
] = 0


# Stronger identity schema
high_interest[
    "candidate_score"
] += (
    high_interest[
        "has_response_id"
    ].astype(int)
    * 5
)

high_interest[
    "candidate_score"
] += (
    high_interest[
        "has_session_id"
    ].astype(int)
    * 3
)

high_interest[
    "candidate_score"
] += (
    high_interest[
        "has_objective_uid"
    ].astype(int)
    * 2
)


# Prefer zero response overlap over partial response overlap
high_interest[
    "candidate_score"
] += (
    (
        high_interest[
            "response_overlap_count"
        ]
        == 0
    )
    .astype(int)
    * 4
)


# Penalize training-like population overlap
high_interest[
    "candidate_score"
] -= (
    high_interest[
        "response_overlap_count"
    ]
    > 0
).astype(int) * 3


high_interest = high_interest.sort_values(
    [
        "candidate_score",
        "rows",
        "has_response_id",
        "has_session_id",
    ],
    ascending=[
        False,
        False,
        False,
        False,
    ],
)


print("\n" + "=" * 100)
print("HIGH-INTEREST UNLABELLED CANDIDATES")
print("=" * 100)

print(
    f"Shortlist size : "
    f"{len(high_interest):,}"
)

if len(high_interest):

    display(
        high_interest[
            [
                "relative_path",
                "rows",
                "columns",
                "has_response_id",
                "has_session_id",
                "has_objective_uid",
                "response_overlap_count",
                "session_overlap_count",
                "objective_overlap_count",
                "candidate_score",
                "overlap_class",
            ]
        ].head(100)
    )


# =============================================================================
# 11. IMPORTANT SAFETY ASSERTIONS
# =============================================================================

# No candidate may be declared "LOCKED_TEST" here.
assert (
    "LOCKED_TEST"
    not in identity_forensic.columns
)


# This cell must not generate predictions.
assert (
    not PRODUCTION_INFERENCE_STARTED
)


# This cell must not modify canonical training artifacts.
assert (
    CANONICAL_RESPONSE_COUNT
    == 35_072
)


print("\n" + "=" * 100)
print("SAFETY CONTRACT")
print("=" * 100)

print(
    "No test population locked : PASS"
)

print(
    "No production inference   : PASS"
)

print(
    "Canonical population unchanged : PASS"
)


# =============================================================================
# 12. WRITE FORENSIC ARTIFACT
# =============================================================================

identity_forensic.to_parquet(
    FORENSIC_PATH,
    index=False,
)

assert FORENSIC_PATH.exists()

print("\nFORENSIC ARTIFACT")
print("-" * 100)
print(
    f"Path : {FORENSIC_PATH}"
)

print(
    "Forensic parquet write : PASS"
)


# =============================================================================
# 13. WRITE SHORTLIST
# =============================================================================

shortlist_columns = [
    "path",
    "relative_path",
    "filename",
    "extension",
    "rows",
    "columns",

    "has_response_id",
    "has_session_id",
    "has_objective_uid",
    "has_target",

    "response_unique_count",
    "session_unique_count",
    "objective_unique_count",

    "response_overlap_count",
    "session_overlap_count",
    "objective_overlap_count",

    "response_overlap_rate",
    "session_overlap_rate",
    "objective_overlap_rate",

    "candidate_score",
    "overlap_class",
]


shortlist_columns = [
    c for c in shortlist_columns
    if c in high_interest.columns
]


high_interest[
    shortlist_columns
].to_parquet(
    SHORTLIST_PATH,
    index=False,
)

assert SHORTLIST_PATH.exists()

print(
    f"Shortlist : {SHORTLIST_PATH}"
)

print(
    "Shortlist write : PASS"
)


# =============================================================================
# 14. WRITE SUMMARY JSON
# =============================================================================

summary = {
    "cell": "12_test_population_lock_cell2",

    "status": "PASS",

    "identity_files_audited": int(
        len(identity_forensic)
    ),

    "overlap_classes": {
        str(row["overlap_class"]): int(
            row["files"]
        )
        for _, row
        in overlap_summary.iterrows()
    },

    "zero_canonical_overlap_files": int(
        len(zero_overlap)
    ),

    "high_interest_unlabelled_candidates": int(
        len(high_interest)
    ),

    "canonical_population": {
        "responses": int(
            CANONICAL_RESPONSE_COUNT
        ),
        "sessions": int(
            CANONICAL_SESSION_COUNT
        ),
        "objectives": int(
            CANONICAL_OBJECTIVE_COUNT
        ),
    },

    "test_population_locked": False,

    "production_inference_started": False,

    "submission_generated": False,

    "forensic_artifact": str(
        FORENSIC_PATH
    ),

    "shortlist_artifact": str(
        SHORTLIST_PATH
    ),

    "next_cell": (
        "Cell 3 — candidate structural "
        "forensic comparison and test-population evidence audit"
    ),
}


with open(
    SUMMARY_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        summary,
        f,
        indent=2,
    )


assert SUMMARY_PATH.exists()

print(
    f"Summary : {SUMMARY_PATH}"
)

print(
    "Summary write : PASS"
)


# =============================================================================
# 15. FINAL STATUS
# =============================================================================

print("\n" + "=" * 100)
print("TRACE THE ACE — CELL 2 FINAL STATUS")
print("=" * 100)

print(
    "Cell 1 dependency              : PASS"
)

print(
    "Exact identity audit           : PASS"
)

print(
    "Response overlap audit         : PASS"
)

print(
    "Session overlap audit          : PASS"
)

print(
    "Objective overlap audit        : PASS"
)

print(
    "Candidate forensic shortlist   : PASS"
)

print(
    "Test population lock           : NOT YET"
)

print(
    "Production inference           : NOT STARTED"
)

print(
    "Submission generation          : NOT STARTED"
)

print("-" * 100)

print(
    "CELL 2 COMPLETE — PASS"
)

print(
    "IMPORTANT: Zero overlap is a candidate signal, "
    "NOT proof of test population."
)

print("=" * 100)

====================================================================================================
TRACE THE ACE — TEST POPULATION LOCK
CELL 2 — EXACT IDENTITY OVERLAP + CANDIDATE FORENSIC AUDIT
====================================================================================================

Cell 1 dependency : PASS

====================================================================================================
CANONICAL POPULATION
====================================================================================================
Responses  : 35,072
Sessions   : 22,821
Objectives : 398
Canonical population : PASS

====================================================================================================
IDENTITY AUDIT INPUT
====================================================================================================
Identity-bearing files : 22,823
Identity audit input : PASS

====================================================================================================
RUNNING EXACT IDENTITY OVERLAP AUDIT
====================================================================================================
Audited 500 / 22,823
Audited 1,000 / 22,823
Audited 1,500 / 22,823
Audited 2,000 / 22,823
Audited 2,500 / 22,823
Audited 3,000 / 22,823
Audited 3,500 / 22,823
Audited 4,000 / 22,823
Audited 4,500 / 22,823
Audited 5,000 / 22,823
Audited 5,500 / 22,823
Audited 6,000 / 22,823
Audited 6,500 / 22,823
Audited 7,000 / 22,823
Audited 7,500 / 22,823
Audited 8,000 / 22,823
Audited 8,500 / 22,823
Audited 9,000 / 22,823
Audited 9,500 / 22,823
Audited 10,000 / 22,823
Audited 10,500 / 22,823
Audited 11,000 / 22,823
Audited 11,500 / 22,823
Audited 12,000 / 22,823
Audited 12,500 / 22,823
Audited 13,000 / 22,823
Audited 13,500 / 22,823
Audited 14,000 / 22,823
Audited 14,500 / 22,823
Audited 15,000 / 22,823
Audited 15,500 / 22,823
Audited 16,000 / 22,823
Audited 16,500 / 22,823
Audited 17,000 / 22,823
Audited 17,500 / 22,823
Audited 18,000 / 22,823
Audited 18,500 / 22,823
Audited 19,000 / 22,823
Audited 19,500 / 22,823
Audited 20,000 / 22,823
Audited 20,500 / 22,823
Audited 21,000 / 22,823
Audited 21,500 / 22,823
Audited 22,000 / 22,823
Audited 22,500 / 22,823

Exact identity audit complete : PASS

====================================================================================================
IDENTITY OVERLAP SUMMARY
====================================================================================================
        overlap_class  files
 FULL_SESSION_OVERLAP  22821
FULL_RESPONSE_OVERLAP      2

====================================================================================================
ZERO-CANONICAL-OVERLAP CANDIDATES
====================================================================================================
Zero-overlap files : 0

====================================================================================================
HIGH-INTEREST UNLABELLED CANDIDATES
====================================================================================================
Shortlist size : 0

====================================================================================================
SAFETY CONTRACT
====================================================================================================
No test population locked : PASS
No production inference   : PASS
Canonical population unchanged : PASS

FORENSIC ARTIFACT
----------------------------------------------------------------------------------------------------
Path : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell2\cell2_identity_forensic.parquet
Forensic parquet write : PASS
Shortlist : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell2\cell2_candidate_shortlist.parquet
Shortlist write : PASS
Summary : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell2\cell2_identity_forensic.json
Summary write : PASS

====================================================================================================
TRACE THE ACE — CELL 2 FINAL STATUS
====================================================================================================
Cell 1 dependency              : PASS
Exact identity audit           : PASS
Response overlap audit         : PASS
Session overlap audit          : PASS
Objective overlap audit        : PASS
Candidate forensic shortlist   : PASS
Test population lock           : NOT YET
Production inference           : NOT STARTED
Submission generation          : NOT STARTED
----------------------------------------------------------------------------------------------------
CELL 2 COMPLETE — PASS
IMPORTANT: Zero overlap is a candidate signal, NOT proof of test population.
====================================================================================================

In [4]:
# =============================================================================
# TRACE THE ACE — TEST POPULATION LOCK
# CELL 3 — FULL-RESPONSE OVERLAP FORENSIC +
#          DATASET POPULATION STRUCTURE AUDIT
# =============================================================================

from pathlib import Path
import json

import numpy as np
import pandas as pd


print("=" * 100)
print("TRACE THE ACE — TEST POPULATION LOCK")
print("CELL 3 — FULL-RESPONSE OVERLAP FORENSIC + POPULATION STRUCTURE AUDIT")
print("=" * 100)


# =============================================================================
# 0. DEPENDENCY GATE
# =============================================================================

assert "identity_forensic" in globals(), (
    "Cell 2 dependency failed: identity_forensic is missing."
)

assert "responses" in globals(), (
    "Cell 2 dependency failed: responses is missing."
)

assert "CANONICAL_RESPONSE_IDS" in globals(), (
    "Cell 2 dependency failed: canonical response IDs are missing."
)

assert "CANONICAL_SESSION_IDS" in globals(), (
    "Cell 2 dependency failed: canonical session IDs are missing."
)

assert "CANONICAL_OBJECTIVE_IDS" in globals(), (
    "Cell 2 dependency failed: canonical objective IDs are missing."
)


print("\nCell 2 dependency : PASS")


# =============================================================================
# 1. OUTPUT PATHS
# =============================================================================

CELL_ROOT = (
    SCRATCH_ROOT
    / "09C"
    / "final_test_discovery"
    / "cell3"
)

CELL_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

FORENSIC_PATH = (
    CELL_ROOT
    / "cell3_full_response_overlap_forensic.parquet"
)

SUMMARY_PATH = (
    CELL_ROOT
    / "cell3_population_structure.json"
)


# =============================================================================
# 2. FULL RESPONSE OVERLAP FILES
# =============================================================================

full_response_overlap = identity_forensic[
    identity_forensic[
        "overlap_class"
    ]
    ==
    "FULL_RESPONSE_OVERLAP"
].copy()


print("\n" + "=" * 100)
print("FULL-RESPONSE-OVERLAP FILES")
print("=" * 100)

print(
    f"Files : {len(full_response_overlap):,}"
)


assert len(full_response_overlap) == 2, (
    "Expected exactly 2 FULL_RESPONSE_OVERLAP files "
    "from Cell 2."
)


display(
    full_response_overlap[
        [
            "relative_path",
            "filename",
            "extension",
            "rows",
            "columns",
            "has_response_id",
            "has_session_id",
            "has_objective_uid",
            "has_target",
            "has_fold",
            "response_unique_count",
            "response_overlap_count",
            "session_unique_count",
            "session_overlap_count",
        ]
    ]
)


# =============================================================================
# 3. LOAD EXACT IDENTITY DATA FOR THE TWO FILES
# =============================================================================

def load_identity_frame(path):

    suffix = path.suffix.lower()

    if suffix == ".parquet":

        import pyarrow.parquet as pq

        cols = pq.ParquetFile(
            path
        ).schema.names

        lower_map = {
            str(c).lower(): c
            for c in cols
        }

        selected = [
            lower_map[c]
            for c in [
                "response_id",
                "session_id",
                "objective_uid",
                "target",
                "fold",
            ]
            if c in lower_map
        ]

        return pd.read_parquet(
            path,
            columns=selected,
            engine="pyarrow",
        )

    if suffix == ".csv":

        header = pd.read_csv(
            path,
            nrows=0,
        )

        lower_map = {
            str(c).lower(): c
            for c in header.columns
        }

        selected = [
            lower_map[c]
            for c in [
                "response_id",
                "session_id",
                "objective_uid",
                "target",
                "fold",
            ]
            if c in lower_map
        ]

        return pd.read_csv(
            path,
            usecols=selected,
        )

    raise ValueError(
        f"Unsupported file type: {suffix}"
    )


full_overlap_records = []


for _, row in full_response_overlap.iterrows():

    path = Path(
        row["path"]
    )

    df = load_identity_frame(
        path
    )

    print("\n" + "-" * 100)
    print(
        f"FILE: {path}"
    )

    print(
        f"Rows loaded : {len(df):,}"
    )

    # -------------------------------------------------------------------------
    # Exact response comparison
    # -------------------------------------------------------------------------

    assert "response_id" in df.columns

    file_response_ids = set(
        df[
            "response_id"
        ]
        .dropna()
        .astype(str)
    )

    response_overlap = (
        file_response_ids
        & CANONICAL_RESPONSE_IDS
    )

    print(
        f"Unique response IDs : "
        f"{len(file_response_ids):,}"
    )

    print(
        f"Canonical overlap   : "
        f"{len(response_overlap):,}"
    )

    # -------------------------------------------------------------------------
    # Exact equality test
    # -------------------------------------------------------------------------

    exact_response_population = (
        file_response_ids
        ==
        CANONICAL_RESPONSE_IDS
    )

    print(
        f"Exact canonical response population : "
        f"{exact_response_population}"
    )

    # -------------------------------------------------------------------------
    # Session population
    # -------------------------------------------------------------------------

    if "session_id" in df.columns:

        file_session_ids = set(
            df[
                "session_id"
            ]
            .dropna()
            .astype(str)
        )

        session_overlap = (
            file_session_ids
            & CANONICAL_SESSION_IDS
        )

        exact_session_population = (
            file_session_ids
            ==
            CANONICAL_SESSION_IDS
        )

    else:

        file_session_ids = set()
        session_overlap = set()
        exact_session_population = False


    print(
        f"Unique session IDs   : "
        f"{len(file_session_ids):,}"
    )

    print(
        f"Canonical session overlap : "
        f"{len(session_overlap):,}"
    )

    print(
        f"Exact canonical session population : "
        f"{exact_session_population}"
    )


    # -------------------------------------------------------------------------
    # Target presence
    # -------------------------------------------------------------------------

    has_target = (
        "target" in df.columns
    )

    if has_target:

        target_values = (
            df[
                "target"
            ]
            .dropna()
            .unique()
        )

    else:

        target_values = []


    # -------------------------------------------------------------------------
    # Fold presence
    # -------------------------------------------------------------------------

    has_fold = (
        "fold" in df.columns
    )

    if has_fold:

        fold_values = sorted(
            pd.to_numeric(
                df["fold"],
                errors="coerce",
            )
            .dropna()
            .astype(int)
            .unique()
            .tolist()
        )

    else:

        fold_values = []


    full_overlap_records.append(
        {
            "path": str(path),

            "rows": int(len(df)),

            "unique_response_ids": int(
                len(file_response_ids)
            ),

            "canonical_response_overlap": int(
                len(response_overlap)
            ),

            "exact_response_population": bool(
                exact_response_population
            ),

            "unique_session_ids": int(
                len(file_session_ids)
            ),

            "canonical_session_overlap": int(
                len(session_overlap)
            ),

            "exact_session_population": bool(
                exact_session_population
            ),

            "has_target": bool(
                has_target
            ),

            "target_unique_values": [
                str(x)
                for x in target_values[:50]
            ],

            "has_fold": bool(
                has_fold
            ),

            "fold_values": fold_values,
        }
    )


# =============================================================================
# 4. FORENSIC TABLE
# =============================================================================

full_overlap_forensic = pd.DataFrame(
    full_overlap_records
)


assert len(
    full_overlap_forensic
) == 2


print("\n" + "=" * 100)
print("FULL-RESPONSE FORENSIC RESULT")
print("=" * 100)

display(
    full_overlap_forensic
)


# =============================================================================
# 5. DATASET POPULATION STRUCTURE
# =============================================================================

dataset_row_counts = (
    identity_forensic[
        identity_forensic[
            "readable"
        ]
    ]
    .groupby(
        "rows",
        dropna=False,
    )
    .size()
    .reset_index(
        name="files"
    )
    .sort_values(
        "files",
        ascending=False,
    )
)


print("\n" + "=" * 100)
print("DATASET POPULATION STRUCTURE")
print("=" * 100)

display(
    dataset_row_counts.head(50)
)


# =============================================================================
# 6. CANONICAL-SIZE FILES
# =============================================================================

canonical_size_files = identity_forensic[
    identity_forensic[
        "rows"
    ]
    .isin([
        35_072,
        22_821,
    ])
].copy()


print("\n" + "=" * 100)
print("CANONICAL-SIZE FILES")
print("=" * 100)

print(
    f"Files with canonical-sized populations : "
    f"{len(canonical_size_files):,}"
)


if len(canonical_size_files):

    display(
        canonical_size_files[
            [
                "relative_path",
                "rows",
                "columns",
                "has_response_id",
                "has_session_id",
                "has_objective_uid",
                "has_target",
                "overlap_class",
            ]
        ]
        .sort_values(
            [
                "rows",
                "relative_path",
            ]
        )
        .head(200)
    )


# =============================================================================
# 7. LOOK FOR ANY DATASET FILE WITH A POPULATION SIZE
#    THAT DOES NOT MATCH TRAINING STRUCTURE
# =============================================================================

# We intentionally do NOT infer test from row count.
#
# This section only reports unusual population sizes.

known_training_population_sizes = {
    35_072,
    22_821,
    398,
}


unusual_population_files = identity_forensic[
    ~identity_forensic[
        "rows"
    ].isin(
        known_training_population_sizes
    )
].copy()


print("\n" + "=" * 100)
print("UNUSUAL POPULATION-SIZE FILES")
print("=" * 100)

print(
    f"Files with non-canonical row counts : "
    f"{len(unusual_population_files):,}"
)


if len(unusual_population_files):

    display(
        unusual_population_files[
            [
                "relative_path",
                "rows",
                "columns",
                "has_response_id",
                "has_session_id",
                "has_objective_uid",
                "has_target",
                "response_overlap_count",
                "session_overlap_count",
                "objective_overlap_count",
                "overlap_class",
            ]
        ]
        .sort_values(
            [
                "rows",
                "relative_path",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .head(200)
    )


# =============================================================================
# 8. HARD NEGATIVE TEST ASSERTION
# =============================================================================
# If every identity-bearing Dataset file is tied to canonical training
# population, then Dataset/ is NOT a discoverable unseen-test source.
#
# This is a conclusion about Dataset/ only.
# It does NOT claim that the competition has no test data elsewhere.

zero_overlap_count = int(
    (
        identity_forensic[
            "overlap_class"
        ]
        ==
        "ZERO_CANONICAL_OVERLAP"
    ).sum()
)

partial_overlap_count = int(
    (
        identity_forensic[
            "overlap_class"
        ]
        ==
        "PARTIAL_CANONICAL_OVERLAP"
    ).sum()
)

full_session_count = int(
    (
        identity_forensic[
            "overlap_class"
        ]
        ==
        "FULL_SESSION_OVERLAP"
    ).sum()
)

full_response_count = int(
    (
        identity_forensic[
            "overlap_class"
        ]
        ==
        "FULL_RESPONSE_OVERLAP"
    ).sum()
)


dataset_contains_zero_overlap_candidate = (
    zero_overlap_count > 0
)


dataset_contains_unseen_identity_candidate = (
    zero_overlap_count > 0
    or
    partial_overlap_count > 0
)


print("\n" + "=" * 100)
print("DATASET TEST-POPULATION EVIDENCE")
print("=" * 100)

print(
    f"Zero-overlap files       : "
    f"{zero_overlap_count:,}"
)

print(
    f"Partial-overlap files    : "
    f"{partial_overlap_count:,}"
)

print(
    f"Full-session-overlap     : "
    f"{full_session_count:,}"
)

print(
    f"Full-response-overlap    : "
    f"{full_response_count:,}"
)


if not dataset_contains_unseen_identity_candidate:

    print(
        "\nDataset unseen-identity candidate : NONE"
    )

    print(
        "Dataset test population evidence : NOT FOUND"
    )

else:

    print(
        "\nDataset unseen-identity candidate : PRESENT"
    )

    print(
        "Further forensic analysis required."
    )


# =============================================================================
# 9. NO LOCK / NO INFERENCE GUARD
# =============================================================================

TEST_POPULATION_LOCKED = False

assert (
    TEST_POPULATION_LOCKED is False
)

assert (
    not PRODUCTION_INFERENCE_STARTED
)


print("\n" + "=" * 100)
print("SAFETY GATE")
print("=" * 100)

print(
    "Test population locked : NO"
)

print(
    "Production inference   : NOT STARTED"
)

print(
    "Submission             : NOT GENERATED"
)


# =============================================================================
# 10. WRITE FORENSIC ARTIFACT
# =============================================================================

full_overlap_forensic.to_parquet(
    FORENSIC_PATH,
    index=False,
)

assert FORENSIC_PATH.exists()

print("\nForensic parquet : PASS")
print(
    f"Path : {FORENSIC_PATH}"
)


# =============================================================================
# 11. SUMMARY
# =============================================================================

dataset_test_population_status = (
    "NOT_FOUND_IN_DATASET"
    if not dataset_contains_unseen_identity_candidate
    else
    "CANDIDATES_REQUIRE_FURTHER_AUDIT"
)


summary = {
    "cell": "12_test_population_lock_cell3",

    "status": "PASS",

    "dataset_test_population_status": (
        dataset_test_population_status
    ),

    "identity_files_audited": int(
        len(identity_forensic)
    ),

    "full_response_overlap_files": int(
        full_response_count
    ),

    "full_session_overlap_files": int(
        full_session_count
    ),

    "partial_overlap_files": int(
        partial_overlap_count
    ),

    "zero_overlap_files": int(
        zero_overlap_count
    ),

    "canonical_population": {
        "responses": 35_072,
        "sessions": 22_821,
        "objectives": 398,
    },

    "test_population_locked": False,

    "production_inference_started": False,

    "submission_generated": False,

    "forensic_artifact": str(
        FORENSIC_PATH
    ),

    "next_action": (
        "If Dataset has no unseen identity candidate, "
        "search outside Dataset/ for the actual competition "
        "test/submission population before locking."
    ),
}


with open(
    SUMMARY_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        summary,
        f,
        indent=2,
    )


assert SUMMARY_PATH.exists()

print(
    f"Summary : {SUMMARY_PATH}"
)

print(
    "Summary write : PASS"
)


# =============================================================================
# 12. FINAL STATUS
# =============================================================================

print("\n" + "=" * 100)
print("TRACE THE ACE — CELL 3 FINAL STATUS")
print("=" * 100)

print(
    "Cell 2 dependency                 : PASS"
)

print(
    "Full-response overlap forensic    : PASS"
)

print(
    "Dataset population structure      : PASS"
)

print(
    "Canonical-size audit              : PASS"
)

print(
    "Unusual population audit          : PASS"
)

print(
    f"Zero-overlap candidates           : "
    f"{zero_overlap_count}"
)

print(
    f"Partial-overlap candidates        : "
    f"{partial_overlap_count}"
)

print(
    f"Dataset test evidence             : "
    f"{dataset_test_population_status}"
)

print(
    "Test population lock              : NOT YET"
)

print(
    "Production inference              : NOT STARTED"
)

print(
    "Submission generation             : NOT STARTED"
)

print("-" * 100)

print(
    "CELL 3 COMPLETE — PASS"
)

print("=" * 100)

====================================================================================================
TRACE THE ACE — TEST POPULATION LOCK
CELL 3 — FULL-RESPONSE OVERLAP FORENSIC + POPULATION STRUCTURE AUDIT
====================================================================================================

Cell 2 dependency : PASS

====================================================================================================
FULL-RESPONSE-OVERLAP FILES
====================================================================================================
Files : 2

,relative_path,filename,extension,rows,columns,has_response_id,has_session_id,has_objective_uid,has_target,has_fold,response_unique_count,response_overlap_count,session_unique_count,session_overlap_count
0,Dataset\train_features_TMQTWsB.csv,train_features_TMQTWsB.csv,.csv,35072,4,True,True,False,False,False,35072,35072,22821,22821
1,Dataset\train_labels_44ujmj2.csv,train_labels_44ujmj2.csv,.csv,35072,2,True,False,False,False,False,35072,35072,0,0

----------------------------------------------------------------------------------------------------
FILE: D:\Competition\Trace-the-race-local\Dataset\train_features_TMQTWsB.csv
Rows loaded : 35,072
Unique response IDs : 35,072
Canonical overlap   : 35,072
Exact canonical response population : True
Unique session IDs   : 22,821
Canonical session overlap : 22,821
Exact canonical session population : True

----------------------------------------------------------------------------------------------------
FILE: D:\Competition\Trace-the-race-local\Dataset\train_labels_44ujmj2.csv
Rows loaded : 35,072
Unique response IDs : 35,072
Canonical overlap   : 35,072
Exact canonical response population : True
Unique session IDs   : 0
Canonical session overlap : 0
Exact canonical session population : False

====================================================================================================
FULL-RESPONSE FORENSIC RESULT
====================================================================================================

,path,rows,unique_response_ids,canonical_response_overlap,exact_response_population,unique_session_ids,canonical_session_overlap,exact_session_population,has_target,target_unique_values,has_fold,fold_values
0,D:\Competition\Trace-the-race-local\Dataset\tr...,35072,35072,35072,True,22821,22821,True,False,[],False,[]
1,D:\Competition\Trace-the-race-local\Dataset\tr...,35072,35072,35072,True,0,0,False,False,[],False,[]

====================================================================================================
DATASET POPULATION STRUCTURE
====================================================================================================

     rows  files
235   259    156
231   255    153
210   234    152
245   269    150
264   288    150
248   272    149
213   237    146
224   248    143
237   261    143
251   275    142
241   265    141
219   243    140
225   249    140
268   292    139
252   276    138
233   257    138
234   258    137
242   266    136
273   297    136
227   251    136
267   291    134
206   230    134
262   286    133
220   244    133
229   253    132
205   229    132
223   247    132
232   256    131
246   270    130
239   263    130
247   271    129
258   282    129
257   281    128
249   273    128
228   252    127
243   267    127
218   242    127
254   278    125
238   262    125
208   232    124
253   277    123
211   235    123
216   240    123
270   294    122
221   245    121
269   293    119
271   295    119
222   246    119
230   254    119
244   268    119

====================================================================================================
CANONICAL-SIZE FILES
====================================================================================================
Files with canonical-sized populations : 2

,relative_path,rows,columns,has_response_id,has_session_id,has_objective_uid,has_target,overlap_class
0,Dataset\train_features_TMQTWsB.csv,35072,4,True,True,False,False,FULL_RESPONSE_OVERLAP
1,Dataset\train_labels_44ujmj2.csv,35072,2,True,False,False,False,FULL_RESPONSE_OVERLAP

====================================================================================================
UNUSUAL POPULATION-SIZE FILES
====================================================================================================
Files with non-canonical row counts : 22,797

,relative_path,rows,columns,has_response_id,has_session_id,has_objective_uid,has_target,response_overlap_count,session_overlap_count,objective_overlap_count,overlap_class
2944,Dataset\train_transcripts\bvnewyc.csv,622,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
6306,Dataset\train_transcripts\dwcgsqm.csv,600,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
7307,Dataset\train_transcripts\emltsuv.csv,586,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
21021,Dataset\train_transcripts\mvkburc.csv,582,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
19991,Dataset\train_transcripts\mfkdqcm.csv,572,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
...,...,...,...,...,...,...,...,...,...,...,...
15110,Dataset\train_transcripts\jgerhod.csv,456,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
15623,Dataset\train_transcripts\jomrkzt.csv,456,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
21258,Dataset\train_transcripts\mzahqbr.csv,456,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
8917,Dataset\train_transcripts\fmkufzn.csv,455,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP
12581,Dataset\train_transcripts\hrklyfs.csv,455,5,False,True,False,False,0,1,0,FULL_SESSION_OVERLAP

====================================================================================================
DATASET TEST-POPULATION EVIDENCE
====================================================================================================
Zero-overlap files       : 0
Partial-overlap files    : 0
Full-session-overlap     : 22,821
Full-response-overlap    : 2

Dataset unseen-identity candidate : NONE
Dataset test population evidence : NOT FOUND

====================================================================================================
SAFETY GATE
====================================================================================================
Test population locked : NO
Production inference   : NOT STARTED
Submission             : NOT GENERATED

Forensic parquet : PASS
Path : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell3\cell3_full_response_overlap_forensic.parquet
Summary : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell3\cell3_population_structure.json
Summary write : PASS

====================================================================================================
TRACE THE ACE — CELL 3 FINAL STATUS
====================================================================================================
Cell 2 dependency                 : PASS
Full-response overlap forensic    : PASS
Dataset population structure      : PASS
Canonical-size audit              : PASS
Unusual population audit          : PASS
Zero-overlap candidates           : 0
Partial-overlap candidates        : 0
Dataset test evidence             : NOT_FOUND_IN_DATASET
Test population lock              : NOT YET
Production inference              : NOT STARTED
Submission generation             : NOT STARTED
----------------------------------------------------------------------------------------------------
CELL 3 COMPLETE — PASS
====================================================================================================

In [5]:
# =============================================================================
# TRACE THE ACE — TEST RUNTIME CONTRACT
# CELL 4 — OFFICIAL COMPETITION INFERENCE RUNTIME CONTRACT
# =============================================================================

from pathlib import Path
import json
import platform
import sys


print("=" * 100)
print("TRACE THE ACE — TEST RUNTIME CONTRACT")
print("CELL 4 — OFFICIAL COMPETITION INFERENCE RUNTIME CONTRACT")
print("=" * 100)


# =============================================================================
# 1. DEPENDENCY GATE
# =============================================================================

assert "identity_forensic" in globals(), (
    "Cell 3 dependency failed: identity_forensic is missing."
)

assert "TEST_POPULATION_LOCKED" in globals(), (
    "Cell 3 dependency failed: TEST_POPULATION_LOCKED is missing."
)

assert TEST_POPULATION_LOCKED is False, (
    "Test population must NOT be locally locked."
)

assert not PRODUCTION_INFERENCE_STARTED, (
    "Production inference must not have started."
)


print("\nCell 3 dependency              : PASS")
print("Local test population lock     : NOT REQUIRED")


# =============================================================================
# 2. PROJECT PATHS
# =============================================================================

PROJECT_ROOT = Path(
    r"D:\Competition\Trace-the-race-local"
)

SCRATCH_ROOT = (
    PROJECT_ROOT
    / "scratch_mastery_outputs"
)

CELL_ROOT = (
    SCRATCH_ROOT
    / "09C"
    / "final_test_discovery"
    / "cell4"
)

CELL_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

CONTRACT_PATH = (
    CELL_ROOT
    / "cell4_test_runtime_contract.json"
)


assert PROJECT_ROOT.exists()
assert SCRATCH_ROOT.exists()

print("\nPROJECT ROOT")
print("-" * 80)
print(
    f"PROJECT_ROOT : {PROJECT_ROOT}"
)
print(
    "Project root : PASS"
)


# =============================================================================
# 3. OFFICIAL RUNTIME CONTRACT
# =============================================================================

RUNTIME_CONTRACT = {

    "competition": "Trace the Ace",

    "runtime": {
        "python_version": "3.12",
        "network_access": False,
        "max_full_submission_hours": 6,
        "max_smoke_test_minutes": 20,
        "gpu_count": 1,
        "gpu_type": "NVIDIA A100",
        "gpu_vram_gb": 80,
        "cpu_vcpus": 24,
        "ram_gb": 220,
        "root_access": False,
        "submission_zip_max_gb": 60,
    },

    "provided_runtime_data": {

        "data_root": "data",

        "submission_format": (
            "data/submission_format.csv"
        ),

        "test_features": (
            "data/test_features.csv"
        ),

        "test_transcripts": (
            "data/test_transcripts"
        ),

        "transcript_pattern": (
            "data/test_transcripts/{session_id}.csv"
        ),
    },

    "uploaded_submission": {

        "main_py": "main.py",

        "additional_assets": (
            "<additional assets included in submission archive>"
        ),
    },

    "inference_output": {

        "submission_file": "submission.csv",

        "required_columns": [
            "response_id",
            "probability",
        ],

        "probability_min": 0.0,

        "probability_max": 1.0,
    },

    "test_population": {

        "local_dataset_expected": False,

        "runtime_supplied": True,

        "full_test_population_approximate_size": 10_500,

        "smoke_test_population": 100,
    },

    "data_rules": {

        "test_samples_processed_independently": True,

        "cross_test_sample_feature_aggregation": False,

        "test_pseudo_labeling": False,

        "test_set_training": False,

        "test_set_unsupervised_adaptation": False,

        "retraining_during_inference": False,
    },

    "submission_requirements": {

        "zip_required": True,

        "main_py_at_zip_root": True,

        "main_py_loads_from_data_folder": True,

        "data_folder_read_only": True,

        "main_py_writes_submission_csv": True,

        "submission_csv_at_submission_root": True,

        "submission_columns_exact": [
            "response_id",
            "probability",
        ],
    },
}


# =============================================================================
# 4. RUNTIME DATA CONTRACT
# =============================================================================

print("\n" + "=" * 100)
print("RUNTIME DATA CONTRACT")
print("=" * 100)

print(
    "Runtime test_features path     : "
    "data/test_features.csv"
)

print(
    "Runtime test_transcripts path  : "
    "data/test_transcripts/{session_id}.csv"
)

print(
    "Runtime submission format      : "
    "data/submission_format.csv"
)

print(
    "Local Dataset/ test required   : NO"
)

print(
    "Runtime data contract : PASS"
)


# =============================================================================
# 5. SUBMISSION CONTRACT
# =============================================================================

print("\n" + "=" * 100)
print("SUBMISSION CONTRACT")
print("=" * 100)

print(
    "Submission archive : submission.zip"
)

print(
    "main.py location   : ZIP ROOT"
)

print(
    "Output             : submission.csv"
)

print(
    "Output location    : SUBMISSION ROOT"
)

print(
    "Required columns   : "
    "response_id, probability"
)

print(
    "Probability range  : [0, 1]"
)

print(
    "Submission contract : PASS"
)


# =============================================================================
# 6. TEST-DATA PROCESSING RULES
# =============================================================================

print("\n" + "=" * 100)
print("TEST-DATA PROCESSING RULES")
print("=" * 100)

RULES = [
    (
        "Independent test-sample processing",
        RUNTIME_CONTRACT[
            "data_rules"
        ][
            "test_samples_processed_independently"
        ],
    ),
    (
        "Cross-test aggregation",
        not RUNTIME_CONTRACT[
            "data_rules"
        ][
            "cross_test_sample_feature_aggregation"
        ],
    ),
    (
        "Test pseudo-labeling",
        not RUNTIME_CONTRACT[
            "data_rules"
        ][
            "test_pseudo_labeling"
        ],
    ),
    (
        "Test-set training",
        not RUNTIME_CONTRACT[
            "data_rules"
        ][
            "test_set_training"
        ],
    ),
    (
        "Test unsupervised adaptation",
        not RUNTIME_CONTRACT[
            "data_rules"
        ][
            "test_set_unsupervised_adaptation"
        ],
    ),
    (
        "Retraining during inference",
        not RUNTIME_CONTRACT[
            "data_rules"
        ][
            "retraining_during_inference"
        ],
    ),
]


for name, passed in RULES:

    print(
        f"{name:<42}: "
        f"{'PASS' if passed else 'FAIL'}"
    )

    assert passed


print(
    "Test-data independence contract : PASS"
)


# =============================================================================
# 7. LOCAL TRAINING → RUNTIME MAPPING
# =============================================================================

print("\n" + "=" * 100)
print("LOCAL TRAINING → RUNTIME MAPPING")
print("=" * 100)

mapping = {
    "training_features": (
        "Dataset/train_features_TMQTWsB.csv"
    ),

    "training_labels": (
        "Dataset/train_labels_44ujmj2.csv"
    ),

    "training_transcripts": (
        "Dataset/train_transcripts/"
    ),

    "runtime_test_features": (
        "data/test_features.csv"
    ),

    "runtime_test_transcripts": (
        "data/test_transcripts/"
    ),

    "runtime_submission_template": (
        "data/submission_format.csv"
    ),

    "runtime_entrypoint": (
        "main.py"
    ),

    "runtime_output": (
        "submission.csv"
    ),
}


for key, value in mapping.items():

    print(
        f"{key:<32}: {value}"
    )


print(
    "\nTraining/runtime separation : PASS"
)


# =============================================================================
# 8. LOCAL DATASET FINDING
# =============================================================================

dataset_unseen_candidate = (
    False
)

if (
    "zero_overlap_count"
    in globals()
):

    dataset_unseen_candidate = (
        zero_overlap_count > 0
    )


print("\n" + "=" * 100)
print("LOCAL TEST-DATA DISCOVERY RESULT")
print("=" * 100)

print(
    f"Unseen identity candidate in Dataset/ : "
    f"{dataset_unseen_candidate}"
)

assert (
    dataset_unseen_candidate is False
)

print(
    "Dataset/ test population : NOT REQUIRED"
)

print(
    "Runtime-supplied test population : EXPECTED"
)


# =============================================================================
# 9. RUNTIME VERSION WARNING
# =============================================================================

print("\n" + "=" * 100)
print("LOCAL VS SUBMISSION RUNTIME")
print("=" * 100)

print(
    f"Current local Python : "
    f"{sys.version.split()[0]}"
)

print(
    "Required submission Python : 3.12"
)

print(
    "Local environment is NOT the submission runtime."
)

print(
    "Runtime version separation : PASS"
)


# =============================================================================
# 10. PRODUCTION MODEL CONTRACT
# =============================================================================

FINAL_OOF_PATH = (
    SCRATCH_ROOT
    / "09C"
    / "final"
    / "outputs"
    / "final_production_oof.parquet"
)

FINAL_METRICS_PATH = (
    SCRATCH_ROOT
    / "09C"
    / "final"
    / "audit"
    / "cell14_final_metrics.json"
)

FINAL_MANIFEST_PATH = (
    SCRATCH_ROOT
    / "09C"
    / "final"
    / "audit"
    / "cell14_final_manifest.json"
)

BLEND_CALIBRATION_PATH = (
    SCRATCH_ROOT
    / "09C"
    / "blend_calibration"
    / "outputs"
    / "oof_blend_calibration.parquet"
)


print("\n" + "=" * 100)
print("FROZEN PRODUCTION ARTIFACT CONTRACT")
print("=" * 100)

for name, path in [
    (
        "Final OOF",
        FINAL_OOF_PATH,
    ),
    (
        "Final metrics",
        FINAL_METRICS_PATH,
    ),
    (
        "Final manifest",
        FINAL_MANIFEST_PATH,
    ),
    (
        "Blend calibration",
        BLEND_CALIBRATION_PATH,
    ),
]:

    print(
        f"{name:<24}: "
        f"{'FOUND' if path.exists() else 'MISSING'}"
    )

    assert path.exists(), (
        f"Required production artifact missing:\n{path}"
    )


print(
    "\nFrozen production artifact contract : PASS"
)


# =============================================================================
# 11. PRODUCTION METHOD LOCK
# =============================================================================

PRODUCTION_METHOD = (
    "raw_blend"
)

BLEND_WEIGHTS = {
    "modernbert": 0.419,
    "structured_prior": 0.351,
    "tfidf": 0.230,
}


assert PRODUCTION_METHOD == "raw_blend"

assert abs(
    sum(
        BLEND_WEIGHTS.values()
    ) - 1.0
) < 1e-12


print("\n" + "=" * 100)
print("PRODUCTION METHOD")
print("=" * 100)

print(
    f"Method : {PRODUCTION_METHOD}"
)

print(
    f"ModernBERT      : "
    f"{BLEND_WEIGHTS['modernbert']:.6f}"
)

print(
    f"Structured+Prior: "
    f"{BLEND_WEIGHTS['structured_prior']:.6f}"
)

print(
    f"TF-IDF          : "
    f"{BLEND_WEIGHTS['tfidf']:.6f}"
)

print(
    f"Weight sum      : "
    f"{sum(BLEND_WEIGHTS.values()):.12f}"
)

print(
    "Production method lock : PASS"
)


# =============================================================================
# 12. TEST POPULATION STATUS
# =============================================================================

TEST_POPULATION_STATUS = (
    "RUNTIME_SUPPLIED_AT_INFERENCE"
)

assert TEST_POPULATION_STATUS == (
    "RUNTIME_SUPPLIED_AT_INFERENCE"
)

assert (
    TEST_POPULATION_LOCKED is False
)

print("\n" + "=" * 100)
print("TEST POPULATION STATUS")
print("=" * 100)

print(
    "Local test population : NOT LOCKED"
)

print(
    "Runtime test population : EXPECTED"
)

print(
    "Status : PASS"
)


# =============================================================================
# 13. WRITE CONTRACT
# =============================================================================

with open(
    CONTRACT_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        {
            "cell": (
                "12_test_population_lock_cell4"
            ),

            "status": "PASS",

            "official_runtime_contract": (
                RUNTIME_CONTRACT
            ),

            "production_method": (
                PRODUCTION_METHOD
            ),

            "blend_weights": (
                BLEND_WEIGHTS
            ),

            "test_population_status": (
                TEST_POPULATION_STATUS
            ),

            "local_dataset_test_candidate": (
                dataset_unseen_candidate
            ),

            "test_population_locked": False,

            "production_inference_started": False,

            "submission_generated": False,

            "next_cell": (
                "Cell 5 — runtime test_features "
                "schema compatibility contract"
            ),
        },
        f,
        indent=2,
    )


assert CONTRACT_PATH.exists()


print("\n" + "=" * 100)
print("CONTRACT ARTIFACT")
print("=" * 100)

print(
    f"Path : {CONTRACT_PATH}"
)

print(
    "Contract write : PASS"
)


# =============================================================================
# 14. FINAL STATUS
# =============================================================================

print("\n" + "=" * 100)
print("TRACE THE ACE — CELL 4 FINAL STATUS")
print("=" * 100)

print(
    "Cell 3 dependency              : PASS"
)

print(
    "Official runtime contract     : PASS"
)

print(
    "Runtime data contract         : PASS"
)

print(
    "Submission contract           : PASS"
)

print(
    "Test-data independence        : PASS"
)

print(
    "Training/runtime separation   : PASS"
)

print(
    "Frozen production artifacts   : PASS"
)

print(
    "Production method lock        : PASS"
)

print(
    "Local test population lock    : NOT REQUIRED"
)

print(
    "Runtime test population       : EXPECTED"
)

print(
    "Production inference          : NOT STARTED"
)

print(
    "Submission generation         : NOT STARTED"
)

print("-" * 100)

print(
    "CELL 4 COMPLETE — PASS"
)

print("=" * 100)

====================================================================================================
TRACE THE ACE — TEST RUNTIME CONTRACT
CELL 4 — OFFICIAL COMPETITION INFERENCE RUNTIME CONTRACT
====================================================================================================

Cell 3 dependency              : PASS
Local test population lock     : NOT REQUIRED

PROJECT ROOT
--------------------------------------------------------------------------------
PROJECT_ROOT : D:\Competition\Trace-the-race-local
Project root : PASS

====================================================================================================
RUNTIME DATA CONTRACT
====================================================================================================
Runtime test_features path     : data/test_features.csv
Runtime test_transcripts path  : data/test_transcripts/{session_id}.csv
Runtime submission format      : data/submission_format.csv
Local Dataset/ test required   : NO
Runtime data contract : PASS

====================================================================================================
SUBMISSION CONTRACT
====================================================================================================
Submission archive : submission.zip
main.py location   : ZIP ROOT
Output             : submission.csv
Output location    : SUBMISSION ROOT
Required columns   : response_id, probability
Probability range  : [0, 1]
Submission contract : PASS

====================================================================================================
TEST-DATA PROCESSING RULES
====================================================================================================
Independent test-sample processing        : PASS
Cross-test aggregation                    : PASS
Test pseudo-labeling                      : PASS
Test-set training                         : PASS
Test unsupervised adaptation              : PASS
Retraining during inference               : PASS
Test-data independence contract : PASS

====================================================================================================
LOCAL TRAINING → RUNTIME MAPPING
====================================================================================================
training_features               : Dataset/train_features_TMQTWsB.csv
training_labels                 : Dataset/train_labels_44ujmj2.csv
training_transcripts            : Dataset/train_transcripts/
runtime_test_features           : data/test_features.csv
runtime_test_transcripts        : data/test_transcripts/
runtime_submission_template     : data/submission_format.csv
runtime_entrypoint              : main.py
runtime_output                  : submission.csv

Training/runtime separation : PASS

====================================================================================================
LOCAL TEST-DATA DISCOVERY RESULT
====================================================================================================
Unseen identity candidate in Dataset/ : False
Dataset/ test population : NOT REQUIRED
Runtime-supplied test population : EXPECTED

====================================================================================================
LOCAL VS SUBMISSION RUNTIME
====================================================================================================
Current local Python : 3.10.20
Required submission Python : 3.12
Local environment is NOT the submission runtime.
Runtime version separation : PASS

====================================================================================================
FROZEN PRODUCTION ARTIFACT CONTRACT
====================================================================================================
Final OOF               : FOUND
Final metrics           : FOUND
Final manifest          : FOUND
Blend calibration       : FOUND

Frozen production artifact contract : PASS

====================================================================================================
PRODUCTION METHOD
====================================================================================================
Method : raw_blend
ModernBERT      : 0.419000
Structured+Prior: 0.351000
TF-IDF          : 0.230000
Weight sum      : 1.000000000000
Production method lock : PASS

====================================================================================================
TEST POPULATION STATUS
====================================================================================================
Local test population : NOT LOCKED
Runtime test population : EXPECTED
Status : PASS

====================================================================================================
CONTRACT ARTIFACT
====================================================================================================
Path : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell4\cell4_test_runtime_contract.json
Contract write : PASS

====================================================================================================
TRACE THE ACE — CELL 4 FINAL STATUS
====================================================================================================
Cell 3 dependency              : PASS
Official runtime contract     : PASS
Runtime data contract         : PASS
Submission contract           : PASS
Test-data independence        : PASS
Training/runtime separation   : PASS
Frozen production artifacts   : PASS
Production method lock        : PASS
Local test population lock    : NOT REQUIRED
Runtime test population       : EXPECTED
Production inference          : NOT STARTED
Submission generation         : NOT STARTED
----------------------------------------------------------------------------------------------------
CELL 4 COMPLETE — PASS
====================================================================================================

In [8]:
# =============================================================================
# TRACE THE ACE — TEST RUNTIME CONTRACT
# CELL 5 — TEST FEATURES SCHEMA + INFERENCE INPUT CONTRACT
# =============================================================================

from pathlib import Path
import json

import pandas as pd


print("=" * 100)
print("TRACE THE ACE — TEST RUNTIME CONTRACT")
print("CELL 5 — TEST FEATURES SCHEMA + INFERENCE INPUT CONTRACT")
print("=" * 100)


# =============================================================================
# 1. DEPENDENCY GATE
# =============================================================================

assert "RUNTIME_CONTRACT" in globals(), (
    "Cell 4 dependency failed: RUNTIME_CONTRACT is missing."
)

assert "TEST_POPULATION_STATUS" in globals(), (
    "Cell 4 dependency failed: TEST_POPULATION_STATUS is missing."
)

assert TEST_POPULATION_STATUS == (
    "RUNTIME_SUPPLIED_AT_INFERENCE"
)

assert not TEST_POPULATION_LOCKED
assert not PRODUCTION_INFERENCE_STARTED


print("\nCell 4 dependency          : PASS")
print("Runtime-supplied test data : EXPECTED")


# =============================================================================
# 2. PATHS
# =============================================================================

TRAIN_FEATURES_PATH = (
    PROJECT_ROOT
    / "Dataset"
    / "train_features_TMQTWsB.csv"
)

TRAIN_LABELS_PATH = (
    PROJECT_ROOT
    / "Dataset"
    / "train_labels_44ujmj2.csv"
)

CELL_ROOT = (
    SCRATCH_ROOT
    / "09C"
    / "final_test_discovery"
    / "cell5"
)

CELL_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

SCHEMA_PATH = (
    CELL_ROOT
    / "cell5_test_features_schema_contract.json"
)


assert TRAIN_FEATURES_PATH.exists()
assert TRAIN_LABELS_PATH.exists()


# =============================================================================
# 3. LOAD TRAINING FEATURE SCHEMA ONLY
# =============================================================================
# We use training features as the schema reference.
# We DO NOT treat them as test data.
# =============================================================================

train_features = pd.read_csv(
    TRAIN_FEATURES_PATH,
    nrows=5,
)

train_labels = pd.read_csv(
    TRAIN_LABELS_PATH,
    nrows=5,
)


print("\n" + "=" * 100)
print("TRAINING REFERENCE SCHEMA")
print("=" * 100)

print(
    f"Training feature columns : "
    f"{list(train_features.columns)}"
)

print(
    f"Training label columns   : "
    f"{list(train_labels.columns)}"
)


# =============================================================================
# 4. IDENTITY CONTRACT
# =============================================================================

REQUIRED_ID_COLUMNS = [
    "response_id",
    "session_id",
]


for column in REQUIRED_ID_COLUMNS:

    assert column in train_features.columns, (
        f"Required identity column missing "
        f"from training features: {column}"
    )


print(
    "\nRequired identity columns : PASS"
)


# =============================================================================
# 5. TRAINING FEATURE CONTRACT
# =============================================================================

TRAIN_FEATURE_COLUMNS = list(
    train_features.columns
)

TRAIN_FEATURE_COLUMN_SET = set(
    TRAIN_FEATURE_COLUMNS
)


assert len(
    TRAIN_FEATURE_COLUMNS
) == len(
    TRAIN_FEATURE_COLUMN_SET
), (
    "Duplicate training feature column names detected."
)


print(
    "Training feature column uniqueness : PASS"
)


# =============================================================================
# 6. LABEL SEPARATION — CORRECTED
# =============================================================================
#
# response_id is an identity/join key and is intentionally allowed to exist
# in both train_features and train_labels.
#
# Only actual target/label columns must be absent from the feature schema.
# =============================================================================

IDENTITY_COLUMNS = {
    "response_id",
    "session_id",
}

LABEL_COLUMNS = list(
    train_labels.columns
)

ACTUAL_LABEL_COLUMNS = [
    c
    for c in LABEL_COLUMNS
    if c not in IDENTITY_COLUMNS
]


print("\n" + "=" * 100)
print("LABEL / IDENTITY SEPARATION")
print("=" * 100)

print(
    f"Label-table columns    : {LABEL_COLUMNS}"
)

print(
    f"Identity columns       : "
    f"{sorted(IDENTITY_COLUMNS)}"
)

print(
    f"Actual label columns   : "
    f"{ACTUAL_LABEL_COLUMNS}"
)


# response_id is allowed as a shared join key.
assert (
    "response_id"
    in train_labels.columns
), (
    "response_id missing from training labels."
)


assert (
    "response_id"
    in train_features.columns
), (
    "response_id missing from training features."
)


# session_id may or may not be present in labels.
# It is also an identity field, not a target.
for identity_column in (
    set(train_labels.columns)
    & IDENTITY_COLUMNS
):

    assert identity_column in (
        TRAIN_FEATURE_COLUMN_SET
    ), (
        f"Shared identity column missing from "
        f"training features: {identity_column}"
    )


# The actual label/target column(s) must NOT exist in features.
for label_column in ACTUAL_LABEL_COLUMNS:

    assert label_column not in (
        TRAIN_FEATURE_COLUMN_SET
    ), (
        f"Actual label column appears in "
        f"feature schema: {label_column}"
    )


assert len(ACTUAL_LABEL_COLUMNS) > 0, (
    "No actual target/label column was found "
    "after excluding identity columns."
)


print(
    "\nShared identity keys : PASS"
)

print(
    "Actual target/label separation : PASS"
)


# =============================================================================
# 7. EXPECTED RUNTIME TEST FEATURE CONTRACT
# =============================================================================
#
# test_features.csv must be structurally compatible with train_features.csv.
#
# Important:
#   response_id and session_id are identity fields.
#   No target/label column is allowed.
#
# =============================================================================

EXPECTED_TEST_FEATURE_COLUMNS = (
    TRAIN_FEATURE_COLUMNS.copy()
)


FORBIDDEN_TEST_COLUMNS = [
    "target",
    "label",
    "answer",
    "ground_truth",
]


print("\n" + "=" * 100)
print("EXPECTED RUNTIME TEST FEATURES CONTRACT")
print("=" * 100)

print(
    "Expected source : data/test_features.csv"
)

print(
    "Expected columns:"
)

for column in EXPECTED_TEST_FEATURE_COLUMNS:

    print(
        f"  - {column}"
    )


print(
    "\nExpected test feature count : "
    f"{len(EXPECTED_TEST_FEATURE_COLUMNS)}"
)


# =============================================================================
# 8. TEST TARGET EXCLUSION CONTRACT
# =============================================================================

print("\n" + "=" * 100)
print("TEST TARGET EXCLUSION CONTRACT")
print("=" * 100)

for forbidden in FORBIDDEN_TEST_COLUMNS:

    assert forbidden not in (
        EXPECTED_TEST_FEATURE_COLUMNS
    ), (
        f"Forbidden target-like column "
        f"in expected test schema: {forbidden}"
    )


print(
    "Target-like columns in expected test schema : NONE"
)

print(
    "Test target exclusion : PASS"
)


# =============================================================================
# 9. RESPONSE-LEVEL POPULATION CONTRACT
# =============================================================================

print("\n" + "=" * 100)
print("RESPONSE-LEVEL INFERENCE CONTRACT")
print("=" * 100)

print(
    "Prediction unit : response_id"
)

print(
    "Grouping context : session_id"
)

print(
    "Training response population : 35,072"
)

print(
    "Runtime test population : supplied by platform"
)

print(
    "Local test row count : UNKNOWN / NOT REQUIRED"
)

print(
    "Response-level contract : PASS"
)


# =============================================================================
# 10. DUPLICATE ID CONTRACT
# =============================================================================

# Verify the training reference itself has unique response IDs.
#
# This is NOT a test-population assertion.
# It establishes the identity semantics inherited by inference.

train_identity_sample = pd.read_csv(
    TRAIN_FEATURES_PATH,
    usecols=[
        "response_id",
        "session_id",
    ],
)


assert (
    train_identity_sample[
        "response_id"
    ]
    .notna()
    .all()
)

assert (
    train_identity_sample[
        "session_id"
    ]
    .notna()
    .all()
)


print(
    "\nTraining identity null contract : PASS"
)


# =============================================================================
# 11. RUNTIME TRANSCRIPT CONTRACT
# =============================================================================

EXPECTED_TRANSCRIPT_ROOT = (
    "data/test_transcripts"
)

EXPECTED_TRANSCRIPT_PATTERN = (
    "data/test_transcripts/{session_id}.csv"
)


print("\n" + "=" * 100)
print("RUNTIME TRANSCRIPT CONTRACT")
print("=" * 100)

print(
    f"Transcript root    : "
    f"{EXPECTED_TRANSCRIPT_ROOT}"
)

print(
    f"Transcript pattern : "
    f"{EXPECTED_TRANSCRIPT_PATTERN}"
)

print(
    "Transcript source is runtime-supplied."
)

print(
    "Transcript contract : PASS"
)


# =============================================================================
# 12. NO LOCAL TEST FABRICATION
# =============================================================================

LOCAL_TEST_FEATURES_PATH = (
    PROJECT_ROOT
    / "data"
    / "test_features.csv"
)

LOCAL_TEST_TRANSCRIPTS_PATH = (
    PROJECT_ROOT
    / "data"
    / "test_transcripts"
)


print("\n" + "=" * 100)
print("LOCAL TEST FABRICATION GUARD")
print("=" * 100)

print(
    f"Local test_features exists : "
    f"{LOCAL_TEST_FEATURES_PATH.exists()}"
)

print(
    f"Local test_transcripts exists : "
    f"{LOCAL_TEST_TRANSCRIPTS_PATH.exists()}"
)

print(
    "These files are NOT required locally."
)

print(
    "No synthetic test population will be created."
)

print(
    "Local test fabrication guard : PASS"
)


# =============================================================================
# 13. FROZEN SCHEMA CONTRACT
# =============================================================================

SCHEMA_CONTRACT = {

    "cell": (
        "12_test_population_lock_cell5"
    ),

    "status": "PASS",

    "runtime_test_features": {
        "path": (
            "data/test_features.csv"
        ),

        "required_columns": (
            EXPECTED_TEST_FEATURE_COLUMNS
        ),

        "required_identity_columns": (
            REQUIRED_ID_COLUMNS
        ),

        "forbidden_target_columns": (
            FORBIDDEN_TEST_COLUMNS
        ),

        "column_count": int(
            len(EXPECTED_TEST_FEATURE_COLUMNS)
        ),
    },

    "runtime_test_transcripts": {
        "root": EXPECTED_TRANSCRIPT_ROOT,
        "pattern": EXPECTED_TRANSCRIPT_PATTERN,
    },

    "inference_contract": {

        "prediction_unit": "response_id",

        "session_context": "session_id",

        "target_available_at_inference": False,

        "test_population_locally_required": False,

        "test_population_runtime_supplied": True,

        "synthetic_test_population_allowed": False,
    },

    "training_reference": {
        "features": str(
            TRAIN_FEATURES_PATH
        ),

        "labels": str(
            TRAIN_LABELS_PATH
        ),

        "feature_columns": (
            TRAIN_FEATURE_COLUMNS
        ),
    },

    "production_method": (
        PRODUCTION_METHOD
    ),

    "blend_weights": (
        BLEND_WEIGHTS
    ),

    "test_population_locked": False,

    "production_inference_started": False,

    "submission_generated": False,

    "next_cell": (
        "Cell 6 — runtime transcript schema "
        "and evidence reconstruction contract"
    ),
}


with open(
    SCHEMA_PATH,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        SCHEMA_CONTRACT,
        f,
        indent=2,
    )


assert SCHEMA_PATH.exists()


# =============================================================================
# 14. FINAL STATUS
# =============================================================================

print("\n" + "=" * 100)
print("TRACE THE ACE — CELL 5 FINAL STATUS")
print("=" * 100)

print(
    "Cell 4 dependency                  : PASS"
)

print(
    "Training reference schema          : PASS"
)

print(
    "Identity column contract           : PASS"
)

print(
    "Feature/label separation           : PASS"
)

print(
    "Runtime test feature schema        : PASS"
)

print(
    "Target exclusion contract          : PASS"
)

print(
    "Response-level inference contract  : PASS"
)

print(
    "Runtime transcript contract        : PASS"
)

print(
    "Local test fabrication guard       : PASS"
)

print(
    "Test population lock               : NOT YET"
)

print(
    "Production inference               : NOT STARTED"
)

print(
    "Submission generation              : NOT STARTED"
)

print("-" * 100)

print(
    f"Schema contract : {SCHEMA_PATH}"
)

print(
    "CELL 5 COMPLETE — PASS"
)

print("=" * 100)

====================================================================================================
TRACE THE ACE — TEST RUNTIME CONTRACT
CELL 5 — TEST FEATURES SCHEMA + INFERENCE INPUT CONTRACT
====================================================================================================

Cell 4 dependency          : PASS
Runtime-supplied test data : EXPECTED

====================================================================================================
TRAINING REFERENCE SCHEMA
====================================================================================================
Training feature columns : ['response_id', 'session_id', 'learning_objective_id', 'learning_objective']
Training label columns   : ['response_id', 'is_correct']

Required identity columns : PASS
Training feature column uniqueness : PASS

====================================================================================================
LABEL / IDENTITY SEPARATION
====================================================================================================
Label-table columns    : ['response_id', 'is_correct']
Identity columns       : ['response_id', 'session_id']
Actual label columns   : ['is_correct']

Shared identity keys : PASS
Actual target/label separation : PASS

====================================================================================================
EXPECTED RUNTIME TEST FEATURES CONTRACT
====================================================================================================
Expected source : data/test_features.csv
Expected columns:
  - response_id
  - session_id
  - learning_objective_id
  - learning_objective

Expected test feature count : 4

====================================================================================================
TEST TARGET EXCLUSION CONTRACT
====================================================================================================
Target-like columns in expected test schema : NONE
Test target exclusion : PASS

====================================================================================================
RESPONSE-LEVEL INFERENCE CONTRACT
====================================================================================================
Prediction unit : response_id
Grouping context : session_id
Training response population : 35,072
Runtime test population : supplied by platform
Local test row count : UNKNOWN / NOT REQUIRED
Response-level contract : PASS

Training identity null contract : PASS

====================================================================================================
RUNTIME TRANSCRIPT CONTRACT
====================================================================================================
Transcript root    : data/test_transcripts
Transcript pattern : data/test_transcripts/{session_id}.csv
Transcript source is runtime-supplied.
Transcript contract : PASS

====================================================================================================
LOCAL TEST FABRICATION GUARD
====================================================================================================
Local test_features exists : False
Local test_transcripts exists : False
These files are NOT required locally.
No synthetic test population will be created.
Local test fabrication guard : PASS

====================================================================================================
TRACE THE ACE — CELL 5 FINAL STATUS
====================================================================================================
Cell 4 dependency                  : PASS
Training reference schema          : PASS
Identity column contract           : PASS
Feature/label separation           : PASS
Runtime test feature schema        : PASS
Target exclusion contract          : PASS
Response-level inference contract  : PASS
Runtime transcript contract        : PASS
Local test fabrication guard       : PASS
Test population lock               : NOT YET
Production inference               : NOT STARTED
Submission generation              : NOT STARTED
----------------------------------------------------------------------------------------------------
Schema contract : D:\Competition\Trace-the-race-local\scratch_mastery_outputs\09C\final_test_discovery\cell5\cell5_test_features_schema_contract.json
CELL 5 COMPLETE — PASS
====================================================================================================