In [2]:
import pandas as pd

In [6]:
df=pd.read_parquet("turns_candidate.parquet")

In [7]:
df.head(10)

,session_id,turn_uid,source_row_uid,turn_index,session_id_raw,utterance_id_raw,utterance_id,utterance_id_status,role_raw,role,...,content_hash,turn_uid_version,missing_session_id_flag,missing_utterance_id_flag,missing_role_flag,empty_content_flag,missing_timestamp_flag,duplicate_utterance_id_flag,natural_key_collision_flag,duplicate_raw_field_flag
0,aaaedit,b42a03fee3a9fcf6b5d34f033d42896d409c6ad3fa2ab8...,345f367256e99f6a79cd183db1ee716cac132302405c80...,0,aaaedit,0,0,VALID,tutor,tutor,...,c36b40652bc4e6a89a36d5fd0a79cacb49f113c865de86...,1.0,False,False,False,False,False,False,False,False
1,aaaedit,76182f86f777c2402798e5c6f15f66d08b97a0fbd6c0a0...,4715f653dd108b64f2907e6d6e5f395d9e15b050cb00b5...,1,aaaedit,1,1,VALID,background,background,...,239674fd86ecd7be8672a4f17e6de45a479c64086d40bb...,1.0,False,False,False,False,False,False,False,False
2,aaaedit,c84d92d0b88ce952b2baac597b244712acc01bf3baaabc...,7b26d2b47d0d19b819438dbb21b83b41e5ab07e1a8d6f5...,2,aaaedit,2,2,VALID,background,background,...,4487548212d8f2f4736ac097d1a3043ffa5f56459056b8...,1.0,False,False,False,False,False,False,False,False
3,aaaedit,3c65ccc768a67021e334cb99fb62f0e8e8b4581678f93a...,63a3a628059baaffc0fdd643d45f3e7485c7518ce9ef28...,3,aaaedit,3,3,VALID,tutor,tutor,...,6b610cd18373d7c9bb11b884b2f5a1aa62152d1838b9e0...,1.0,False,False,False,False,False,False,False,False
4,aaaedit,5dbe6e8c9d8c9027b59d1309bdb59b2f18a61535efc314...,5ec0ba24508c738df22319fff17d191ff8ba5d1c3aaf31...,4,aaaedit,4,4,VALID,student,student,...,22c16c191562325739cf592873463b98dcee8635a53e52...,1.0,False,False,False,False,False,False,False,False
5,aaaedit,94f7b89d7324d975ac8db8c0fe8260d1f8cf0530cfca48...,932bcf3f29f333339d952f1ed946ad89d8a1db7e9528b2...,5,aaaedit,5,5,VALID,tutor,tutor,...,b490ae42c6888fb25bf152f4cf3493e972f78e062d2ef4...,1.0,False,False,False,False,False,False,False,False
6,aaaedit,91025ca7a77dc67f2ce243973e377381d6d81d0e06630b...,41905769d291cdf0f55f510d59367d35d34017193e0770...,6,aaaedit,6,6,VALID,student,student,...,22c16c191562325739cf592873463b98dcee8635a53e52...,1.0,False,False,False,False,False,False,False,False
7,aaaedit,603e4a06653a900460a6f86c145dde00d5a3c8d8608fe8...,882fc5f5280df34385abfb2890072598945eed0ede0a5b...,7,aaaedit,7,7,VALID,tutor,tutor,...,f074aac469eab2c36140f772c66b82e4507dc59751d810...,1.0,False,False,False,False,False,False,False,False
8,aaaedit,6aa46a419b5502f64eec58890d604da20ef9a5a91ebe88...,c45a11b0f9cd26e969779ea98aa844820f6ac1b36ae278...,8,aaaedit,8,8,VALID,student,student,...,016166726e7f62cbda2f71a6b71d2919ed8ff519faefa8...,1.0,False,False,False,False,False,False,False,False
9,aaaedit,5a25f986984687e3ca4c6f4ec0a689b9beba76e4ef8600...,c95e1373f45e9fd4f32ab6c1ba7b93fde0d3e9977340ec...,9,aaaedit,9,9,VALID,tutor,tutor,...,5afa099237f4b84cbde4d3d41dd81cf0251c504452e9ea...,1.0,False,False,False,False,False,False,False,False

In [12]:
df1=pd.read_parquet("sessions_candidate.parquet")

In [13]:
df.head(10)

,session_id,turn_uid,source_row_uid,turn_index,session_id_raw,utterance_id_raw,utterance_id,utterance_id_status,role_raw,role,...,content_hash,turn_uid_version,missing_session_id_flag,missing_utterance_id_flag,missing_role_flag,empty_content_flag,missing_timestamp_flag,duplicate_utterance_id_flag,natural_key_collision_flag,duplicate_raw_field_flag
0,aaaedit,b42a03fee3a9fcf6b5d34f033d42896d409c6ad3fa2ab8...,345f367256e99f6a79cd183db1ee716cac132302405c80...,0,aaaedit,0,0,VALID,tutor,tutor,...,c36b40652bc4e6a89a36d5fd0a79cacb49f113c865de86...,1.0,False,False,False,False,False,False,False,False
1,aaaedit,76182f86f777c2402798e5c6f15f66d08b97a0fbd6c0a0...,4715f653dd108b64f2907e6d6e5f395d9e15b050cb00b5...,1,aaaedit,1,1,VALID,background,background,...,239674fd86ecd7be8672a4f17e6de45a479c64086d40bb...,1.0,False,False,False,False,False,False,False,False
2,aaaedit,c84d92d0b88ce952b2baac597b244712acc01bf3baaabc...,7b26d2b47d0d19b819438dbb21b83b41e5ab07e1a8d6f5...,2,aaaedit,2,2,VALID,background,background,...,4487548212d8f2f4736ac097d1a3043ffa5f56459056b8...,1.0,False,False,False,False,False,False,False,False
3,aaaedit,3c65ccc768a67021e334cb99fb62f0e8e8b4581678f93a...,63a3a628059baaffc0fdd643d45f3e7485c7518ce9ef28...,3,aaaedit,3,3,VALID,tutor,tutor,...,6b610cd18373d7c9bb11b884b2f5a1aa62152d1838b9e0...,1.0,False,False,False,False,False,False,False,False
4,aaaedit,5dbe6e8c9d8c9027b59d1309bdb59b2f18a61535efc314...,5ec0ba24508c738df22319fff17d191ff8ba5d1c3aaf31...,4,aaaedit,4,4,VALID,student,student,...,22c16c191562325739cf592873463b98dcee8635a53e52...,1.0,False,False,False,False,False,False,False,False
5,aaaedit,94f7b89d7324d975ac8db8c0fe8260d1f8cf0530cfca48...,932bcf3f29f333339d952f1ed946ad89d8a1db7e9528b2...,5,aaaedit,5,5,VALID,tutor,tutor,...,b490ae42c6888fb25bf152f4cf3493e972f78e062d2ef4...,1.0,False,False,False,False,False,False,False,False
6,aaaedit,91025ca7a77dc67f2ce243973e377381d6d81d0e06630b...,41905769d291cdf0f55f510d59367d35d34017193e0770...,6,aaaedit,6,6,VALID,student,student,...,22c16c191562325739cf592873463b98dcee8635a53e52...,1.0,False,False,False,False,False,False,False,False
7,aaaedit,603e4a06653a900460a6f86c145dde00d5a3c8d8608fe8...,882fc5f5280df34385abfb2890072598945eed0ede0a5b...,7,aaaedit,7,7,VALID,tutor,tutor,...,f074aac469eab2c36140f772c66b82e4507dc59751d810...,1.0,False,False,False,False,False,False,False,False
8,aaaedit,6aa46a419b5502f64eec58890d604da20ef9a5a91ebe88...,c45a11b0f9cd26e969779ea98aa844820f6ac1b36ae278...,8,aaaedit,8,8,VALID,student,student,...,016166726e7f62cbda2f71a6b71d2919ed8ff519faefa8...,1.0,False,False,False,False,False,False,False,False
9,aaaedit,5a25f986984687e3ca4c6f4ec0a689b9beba76e4ef8600...,c95e1373f45e9fd4f32ab6c1ba7b93fde0d3e9977340ec...,9,aaaedit,9,9,VALID,tutor,tutor,...,5afa099237f4b84cbde4d3d41dd81cf0251c504452e9ea...,1.0,False,False,False,False,False,False,False,False